### ISSUE TITLE
TensorRT Environment

### ISSUE THREAD

**Issue by yqlbu** [dusty-nv/jetson-inference#1001]
Hi,

I recently tested the jetson-inference container, and I had the following questions about the TensorRT Environment inside the container:

When I run `pip list`, I did not find `tensorrt` in the list. However, if I run `python3 -c "import tensorrt as trt`, it executes with no error prompt. I wonder if the container already included the `tensorrt` package installed, or more specifically, how does it work inside the container?

![image](https://user-images.githubusercontent.com/31861128/114038486-7df9f300-98b4-11eb-891f-9ab411ef9559.png)

Best,
Kev

**Comment by dusty-nv** [comment]
Hi @yqlbu, on Jetson the CUDA/cuDNN/TensorRT headers+libraries are mounted at runtime into the container when it is run with `--runtime nvidia` (which is used in my `docker/run.sh` script).   That is probably why pip is not listing it, but it actually is there.   

For more info, see here:  https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson#mount-plugins

**Comment by yqlbu** [comment]
> Hi @yqlbu, on Jetson the CUDA/cuDNN/TensorRT headers+libraries are mounted at runtime into the container when it is run with `--runtime nvidia` (which is used in my `docker/run.sh` script). That is probably why pip is not listing it, but it actually is there.
> 
> For more info, see here: https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson#mount-plugins

Thanks for the notes. I will try it out!
