### ISSUE TITLE
Nvidia GTC21: 

### ISSUE THREAD

**Issue by h3retek** [dusty-nv/jetson-inference#1004]
Watch the man in action:

[Build Edge AI Projects with the Jetson Community](https://gtc21.event.nvidia.com/media/Build%20Edge%20AI%20Projects%20with%20the%20Jetson%20Community%20%5BS32750%5D/1_h6y685li)

**Comment by dusty-nv** [comment]
Thanks @h3retek, we are super excited for GTC this week and to see some great projects presented by the community tomorrow in that session!

Check out more highlighted Jetson talks from GTC here:
https://forums.developer.nvidia.com/t/gtc-2021-edge-ai-and-robotics-conference-topics/173375
