### ISSUE TITLE
Detection Outputs to SQL

### ISSUE THREAD

**Issue by DJT777** [dusty-nv/jetson-inference#1020]
Dusty,

I want to create an SQL entry for every time the detect net model makes a detection using your 10 lines of code example. Is this possible to do using python, and could you give me some insight on where the outputs of the model can be accessed?

Thank you

**Comment by dusty-nv** [comment]
Hi @DJT777 , sure - the detections are output into a list of `detectNet.Detection` objects:

``` python
detections = net.Detect(img)

for detection in detections:
   print(detection.ClassID)
   print(detection.Confidence)
   print(detection.Left)
   print(detection.Top)
   # ect
```

Here are the members:

```
Detection = <type 'jetson.inference.detectNet.Detection'>
Object Detection Result
 
----------------------------------------------------------------------
Data descriptors defined here:
 
Area
    Area of bounding box
 
Bottom
    Bottom bounding box coordinate
 
Center
    Center (x,y) coordinate of bounding box
 
ClassID
    Class index of the detected object
 
Confidence
    Confidence value of the detected object
 
Height
    Height of bounding box
 
Instance
    Instance index of the detected object
 
Left
    Left bounding box coordinate
 
Right
    Right bounding box coordinate
 
Top
    Top bounding box coordinate
 
Width
     Width of bounding box
```

For SQL, I have used SQLite before (through sqlite3 in python) on Jetson before without issue.

**Comment by DJT777** [comment]
@dusty-nv 


You're awesome. If I have any questions I will use this thread.

**Comment by DJT777** [comment]
@dusty-nv
Is there a way to display on screen detection of only one class? Like filter out detections of other things based on class ID. It seems like the code you offered allows choosing detections based on class ID, for example, for output to SQL. I am wondering if something similar can be done for displaying detection.

I.e. allow only dogs to be displayed on screen.
