### ISSUE TITLE
Pytorch does not install building from source does not install

### ISSUE THREAD

**Issue by Gianni2045** [dusty-nv/jetson-inference#1023]
I have tried many times to install pytorch and when i check if it is installed
it says illegal instruction in python shell core dumped
I am always getting these reports
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/nvidia/.local/include/python3.6m/torch
  sysconfig: /home/nvidia/.local/include/python3.6/torch
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None

I follow all the instructions in setting up the nano this is extremely frustrating and the github pages and nvidia help section does not help

**Comment by Gianni2045** [comment]
Can you please help me get this thing going on my ssd I USB in which i am able to boot my jetpack 4.5?

**Comment by dusty-nv** [comment]
Hi @Gianni2045, please refer to this post:

https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048/769?u=dusty_nv

My guess is you had previously upgraded your version of pip/pip3, and there is a bug in numpy 1.19.5 that only gets installed if you had upgraded pip.  Try running `export OPENBLAS_CORETYPE=ARMV8` beforehand or downgrading to numpy 1.18.2
