### ISSUE TITLE
load tensorrt engine file in c++

### ISSUE THREAD

**Issue by Maximal4028** [dusty-nv/jetson-inference#1036]
Hello. Thanks for your work. I'm new in tensorrt c++. I worked with your detectNet example and successfully used your pre-trained ssd_mobilenet_v2. 
I have nvidia trafficcamnet engine file. How can i load this engine file in detectNet?

**Comment by maazullah96** [comment]
Hi @Maximal4028  did you have found any solution related to loading engine files in C++?
