### ISSUE TITLE
Problem in Re-training SSD-Mobilenet

### ISSUE THREAD

**Issue by mprabhakarece** [dusty-nv/jetson-inference#1048]
Hi,

I am getting below error while running "pip3 install -v -r requirements.txt"

**"Could not find a version that satisfies the requirement"**
Not to install boto3, pandas and urllib3 it seems.
nvidia-jetpack Version: 4.5-b129
Python3 version: Python 3.6.9

Kindly do needful

Thanks and Regards,
Prabhakar M

**Comment by dusty-nv** [comment]
Hi, recommend to use the Docker container until I have chance to look into it more
________________________________
From: mprabhakarece ***@***.***>
Sent: Saturday, May 15, 2021 12:17:59 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] Problem in Re-training SSD-Mobilenet (#1048)


Hi,

I am getting below error while running "pip3 install -v -r requirements.txt"

"Could not find a version that satisfies the requirement"
Not to install boto3, pandas and urllib3 it seems.
nvidia-jetpack Version: 4.5-b129
Python3 version: Python 3.6.9

Kindly do needful

Thanks and Regards,
Prabhakar M

**Comment by mprabhakarece** [comment]
Hi,
Due to some environmental setup I was not able to install the requirements.
I have installed above libraries individually.
Now everything is fine.
