### ISSUE TITLE
How to do  annotation of own dataset

### ISSUE THREAD

**Issue by mprabhakarece** [dusty-nv/jetson-inference#1049]
Hi,

In this repo, Have provided help for downloading dataset.
Kindly help me with the tools for annotation of my own dataset.

Thanks and Regards,
Prabhakar M

**Comment by dusty-nv** [comment]
You can use CVAT tool at cvat.org to annotate detection dataset or the included camera-capture tool
________________________________
From: mprabhakarece ***@***.***>
Sent: Saturday, May 15, 2021 12:33:25 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] How to do annotation of own dataset (#1049)


Hi,

In this repo, Have provided help for downloading dataset.
Kindly help me with the tools for annotation of my own dataset.

Thanks and Regards,
Prabhakar M
