### ISSUE TITLE
How to filter the output of particular segmentation class

### ISSUE THREAD

**Issue by mprabhakarece** [dusty-nv/jetson-inference#1052]
Hi,
I can run the segmentation code successful.
Kindly let me know how to filter the particular class say I want to display only cars.

Thanks and Regards,
Prabhakar M

**Comment by dusty-nv** [comment]
The easiest way without retraining the model, would be to change the colors.txt file so that the other classes have the same color.

**Comment by mprabhakarece** [comment]
Thank you for the quick response.
Yes I can able to filter output by make colour of the other objects as same. 
Is it possible to do through coding.

Regards,
Prabhakar M

**Comment by dusty-nv** [comment]
I don't think so without changing the low-level post-processing code in `c/segNet.cpp`

If you are using the classID mask from segNet.Mask(), you can just ignore the classes you don't want.

**Comment by deemeetree** [comment]
Yes, you can, @mprabhakarece do it programmatically. You would probably need to render the original image using some other tool and overlay the bounding box on top.
