### ISSUE TITLE
pioled doesn't work

### ISSUE THREAD

**Issue by soyeon219** [dusty-nv/jetson-inference#1055]
I installed jetpack 4.3. In that state, I upgraded jetpack to 4.4. for mobilenet ssd. After that pioled won't turn on, libnvrtc.so.10.2: cannot open shared object file: No such file or directory
I also get this error.
Is this a problem that can be caused by upgrading?
If so, if I downgrade to jetpack 4.3 again, is there a way to run mobilenet ssd?

**Comment by dusty-nv** [comment]
Hi @soyeon219, are you building jetson-inference from source?    Try updating the repo and re-build the project.
