### ISSUE TITLE
How to download segmentation dataset for own training or retraining

### ISSUE THREAD

**Issue by mprabhakarece** [dusty-nv/jetson-inference#1056]
Hi,

Kindly help me how to download the segmentation dataset for own training or retraining

Thanks in advance

**Comment by dusty-nv** [comment]
There are various datasets used for the different segmentation models.  For example, cityscapes was downloaded from https://www.cityscapes-dataset.com/

There was then some data prep on the datasets, using scripts from under:  https://github.com/dusty-nv/jetson-inference/tree/master/tools
Sorry I don't have the procedure I followed at the time.

The 'dev' branch of pytorch-segmentation is used for training:   https://github.com/dusty-nv/pytorch-segmentation/tree/dev
Note that I have not tried running this on Jetson, it may be too intensive.
