### ISSUE TITLE
Questions on data transformation

### ISSUE THREAD

**Issue by Lyns01** [dusty-nv/jetson-inference#1062]
Hello,
I have a voc dataset with 100 labelled images and their corresponding annotations (a single class).
There is a file transform.py that has functions to do transformations on image (I guess).
Is there a way to augment my data i.e a way to increase the number of images and their annotations from 100 to 200 or 300, by transforming ( like cropping, flipping ) the images along with their annotations..?

**Comment by dusty-nv** [comment]
Hi @Lyns01, the augmentation is automatically performed on the training dataset:

* https://github.com/dusty-nv/pytorch-ssd/blob/8ed842a408f8c4a8812f430cf8063e0b93a56803/train_ssd.py#L202
* https://github.com/dusty-nv/pytorch-ssd/blob/8ed842a408f8c4a8812f430cf8063e0b93a56803/vision/ssd/data_preprocessing.py#L4
