### ISSUE TITLE
Training with Kaggle dataset: "RuntimeWarning: invalid value encountered in subtract   area_a = ((box_a[:, 2]-box_a[:, 0]) *"

### ISSUE THREAD

**Issue by alessandrolombardini** [dusty-nv/jetson-inference#1067]
I'm trying to train SDD (with MobileNet v2) with this dataset: https://www.kaggle.com/tensor2flow/head-detection-dataset

It is not in OpenImage or VOC annotations, so I convert it to the first one. The problem is that when the training starts the Loss is Nan, and I don't understand why.

I'm getting these warnings, but I don't understand them either:
![image](https://user-images.githubusercontent.com/43758625/119513148-3fd96580-bd74-11eb-85c8-069cd7cec661.png)
 
Some suggestions? Is it actually a good idea to convert my own dataset in this way? How can I do it in another way?

**Comment by dusty-nv** [comment]
It looks like there are invalid bounding boxes in your dataset.   Perhaps the coordinates are malformed such that `top > bottom` or `left > right`
