### ISSUE TITLE
Get different results on jetson with DIGITS on detectnet inference

### ISSUE THREAD

**Issue by pooluut** [dusty-nv/jetson-inference#107]
I'm using the detectnet on Jetson TX2.

I trained my models on DIGITS on PC
the inference result is:
![image](https://user-images.githubusercontent.com/7670423/28161543-74922f5a-67f6-11e7-8799-70553f0d53c6.png)

But I deploy my model to tx2, I got a different result on the same input image:
![output](https://user-images.githubusercontent.com/7670423/28161554-7ee2b86c-67f6-11e7-8976-cc5bc7550202.jpg)

I also modified the threshold of coverage, it doesn't work.
Any  ideas?

**Comment by Fistcar** [comment]
Did you ever find a solution? I am having a similar problem. Using digits I get the right answer for a multi-class detectnet, on TX2 I get a different wrong answer.

**Comment by dusty-nv** [comment]
Hi, does your network have a layer with mean value subtraction?  The DetectNet code performs mean subtraction.  You probably need to compute the mean pixel value and pass it to [`DetectNet::Create`](https://github.com/dusty-nv/jetson-inference/blob/058c88a182ee49bcefc83c0b9ac019f7ca449d80/detectNet.h#L106) function.  

Right now the default mean pixel value is setup for ImageNet, however I bet your license plate database may have a significantly different mean value.
