### ISSUE TITLE
how to change batchsize for models (like detection)

### ISSUE THREAD

**Issue by yuchen2580** [dusty-nv/jetson-inference#1078]
Hi,
This is a great repo and frankly it allows more flexibility compared to Deepstream.

However, I am facing a similar requirement with this repo #882 that may use more than 1 or 2 cameras, from the replies it seems we cannot increase batch size, like:
feeding a batch of imgs with size (2, 640,480, 3) to detection model. I assume it should run faster compared to feeding images twice. 

Could you provide more details in how to handling this case?

**Comment by dusty-nv** [comment]
Hi @yuchen2580, it requires modifying all the pre/post-processing for batched images, for simplicity today it uses batch=1.  If you are on Nano and doing detection with the models from this repo, the batching gains would probably be marginal.  For batching I recommend to use DeepStream.
