### ISSUE TITLE
disabling the log information

### ISSUE THREAD

**Issue by sulthanashafi** [dusty-nv/jetson-inference#108]
When compiling ,a long log information of each layer is appearing each time.how to disable the log information of [GIE] .

**Comment by dusty-nv** [comment]
Hi, to disable the layer profiling/timing info, please comment out this line in the program:

```
net->EnableProfiler();
```
For example, see [imagenet-console.cpp:60](https://github.com/dusty-nv/jetson-inference/blob/058c88a182ee49bcefc83c0b9ac019f7ca449d80/imagenet-console/imagenet-console.cpp#L60)

Disabling this function call will eliminate much of the output logging.
