### ISSUE TITLE
Use Custom models such as Mobilenetv1

### ISSUE THREAD

**Issue by nikunj95** [dusty-nv/jetson-inference#1097]
Hi,

Thank you for this repository and youtube videos. I want to train a custom model such as Mobilenet V1 on Jetson nano and I am not sure how to do this here. Could you provide some guidance or direct me to certain links in how to approach this?

Thanks!
Nikunj

**Comment by dusty-nv** [comment]
Hi, see this section for ResNet18 and SSD-Mobilenet:   https://github.com/dusty-nv/jetson-inference#training
________________________________
From: Nikunj Kotecha ***@***.***>
Sent: Thursday, June 10, 2021 6:30:19 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] Use Custom models such as Mobilenetv1 (#1097)


Hi,

Thank you for this repository and youtube videos. I want to train a custom model such as Mobilenet V1 on Jetson nano and I am not sure how to do this here. Could you provide some guidance or direct me to certain links in how to approach this?

Thanks!
Nikunj

**Comment by nikunj95** [comment]
Thanks for the response. This shows training with PyTorch. I am trying to use Tensorflow. Besides, Mobilenet V1 is not there in Pytorch models. Can you help with working training Tensorflow's model: https://www.tensorflow.org/api_docs/python/tf/keras/applications/MobileNet
