### ISSUE TITLE
Retraining ssd-mobilenet support

### ISSUE THREAD

**Issue by mabdelbari** [dusty-nv/jetson-inference#1098]
Hey,
First of all, thank you for this wonderful tutorial, it helped me a lot. 

I am working on retraining ssd-mobilenet on my own choices of the class list (about 6 classes).

I just wanna understand what --workers is used for and is it fine if I increase it or not?

Thanks in advance

**Comment by dusty-nv** [comment]
Hi, workers is the number of dataloader threads. They are only used for loading the images and not the actual training.  I'm not sure if you will see much benefit from increasing it or not.
________________________________
From: Mostafa Abdelbari ***@***.***>
Sent: Thursday, June 10, 2021 7:06:48 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] Retraining ssd-mobilenet support (#1098)


Hey,
First of all, thank you for this wonderful tutorial, it helped me a lot.

I am working on retraining ssd-mobilenet on my own choices of the class list (about 6 classes).

I just wanna understand what --workers is used for and is it fine if I increase it or not?

Thanks in advance

**Comment by mabdelbari** [comment]
Thanks for your response @dusty-nv  😄 

Yea... I got it.

What about increasing batch-size as I wanna increase the speed of training?

**Comment by dusty-nv** [comment]
batch size may increase it but if you are on Nano it may be marginal because the GPU is already pretty fully utilized
________________________________

**Comment by mabdelbari** [comment]
Indeed I am working on it from my laptop. So if I increase it, it will result in reducing training time?

**Comment by dusty-nv** [comment]
Ah, yes in that case it should
________________________________

**Comment by mabdelbari** [comment]
Thanks for your help. I appreciate it 😃
