### ISSUE TITLE
How to cite this repository?

### ISSUE THREAD

**Issue by priyaganaboor-hash** [dusty-nv/jetson-inference#1100]
@dusty-nv How to cite this repository, in my thesis?

**Comment by dusty-nv** [comment]
Hi @priyaganaboor-hash, are you able to cite it like shown here?   https://academia.stackexchange.com/a/14015

**Comment by priyaganaboor-hash** [comment]
@dusty-nv thanks

@misc{2,
  author = {Dustin Franklin},
  title = {jetson-inference},
  year = {2016-2019},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/dusty-nv/jetson-inference}},
}
