### ISSUE TITLE
How to run run_ssd_example.py

### ISSUE THREAD

**Issue by anish-faiz** [dusty-nv/jetson-inference#1101]
How to run run_ssd_example.py with real time video streaming using VGG-16. can you give a clear program for that, waiting for your response.

**Comment by dusty-nv** [comment]
VGG-16 is a classification network, ssd is for object detection.   video streaming is done through imagenet/imagenet.py samples for classification, and detectnet/detectnet.py for object detection.

**Comment by anish-faiz** [comment]
Is it possible for me to load VGG16-SSD on detectnet.py
I tried to load but I'm not having skeleton for VGG16-SSD network on detectnet.py
So I have tested with run_ssd_example.py. Now I have to go with video streaming.
Please help me sir...
