### ISSUE TITLE
Easy way to install pyTorch with  Gpu /Cuda support on Jetson nano

### ISSUE THREAD

**Issue by SaddamBInSyed** [dusty-nv/jetson-inference#1104]
@dusty-nv 

I have my new Jetson nano device here and would like to install PyTorch with GPU support.

Can you please advise the easiest way to install PyTorch with  GPU / Cuda support on Jetson nano?

I have tried several methods but no luck still ?

thank you

**Comment by dusty-nv** [comment]
If you run the jetson-inference container, it already has PyTorch with GPU installed in the container.

For the PyTorch wheels, see this thread:  https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048
________________________________
From: SaddamBinSyed ***@***.***>
Sent: Monday, June 14, 2021 4:24:04 AM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Dustin Franklin ***@***.***>; Mention ***@***.***>
Subject: [dusty-nv/jetson-inference] Easy way to install pyTorch with Gpu /Cuda support on Jetson nano (#1104)


@dusty-nv<https://github.com/dusty-nv>

I have my new Jetson nano device here and would like to install PyTorch with GPU support.

Can you please advise the easiest way to install PyTorch with GPU / Cuda support on Jetson nano?

I have tried several methods but no luck still ?

thank you

**Comment by SaddamBInSyed** [comment]
@dusty-nv 
S. I have followed this "https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048" thread .

now torch running on my cuda.

Thank you
