### ISSUE TITLE
About Int8

### ISSUE THREAD

**Issue by jack55436001** [dusty-nv/jetson-inference#111]
Hello I want to know if Tx2 support Int8
and how to modify the code to support Int8 on Tx2
I try following code 
	builder->setInt8Mode(true);
	nvinfer1::IInt8Calibrator* calibrator;
	builder->setInt8Calibrator(calibrator);
But got error
Did everyone have some hints?

**Comment by dusty-nv** [comment]
Hi, TX2 doesn’t support INT8.  Xavier has been announced to include it, though.

**Comment by jack55436001** [comment]
Thanks a lot!!
