### ISSUE TITLE
Can't download pre-train Inception-v4 caffe 

### ISSUE THREAD

**Issue by SokPhanith** [dusty-nv/jetson-inference#1111]
sorry when I run ./download-models.sh and then space to Inception-v4 for download but the script skip for download this model.
from : https://github.com/SnailTyan/caffe-model-zoo/tree/master/Inception-v4 I can't find pre-trian too.

**Comment by dusty-nv** [comment]
Hi @SokPhanith, you can find it on this page also:  https://github.com/dusty-nv/jetson-inference/releases/tag/model-mirror-190618

**Comment by SokPhanith** [comment]
Thank you so much @dusty-nv

**Comment by SokPhanith** [comment]
sorry, How can I download train_val.prototxt and solver.prototxt with model : resnet50 resnet101 resnet152 that using train for caffe. I can't fine at path : jetson-inference/data/networks

**Comment by dusty-nv** [comment]
I believe these models originally came from here:  https://github.com/KaimingHe/deep-residual-networks

There appears to only be the deploy prototxt
