### ISSUE TITLE
Can I use/build jetson-inference on my x64 host PC?

### ISSUE THREAD

**Issue by sardanian** [dusty-nv/jetson-inference#1116]
I'd like to develop on my desktop vs. on the Jetson. Can I install these packages on my hose machine? I'd also like to be able to use the ROS packages from my desktop vs. having to use it on a jetson. Is that also possible?

Thank you.

**Comment by dusty-nv** [comment]
Hi @sardanian, I believe some other folks have compiled this project on x86 (Ubuntu) once they installed CUDA Toolkit and TensorRT, however I don't formally support it in the repo.   

For ROS, you can install ROS on PC the normal way you would.  If you are referring to my ros_deep_learning, if you get jetson-inference built/installed on x86 then you should be able to build ros_deep_learning too
