### ISSUE TITLE
compile jetson inference error cmake

### ISSUE THREAD

**Issue by syliabe** [dusty-nv/jetson-inference#1120]
Hello, 
I am trying to run jetson inference cmake ../ I get this error

thanks
![Screenshot from 2021-06-21 13-34-55](https://user-images.githubusercontent.com/86236508/122755762-c3b04000-d295-11eb-89fc-79f45074db4a.png)

**Comment by dusty-nv** [comment]
Hi @syliabe, it doesn't look like your Jetson was setup with CUDA Toolkit (and probably not TensorRT either)

If you are using the Nano or Xavier NX devkit, CUDA should already come pre-installed on the SD card images.

If you are using another Jetson that you flashed with SDK Manager, run SDK Manager again from your PC and have it install CUDA, cuDNN, TensorRT, ect to your Jetson device.

**Comment by syliabe** [comment]
sorry I did not specify that I am working on an x64  pc

**Comment by syliabe** [comment]
is there a specific version (CUDA Toolkit / cuDNN / TensoRrt? or any?

**Comment by dusty-nv** [comment]
I would suggest CUDA 10.2, cuDNN 8, and TensorRT 7.1 because this is what the Jetson currently runs in JetPack 4.5 (and hence those versions I have tested)

**Comment by syliabe** [comment]
Thanks
