### ISSUE TITLE
How to evaluate trained models?

### ISSUE THREAD

**Issue by zoeyhl** [dusty-nv/jetson-inference#1123]
Hi, now I have my trained custom model from jetson-inference/python/training/segmentation/train.py, and I need to evaluate the model again. But how can we evaluate our trained model? I didn't find any file related to evaluation, so I just want to make sure if I miss anything. Thank you!

**Comment by dusty-nv** [comment]
Hi @zoeyhl, there is an `eval_ssd.py` script - https://github.com/dusty-nv/pytorch-ssd/blob/master/eval_ssd.py

However I haven't used it, so YMMV.  It came from the upstream author.

**Comment by zoeyhl** [comment]
Thank you, I will try that!
