### ISSUE TITLE
Convert output to excel 

### ISSUE THREAD

**Issue by Ehtasham782** [dusty-nv/jetson-inference#1131]
Hey,
Myself Ehtasham ali and I'm folloingw your instruction for object detection. Is there is any way to convert the output into excel sheet
Thank you

**Comment by saifurrehman4114** [comment]
https://github.com/dusty-nv/jetson-inference/blob/master/python/examples/detectnet.py#L69

Beneath this line paste this line inside the loop and save the results of detected in the variable and use excel python package for excel operations :[](https://pypi.org/project/openpyxl/
)

`net.GetClassDesc(detection.Instance)`
