### ISSUE TITLE
detectnet command in Retraining ssd mobilenet

### ISSUE THREAD

**Issue by mabdelbari** [dusty-nv/jetson-inference#1133]
Hey @dusty-nv 
First of all, thank you for your wonderful tutorial..

I just wanna know which file is executed when i write the command below:

detectnet --model=models/fruit/ssd-mobilenet.onnx --labels=models/fruit/labels.txt 
          --input-blob=input_0 --output-cvg=scores --output-bbox=boxes \
            csi://0

as i wanna make some customization for the output such as resizing the output window, title of the window .. etc

and for further if i wanna calculate the distance from the detected object

Thanks in advance

**Comment by dusty-nv** [comment]
Hi @mabdelbari, that is the C++ detectnet example found under jetson-inference/examples/detectnet/detectnet.cpp

There is also detectnet.py from jetson-inference/python/examples/detectnet.py

**Comment by mabdelbari** [comment]
I tried to edit on the detectnet.py from jetson-inference/python/examples/detectnet.py 
but nothing changed although I used the command below 

detectnet.py --model=models/fruit/ssd-mobilenet.onnx --labels=models/fruit/labels.txt
--input-blob=input_0 --output-cvg=scores --output-bbox=boxes
csi://0

**Comment by dusty-nv** [comment]
After you make changes to ` jetson-inference/python/examples/detectnet.py`, you need to re-run cmake to copy it into the bin directory:

``` bash
$ cd /path/to/your/jetson-inference
$ cd build
$ cmake ../
```

**Comment by mabdelbari** [comment]
I tried to edit on both py and cpp files and after editing, I did execute cmake but still no changes happened

**Comment by dusty-nv** [comment]
Are you using the docker container, or not docker container?
________________________________

**Comment by mabdelbari** [comment]
Nope. i am not using docker container

**Comment by dusty-nv** [comment]
Hmm ok.  If you run `cd jetson-inference/python/examples` and run `detectnet.py` from there, do you see your modifications taking effect?

**Comment by mabdelbari** [comment]
i executed the command `detectnet.py --model=../training/detection/ssd/models/fruit/ssd-mobilenet.onnx --labels=../training/detection/ssd/models/fruit/labels.txt --input-blob=input_0 --output-cvg=scores --output-bbox=boxes csi://0` inside `jetson-inference/python/examples` but still no changes 

and I tried to add python3 before detectnet.py, I started to see some changes but there's no output window

**Comment by dusty-nv** [comment]
> and I tried to add python3 before detectnet.py, I started to see some changes but there's no output window

Perhaps the changes you made changed or precluded the use of the output window?

**Comment by mabdelbari** [comment]
Nope I only changed some text of the print statements

**Comment by dusty-nv** [comment]
Also, I forgot that maybe you need `sudo make install` also to pick up your changes:

``` bash
$ cd /path/to/your/jetson-inference/build
$ cmake ../
$ make
$ sudo make install
```

You should then be able to run your updated `detectnet.py` from anywhere

**Comment by mabdelbari** [comment]
Yeah, it works now :) 
Many thanks for your help, I appreciate it :)

I just have another point, I only see a part of the whole image, so how can i fit it on my screen at once?

**Comment by dusty-nv** [comment]
> is there any way to calculate the distance of the object from the camera?

Doing that would require depth camera, or known object size and camera calibration.  https://www.pyimagesearch.com/2015/01/19/find-distance-camera-objectmarker-using-python-opencv/

**Comment by mabdelbari** [comment]
I am a little confused.. "depth camera" do you mean dual camera?
and how can I know object size in real-time streaming?

**Comment by dusty-nv** [comment]
Yes, either a stereo camera or a RGBD camera like the Realsense
