### ISSUE TITLE
multiped-500 : dataset used for luggage detection

### ISSUE THREAD

**Issue by MattVAD** [dusty-nv/jetson-inference#1136]
Hi there ! 

Which datasets you used for that model (multiped-500) in order to train the luggage detection ? 

Many thanks in advance, your dear AI friend 😍

**Comment by saifurrehman4114** [comment]
"Hi @bpinaya, the multiped-500 model used a few different datasets, including KITTI and some internal datasets that are unable to be released at this time. All datasets were in KITTI format however, as that's what DIGITS uses for parsing object detection ground truth data. So I recommend starting with KITTI and MS-COCO, as the KITTI converter for MS-COCO is provided. Cityscapes is a good dataset for pedestrian too, however it's not KITTI format but rather segmentation. Technically segmentation could be used for pedestrian detection also, just not providing the bounding boxes (but potentially supporting many more classes simultaneously)."

https://github.com/dusty-nv/jetson-inference/issues/132
