### ISSUE TITLE
CUDA initialization failure while building

### ISSUE THREAD

**Issue by senturank** [dusty-nv/jetson-inference#1138]
![WhatsApp Image 2021-07-01 at 3 17 41 PM](https://user-images.githubusercontent.com/32015705/124104834-4a2c0500-da80-11eb-9b60-ca3fc30469c1.jpeg)

We are getting a CUDA initialization failure while trying to build the package. I am using a Jetson Nano production SOM and have installed all the required packages including CUDA using the SDK manager. I even tried uninstalling & reinstalling CUDA, flashing the SD card again, but the issue persists. We did not face this issue when we were testing out on the Nano Devkit though.

Any help will be highly appreciated.

**Comment by dusty-nv** [comment]
Hi @senturank, do you see the CUDA toolkit under `/usr/local/cuda` ?  Can you build and run the `deviceQuery` sample?

**Comment by senturank** [comment]
Hi @dusty-nv ,
I do see the CUDA toolkit under /usr/local/cuda. But the Device query is showing errors.
![WhatsApp Image 2021-07-02 at 11 00 23 AM](https://user-images.githubusercontent.com/32015705/124226914-75b5fa80-db27-11eb-93c6-30f4e0c04288.jpeg)

I have also attached a screenshot of our nvcc version. Not able to figure our what I am doing wrong.
![WhatsApp Image 2021-07-02 at 11 10 03 AM](https://user-images.githubusercontent.com/32015705/124227017-9b430400-db27-11eb-9343-46b9875e28d4.jpeg)

**Comment by dusty-nv** [comment]
It seems that your CUDA driver / toolkit got it a bad state somehow, perhaps it was inadvertently upgraded.   I would backup your work and reflash the device.
