### ISSUE TITLE
annotate own data

### ISSUE THREAD

**Issue by syliabe** [dusty-nv/jetson-inference#1140]
Hello,

Please, is there a tool to make automatic annotations of my own data, because manual annotation takes a lot of time?
I tried with cvat.org,  on the other hand it cannot annotate all the existing object in an image

thank you

**Comment by dusty-nv** [comment]
Hi @syliabe, CVAT is more comprehensive than I could provide and support myself.  What do you mean when you say it can't annotate all the objects?

**Comment by syliabe** [comment]
I mean in an image if I have 4 person to annotate,  the CVAT annotate just 2 instead of 4 person

**Comment by dusty-nv** [comment]
I have annotated many objects per image with CVAT, more than 4.  Are you able to add more bounding boxes?

**Comment by syliabe** [comment]
![image](https://user-images.githubusercontent.com/86236508/124619371-e424f080-de78-11eb-95ed-c7e72627f491.png)

on my side I select automatic annotation as shown in the image above
then i downloaded it as long as pascal voc data,
we can do manual annotation but I want to avoid it as much as possible

**Comment by syliabe** [comment]
![image](https://user-images.githubusercontent.com/86236508/124620037-6ad9cd80-de79-11eb-8ed0-4feb5b6ec547.png)


on my side I select automatic annotation as shown in the image above
then i downloaded it as long as pascal voc data,
we can do manual annotation but I want to avoid it as much as possible
