### ISSUE TITLE
Easiest way to convert inference resolution arbitrarily for SSD-Mobilenet-v2?

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [dusty-nv/jetson-inference#1149]
Title.

**Comment by dusty-nv** [comment]
You need to re-train the model and make modifications to the pytorch_ssd source code.  See this post:

https://forums.developer.nvidia.com/t/how-train-jetson-inference-ssd512-model/168510/6?u=dusty_nv

**Comment by rocketsfallonrocketfalls** [comment]
Hey @dusty-nv, thanks for the lightning-fast answer!

I've already read that post in depth, but I am still confused. How will changing the input resolution affect the priors? 

What considerations that I should make defining the priors based in an input size, say I want to use `832x832`?

**Comment by dusty-nv** [comment]
Also see https://github.com/dusty-nv/jetson-inference/issues/931#issuecomment-846808434

**Comment by dusty-nv** [comment]
> What considerations that I should make defining the priors based in an input size, say I want to use `832x832`?

See the script from https://github.com/dusty-nv/jetson-inference/issues/931#issuecomment-846808434 for generating priors for other sizes

**Comment by rocketsfallonrocketfalls** [comment]
Thanks a lot, @dusty-nv!
