### ISSUE TITLE
Overlay output accuracy in segmentation

### ISSUE THREAD

**Issue by mprabhakarece** [dusty-nv/jetson-inference#1150]
Hi,

I have trained a model with my own dataset for segmentation. Everything is fine. But still I want to get clarified with few things.
In image everything looks fine. When we run with video I have some problems.

1. Say the overlay mask boundary is not smooth with the objects[looks like square boxes].
2. Boundary of the overlay mask looks like blinking when running with videos
3. Looks like little overlap between the objects in output

Kindly give suggestion to overcome above problems and please guide me to understand the reason behind the problems.

Thanks and Regards,
Prabhakar M

**Comment by dusty-nv** [comment]
You can train on higher-resolution data to increase the resolution of the output/overlay mask - however this will lead to longer execution times.
