### ISSUE TITLE
RuntimeError: Only one file(not dir) is allowed in the zipfile

### ISSUE THREAD

**Issue by dickang** [dusty-nv/jetson-inference#1155]
Hello @dusty-nv 
to launch the training, run the following commands :  python3 train.py --model-dir=models/cat_dog data/cat_dog.
But this is a mistake： RuntimeError: Only one file(not dir) is allowed in the zipfile

How to solve this problem?

Thank you!

**Comment by dusty-nv** [comment]
Hmm it seems like the pre-trained resnet18 model that PyTorch automatically downloads may be corrupted.  Can you try restarting the container, or if not using container deleting ~/.torch
________________________________
From: dickang ***@***.***>
Sent: Monday, July 19, 2021 1:42:34 AM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Dustin Franklin ***@***.***>; Mention ***@***.***>
Subject: [dusty-nv/jetson-inference] RuntimeError: Only one file(not dir) is allowed in the zipfile (#1155)


Hello @dusty-nv<https://github.com/dusty-nv>
to launch the training, run the following commands : python3 train.py --model-dir=models/cat_dog data/cat_dog.
But this is a mistake： RuntimeError: Only one file(not dir) is allowed in the zipfile

How to solve this problem?

Thank you!
