### ISSUE TITLE
Batch inferencing in detectnet.py

### ISSUE THREAD

**Issue by tensorturtle** [dusty-nv/jetson-inference#1158]
I see in detectnet.h line 64, that there is an option for --batch-size. https://github.com/dusty-nv/jetson-inference/blob/19ed62150b3e9499bad2ed6be1960dd38002bb7d/c/detectNet.h#L64-L88

After I set this flag,
How would I pass in a batch of images to net.Detect() for batch inferencing?

**Comment by dusty-nv** [comment]
@tensorturtle batch processing isn't implemented in the API.  recommend that you use DeepStream for batching.

**Comment by tensorturtle** [comment]
Okay, thank you for your reply!
