### ISSUE TITLE
how to use serial in container?

### ISSUE THREAD

**Issue by whxhwhx** [dusty-nv/jetson-inference#1160]
I want to use the serial in the container . And I did not see the relevant parameters in command “docker/run --help”. How can I mount the serial port to the container?

**Comment by dusty-nv** [comment]
Hi @whxhwhx, I haven't done this before myself - you might want to see if the steps from this article work:

https://www.losant.com/blog/how-to-access-serial-devices-in-docker

You can edit the [`sudo docker run`](https://github.com/dusty-nv/jetson-inference/blob/19ed62150b3e9499bad2ed6be1960dd38002bb7d/docker/run.sh#L168) command inside the `docker/run.sh` script as needed.

**Comment by whxhwhx** [comment]
I was struggling with how to edit the "run.sh" script yesterday, and then I added a command "--device /dev/ttyTHS1:/dev/ttyTHS1" according to your suggestion.
It working. 
Thank you.
