### ISSUE TITLE
How to check gstreamer changed state from READY to PAUSED i.e. [gstreamer] gstCamera end of pipeline using python api?

### ISSUE THREAD

**Issue by NISHANTSHRIVASTAV** [dusty-nv/jetson-inference#1161]
Hello All,

For reading live input stream we are using **jetson.utils.videoSource** python API.

_input = jetson.utils.videoSource('/dev/video2', argv=sys.argv)
img = input.Capture()_

But gstreamer pipeline get PAUSED and the program execution is getting stuck at img=input.capture() line in code.

We also applied this logic to check whether streaming is working or not using the below code snippet:
 
_if input.IsStreaming():
      img = input.Capture()_
       
But input.IsStreaming() returns False when the streaming is open. Is this IsStreaming() function working properly?

So, How to check what is the state of the GStreamer pipeline and start the GStreamer pipeline again using python API?

**Comment by dusty-nv** [comment]
`input.IsStreaming()` will only return true after you call `input.Capture()` once or call `input.Open()`

`input.Capture()` will implicitly call `input.Open()` for you if the stream hasn't already been opened.

**Comment by NISHANTSHRIVASTAV** [comment]
Thanks, it worked after giving a passing timeout argument i.e input.Capture(timeout=10000)
