### ISSUE TITLE
ImportError:failed to load Pytorch C extensions:It appears that Pytorch has loaded the ‘torch/_C’ folder of the Pytorch repository rather than the C extensions which are expected in the ‘torch._C’ namespace.

### ISSUE THREAD

**Issue by baikaishui35** [dusty-nv/jetson-inference#1169]
I am using Jetson agx xavier from nvida.
jetpack4.4 ubuntu18.04 CUDA 10.02.
Now i want to download torch into this ARM, here is how Nvida tells me to do.
![image](https://user-images.githubusercontent.com/88184005/127620014-37cd6557-1dbe-498b-b132-4436f4b93d02.png)
But my internet can not do the first step ,i can not wget https://nvida.box.com.
So i download it by chrom, then pip install and import it into pycharm.
Then i see this error, it has bother me for a half month.
![image](https://user-images.githubusercontent.com/88184005/127620256-5c7a8033-c190-4324-8007-e175feea3f7a.png)
ImportError:failed to load Pytorch C extensions:It appears that Pytorch has loaded the ‘torch/_C’ folder of the Pytorch repository rather than the C extensions which are expected in the ‘torch._C’ namespace.This can occur when using the ‘install’ workflow.
$ pthon setup.py install && python -c “import torch”
This error can generally be solved using the ‘develop’ work flow
$ python setup.py develop &&python -c “import torch” #This should succeed or by running Python from a different directory.

I find this error from the init.file:
![image](https://user-images.githubusercontent.com/88184005/127620297-dfd2a090-fe57-49f0-ac81-ed6233e24b48.png)
My anaconda is python3.7, then i see this and change it to python3.6. And then i see this error:
![image](https://user-images.githubusercontent.com/88184005/127620328-0f713a86-d34d-4b70-bff7-c8c71886ce96.png)
The both error bothered me for a long time, i really hope someone to save me.

**Comment by dusty-nv** [comment]
> But my internet can not do the first step ,i can not wget https://nvida.box.com.
> So i download it by chrom, then pip install and import it into pycharm.

I'm not sure about the error or chrom, but are you able to access other filesharing sites like Google Drive?   Are you able to use a VPN to access?

Here is a link to the PyTorch 1.8 wheel on Google Drive:  https://drive.google.com/file/d/1UYMxM_NO3gUZsnfGzvAUmawOyZuYtrr4/view?usp=sharing

If that doesn't work, I recommend using the [l4t-pytorch container](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch), which you should be able to access I think.
