### ISSUE TITLE
failed to capture video frame/realsense - sr300

### ISSUE THREAD

**Issue by CailynH** [dusty-nv/jetson-inference#1170]
when I connect the sr300 as the camera and use the command like 
detectnet --model=models/fruit/ssd-mobilenet.onnx --labels=models/fruit/labels.txt \
          --input-blob=input_0 --output-cvg=scores --output-bbox=boxes \
          /dev/video0
then error appear
![图片](https://user-images.githubusercontent.com/58588363/127642735-49d2242a-c432-413f-a713-9d1a19cc4ded.png)

**Comment by arvind-nd** [comment]
1.make sure you connected camera before starting jetson nano
2.try to run below code
`$ video-viewer v4l2:///dev/video0                 # /dev/video0 can be replaced with /dev/video1, ect.
$ video-viewer /dev/video0                        # dropping the v4l2:// protocol prefix is fine
$ video-viewer /dev/video0 output.mp4             # save output stream to MP4 file (H.264 by default)
$ video-viewer /dev/video0 rtp://<remote-ip>:1234 # broadcast output stream over RTP to <remote-ip>
`
3.or try to run command for view camera(by which you can see camera is working)

above code is from https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md
