### ISSUE TITLE
Docker RUN

### ISSUE THREAD

**Issue by syliabe** [dusty-nv/jetson-inference#1173]
Hello,

I am wondering if I can use docker on a pc by changing the architecture from linux / arm to linux / x86_x64?
What are the steps to follow please,

I have already succeeded in completing the project from the sources on the PC, by specifying compute from my gpu card, but for the docker, I don't know much about it ..
do I have to create a new image? or used the one on this link? https://hub.docker.com/r/dustynv/jetson-inference/tags?page=1&ordering=last_updated

thanks

**Comment by dusty-nv** [comment]
Forum cross-post:  https://forums.developer.nvidia.com/t/docker-run-jetson-inference/185633
