### ISSUE TITLE
(jetson-inference) Error in training image classification model

### ISSUE THREAD

**Issue by b2992872** [dusty-nv/jetson-inference#1184]
I run the camera to test my model. My "val" folder has 100 training photos, and there are 20 photos in the "train" folder, but the result is 100% regardless of whether there is a target or not.

So far, the content is the same as in the example https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect.md Not sure what happened to the training process, thank you I need some help.

![116](https://user-images.githubusercontent.com/61401570/128795882-ef51cf8e-7404-4b8d-b901-dac185f32c8f.png)
![117](https://user-images.githubusercontent.com/61401570/128795885-c8b3e367-15bd-4de7-8d65-2a45be52aca9.png)

**Comment by dusty-nv** [comment]
> My "val" folder has 100 training photos, and there are 20 photos in the "train" folder

Hi @b2992872, you should have that reversed - val folder should have 20 photos, while train folder should have 80 photos.  You can just move them from one folder to another by renaming the folders in the file browser or with the `mv` command.

Then train your model again.  If it still isn't working well, you probably need even more photos in train folder.

**Comment by b2992872** [comment]
Now there are 20 training photos in my "val" folder and 200 photos in the "train" folder, but the result is the same. My training images contain different lights. Is there any other problem?

**Comment by dusty-nv** [comment]
Oh, try exporting the ONNX model again and deleting the .engine file so that TensorRT regenerates it.

What accuracy did PyTorch train the model to?
________________________________

**Comment by b2992872** [comment]
This is the training result
![118](https://user-images.githubusercontent.com/61401570/128953970-a7961ea9-0d19-4160-974d-8b6a761d5073.png)

**Comment by dusty-nv** [comment]
At the beginning of training, how many classes does it find?

In your train folder, how many images are in each class sub-folder?
________________________________

**Comment by b2992872** [comment]
I only have one category. There are 20 photos in the "val" folder, 200 training photos in the "train" folder, and no photos in the "test" folder.

**Comment by b2992872** [comment]
After I am sure that both categories are found, everything is normal, thank you very much!
