### ISSUE TITLE
fatal error: connect_parts.hpp

### ISSUE THREAD

**Issue by BiCffQ** [dusty-nv/jetson-inference#1188]
/home/x/jetson-inference/c/poseNet.cpp:32:10: fatal error: connect_parts.hpp: 没有那个文件或目录
 #include "connect_parts.hpp"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/jetson-inference.dir/build.make:1207: recipe for target 'CMakeFiles/jetson-inference.dir/c/poseNet.cpp.o' failed
make[2]: *** [CMakeFiles/jetson-inference.dir/c/poseNet.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jetson-inference.dir/all' failed
make[1]: *** [CMakeFiles/jetson-inference.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Jason-xy** [comment]
Hi, did you solve this error？I have met the same situation today >_<

**Comment by dusty-nv** [comment]
Did you clone the repo with `--recursive`?   It seems like the `jetson-inference/plugins/pose` submodule is missing

**Comment by Jason-xy** [comment]
> Did you clone the repo with `--recursive`? It seems like the `jetson-inference/plugins/pose` submodule is missing
Hi Dusty,
Thank you so much for your suggestion! As you said, I successfully completed the build after re-cloning the repository. Probably due to network reasons, the submodule was not successfully cloned.  Thanks!
