### ISSUE TITLE
use the middle layer as output?

### ISSUE THREAD

**Issue by Toyotomi** [dusty-nv/jetson-inference#119]
I'm trying detect object by use ./detectnet-console and ./detectnet-camera
Can I use the middle layer as output?
For example, "conv2/3x3[34]" ( I want to output 34th in conv2/3x3 layers.)

$ NET=/home/nvidia/jetson-inference/build/aarch64/bin/Detect
$ ./detectnet-console test.bmp output.bmp --prototxt=$NET/deploy.prototxt --model=$NET/Test.caffemodel --input_blob=data --output_cvg = conv2/3x3[34] --output_bbox=bboxes --threshold=200

detectNet -- loading detection network model from:
          -- prototxt    /home/nvidia/jetson-inference/build/aarch64/bin/Detect/deploy.prototxt
          -- model       /home/nvidia/jetson-inference/build/aarch64/bin/Detect/Test.caffemodel
          -- input_blob  'data'
          -- output_cvg  'conv2/3x3[34]'
          -- output_bbox 'bboxes'
          -- threshold   200.000000
          -- batch_size  2

[GIE]  attempting to open cache file /home/nvidia/jetson-inference/build/aarch64/bin/Detect/Test.caffemodel.2.tensorcache
[GIE]  cache file not found, profiling network model
[GIE]  platform has FP16 support.
[GIE]  loading /home/nvidia/jetson-inference/build/aarch64/bin/Detect/deploy.prototxt /home/nvidia/jetson-inference/build/aarch64/bin/Detect/Test.caffemodel
[GIE]  failed to retrieve tensor for output 'conv2/3x3[34]'
[GIE]  retrieved output tensor 'bboxes'
[GIE]  configuring CUDA engine
[GIE]  building CUDA engine
Segmentation fault (core dumped)

Thanks.

**Comment by dusty-nv** [comment]
Hi, to get middle layer as output, you need to send the layer name in the `output_blobs` array passed to [`tensorNet::LoadNetwork()`](https://github.com/dusty-nv/jetson-inference/blob/master/tensorNet.cpp#L213).   You will probably need to modify the `segNet` class code to do that.   

The blobs named in `output_blobs` array get tagged in TensorRT as output layers.   An object will be added to [`tensorNet::mOutputs`](https://github.com/dusty-nv/jetson-inference/blob/f41f1c06f8fd31e17069d69f5822e0864026ac2f/tensorNet.h#L204) array corresponding to that blob.
