### ISSUE TITLE
data augmentation transforms: RandomResizedCrop not available

### ISSUE THREAD

**Issue by silent-code** [dusty-nv/jetson-inference#1190]
Hi Dusty, I'm trying to do data augmentation using pytorch's RandomResizedCrop. However it does not appear to be included in the ssd vision transforms used in jetson-inference. 

I was wondering why the data augmentation transforms offered in the jetson-inference torchvision [here](https://github.com/dusty-nv/pytorch-ssd/blob/master/vision/transforms/transforms.py) vs. [the original](https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py) are not the same?

Thanks for your help!

**Comment by dusty-nv** [comment]
> I was wondering why the data augmentation transforms offered in the jetson-inference torchvision [here](https://github.com/dusty-nv/pytorch-ssd/blob/master/vision/transforms/transforms.py) vs. [the original](https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py) are not the same?

Hi @silent-code, I'm not exactly sure, if think the original upstream author wanted to use cv2 to do the transformations so they could more easily do realtime cv demo?   https://github.com/qfgaohao/pytorch-ssd

Not sure - some of them seem custom for bounding box data / ect.

**Comment by silent-code** [comment]
Ah I see. Thanks for the quick response Dusty.
