### ISSUE TITLE
re-training of SSD network

### ISSUE THREAD

**Issue by syliabe** [dusty-nv/jetson-inference#1193]
Hello,

I opted for a re-training of SSD network, one for the detection of people and the other for the detection of the vehicles, after several tests, I noticed that the precision is always the same, no improvement of the networks knowing that I have well increase the database (openImage) and also epoch/batch-size of each network,
I did tests with my own data the precision is reduced!

Any suggestions please?

Thanks

**Comment by dusty-nv** [comment]
Forum cross-post here:  https://forums.developer.nvidia.com/t/re-training-of-ssd-network/186646/

**Comment by sridhatta** [comment]
Can you please elaborate on the metrics you got after training and what was the training all about(is it finetuning) and how did u increase on the size of the dataset?
