### ISSUE TITLE
.../tensorNet.h(183): error: expected an identifier

### ISSUE THREAD

**Issue by NicolasBilberry** [dusty-nv/jetson-inference#120]
Hi,

I'm trying to integrate the segNet example in another project and I get this error I don't manage to understand : 
".../tensorNet.h(183): error: expected an identifier".

The corresponding code is : 
struct outputLayer
	{
		std::string name;
		Dims3 dims;
		uint32_t size;
		float* CPU;
		float* CUDA;          <--- line 183
	};

I managed to build and execute the example alone and I haven't changed anything in tensorNet.h/.cpp, neither in segNet.h/.cpp during the implementation so I have no idea what could have brought this issue.

Any idea ?

Thanks a lot !

**Comment by dusty-nv** [comment]
Hello, if you pull from master using the latest JetPack on your TX1/TX2, you should now get it to build ok.
