### ISSUE TITLE
How to capture HDMI input for detectnet?

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#1222]
Hi,

My project is to get the hdmi input for the detectnet. I have bought a HDMI-to-USB adapter and HDMI-to-csi board, but both fail to capture the video...
It will be funny that I need to use a csi camera to look at a monitor for detectnet. :<

I have searched the nvidia forum but don't get the right answer. May I know the criteria format for the detectnet to capture the video? YUV422? Is there any code I can modify for my capturing device?
And is there any cheap HDMI capturing device that work with nano? Thx

This is my question in nvidia forum, thx
https://forums.developer.nvidia.com/t/input-video-from-usb-capturing-device-core-dump-in-video-viewer-detectnet/188812/4

**Comment by dusty-nv** [comment]
Closing this issue as it was resolved on the forum thread.
