### ISSUE TITLE
finding coordinates of key points in Posenet 

### ISSUE THREAD

**Issue by aliszs** [dusty-nv/jetson-inference#1233]
Hi Dusty,
Thanks for the interesting tutorials of jetson nano,
is there any function in class PoseNet() to return the exact coordinates of a special key point?
I wanna compare them for distinguish some simple gesture

**Comment by dusty-nv** [comment]
Hi @aliszs, yes see this example code:  

https://github.com/dusty-nv/jetson-inference/blob/master/docs/posenet.md#working-with-object-poses

It gets the coordinates of specific key points.
