### ISSUE TITLE
nvinfer1::IExecutionContext  cannot destroy()

### ISSUE THREAD

**Issue by guduzhixing** [dusty-nv/jetson-inference#1235]
I have NVIDIA Jetson Xavier NX(4.4.1),then I find some error in https://github.com/dusty-nv/jetson-inference/blob/master/c/tensorNet.cpp : 1378
```
mContext = context;
```
this mContext can not destory in tensorNet::~tensorNet(),for example my code is 
```
// Destructor
tensorNet::~tensorNet()
{
	if( mEngine != NULL )
	{
		mEngine->destroy();
		mEngine = NULL;
	}
		
	if( mInfer != NULL )
	{
		mInfer->destroy();
		mInfer = NULL;
	}

	if( mContext != NULL )
	{
		mContext->destroy();
		mmContextnfer = NULL;
	}
}
```
run code printf error info is 
Thread 1 "test_upedester_" received signal SIGSEGV, Segmentation fault.
0x0000007faa78e8e4 in nvinfer1::rt::SafeExecutionContext::~SafeExecutionContext() () from /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
(gdb) bt
#0  0x0000007faa78e8e4 in nvinfer1::rt::SafeExecutionContext::~SafeExecutionContext() () at /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#1  0x0000007faa50eaa4 in nvinfer1::rt::ExecutionContext::~ExecutionContext() () at /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#2  0x0000007faa50eb94 in nvinfer1::rt::ExecutionContext::~ExecutionContext() () at /usr/lib/aarch64-linux-gnu/libnvinfer.so.7
#3  0x0000007fb7b0a71c in tensorNet::~tensorNet() (this=0x5556859980, __in_chrg=<optimized out>)

if not destory mContext,when constantly creating and destroying objects, memory will continue to increase
But, I add code in  https://github.com/dusty-nv/jetson-inference/blob/master/c/tensorNet.cpp : 1434
```
context->destroy();
mContext = context;
```
this context success destory

**Comment by harryxdl** [comment]
Hi,
You shoud destroy mContext before mEngine.

**Comment by guduzhixing** [comment]
@harryxdl ,thanks,this is work!

**Comment by dicky98** [comment]
what is destroy is marked deprecated now?

**Comment by dusty-nv** [comment]
@dicky98 what version of JetPack/L4T or TensorRT are you building on?
