### ISSUE TITLE
How to convert a video frame to grayscale and also generate a diff image

### ISSUE THREAD

**Issue by deemeetree** [dusty-nv/jetson-inference#1236]
I'm trying to convert a video frame to grayscale like this:

```
        img = input.Capture()

	input_img = jetson.utils.loadImage(img)
	
	copied_img = jetson.utils.cudaAllocMapped(width=img.width, height=img.height, format=img.format)
	jetson.utils.cudaMemcpy(copied_img, img)   # dst, src
	
	imgOutput = jetson.utils.cudaAllocMapped(width=img.width, height=img.height, format='gray8')
	jetson.utils.cudaConvertColor(img, imgOutput)
```

However, it's not working because in your examples the image is sent to Cuda using only `loadImage` function. 

So how do I do manipulations on video frames such as converting them to grayscale, resizing them, and also maybe an analogy of CV2's .diff function that creates a difference between the two frames. 

If it's not possible with Cuda or Jetson's functionalities, then will it be a big problem for performance to convert this image to cv2, do the manipulations there, and then get the image back to the format to be rendered? How would you do that?

**Comment by dusty-nv** [comment]
`jetson.utils.loadImage()` loads an image from disk.   You do not need it if you are using videoSource to capture the images.
