### ISSUE TITLE
How to change the design of the output on the image (boxes, text) in detectnet?

### ISSUE THREAD

**Issue by deemeetree** [dusty-nv/jetson-inference#1237]
Right now in your example `detectnet.py` the following code is used to detect the bounding boxes and display the info. What if I want to customize it - the colors used, the data shown, in fact, all the overlay - how do I do that? Is there a function or a parameter or do I have to convert this image to CV2 and add all the information manually like that?

```
	# capture the next image
	img = input.Capture()

	# detect objects in the image (with overlay)
	detections = net.Detect(img, overlay=opt.overlay)

	# print the detections
	print("detected {:d} objects in image".format(len(detections)))

	for detection in detections:
		print(detection)

	# render the image
	output.Render(img)
```

**Comment by dusty-nv** [comment]
Hi @deemeetree, you can edit how the overlay is performed in `c/detectNet.cpp` or do it with the cv2 way that you suggested.

https://github.com/dusty-nv/jetson-inference/blob/baf9006e7204f8d754c9cc161d6abe62ca9bdbe4/c/detectNet.cpp#L1041
