### ISSUE TITLE
"failed to capture RGBA image from camera" -- IMX477 Arducam

### ISSUE THREAD

**Issue by jarthomas** [dusty-nv/jetson-inference#1238]
Hello, I am experiencing an error after swapping out my standard piCam for a mini 12.3MP Arducam. It appears that device discovery has failed but my device, /dev/video0 exists. Can someone advise what I could try to fix this? I attached a screenshot, thank you kindly
![Screenshot from 2021-09-27 21-27-22](https://user-images.githubusercontent.com/70306328/135024013-47847336-9a86-4c68-b303-042a1d4c6be6.png)
.

**Comment by dusty-nv** [comment]
@jarthomas are you able to view your camera with another independent program like cheese or nvgstcapture-1.0?

**Comment by jarthomas** [comment]
> @jarthomas are you able to view your camera with another independent program like cheese or nvgstcapture-1.0?

Yes, I am able to display the camera's output in other programs.

**Comment by dusty-nv** [comment]
Since the device discovery failed, you may want to try manually specifying the `--input-width`, `--input-height`, and `--input-codec` options:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#input-options
