### ISSUE TITLE
Object detection demo does not work

### ISSUE THREAD

**Issue by Gianni86M** [dusty-nv/jetson-inference#1242]
Please help ASAP
I cannot go further because I have no idea why I downloaded human pictures from open images to perform the object detection demo and it says it cannot find ('/jetson-inference/data/images/Human_*.jpg')
i already completed the training and processed it to onnx

I followed every step in your video and this should not be happening

**Comment by Gianni86M** [comment]
this is the complete error list
listDir('/jetson-inference/data/images/Human_*.jpg') - found no matches
[image]  imageLoader -- failed to find '/jetson-inference/data/images/Human_*.jpg'
detectnet:  failed to create input stream

**Comment by Gianni86M** [comment]
I need to advance and finish everything that Nvidia has to offer

**Comment by Gianni86M** [comment]
Can I please have an answer with due respect

**Comment by Gianni86M** [comment]
?

**Comment by dusty-nv** [comment]
You have typo, it's `"/jetson-inference/data/images/humans_*.jpg"`
