### ISSUE TITLE
Can I train the posenet model?

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#1247]
Hi,

The densenet121-body performs pretty well when the person is facing the camera, but some pose could not be recognized easy, e.g. the person stands at 90 degree. I tried to tuned the threshold but no luck.
And many people stand close together.
How many body model I can try? (just the default model and densenet121-body?)
Is it possible for me to train the model just like detectnet?

Thx

**Comment by H19012** [comment]
How did you convert hand_pose_resnet18_baseline_att_224x224_A pth from NVIDIA-AI-IOT/trt_pose_hand to ONNX? Did you make any edits to the .pth file?

**Comment by edge-ai4cv** [comment]
> How did you convert hand_pose_resnet18_baseline_att_224x224_A pth from NVIDIA-AI-IOT/trt_pose_hand to ONNX? Did you make any edits to the .pth file?

Same question here, cause I converted the hand model to ONNX following a thread in that Git but it seemed to have issues.
