### ISSUE TITLE
Error on Detection Model on Xavier nx Using DLA 

### ISSUE THREAD

**Issue by Awais-commit** [dusty-nv/jetson-inference#1248]
Hello @dusty-nv thanks for this great tutorial. 

I followed tour tutorial and train the model for detection on custom data-set and saved it as `ssd-mobilenet.onnx`. 
It run perfectly and give the inference using `detectnet.py` as you explained. 

But the problem occur when I try to run it using `DLA` on `jetson Xavier nx`. 

**First Problem**
I don't know how can I run the script for inference the same model by only using the `DLA` (not using the GPU). (if there is any source or example that  show how to do it would be great, I search it but couldn't find any.)

**Second Problem**
I couldn't get the inference using DLA, So I thought it would be good idea to get the performance measurement for comparison that if my model is running on `GPU only` and then on` DLA only` what would be difference. 

So I used the `trtexec` from` /usr/src/tensorrt/bin` (the command that I used is `./trtexec --onnx=/home/nvidia/jetson-inference/python/training/detection/ssd/models/my_model/ssd-mobilenet.onnx --int8` ) . 
It give the detection benchmark on GPU correctly.  as shown the picture

![image](https://user-images.githubusercontent.com/53480734/136248522-7f35511d-8dd5-48f1-b142-79dae3074024.png)

But when I run it for DLA using the command
 `/usr/src/tensorrt/bin/trtexec --onnx=/home/nvidia/jetson-inference/python/training/detection/ssd/models/my_model/ssd-mobilenet.onnx  --useDLACore=1 --int8 --allowGPUFallbac`
it give the error as

```[10/06/2021-21:53:09] [E] Error[2]: [graph.cpp::checkSanity::1264] Error Code 2: Internal Error (Assertion !never(t->start.d[i] + t->extent.d[i] <= r.dims.d[i]) failed.)```
```[10/06/2021-21:53:09] [E] Error[2]: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)```
 ```Segmentation fault (core dumped)```

as the picture shows

![image](https://user-images.githubusercontent.com/53480734/136249333-06aa866c-0ba3-43a0-8f0e-8cb187f6d69b.png)

**So my question are:**
1) How can we ran the model only on `DLA for inference on Xavier nx`? if there is any procedure with some script that I can follow.

2) How to resolve the error for `trtexec` so that it can give the banchmark.

3) What is whole procedure that I can run the one model on DLA and other on GPU concurrently.

Thanks in advance for your help

**Comment by dusty-nv** [comment]
Hi @Awais-commit, to be honest I don't use DLA much with this project.  There is minimal support but it isn't really used.  For DLA, I would use DeepStream instead.

And regarding SSD-Mobilenet in particular, not all models are supported on DLA.   DeepStream does support other detection models on DLA though.
