### ISSUE TITLE
DetectNet script Issue

### ISSUE THREAD

**Issue by pouyashiri** [dusty-nv/jetson-inference#1253]
Changing the network input argument of the `detectnet.py` script, does not change the pretrained network used for inference.
For example, I use `ssd-inception-v2` instead of the default `mobilenet` network, but still it prints to the console the following:
`device GPU, ssd_mobilenet_v2_coco.uff initialized`

**Comment by rajeshroy402** [comment]
Can you try creating a new script and check whether it's working or not? 
Thanks

**Comment by pouyashiri** [comment]
> Can you try creating a new script and check whether it's working or not? Thanks

I did so, the issue remains.
