### ISSUE TITLE
segmentation fault core dumped python

### ISSUE THREAD

**Issue by neeldesai123** [dusty-nv/jetson-inference#1260]
Hello, 
I tried to install jetson inference on Jetson Xavier Nx. when I import jetson.inference or jetson.utils I get error 

 **segmentation fault core dump**
I sued following command to build the repo:

$ git clone https://github.com/dusty-nv/jetson-inference
$ cd jetson-inference
$ git submodule update --init
$ mkdir build
$ cd build
$ cmake ..
$ make
$ sudo make install

need help

**Comment by bobsmith947** [comment]
Saw this issue on Jetson Nano 2GB as well. Is there a solution besides running the libraries in the Docker container?

**Comment by dusty-nv** [comment]
@bobsmith947 unless you are able to get the backtrace and/or instrument the code with debug print() statements to find out where/why it's crashing, or trying a fresh SD card to rule out any environmental issues, then yea I would just run it in the container.
