### ISSUE TITLE
How to run multiple inferences on detectnet using RTSP

### ISSUE THREAD

**Issue by rajeshroy402** [dusty-nv/jetson-inference#1269]
Hey @dusty-nv ,
Can I run multiple inferences on RTSP sources (around 2-3) with the same model?
Which file code/file should I change to apply more custom logic on detectnet?

**Comment by dusty-nv** [comment]
Yes, you may use multiple sources with the same model.  detectNet object doesn't store any information frame-to-frame, so it doesn't care where the input came from.

**Comment by rlrahulkanojia** [comment]
Is there a way we can differenciate the output? Like from which source a particular detection is?

**Comment by dusty-nv** [comment]
Well, keep track of which input source you fed into it.  That should be pretty simple since detectNet.Detect() takes the image and returns the detections.
________________________________

**Comment by rlrahulkanojia** [comment]
understood, Thanks

**Comment by rajeshroy402** [comment]
> I think the answer to my second question is _jetson-inference/python/examples/detectnet.py_ and probably need to define multiple sources over there?

This file path is connect?
I usually run this command: `cd jetson-inference/python/training/detection/ssd`
And then I run - `detectnet --model=models/box/ssd-mobilenet.onnx --labels=models/box/labels.txt -input-blob=input_0 --output-cvg=scores --output-bbox=boxes --threshold=0.85 --input-codec=h265 rtsp://user:passwd@static_ip:port_number/h265/main/ch1/main/av_stream`


So the detectnet which I call is from 'jetson-inference/python/examples/detectnet.py ' this path right @dusty-nv ?
And other logic based on the detection which I have to put will be over here itself right?

**Comment by rajeshroy402** [comment]
> > I think the answer to my second question is _jetson-inference/python/examples/detectnet.py_ and probably need to define multiple sources over there?
> 
> This file path is connect? I usually run this command: `cd jetson-inference/python/training/detection/ssd` And then I run - `detectnet --model=models/box/ssd-mobilenet.onnx --labels=models/box/labels.txt -input-blob=input_0 --output-cvg=scores --output-bbox=boxes --threshold=0.85 --input-codec=h265 rtsp://user:passwd@static_ip:port_number/h265/main/ch1/main/av_stream`
> 
> So the detectnet which I call is from 'jetson-inference/python/examples/detectnet.py ' this path right @dusty-nv ? And other logic based on the detection which I have to put will be over here itself right?

@dusty-nv @rlrahulkanojia any comments?

**Comment by rlrahulkanojia** [comment]
when you install detectnet following the steps mentioned in the readme, it is installed systemwide. You can call it from anywhere on the same system. If you are using python API, its just a wrapper around c binaries that can be imported using `import jetson_inference` in python. 

You don't need to cd into any directory and you can create a new script from scratch using the sample provided in detectnet.py.

**Comment by rajeshroy402** [comment]
> when you install detectnet following the steps mentioned in the readme, it is installed systemwide. You can call it from anywhere on the same system. If you are using python API, its just a wrapper around c binaries that can be imported using `import jetson_inference` in python.
> 
> You don't need to cd into any directory and you can create a new script from scratch using the sample provided in detectnet.py.

@rlrahulkanojia - where can I find the source code for the detectnet which I installed in my machine?

**Comment by rajeshroy402** [comment]
I tried adding couple of print statements and tried running detect.py file.. but the print statements are not getting executed.

**Comment by rajeshroy402** [comment]
> > when you install detectnet following the steps mentioned in the readme, it is installed systemwide. You can call it from anywhere on the same system. If you are using python API, its just a wrapper around c binaries that can be imported using `import jetson_inference` in python.
> > You don't need to cd into any directory and you can create a new script from scratch using the sample provided in detectnet.py.
> 
> @rlrahulkanojia - where can I find the source code for the detectnet which I installed in my machine?

@dusty-nv

**Comment by rajeshroy402** [comment]
> I tried adding couple of print statements and tried running detect.py file.. but the print statements are not getting executed.

It is not working in detect.py but is working with some other python script which I create and run with my custom inference logic

**Comment by dusty-nv** [comment]
If you edit [`jetson-inference/python/examples/detectnet.py`](https://github.com/dusty-nv/jetson-inference/blob/master/python/examples/detectnet.py), then re-run the following:

``` bash
cd jetson-inference/build
cmake ../
make
sudo make install
```

This is so that your version of detectnet.py gets installed system-wide.  You might have actually been running an outdated copy of detectnet.py which didn't have your changes.

**Comment by rajeshroy402** [comment]
I get these errors when I try to run RTSP on nvmm-disabled branch @dusty-nv 
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)15120, maximum-bitrate=(uint)6015360, bitrate=(uint)701484;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)687175;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)673488;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)649162;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)625322;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)603185;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)582787;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)563719;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)545976;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)634192;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)614891;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)597236;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)580242;
[gstreamer] gstreamer mysink taglist, video-codec=(string)"H.265\ \(Main\ Profile\)", minimum-bitrate=(uint)14640, maximum-bitrate=(uint)6015360, bitrate=(uint)564178;

**Comment by dusty-nv** [comment]
@rajeshroy402 those aren't errors.   does the stream display?  if not, can you post the console output

**Comment by rajeshroy402** [comment]
Do you have a syntax for multiple sources as input and output?

**Comment by dusty-nv** [comment]
You can create multiple `jetson.utils.videoSource` and `jetson.utils.videoOutput` objects, however just have the argument parsing handle multiple streams.
