### ISSUE TITLE
Compilation Issues CUDA

### ISSUE THREAD

**Issue by eanmikale** [dusty-nv/jetson-inference#1271]
Dusty, I keep getting the following error when compiling on x86. I have CUDA 11.5 installed and the Cuda Compilation Tools 9.0. The Graphics Card is a 1050. Driver Version is 495. 

~/jetson-inference/build$ make -j4
[  4%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaCrop.cu.o
[  4%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaDraw.cu.o
[  4%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaColormap.cu.o
[  4%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaYUV-YV12.cu.o
[  4%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaFilterMode.cu.o
[  5%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaFont.cu.o
[  6%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaGrayscale.cu.o
[  6%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaNormalize.cu.o
[  7%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaOverlay.cu.o
[  8%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaPointCloud.cu.o
[  9%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaRGB.cu.o
[  9%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaResize.cu.o
[ 10%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaWarp-affine.cu.o
[ 11%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaWarp-fisheye.cu.o
[ 11%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaWarp-intrinsic.cu.o
[ 12%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaYUV-NV12.cu.o
[ 13%] Building NVCC (Device) object utils/CMakeFiles/jetson-utils.dir/cuda/jetson-utils_generated_cudaYUV-YUYV.cu.o
Scanning dependencies of target jetson-utils
[ 14%] Building CXX object utils/CMakeFiles/jetson-utils.dir/commandLine.cpp.o
[ 15%] Building CXX object utils/CMakeFiles/jetson-utils.dir/XML.cpp.o
[ 15%] Building CXX object utils/CMakeFiles/jetson-utils.dir/URI.cpp.o
[ 15%] Building CXX object utils/CMakeFiles/jetson-utils.dir/filesystem.cpp.o
[ 16%] Building CXX object utils/CMakeFiles/jetson-utils.dir/logging.cpp.o
[ 17%] Building CXX object utils/CMakeFiles/jetson-utils.dir/timespec.cpp.o
[ 17%] Building CXX object utils/CMakeFiles/jetson-utils.dir/camera/gstCamera.cpp.o
[ 18%] Building CXX object utils/CMakeFiles/jetson-utils.dir/camera/v4l2Camera.cpp.o
[ 19%] Building CXX object utils/CMakeFiles/jetson-utils.dir/codec/gstBufferManager.cpp.o
[ 20%] Building CXX object utils/CMakeFiles/jetson-utils.dir/codec/gstDecoder.cpp.o
/home/infinitesandbox/jetson-inference/utils/codec/gstBufferManager.cpp:30:10: fatal error: cuda_egl_interop.h: No such file or directory
 #include <cuda_egl_interop.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
utils/CMakeFiles/jetson-utils.dir/build.make:373: recipe for target 'utils/CMakeFiles/jetson-utils.dir/codec/gstBufferManager.cpp.o' failed
make[2]: *** [utils/CMakeFiles/jetson-utils.dir/codec/gstBufferManager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:831: recipe for target 'utils/CMakeFiles/jetson-utils.dir/all' failed
make[1]: *** [utils/CMakeFiles/jetson-utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Thank you.

**Comment by dusty-nv** [comment]
Hi @eanmikale, I've not built this repo for desktop before, as it is intended for Jetson.  So maybe that is why there is the missing header.  Although I believe if you run cmake with `-DDISABLE_NVMM` it may get around this particular error.

**Comment by eanmikale** [comment]
Sorry, the solution to what I want to accomplish, you answer before in issue 1152, here, which is to train the Pytorch models faster using my x86 laptop - https://github.com/dusty-nv/jetson-inference/issues/1152. Thanks!
