### ISSUE TITLE
CODE EXPLAINATION

### ISSUE THREAD

**Issue by rlrahulkanojia** [dusty-nv/jetson-inference#1272]
`template<typename T, bool isBGR>
__global__ void gpuTensorNorm( float2 scale, T* input, int iWidth, float* output, int oWidth, int oHeight, float multiplier, float min_value )
{
	const int x = blockIdx.x * blockDim.x + threadIdx.x;
	const int y = blockIdx.y * blockDim.y + threadIdx.y;

	if( x >= oWidth || y >= oHeight )
		return;

	const int n = oWidth * oHeight;
	const int m = y * oWidth + x;

	const int dx = ((float)x * scale.x);
	const int dy = ((float)y * scale.y);

	const T px = input[ dy * iWidth + dx ];

	const float3 rgb = isBGR ? make_float3(px.z, px.y, px.x)
						: make_float3(px.x, px.y, px.z);
	
	output[n * 0 + m] = rgb.x * multiplier + min_value;
	output[n * 1 + m] = rgb.y * multiplier + min_value;
	output[n * 2 + m] = rgb.z * multiplier + min_value;
	printf("DETECTNET _____ %d _____ %d _____ %d \n",n * 0 + m,n * 1 + m, n * 2 + m );

}

template<bool isBGR>
cudaError_t launchTensorNorm( void* input, imageFormat format, size_t inputWidth, size_t inputHeight,
						float* output, size_t outputWidth, size_t outputHeight, 
						const float2& range, cudaStream_t stream )
{
	if( !input || !output )
		return cudaErrorInvalidDevicePointer;

	if( inputWidth == 0 || outputWidth == 0 || inputHeight == 0 || outputHeight == 0 )
		return cudaErrorInvalidValue;

	printf(" DETECTNET DEBUG %f %f %f %f", float(inputWidth), float(outputWidth), float(inputHeight) , float(outputHeight));

	const float2 scale = make_float2( float(inputWidth) / float(outputWidth),
							    float(inputHeight) / float(outputHeight) );
	
	printf("DETECTNET _____  %f %f \n", scale.x ,scale.y );

	const float multiplier = (range.y - range.x) / 255.0f;
	
	// launch kernel
	const dim3 blockDim(8, 8);
	const dim3 gridDim(iDivUp(outputWidth,blockDim.x), iDivUp(outputHeight,blockDim.y));

	if( format == IMAGE_RGB8 )
		gpuTensorNorm<uchar3, isBGR><<<gridDim, blockDim, 0, stream>>>(scale, (uchar3*)input, inputWidth, output, outputWidth, outputHeight, multiplier, range.x);
	else if( format == IMAGE_RGBA8 )
		gpuTensorNorm<uchar4, isBGR><<<gridDim, blockDim, 0, stream>>>(scale, (uchar4*)input, inputWidth, output, outputWidth, outputHeight, multiplier, range.x);
	else if( format == IMAGE_RGB32F )
		gpuTensorNorm<float3, isBGR><<<gridDim, blockDim, 0, stream>>>(scale, (float3*)input, inputWidth, output, outputWidth, outputHeight, multiplier, range.x);
	else if( format == IMAGE_RGBA32F )
		gpuTensorNorm<float4, isBGR><<<gridDim, blockDim, 0, stream>>>(scale, (float4*)input, inputWidth, output, outputWidth, outputHeight, multiplier, range.x);
	else
		return cudaErrorInvalidValue;

	return CUDA(cudaGetLastError());
}
`

Can you please explain the code in terms of how the output is calculated?  ( tensorConvert.cu , line ~140)

@dusty-nv

**Comment by dusty-nv** [comment]
Hi @rlrahulkanojia, it takes an images with pixels in the range of `0-255` and converts them to be in the specified range (for example `-1 to 1` or `0 to 1`

**Comment by rlrahulkanojia** [comment]
That part is clear but the print statement you see at the last of the first snippets prints only 4096 times irrespective of the model input dimension ( multiple input). My end goal is to visualize the output ( after preprocessing) by printing it on terminal

**Comment by rlrahulkanojia** [comment]
@dusty-nv would really appreciate any leads to look into.

**Comment by dusty-nv** [comment]
I'm not sure why it would only print 4096 times, maybe that is the limit that CUDA can printf in a kernel or something.  Regardless the print is only for debugging and you won't get realtime performance anymore.   You can also just do the printf on CPU after calling the kernel and inserting a call to `cudaDeviceSynchronize()` before the printf's begin.

**Comment by rlrahulkanojia** [comment]
That does make sense. Thanks for your advice, will try that too.
