### ISSUE TITLE
Monitor not connecting to the Jetson Nano 2gb

### ISSUE THREAD

**Issue by 1030533** [dusty-nv/jetson-inference#1278]
I've checked all the connections, and even plugged different things in, but as soon as I connect the Jetson Nano 2gb to it, it goes into low power mode and won't connect

**Comment by dusty-nv** [comment]
Hi @1030533, I recommend posting your general issue to the Jetson Nano forum:  https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76
