### ISSUE TITLE
CUDA_nppicc_LIBRARY (ADVANCED)

### ISSUE THREAD

**Issue by kk52099** [dusty-nv/jetson-inference#1286]
when I run "cmake ..", 
![image](https://user-images.githubusercontent.com/18585577/140926001-ad90d7ba-c9ca-4586-9495-248831b2ea44.png)

**Comment by kk52099** [comment]
> when I run "cmake ..", ![image](https://user-images.githubusercontent.com/18585577/140926001-ad90d7ba-c9ca-4586-9495-248831b2ea44.png)

**Comment by bastianhjaeger** [comment]
Same issue here. Any updates?

**Comment by dusty-nv** [comment]
Do you have CUDA toolkit installed under `/usr/local/cuda`?   It should have been installed with JetPack

**Comment by bastianhjaeger** [comment]
Thanks. I think we follow up on https://github.com/dusty-nv/jetson-inference/issues/735
