### ISSUE TITLE
Something is wrong with the paths, may it be due to using a SDD with Jetson Xavier NX?

### ISSUE THREAD

**Issue by Shemesu** [dusty-nv/jetson-inference#1293]
Something is wrong with the paths, may it be due to using a SDD with Jetson Xavier NX?

I run the docker and it works, but to run the imagenet I have to add the path of the files:

./imagenet.py ../../data/images/jellyfish.jpg ../../data/images/test/output_0.jpg 

But then I thried the posenet and, even with the full path, or even adding the network it doesn't work:

root@shemesu-desktop:/jetson-inference/python/examples# ./posenet.py "../../data/images/humans_*.jpg" ../../data/images/test/pose_humans_%i.jpg

poseNet -- loading pose estimation model from:
        -- model        networks/Pose-ResNet18-Body/pose_resnet18_body.onnx
        -- topology     networks/Pose-ResNet18-Body/human_pose.json
        -- colors       networks/Pose-ResNet18-Body/colors.txt
        -- input_blob   'input'
        -- output_cmap  'cmap'
        -- output_paf   'paf'
        -- threshold    0.150000
        -- batch_size   1

[TRT]    poseNet -- failed to load topology json from 'networks/Pose-ResNet18-Body/human_pose.json'
Segmentation fault (core dumped)

OR

root@shemesu-desktop:/jetson-inference/python/examples# ./posenet.py --network="resnet18-body" "../../data/images/humans_*.jpg" ../../data/images/test/pose_humans_%i.jpg

poseNet -- loading pose estimation model from:
        -- model        networks/Pose-ResNet18-Body/pose_resnet18_body.onnx
        -- topology     networks/Pose-ResNet18-Body/human_pose.json
        -- colors       networks/Pose-ResNet18-Body/colors.txt
        -- input_blob   'input'
        -- output_cmap  'cmap'
        -- output_paf   'paf'
        -- threshold    0.150000
        -- batch_size   1

[TRT]    poseNet -- failed to load topology json from 'networks/Pose-ResNet18-Body/human_pose.json'
Segmentation fault (core dumped)

I'm running it in L4T 32.5.1 in a Jetson Xavier NX with SDD drive.

Thanks,

**Comment by dusty-nv** [comment]
Hmm... is the SSD formatted as NTFS/FAT as opposed to ext3/ext4?   If so, that may explain why the symbolic links aren't working for you.
