### ISSUE TITLE
CUDNN Problem installing NVCaffe

### ISSUE THREAD

**Issue by eweill** [dusty-nv/jetson-inference#13]
@dusty-nv 
I would like to use TensorRT and accompanying software that was recently made public by NVIDIA.  I am working on installing your repo on my TX1, but first I must install the fp16 branch of NVCaffe.

I seem to be getting a CUDNN error with the version that comes with the most recent JetPack install.  I can run `make all`, `make test`, and `make pycaffe` all with no problems.  Then I try to run `make runtest CUDA_DEVICES_VISIBLE=0` and get the following error about CUDNN.

F1003 02:38:10.825604  1032 cudnn_conv_layer.cpp:157] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
**\* Check failure stack trace: ***
    @       0x7f8bfb1718  google::LogMessage::Fail()
    @       0x7f8bfb3614  google::LogMessage::SendToLog()
    @       0x7f8bfb1290  google::LogMessage::Flush()
    @       0x7f8bfb3eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7f8ade7424  caffe::CuDNNConvolutionLayer<>::Reshape()
    @       0x7f8ae8a8a8  caffe::Net<>::Init()
    @       0x7f8ae8c0f8  caffe::Net<>::Net()
    @           0x662e7c  caffe::NetTest<>::InitNetFromProtoString()
    @           0x607dc0  caffe::NetTest<>::InitReshapableNet()
    @           0x66b12c  caffe::NetTest_TestReshape_Test<>::TestBody()
    @           0xa71e6c  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0xa6b174  testing::Test::Run()
    @           0xa6b2b0  testing::TestInfo::Run()
    @           0xa6b370  testing::TestCase::Run()
    @           0xa6c4d0  testing::internal::UnitTestImpl::RunAllTests()
    @           0xa6c7e4  testing::UnitTest::Run()
    @           0x56c0e8  main
    @       0x7f8a9728a0  __libc_start_main
Makefile:552: recipe for target 'runtest' failed
make: **\* [runtest] Aborted

Do I need to use a different version of CUDNN than is present with the JetPack?

**Comment by goonder** [comment]
hello!Did you find the sovolution?I got the same problem.Please help me! thanks!!!
