### ISSUE TITLE
coco2kitty.py is missing

### ISSUE THREAD

**Issue by TheMikeyR** [dusty-nv/jetson-inference#130]
The coco2kitty.py file linked to in the README.md [here](https://github.com/dusty-nv/jetson-inference/blob/master/README.md#downloading-the-detection-dataset) is not existing. 
The file can be found in the [coco dataset download](https://nvidia.box.com/shared/static/tdrvaw3fd2cwst2zu2jsi0u43vzk8ecu.gz) which is linked in the same section. I think the section should be edited to imply that or a link to the raw file should be there. I've already the coco dataset, so I was only interested in downloading the coco2kitty.py instead of the dataset once again.

**Comment by dusty-nv** [comment]
Thank you for raising this, the coco2kitti.py script actually was under /tools in the repo all along, however I misspelled the link in the readme as coco2kitty :)

The link's been fixed now in master.
