### ISSUE TITLE
invalid argument (error 11) (hex 0x0b) & gstDecoder -- failed to retrieve next image buffer

### ISSUE THREAD

**Issue by MulderKim** [dusty-nv/jetson-inference#1303]
I'm trying it now with the jetson nano 4G developer kit model.
when I first watched the YouTube video(**[Real-Time Object Detection in 10 Lines of Python Code on Jetson Nano](https://youtu.be/bcM5AQSAzUY)**) and tested the code, it worked fine. and I tried again with the SD-card image provided by the jetbot manufacturer.
the difference from before is that all models are installed when model is installed. 
and the sample image test was successful. (./detectnet-console.py images/peds_0.jpg output_0.jpg)
finally, when i run the **my-detection.py** code introduced in **detectnet-example-2.md** .

![my-detection](https://user-images.githubusercontent.com/75383068/142729587-ef4d5fa6-e40a-4848-b0c7-b65396c258bb.png)

pi-camera is not working

is the problem caused by installing all the models?
i tried the following work because I thought I was running out of memory.

$ sudo apt-get install dphys-swapfile

/sbin/dphys-swapfile and /etc/dphys-swapfile edit "CONF_SWAPSIZE=4096, CONF_SWAPFACTOR=2, CONF_MAXSWAP=4096"

can you tell me what mistake I made?

**Comment by michaelgeorge2010** [comment]
Did you receive a solution for this?
