### ISSUE TITLE
Docker Attach After docker/run.sh

### ISSUE THREAD

**Issue by eanmikale** [dusty-nv/jetson-inference#1304]
Dusty,
I hope all is well. It seems I can not issue a "docker attach [OPTIONS] CONTAINER" command after running the run.sh. The docker attach command gives us access to the stdin and stdout pipelines for the container. 

Regards, 
EM

**Comment by dusty-nv** [comment]
Hi @eanmikale, what error do you get when you attempt to `docker attach`?   Is it perhaps because docker/run.sh starts the container in interactive mode?  (`-it` flag)

Perhaps instead you could use `docker exec ... /bin/bash` to start a new terminal in the container instance.
