### ISSUE TITLE
Unnecessary GPU memory allocation

### ISSUE THREAD

**Issue by emielsteerneman** [dusty-nv/jetson-inference#1307]
Hello Dusty,

I am working through your code in my attempt to extend it with YOLO. While looking at the memory allocation, I noticed that the variable [mDetectionSets](https://github.com/dusty-nv/jetson-inference/blob/9b66fbf38dcd0e81f37eb3748db3df0a221b4fa7/c/detectNet.h#L497) is used with [cudaAllocMapped](https://github.com/dusty-nv/jetson-inference/blob/9b66fbf38dcd0e81f37eb3748db3df0a221b4fa7/c/detectNet.cpp#L435). However, the pointer to GPU memory, `mDetectionSets[1]`, is never used. Does this mean that this is essentially space wasted on the GPU, or am I misunderstanding `cudaAllocMapped`? 

Thanks

**Comment by dusty-nv** [comment]
Hi @emielsteerneman, `cudaAllocMapped()` returns two pointers to the same physical memory - the first is the CPU pointer, and the second is the GPU/CUDA pointer.   For legacy reasons I had a habit of storing these two points in array like you see in mDetectionSets.

However, for sometime now CUDA has used 64-bit unified memory addressing, where the CPU/GPU pointers are the same, so there is no need for two different pointers anymore.  Some places in the code you still me storing these pointers separately though.

Note that the memory is not being allocated twice - it is just storing the pointers twice.
