### ISSUE TITLE
Datasets used to train multiped-500

### ISSUE THREAD

**Issue by bpinaya** [dusty-nv/jetson-inference#132]
Hi there @dusty-nv ! Had a question, I am training a pedestrian detector and was wondering which datasets you used for that model, did you just used KITTI and MS-Coco? I am trying to used Cityscapes, FLIC, LSP and some others.

**Comment by dusty-nv** [comment]
Hi @bpinaya, the multiped-500 model used a few different datasets, including KITTI and some internal datasets that are unable to be released at this time.   All datasets were in KITTI format however, as that's what DIGITS uses for parsing object detection ground truth data.  So I recommend starting with KITTI and MS-COCO, as the KITTI converter for MS-COCO is provided.  Cityscapes is a good dataset for pedestrian too, however it's not KITTI format but rather segmentation.  Technically segmentation could be used for pedestrian detection also, just not providing the bounding boxes (but potentially supporting many more classes simultaneously).
