### ISSUE TITLE
Cannot find posenet in Nvidia nano 2G...

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#1324]
Hi,

I have setup your project in my Nvidia Nano 2G, everything is fine except that I cannot find the posenet.
Is it too slow in 2G? Is there any way I can enable the posenet?

Thanks

**Comment by dusty-nv** [comment]
Hi @AK51, it should be there - did the model downloader tool download them?

Do you see the `jetson-inference/c/poseNet.cpp` file and `posenet` under the bin directory?

**Comment by AK51** [comment]
Yes yes sorry, I was using a really old version, I clone your repo again and I see the posenet
Sorry about that.
Cheers.
