### ISSUE TITLE
How to get the http video stream instead of rtsp?

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#1325]
Hi,
I can get the rtsp stream from a IP camera but there is lots of lagging. (several seconds)
I can use opencv to capture the http video stream and the lagging is small
Is there anyway I can capture the http stream in your code? Thx
Note: I don't understand is that why my typical NVR (Network video recorder) does not have lagging, how it's protocol work? Just http? Can I do the same thing in nano?

Plan A: reduce the lagging in rtsp stream. I have added the --input-rtsp-latency = 0, it still has 4 seconds delay for 1920x1080 (h264)

Plan B: 
use openCV to capture the http, then convert it using this example
https://github.com/dusty-nv/jetson-utils/blob/master/python/examples/cuda-from-cv.py
But mjpeg only has max 704x576 in the IP camera sub-stream...

Thanks.

**Comment by dusty-nv** [comment]
Hi @AK51, can you try the suggestion from this post?

https://github.com/dusty-nv/jetson-inference/issues/1323#issuecomment-992544823

**Comment by AK51** [comment]
ok, I will ask question in #1323 , thx
