### ISSUE TITLE
detectnet - ros publisher

### ISSUE THREAD

**Issue by vusdo** [dusty-nv/jetson-inference#133]
I want to know how to use detectnet to publish detected images in a ros message.
I am not familiar with CPP.

Thank you for your help.

// convert from YUV to RGBA
void* imgRGBA = NULL;

if( !camera->ConvertRGBA(imgCUDA, &imgRGBA) )
printf("detectnet-camera:  failed to convert from NV12 to RGBA\n");

`

// detect image pub
sensor_msgs::ImagePtr img(new sensor_msgs::Image());

img->header.seq = 1;
img->header.stamp = ros::Time::now();
img->header.frame_id = "det_img";

// Image data and metadata
img->width = camera->GetWidth();
img->height = camera->GetHeight();
img->encoding = sensor_msgs::image_encodings::RGBA8;
img->is_bigendian = false;
//img->data.resize(camera->GetWidth() * camera->GetHeight() * 3);
//img->step = camera->GetWidth() * 3;

uint32_t size = camera->GetWidth()+camera->GetHeight();
std::copy(imgRGBA, imgRGBA+size, img->data.begin());

det_img_pub.publish(img);
`

**Comment by bpinaya** [comment]
Hey there @vusdo , I think I tried this once with good results, a good starting point is:
https://github.com/bpinaya/ros_deep_learning
Also, you can check things like: caffe with ros, I remember there was one repo that worked with detectnet for caffe and ROS.
Best of luck!
