### ISSUE TITLE
Confusion Matrix for Classification

### ISSUE THREAD

**Issue by dig19998** [dusty-nv/jetson-inference#1330]
Hi, is it possible to calculate the confusion matrix for the classified images through the imagenet.py file? If yes then how should I go about it?

**Comment by dusty-nv** [comment]
Hi @dig19998, imagenet.py doesn't read in the groundtruth (so it doesn't actually know what classifications are correct or not), but if you added that to the script you should be able to calculate the confusion matrix from it.
