### ISSUE TITLE
Lab instructions are incorrect

### ISSUE THREAD

**Issue by bryonbaker** [dusty-nv/jetson-inference#1331]
The step-by-step instructions are not correct for the code used in this module:
https://github.com/dusty-nv/jetson-inference/blob/master/docs/imagenet-example-python-2.md

E.g. the complete code uses "args" but the step instructions use "opt" and "args". So if you build the code section-by-section instead of copying the entire code it will not run.

**Comment by dusty-nv** [comment]
Thanks for pointing this out @bryonbaker - just fixed this in https://github.com/dusty-nv/jetson-inference/commit/6bf94f753c727ea50f256fdec5fbe74bee540773
