### ISSUE TITLE
Need help installing jetson inference in my tensorbook

### ISSUE THREAD

**Issue by AnamikaPaul** [dusty-nv/jetson-inference#1334]
I am trying to install Jetson-inference in my tensorbook but i am having some issues  , here is the list of errors from my terminal. 

anamika@tensorbook:~/jetson-inference/build$ **make -j$(nproc)**

[  1%] Linking CXX shared library ../x86_64/lib/libjetson-utils.so
/usr/bin/ld: cannot find -lnvbuf_utils
collect2: error: ld returned 1 exit status
utils/CMakeFiles/jetson-utils.dir/build.make:5077: recipe for target 'x86_64/lib/libjetson-utils.so' failed
make[2]: *** [x86_64/lib/libjetson-utils.so] Error 1
CMakeFiles/Makefile2:831: recipe for target 'utils/CMakeFiles/jetson-utils.dir/all' failed
make[1]: *** [utils/CMakeFiles/jetson-utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Also I am having issues with Docker

anamika@tensorbook:~/jetson-inference$ **docker/run.sh**

head: cannot open '/etc/nv_tegra_release' for reading: No such file or directory
reading L4T version from "dpkg-query --show nvidia-l4t-core"
dpkg-query: no packages found matching nvidia-l4t-core
L4T BSP Version:  L4T R.
docker/tag.sh: line 18: [: -eq: unary operator expected
cannot find compatible jetson-inference docker container for L4T R.
please upgrade to the latest JetPack, or build jetson-inference natively from source

**Comment by dusty-nv** [comment]
Hi @AnamikaPaul, please see this forum post:  https://forums.developer.nvidia.com/t/i-am-trying-to-install-jetson-inference-in-my-tensorbook-i-am-getting-error-with-command-make-j-nproc/199987/3?u=dusty_nv

jetson-inference is only officially supported on Jetson platforms
