### ISSUE TITLE
the target detected in the video is garbled

### ISSUE THREAD

**Issue by yahu-11** [dusty-nv/jetson-inference#1336]
Hello, I am a Chinese college student. I used my own dataset. The label is Chinese. The process is no problem, but the Chinese name of the target detected in the video is garbled. Where is the problem and how to change the code?

**Comment by dusty-nv** [comment]
Hi @yahu-11, the bitmap fonts used are limited to ASCII characters.   You may try adjusting the values here to reflect unicode, however I'm not sure if it will work:   https://github.com/dusty-nv/jetson-utils/blob/0d3f59f5c0967a108ec1cd58a518ee5ad817d35b/cuda/cudaFont.h#L149

**Comment by JIA-HONG-CHU** [comment]
@Pi-Boss  Hi, Do you know how to solve this issue? Thanks.
