### ISSUE TITLE
Xavier AGX & Triton Server 

### ISSUE THREAD

**Issue by eanmikale** [dusty-nv/jetson-inference#1338]
Dusty, 
I hope you are well. We are working with a large client and Inception team, trying to run a Triton Server node on the Jetson Xavier AGX with Jetpack 4.6 Bare Metal. We would rather not use Docker. We have also unsuccessfully tried TAO-Iot. However, the source documentation is scattered for Triton Server, but clean for TAO-Iot, which requires CUDA 11.3. And I saw the section on the Quick Start Guide, state "Coming Soon" for Jetson 4.6. Is there any update on that or other advanced documentation you might be able to provide for a Bare Metal Triton Server node? Cyber-security protocols used? Thank you.

**Comment by dusty-nv** [comment]
Hi @eanmikale, I recommend that you post this to either the [Jetson AGX Xavier forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-agx-xavier/75) or the Triton Server github.  Wish you the best of luck with your project!
