### ISSUE TITLE
Changing of "boxes"

### ISSUE THREAD

**Issue by qasmendoza** [dusty-nv/jetson-inference#1342]
Hi @dusty-nv, how can I change these boxes from "filled" with color (green for instance) to just the boxes alone? Thank you in advance.

**Comment by qasmendoza** [comment]
@dusty-nv any inputs? :)

**Comment by qasmendoza** [comment]
anyone? a little help?

**Comment by dusty-nv** [comment]
Hi @qasmendoza, I just added support for this in https://github.com/dusty-nv/jetson-inference/commit/cf9376ff9a78dcd0f512d90e0ea66c37f757261b

You can now run `detectnet --overlay=lines` to get just the lines  (or `--overlay=lines,labels,conf` for example)

**Comment by qasmendoza** [comment]
hi @dusty-nv it didn't work. I've used detectnet --overlay=lines and it didn't detect anything. I deleted --overlay=lines and it can detect the object but still on green boxes.

**Comment by dusty-nv** [comment]
> hi @dusty-nv it didn't work. I've used detectnet --overlay=lines and it didn't detect anything. I deleted --overlay=lines and it can detect the object but still on green boxes.

Did you update your repo or clone the latest source from master and rebuild/reinstall?

**Comment by qasmendoza** [comment]
Sorry I did not. Let me try that and thanks for clarification.
