### ISSUE TITLE
Errors in training of Detection Model on Jetson Nano

### ISSUE THREAD

**Issue by smitpatel30** [dusty-nv/jetson-inference#1357]
Hello @dusty-nv ... I am currently working on object detection model for soccer ball.. But  i got some errors during its training..
According to your Repository of object detection, I  follow all the steps and execute that.. But when enter the last command for training the model i got much of errors...I don't know how to remove those errors.. I had seen the article in which you recommend to label the images using CVAT. But the CVAT website server is not working properly ,so i can't label the images.. You also said that the labelimg tool of jetson nano will not generate the proper VOC data.. So, here are the questions of mine..

1. is it feasible to use labelimg tool for labelling? if it is not then recommend me the another external tool for labelling the images (not CVAT ).
2. If i use the external tool ,then will it generate the same sequence of folder that's the jetson-nano labelimg tool does?(ex:- 1.Annotation,2.ImageSets,3.JPEGimages)
3. will it have the all files like training.txt,testing.txt ,validate.txt,trainval.txt
![Screenshot (286)](https://user-images.githubusercontent.com/80744978/153575631-51110124-b08c-412c-ba76-fefd09022c48.png)
![Screenshot (287)](https://user-images.githubusercontent.com/80744978/153575676-1478d900-c211-4f37-8e0e-318f4fa8c6d1.png)
![Screenshot (288)](https://user-images.githubusercontent.com/80744978/153575684-e6fb1a76-f8ab-4e89-b793-033c2a6aa391.png)
![Screenshot (289)](https://user-images.githubusercontent.com/80744978/153575687-49038893-2289-4d3f-9f9f-999026469409.png)
This is the image of my BallDetectionModel Folder..All the files are generated..
![Screenshot (290)](https://user-images.githubusercontent.com/80744978/153575694-4dd3171e-6c79-4ba6-b396-352e91542dd7.png)
![Screenshot (291)](https://user-images.githubusercontent.com/80744978/153575696-83945b5d-a952-4707-8cae-fdae27926078.png)

Hope ,that your solution will help me to figure out this..

**Comment by dusty-nv** [comment]
> 1. is it feasible to use labelimg tool for labelling? if it is not then recommend me the another external tool for labelling the images (not CVAT ).

You can use labelimg if you make the trainval.txt/ect yourself and also labels.txt itself.  labelimg only gives you the XML annotations, so it's up to you to make the proper directory structure for these (same as Pascal VOC) and the other text files.

You might want to try CVAT again, it is working from here.

I can't tell exactly your issue from the screenshots, but if you download Pascal VOC dataset and make your dataset the same structure as it, this is what train_ssd.py expects.

**Comment by smartsmit407** [comment]
> 

I have an external tool for labelling the images ..But it can't generate the required files of Imagesets folder(ex:-train.txt,val.txt..etc)..
You have said that i have to generate the imagesets  by myself. But i don't know to generate it properly...
Now , let me tell you what problem i am facing with CVAT tool.. I have created my account.. And when i am tried to 
login it have some issue from server side...I have to finished this ball detection project in only 1 month..
The external software that i have for labelling images doesn't generate the imagesets folder that is required in jetson nano ...
![Screenshot (292)](https://user-images.githubusercontent.com/80744978/153701339-6090c965-a46a-4e4b-83d4-f408ac6af57d.png)
This software doesn't generate the imagesets files..

could you please teach me to generate the imagesets folder for my labelled image if i would use this software or any other 
i can generate these files by myself....

**Comment by dusty-nv** [comment]
@smartsmit407 the contents of train.txt/trainval.txt/ect under ImageSets/ is just a list of the Image IDs (typically the Image ID's are the filenames of the XML/JPG files, without the file extensions).  So I would just make a python script or bash script to make these.

**Comment by smartsmit407** [comment]
> @smartsmit407 the contents of train.txt/trainval.txt/etc under ImageSets / is just a list of the Image IDs (typically the Image ID's are the filenames of the XML/JPG files, without the file extensions). So I would just make a python script or bash script to make these.

@dusty-nv ..Ok.. So, i had seen that in images sets folder all the files have the actual names of my images.  And as you said that ,i can generate those by myself  if  i labelled the images externally by some other tool like CVAT  (not by jetson tool) ....
Now , let's say if i labelled 100 images for object detection....Then, will i have to save all the 100 image file name in all  files of 
imageset(train.txt,test.txt,validate.txt,train_validate.txt) or it has some specific ratio like 80:10:10 ((train:test:validate) file images name ?

**Comment by smartsmit407** [comment]
> labelimg does generate valid XML annotation files, it just doesn't put them in the correct directory structure for Pascal VOC or make the labels.txt/ImageSets files. But you can do those yourself if you have to use labelimg.
> 
> CVAT is the better tool, but sounds like you are having problems with it. I am still able to login to CVAT.org ok. CVAT is also an open-source tool that you can install on your own Linux PC and run it from there as a local webserver.

So, what is the correct directory structure for putting the files..

* Questions:- 
1. I have an object detection folder name ball_detection  in which it has all the sub-folders like anottations,imagesets and images folder..Then , i copy the ball_detection to the path:- /Downloads/jetson-inference/python/training/detection/ssd/data..
Then, after i am doing the training process as describe in your repository.....And then at that moment i found errors for training the model..
Am i doing the correct directory structure or it is wrong?..If it is wrong then please tell me the correct process...

**Comment by dusty-nv** [comment]
> So, what is the correct directory structure for putting the files..

Download the original Pascal VOC dataset and replicate it's directory structure.

**Comment by smartsmit407** [comment]
can i do the labelling the images in windows and export it to the jetson-nano... Because, i have not any desktop screen.... Actually, i am  remotely access  jetson-nano by VNC sofrware...so it's difficult for me to do label the images  because the resolution of screen is very less .. So, i can't label the images in my jetson-nano through CVAT software...

**Comment by smartsmit407** [comment]
Traceback (most recent call last):
  File "train_ssd.py", line 214, in <module>
    target_transform=target_transform)
  File "/home/hadyy/Downloads/jetson-inference/python/training/detection/ssd/vision/datasets/voc_dataset.py", line 33, in __init__
    raise IOError("missing ImageSet file {:s}".format(image_sets_file))
TypeError: unsupported format string passed to PosixPath.__format__

I got this error when i do training for object detection model....  please help me to solve this error.... I don't know how to fix this bug..

**Comment by dusty-nv** [comment]
Hi @smartsmit407, do you have the `ImageSets/Main/train.txt` and `ImageSets/Main/trainval.txt` ?  These files should list the ImageID's in your dataset.   These files can be copies of one another - or you can simply have one `ImageSets/Main/default.txt` and the code will use that instead.

**Comment by camilofernandez9405** [comment]
Hola gente quien me puede ayudar creo que tengo todo bien y no se como solucionar este error agradecería mucho a quien me pudiera ayudar  saludos 
![g](https://user-images.githubusercontent.com/64548356/204393307-ba765202-4e7a-40bb-8360-977fa86862ca.png)

**Comment by camilofernandez9405** [comment]
@dusty-nv  hola hermano tengo este error y creo que tengo todo bien estructurado no se que me genera ese erro si me pudiera
![g](https://user-images.githubusercontent.com/64548356/204825216-5fce62c4-619a-4b19-9289-e01bdfd3cbc0.png)
 ayudar se lo agradeciera mucho

**Comment by dusty-nv** [comment]
Hi @camilofernandez9405, try changing your `--data=data/Cuca` to `--data=/home/camilo/Desktop/Cuca`

**Comment by camilofernandez9405** [comment]
@dusty-nv hola, no me sigue generando el mismo error
![12](https://user-images.githubusercontent.com/64548356/204847276-19582eec-f970-47d8-b0c5-9a5ebf0de09c.png)

**Comment by dusty-nv** [comment]
@camilofernandez9405 ok, I see that you are using the container

Please move your Cuca dataset folder to your `/home/camilo/Descargas/jetson-inference/python/training/detection/ssd/data` directory.  And then run train_ssd.py with `--data=data/Cuca` again

**Comment by camilofernandez9405** [comment]
@dusty-nv  listo ya hice ese paso ahora me arroja este nuevo error
![13](https://user-images.githubusercontent.com/64548356/204858019-4addeaea-662d-4366-94e6-85b674929893.png)
![133](https://user-images.githubusercontent.com/64548356/204858032-38c4f1eb-dc68-47fb-9a4a-ad4b82108a99.png)

**Comment by dusty-nv** [comment]
It looks like you have some corrupt/empty XML files under `Annotations/` 
You can fix them or remove them from the ImageSets files

Also, `Labels.txt` should be lowercase => `labels.txt`

**Comment by camilofernandez9405** [comment]
@dusty-nv ya pude solucionar los errores muchas gracias.
Pero tengo una nueva duda corrí el modelo pero todo lo que detecta con la cámara web lo detecta como Cuca o Cucarachas cómo puedo mejorar el modelo

**Comment by dusty-nv** [comment]
> I was able to fix the errors, thank you very much.
But I have a new question, I ran the model, but everything it detects with the webcam is detected as Cuca or Cockroaches, how can I improve the model?

@camilofernandez9405 how many classes are in your model?   Also, how many images are in your dataset?   You may need to add more data and train your model for more epochs.

**Comment by camilofernandez9405** [comment]
@dusty-nv solo es una clase, lo que quiero identificar son cucarachas y estoy utilizando 80 imagenes y 20 epocas, cuantas imagenes minimo me recomienda y cuantas épocas muchas gracias por tu tiempo
