### ISSUE TITLE
Sorry for the simple question.Where I can find the data capture control?

### ISSUE THREAD

**Issue by xuyp4876** [dusty-nv/jetson-inference#1361]
Below is the Data Capture Control window, which allows you to pick the desired path to the dataset and load the class label file that you created above, and then presents options for selecting the current object class and train/val/test set that you are currently collecting data for:
I can't find where it is

**Comment by dusty-nv** [comment]
It should automatically pop up when you start the camera-capture tool, like shown here:  https://youtu.be/2XMkPW_sIGg?t=603

Typically it is in the top-right corner of the screen.  Do you have a monitor attached to your Jetson?
