### ISSUE TITLE
How control jetson-utils log/trace output in python

### ISSUE THREAD

**Issue by fmolinelli** [dusty-nv/jetson-inference#1362]
Hi, probably it's somethng trivial, but I'm stuck there...

is there a way in python to control/disable tracing output from jetson.utils functions?

Example: 
  - whenever I call 
         "img = jetson.utils.loadImage('somefile')"
  - then on the console output I see
         "[image]  loaded '.somefile'  (1280x720, 3 channels)"
If I have to load nK inages is going boring...

Tryed to catch the  python logging.lastResort setting logLevel to logging.CRITICAL but seems not to work

Any help would be apreciated!

Flavio

**Comment by dusty-nv** [comment]
Hi @fmolinelli, normally this is done with one of the logging command-line arguments:

``` bash
logging arguments:
  --log-file=FILE        output destination file (default is stdout)
  --log-level=LEVEL      message output threshold, one of the following:
                             * silent
                             * error
                             * warning
                             * success
                             * info
                             * verbose (default)
                             * debug
  --verbose              enable verbose logging (same as --log-level=verbose)
  --debug                enable debug logging   (same as --log-level=debug)
```

However this relies you on passing the command-line to a class like videoSource/videoOutput/imageNet/ect, where they get parsed and the logging level set.   My guess is that is not happening in your code.

For now, what I would do is change the default logging level here:

https://github.com/dusty-nv/jetson-utils/blob/7de695d94271ba1ae77a4358f427c0887b09084f/logging.h#L70

And then re-build/re-install with:

``` bash
$ cd jetson-inference/build
$ cmake ../
$ make -j$(nproc)
$ sudo make install
```

**Comment by fmolinelli** [comment]
Hi @dusty-nv ,

just awesome! you gave me a lot of hints!

Solved the problem, going to dig more in depth with jetson-inference: just started yesterday ;)

closing the issue...
