### ISSUE TITLE
Gstreamer Pipeline to Get CUDA Frame

### ISSUE THREAD

**Issue by irshadkn** [dusty-nv/jetson-inference#1364]
I assume the jetson inference library uses the CUDA frame for performing inference. 
Could you please give me a sample Gstreamer pipeline that takes CSI camera input and gives CUDA frame output to appsink?

**Comment by rgbsi-mi1** [comment]
How to convert sample emitted by appsink to CUDA image?

**Comment by dusty-nv** [comment]
@rgbsi-mi1 these are the functions that converts GstSample/GstBuffer from appsink to CUDA memory:

https://github.com/dusty-nv/jetson-utils/blob/e82dad8a9e1f2599435671052a39c616e6ab7c56/codec/gstDecoder.cpp#L806

https://github.com/dusty-nv/jetson-utils/blob/e82dad8a9e1f2599435671052a39c616e6ab7c56/codec/gstBufferManager.cpp#L69
