### ISSUE TITLE
jetson.utils -- http video streaming as video source

### ISSUE THREAD

**Issue by haiwang2006** [dusty-nv/jetson-inference#1368]
Is there a plan to add support of http video streaming as video source into jetson-utils? I suppose http streaming is more commonly seen than rtp and rtsp streaming.
I made a few modification on VideoSource and gstDecoder, and http video streaming as video source works in my experimental project.

**Comment by dusty-nv** [comment]
@haiwang2006 sorry for the delay - I don't have plans to add HTTP streaming, but I have added support for WebRTC;  https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#webrtc
