### ISSUE TITLE
Skipping cmake interactive pop-ups (automated script)

### ISSUE THREAD

**Issue by firststep-dev** [dusty-nv/jetson-inference#1373]
Is there a way to run `cmake ../` step (as part of an automated script), automatically skipping these 2 pop-ups?

I am running the following commands:

```
rm -rf build
mkdir build
cd build
cmake ../
make -j$(nproc)
sudo make install
```

Step 1: Quit

![image](https://user-images.githubusercontent.com/82156211/155461320-eee5a903-cbb5-432f-9e53-30f072dbd8fc.png)

Step 2: Skip

![image](https://user-images.githubusercontent.com/82156211/155461437-b452a620-a04c-4b6c-b64d-e9ebaee0b688.png)

**Comment by dusty-nv** [comment]
Hi @firststep-dev, yes there is, with [`-DBUILD_INTERACTIVE=off`](https://github.com/dusty-nv/jetson-inference/blob/3a032b0992d7786b00bcbf19232a8822b6160cf9/CMakeLists.txt#L28)

**Comment by firststep-dev** [comment]
Thanks @dusty-nv

**Comment by firststep-dev** [comment]
@dusty-nv setting this `-DBUILD_INTERACTIVE=off` flag by default this installs "default models".

```
Reading package lists...
[jetson-inference]  BUILD_INTERACTVE=off
[jetson-inference]  Downloading default models...
[jetson-inference]  Downloading GoogleNet...
bvlc_googlenet.caff   3%[                    ]   2,00M   122KB/s    eta 5m 34s
```

How can I disable / skip these 2 pop-ups (i.e. edit the default lists) for non-interactive build mode?

**Comment by leenremm** [comment]
@dusty-nv - just a kind followup.

How can I run `-DBUILD_INTERACTIVE=off` while disabling ALL default model download? 

Is there a config file for default model downloads?

**Comment by leenremm** [comment]
I see that the default list of models is defined in a SH script in `build/download-models.sh`:

```
if [[ "$BUILD_INTERACTIVE" != "YES" ]]; then

        echo "$LOG Downloading default models..."

        download_googlenet
        download_resnet18

        download_ssd_mobilenet_v2
        download_pednet
        download_facenet
        download_detectnet_coco_dog

        download_fcn_resnet18_cityscapes_512x256
        download_fcn_resnet18_cityscapes_1024x512
        download_fcn_resnet18_deepscene_576x320
        download_fcn_resnet18_mhp_512x320
        download_fcn_resnet18_pascal_voc_320x320
        download_fcn_resnet18_sun_rgbd_512x400

        exit_message 0
fi

```

**Comment by leenremm** [comment]
I see that this file is created in the `./build` directory during `cmake`, where it is copied from `tools/download-models.sh`

file(COPY "tools/download-models.sh" DESTINATION ${PROJECT_BINARY_DIR})

So I have edited the file: `tools/download-models.sh`, from:

```
if [[ "$BUILD_INTERACTIVE" != "YES" ]]; then

	echo "$LOG Downloading default models..."

        exit_message 0

	download_googlenet
	download_resnet18

	download_ssd_mobilenet_v2
	download_pednet
	download_facenet
	download_detectnet_coco_dog

	download_fcn_resnet18_cityscapes_512x256
	download_fcn_resnet18_cityscapes_1024x512
	download_fcn_resnet18_deepscene_576x320
	download_fcn_resnet18_mhp_512x320
	download_fcn_resnet18_pascal_voc_320x320
	download_fcn_resnet18_sun_rgbd_512x400

	exit_message 0
fi
```

to the following:

```
if [[ "$BUILD_INTERACTIVE" != "YES" ]]; then

	echo "$LOG Downloading default models..."
        exit_message 0

fi
```

**Comment by ligaz** [comment]
Alternatively you can remove the download step in the pre-build script: [`CMakePreBuild.sh:46`](https://github.com/dusty-nv/jetson-inference/blob/6cf3b12f503d64903ca1e77d4c5474d9b1513a4c/CMakePreBuild.sh#L46).

**Comment by dusty-nv** [comment]
Hi @ligaz, very good, glad you got it figured out - I would have suggested either of your patches.
