### ISSUE TITLE
Can't launch GStreamer with gst-launch-1.0

### ISSUE THREAD

**Issue by EnzoLgvn** [dusty-nv/jetson-inference#1374]
Hi, 
First, I want to thank you for your tutorials, I am currently following your first tutorial about [Hello AI World](https://www.youtube.com/watch?v=QXIwdsyK7Rw&list=PL5B692fm6--uQRRDTPsJDp4o0xbzkoyf8&index=11) .
But i can't launch Gstreamer but i installed it on their website, following the [different steps ](https://gstreamer.freedesktop.org/download/#windows).
The fact is that when i use the command that you wrote on your linux PC : 
` $ gst-launch-1.0 -v udpsrc port=1234 \
 caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" ! \
 rtph264depay ! decodebin ! videoconvert ! autovideosink`
I have the following error (see the enclosed items).
Sorry I'm not a native speaker so my powershell is in French.
Thanks for your help 

![Gstreamer](https://user-images.githubusercontent.com/49230451/155844356-90e870a7-085b-4817-8b33-3a6e2f1720d8.PNG)
!

**Comment by dusty-nv** [comment]
Hi @EnzoLgvn, sorry I don't totally understand the error you are getting (it appears to be in French), but I think it's along the lines of "can't find gst-launch-1.0".   You should find the directory that contains gst-launch-1.0 executable and cd your terminal to there before running it (or add that directory to your PATH)
