### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: 'models/euler/mb1-ssd-Epoch-0-Loss-4.595351078137177.pth'

### ISSUE THREAD

**Issue by ltephanysopez** [dusty-nv/jetson-inference#1376]
Hey all! I'm getting a bug when trying to convert my model to ONNX. Here's a screencap of my log: 

<img width="821" alt="Screen Shot 2022-02-28 at 2 39 40 PM" src="https://user-images.githubusercontent.com/33434208/156055468-73fcbc94-71be-4fef-8db6-6f340bdf23bb.png">

Here are things I've tried so far: 
- Checked all labels.txt files to see if there was an extra space or new line- there aren't any
- Downloaded 'models/mobilenet-v1-ssd-mp-0.675.pth' in case my model didn't save correctly/got corrupted 

Other than that, I've also tried exporting locally outside of the Docker container but unfortunately, get a 'no module named torch found'. Would appreciate any help!

**Comment by dusty-nv** [comment]
Hi @ltephanysopez, the `--model-dir` argument expects a directory, not the full path to your pth checkpoint.  Can you try running it as `python3 onnx_export.py --model-dir=models/euler` instead?

If you are trying to specify a specific pth checkpoint to use (by default, the one with the lowest loss is selected), then use the `--input` and `--output` arguments:  https://github.com/dusty-nv/pytorch-ssd/blob/3f9ba554e33260c8c493a927d7c4fdaa3f388e72/onnx_export.py#L20

**Comment by ltephanysopez** [comment]
Thanks, Dustin! That fixed the error :) On an unrelated note, I was wondering if it was possible to train with multiple datasets in and outside of a Docker container? I'm currently trying to migrate data on my host (roughly 37k pictures/annotations) into my data directory in the container but it's not as easy of a process as I thought. Any insight here would be appreciated 🙏🏽 

@dusty-nv

**Comment by dusty-nv** [comment]
> 'm currently trying to migrate data on my host (roughly 37k pictures/annotations) into my data directory in the container but it's not as easy of a process as I thought.

Oh sure - when you start the container, you can mount an additional path into the container using the `--volume` flag:   https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-docker.md#mounted-data-volumes

So just mount your folder containing your dataset, and then point train_ssd.py to that mounted path instead.

**Comment by ltephanysopez** [comment]
got it- thank you so much @dusty-nv! :)
