### ISSUE TITLE
There are problems even though I used 100 epochs models

### ISSUE THREAD

**Issue by SangkyunAhn** [dusty-nv/jetson-inference#1379]
Hi.
I use Jetson Nano.

I tried these examples,
 - Re-training on the Cat/Dog Dataset(Classification, Recognition)
 - Re-training SSD-Mobilenet(Object Detection)

But, even though I used 100 epochs models, the problems are occurred.

In case of classification, the following problem is occurred.
![cat](https://user-images.githubusercontent.com/87156398/156311086-3b837031-b61b-468b-8787-5f7503734dca.jpg)
![dog](https://user-images.githubusercontent.com/87156398/156311112-bb9cc8cb-ee0c-4a74-aa2a-1b15cb463a06.jpg)
Not only percentage is too low, but also Jetson recognizes dog as cat.

In case of object detection, some fruits are detected, but the others are not detected. But the fruits that are detected don't always detect accurately, for example, some banana pictures are detected, but others are not detected.

Thank you for reading this issue.

**Comment by dusty-nv** [comment]
Hi @SangkyunAhn, can you try deleting the `*.engine` files from your model's directories and try running imagenet/detectnet again?

Also, you can find my trained models for cat/dog and the fruits dataset on the tutorial pages.  Can you try those to see if there is a difference?

**Comment by SangkyunAhn** [comment]
I solved these problems. Thank you for your help.
