### ISSUE TITLE
use another pre-trained weight

### ISSUE THREAD

**Issue by amirafshari** [dusty-nv/jetson-inference#1381]
Hi,

I want to train [SSD object detection](https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-ssd.md#setup) model on my own dataset;

1- How to train it from scratch (without any pre-trained weight)?
2- How to use another pre-trained weight like [mobilenetv2](https://download.pytorch.org/models/mobilenet_v2-b0353104.pth) instead of mobilenetv1?
3- How to train it with different classification heads? ( I set --net to mb2-ssd-lite but received error)

The error I receive when changing the pre-trained weight or --net parameter:
**Unexpected key(s) in state_dict**

**Comment by dusty-nv** [comment]
Hi @amirafshari, sorry for the delay - you can disable the pre-trained weights in train_ssd.py (they are enabled by default).   Also I had recently validated that mobilenetv2 backbone works, although I didn't see much performance improvement from it.
