### ISSUE TITLE
Will there be any update of the posenet.py?

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#1384]
Hi, I am currently using posenet with resnet18-boday and densenet121-body, and I am happy with them. :>

May I know if we can download other network for testing? I aim for crowd skeleton detection in the future.

Btw, mediapipe is getting better as it uses previous frame data to increase accuracy, Will there be any development about it? I am thinking to use the keypoints from previous frame, but if the posenet does not allow any keypoints input, how can I do it?
Thx

**Comment by dusty-nv** [comment]
Hi @AK51, I don't plan to personally make more pose models, they originally came from https://github.com/NVIDIA-AI-IOT/trt_pose project
