### ISSUE TITLE
Issues about fixed the FPS 

### ISSUE THREAD

**Issue by zhuzhuxia1221** [dusty-nv/jetson-inference#1386]
Hello,
When I run fcn-resnet18-cityscapes-512x256 on Jetson Xavier, the FPS is too high for me. 
Can I make the FPS at a fixed value, such as 60? 
Looking forward to u reply.

**Comment by dusty-nv** [comment]
@zhuzhuxia1221 sorry for the delay - you should limit the framerate from the camera, or add the equivalent of a `sleep()` call to slow down the processing.
