### ISSUE TITLE
NVIDIA server downloads fail

### ISSUE THREAD

**Issue by tensorturtle** [dusty-nv/jetson-inference#1396]
Hello @dusty-nv , I know that this is not your responsibility exactly, but several download links are (recently) broken for Jetson-related things, such as SD card images from https://developer.nvidia.com/embedded/downloads (404 Error) . Also,  SDK Manager returns the attached error. My co-worker and I have tried from two different countries. Please forward this problem to whomever is responsible for it in NVIDIA. Thank you.

![sdkerror](https://user-images.githubusercontent.com/75611662/161091092-40e4a51d-6744-456f-8974-12db14730ca0.jpeg)

**Comment by dusty-nv** [comment]
Hi @tensorturtle, sorry about that, yes we are working to resolve the issue:

https://forums.developer.nvidia.com/t/tensorflow-download-removed/209866/2

**Comment by tensorturtle** [comment]
Problem appears to have been fixed. Thank you.
