### ISSUE TITLE
opencv, CSI camera, gstreamer crashes

### ISSUE THREAD

**Issue by daphilpot** [dusty-nv/jetson-inference#1397]
I am trying to use the videocapture functio from opencv2 with a IMX219 CSI camera onboard, but I have been unable to open the camera after many tries.

I have followed code from here: [OpenCV Video Capture with GStreamer doesn't work on ROS-melodic - #3 by DaneLLL](https://forums.developer.nvidia.com/t/opencv-video-capture-with-gstreamer-doesnt-work-on-ros-melodic/113147/3)

trying to use a gstreamer like:

`“nvarguscamerasrc ! video/x-raw(memory:NVMM), width=(int)1920, height=(int)1080,format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv ! video/x-raw, format=(string)BGRx ! videoconvert ! appsink”`

and also from here: [CSI-Camera/simple_camera.py at master · JetsonHacksNano/CSI-Camera · GitHub 1](https://github.com/JetsonHacksNano/CSI-Camera/blob/master/simple_camera.py)

but in both cases the camera fails to open.

Even trying to launch camera from command line using:

gst-launch-1.0 nvarguscamerasrc ! nvoverlaysink

returns an error of:
```

Error generated. /dvs/git/dirty/git-master_linux/multimedia/nvgstreamer/gst-nvarguscamera/gstnvarguscamerasrc.cpp, execute:656 Failed to create CaptureSession

(gst-launch-1.0:32103): GStreamer-CRITICAL **: 22:02:06.568: gst_mini_object_set_qdata: assertion 'object != NULL' failed
Got EOS from element "pipeline0".
```

For reference, I am using Jetpack 4.5 with latest versions of opencv etc.

**Comment by dusty-nv** [comment]
Closing this issue as it is unrelated to this repo.  @daphilpot please post your issue to the Jetson forums
