### ISSUE TITLE
Randomness at inference time

### ISSUE THREAD

**Issue by aafaqin** [dusty-nv/jetson-inference#1402]
When I am running detection on JETSON NANO with 288x192 input size the detection time are different for all detection mostly it gives 10FPS but sometimes detection time drops to 5FPS and it happens randomly for 10% of the time. Any way I can reduce this randomness?
This is only detection time not preprocessing time.
Can someone please help me with this?

**Comment by dusty-nv** [comment]
Hi @aafaqin, can you try running `sudo jetson_clocks.sh` script?

**Comment by aafaqin** [comment]
Yes I have run that. Still the randomness Exists.

**Comment by aafaqin** [comment]
I am doing RTSP but the FPS I am mentioning is only after the RTSP frame is acquired and then the inference function is called.

**Comment by shithanshu-beltech** [comment]
@dusty-nv  can we run jetson_clocks.sh in production mode in a scenario when jetson board will be running 24X7

**Comment by dusty-nv** [comment]
@shithanshu-beltech I would refer to the module datasheet to be sure, but with proper cooling yes it should be fine.  Also you can create your own nvpmodel profile with lower clocks if desired.  Or perhaps in your scenario you don't need jetson_clocks.sh

**Comment by shithanshu-beltech** [comment]
Thanks @dusty-nv Will try it out and update you
