### ISSUE TITLE
Is the Pose-ResNet-18-Body model the same as BodyPoseNet from ngc?

### ISSUE THREAD

**Issue by lanzani** [dusty-nv/jetson-inference#1408]
Hi! 
I have this question, it seems to me that yes, they are the same. Or I miss something?

BodyPoseNet from ngc [here](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/models/bodyposenet).

Thank you for your patience 😄

**Comment by dusty-nv** [comment]
Hi @lanzani, I got the pose models from https://github.com/NVIDIA-AI-IOT/trt_pose
