### ISSUE TITLE
gstDecoder fail!!

### ISSUE THREAD

**Issue by Aziz-repo** [dusty-nv/jetson-inference#1411]
Hi,
I've been using the jetson inference and I want to stream a video from the jetson to my PC so I tried to use the RTP protocol as mentioned in the docs. I run the command "video-viewer --device=/dev/video0 --input-codec=h264 rtp://<PC ip>:<port>
and I run in this issue :
![issue](https://user-images.githubusercontent.com/81187136/167227767-6d00d456-a9e8-44e7-aad6-bc272bd3c2ad.PNG)
 I'm using jetson as headless mode with an USB camera 
![camera](https://user-images.githubusercontent.com/81187136/167227850-5768879d-afc3-48cd-a588-81e2bc024972.PNG)

**Comment by dusty-nv** [comment]
Hi @Aziz-repo, try this command line instead:

``` bash
video-viewer --input-codec=h264 /dev/video0 rtp://192.168.1.100:5000
```

Replace `192.168.1.100` with the IP address of your PC (or hostname of your PC)
