### ISSUE TITLE
How to Set BatchSize in Python example about ImageNet？

### ISSUE THREAD

**Issue by ZengyuanYu** [dusty-nv/jetson-inference#1417]
I wrote it in the following example：https://github.com/dusty-nv/jetson-inference/blob/master/python/examples/my-recognition.py
And It had pass run。
But，when I changed BatchSize to find some speed or optimal，i found i can't do it.
Change like this:
![{0513a408-218e-40d2-bc07-81d435c2adc6}](https://user-images.githubusercontent.com/31333405/168477888-5171478f-9419-4bc2-81a4-cf94b2d136c4.png)

but result like this,BacthSize don‘t work:
![{655e258e-fdb7-4332-9ba4-257679adfc34}](https://user-images.githubusercontent.com/31333405/168477906-bc9d4e8a-ef08-4ef1-a964-29241b67ba84.png)
![{72737600-8d2c-4acc-b1a5-56c0a6c90e7a}](https://user-images.githubusercontent.com/31333405/168477911-781f70ea-592c-4c1b-9b2a-dc0cf5d55dbe.png)

**Comment by dusty-nv** [comment]
Hi @ZengyuanYu, yes you are correct, changing batch size isn't supported with imageNet.  The API only supports single-image inference.
