### ISSUE TITLE
Multi-class Classification with Resnet and jetson-inference

### ISSUE THREAD

**Issue by saeed-musashi** [dusty-nv/jetson-inference#1418]
Is there a way to perform Multi-class (multiple labels per image) Classification with Resnet and jetson-inference library?

**Comment by dusty-nv** [comment]
Hi @saeed-musashi, do you mean returning the top-K classification results or performing true multi-class classifications?

For the former, the data is there but there isn't an API for retrieving it.
For the later, I think it would require a different model (and API changes) that the basic resnet doesn't support?

**Comment by saeed-musashi** [comment]
Thanks @dusty-nv, I meant multi-class classification (the later).
