### ISSUE TITLE
Building the Container for L4T R34.1.0

### ISSUE THREAD

**Issue by arnaudbuy** [dusty-nv/jetson-inference#1419]
Is the `docker/build.sh` script up to date for L4T R34.1.0 ?

**Comment by arnaudbuy** [comment]
Thank you @dusty-nv. The script works when you specify the base image `docker/build.sh nvcr.io/nvidia/l4t-pytorch:r34.1.0-pth1.12-py3`.

**Comment by dusty-nv** [comment]
Thanks @arnaudbuy - just fixed this in https://github.com/dusty-nv/jetson-inference/commit/bed39a4ed9f6477ac7337295bf6713a46caebaec
