### ISSUE TITLE
What's the unit of the Raw Depth Field in depthnet?

### ISSUE THREAD

**Issue by Hazeline2018** [dusty-nv/jetson-inference#1420]
Hi Dusty, I'm working on mono-depth algorithm and testing with provided "depthnet" model. I can get the Raw Depth Field readings by calling GetDepthField() method. But I'm confused about the real meaning of the FP numbers. As far as I understand, the depth number for each pixel (depending on the --depth-size scale) is relative depth estimate. But what is the unit of the depth? If it's a relative ratio, then reference to what? For example, on one image, the range of depth field is (min=0.8974, max=4.3873), are they normalized?

thanks!
Terry

**Comment by Hazeline2018** [comment]
Better yet, is there detailed explanation doc about depthnet model other than just the depthnet.md? I searched API ref doc, but no much details.

**Comment by dusty-nv** [comment]
@Hazeline2018 sorry for the delay - during visualization (rendering of the colorized image), histogram equalization is used, but there is no post-processing applied to the raw depth field, and I'm not sure what normalization the model itself applies.   The models came from https://fastdepth.mit.edu/
