### ISSUE TITLE
is it possible to use SPI from spidev inside detectnet ?

### ISSUE THREAD

**Issue by r2ba7** [dusty-nv/jetson-inference#1423]
I'm using the jetson-inference and using detectnet.py using CSI camera for live inference, I will extract the bounding box heads (xmin,max and ymin,max) and class label and use them to as information to be sent to another microprocessor (TIVA-C ARM), so I was wondering does spidev library can come on handy at this detectnet.py or should I go for the detect.cpp ?

**Comment by dusty-nv** [comment]
Hi @r2ba7, I'm not experienced with using SPI interface myself, but it appears there is a `spidev` module for Python available, so perhaps you can continue using Python if you prefer?

https://pypi.org/project/spidev/
