### ISSUE TITLE
Problem with SPI and live detection

### ISSUE THREAD

**Issue by r2ba7** [dusty-nv/jetson-inference#1425]
I’m trying to use the SPI1 bus on a Jetson NANO configured using Jetpack 4.3.
I followed the instruction from [https://www.jetsonhacks.com/2020/05/04/spi-on-jetson-using-jetson-io/ ](https://www.jetsonhacks.com/2020/05/04/spi-on-jetson-using-jetson-io/)to enable the SPI1. I want to use the SPI to send some info from live detection from jetson-inference ./detectnet csi://0.
The problem before setting the 40-pin configurations the fps was 24-25 … after setting it up, the fps dropped to 3-4
when using simple_camera.py from CSI-Camera repo it lags and it’s really affected.
I know that the problem from the configurations because once I did it I tested it because I reset my nano because of it.

**Comment by dusty-nv** [comment]
Hi @r2ba7, I would recommend posting this issue to the Jetson Nano forum, as I'm not experienced with SPI bus and it doesn't really pertain to this repo.  Thank you - 

https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76
