### ISSUE TITLE
running the docker/build.sh doesn't works 

### ISSUE THREAD

**Issue by DiegoBran16** [dusty-nv/jetson-inference#1426]
Hello I'm facing troubles while trying to save some extra dependencys on the Jetson-inference container, first it showed this error 

cannot build jetson-inference docker container for L4T R32.7.1
please upgrade to the latest JetPack, or build jetson-inference natively

then I tried to build the container with this command 

sudo docker build - < Dockerfile

but I'm getting this error 

failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/0d364a2a0f71ab70ee6cd250b2ca4fb8c4f5ede002aefcb4cc4a167d43190e97/merged/usr/lib/aarch64-linux-gnu/tegra/libnvidia-fatbinaryloader.so.440.18: file exists: unknown

Then I tried to run the solution I found on another repository  that was this one 

distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update
sudo apt-get install nvidia-docker2=2.8.0-1

but I still don't get it work

**Comment by dusty-nv** [comment]
If you're unable to get your docker daemon working correctly, I would just recommend reflashing your device or SD card instead of spending a bunch more time on it.   Then make sure you can run l4t-pytorch container:

``` bash
sudo docker run -it --rm --runtime nvidia --network host nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.9-py3
```

Then when you go to build jetson-inference container:

``` bash
cd jetson-inference
docker/build.sh nvcr.io/nvidia/l4t-pytorch:r32.7.1-pth1.9-py3
```
