### ISSUE TITLE
How can I implement joint (simultaneous) segmentation and classification model ??

### ISSUE THREAD

**Issue by LoyalLumber** [dusty-nv/jetson-inference#1431]
Many thanks for this great work. 

Currently, I'm trying to implement **a joint model** that provides simultaneous segmentation and classification outputs. 
In this case, I use a backbone network **ResNet18**. I want to implement the joint model **adapting this repository** since it is very fast. My model will be simple while I just add another path with FC and softmax layers at the end of the FCN-ResNet18 encoder. 

However, it is hard to figure out where I should start and I hope to hear some answers from the expert. **Please comment** the below questions. 
1) Where is the initial point for the implementation? Probably, I need to prepare the custom model with ONNX format. After this, do I need to modify 'SegNet.cpp', 'SegNet.cu' in your repository '**jetson-inference**'? 
2) If so, it will be complicated to analyze the codes and needs hard coding. Is there easier way to implement the model?

I look forward to hearing from you.

**Comment by dusty-nv** [comment]
Hi @LoyalLumber, yes you would need to modify `segNet.cpp` with the adaptations required for your model.  Typically that means interpreting some additional output layers, changing pre/post-processing, ect.

If you are uncomfortable with the C++ code, you could make a standalone Python program using the TensorRT Python API (like shown in the TensorRT samples)
