### ISSUE TITLE
How to use .onnx object detection custom models in jetson inference engine on jetson nano 2GB ?

### ISSUE THREAD

**Issue by TonioBoubs** [dusty-nv/jetson-inference#1434]
Hi @dusty-nv, I tried to import and use a RetinaNet model in the jetson inference engine. I used two .onnx models as you inform they might be compatible :
- The first : [retinaNet-9.onnx](https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/retinanet)
I do not understand what I should use for both the coverage and the bbox output args since it is written "the model has 2 outputs, both 5 tensors of rank 4".
Could you help me to know how I can fill the arguments --output-bbox and --output-coverage of the command line ?

- The second which is a conversion of a [.pth model](https://github.com/NVIDIA/retinanet-examples/releases/tag/19.04) thanks to this script (adapted from this [pytorch](https://pytorch.org/docs/stable/onnx.html#example-alexnet-from-pytorch-to-onnx) converter example) :
```
import torch
import torchvision
import torch.onnx
dummy_input = torch.randn(1, 3, 640, 480, device=torch.device('cuda' if torch.cuda.is_available() else 'cpu'))
model = torchvision.models.detection.retinanet_resnet50_fpn(pretrained=True, num_classes=91).cuda()
model.eval()
input_names = [ "actual_input_1" ] #+ [ "learned_%d" % i for i in range(16) ]
output_names = [ "output_%d" % i for i in range(3) ]
torch.onnx.export(model, dummy_input,  "retinanet_resnet50_fpn.onnx",export_params=True, verbose=True,input_names=input_names, output_names=output_names,opset_version=11)
```
But unfortunately even by notifying the several args (model, label, input and both bbox and coverage output layers), the engine fails to integrate the model from the beginning of the model loading.

Here is my command line : 
```python3 detectnet.py --model=$MODEL_PATH/retinanet_resnet50_fpn3.onnx --labels=$MODEL_PATH/ssd_coco_labels.txt --input-blob=actual_input_1 --output-cvg=output3 --output-bbox=output1 images/peds_0.jpg images/test/output.jpg```

But the engine rejects them writing : 
```
[TRT]   ModelImporter.cpp:726: ERROR: ModelImporter.cpp:179 In function parseGraph: [6] Invalid Node - Resize_41
[graph.cpp::computeInputExecutionUses::519] Error Code 9: Internal Error (Floor_28: IUnaryLayer cannot be used to compute a shape tensor)
[TRT]    failed to parse ONNX model '/home/roboat/jetson-inference/build/aarch64/bin/mymodels/RETINANET/retinanet_resnet50_fpn3.onnx'
[TRT]    device GPU, failed to load /home/roboat/jetson-inference/build/aarch64/bin/mymodels/RETINANET/retinanet_resnet50_fpn3.onnx
[TRT]    detectNet -- failed to initialize.
jetson.inference -- detectNet failed to load network
Traceback (most recent call last):
 File "detectnet_copy.py", line 54, in <module>
    net = jetson.inference.detectNet(opt.network, sys.argv, opt.threshold)
Exception: jetson.inference -- detectNet failed to load network
```
Could you please try to use the model in the inference engine or to explain me what is wrong or what is missing in this model ?

Many thanks !

**Comment by dusty-nv** [comment]
Hi @TonioBoubs, you could also try loading your ONNX model with trtexec tool (found under `/usr/src/tensorrt/bin`) and see if that's able to load it.  If it isn't, that would confirm that TensorRT has some parsing this model and it would probably require some modification(s) to the model to make it work.

Regarding the output tensors, not every object detection DNN architecture is going to correspond to those exact 2 types of output tensors that I support in the code.  You may need to alter the post-processing in detectNet.cpp to interpret these differently.  There is no one catch-all solution to supporting all types of models without also implementing the pre/post-processing for them.
