### ISSUE TITLE
update:problem with make command

### ISSUE THREAD

**Issue by vijay1421** [dusty-nv/jetson-inference#1441]
hi @dusty-nv 
please give me a solution for this
global@GAT-EEE:~/jetson-inference/build$ make
[ 38%] Built target jetson-utils
[ 51%] Built target jetson-inference
[ 53%] Built target imagenet
[ 55%] Built target imagenet-console
[ 56%] Built target imagenet-camera
[ 57%] Built target depthnet
[ 59%] Built target detectnet-camera
[ 60%] Built target detectnet
[ 61%] Built target detectnet-console
[ 63%] Built target posenet
[ 65%] Built target segnet-camera
[ 66%] Built target segnet
[ 67%] Built target segnet-console
[ 68%] Automatic MOC for target camera-capture
[ 68%] Built target camera-capture_autogen
[ 72%] Built target camera-capture
[ 74%] Built target camera-viewer
[ 76%] Built target video-viewer
[ 78%] Built target gl-display-test
[ 84%] Built target jetson-utils-python-27
[ 84%] Linking CXX shared library ../../../aarch64/lib/python/3.6/jetson_utils_python.so
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_add_one_to_index_F' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(abstract.o): In function `PyBuffer_FromContiguous':
/tmp/Python-3.6.5/Objects/abstract.c:502:(.text+0x1aa4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_add_one_to_index_C' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/abstract.c:502:(.text+0x1aa8): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(typeobject.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `PyType_GenericAlloc' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(typeobject.o): In function `type_new':
/tmp/Python-3.6.5/Objects/typeobject.c:2681:(.text+0x10974): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x5fa4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToTitlecase':
/tmp/Python-3.6.5/Objects/unicodectype.c:69:(.text+0x5fc8): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x600c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x605c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x60ac): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToDecimalDigit':
/tmp/Python-3.6.5/Objects/unicodectype.c:110:(.text+0x60fc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x6154): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToDigit':
/tmp/Python-3.6.5/Objects/unicodectype.c:127:(.text+0x61a4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x61fc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x624c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x629c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x62ec): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x633c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x638c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToUppercase':
/tmp/Python-3.6.5/Objects/unicodectype.c:195:(.text+0x63b4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x63fc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToLowercase':
/tmp/Python-3.6.5/Objects/unicodectype.c:207:(.text+0x6420): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x6470): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToLowerFull':
/tmp/Python-3.6.5/Objects/unicodectype.c:220:(.text+0x64b0): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x6528): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToTitleFull':
/tmp/Python-3.6.5/Objects/unicodectype.c:236:(.text+0x6568): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x65e0): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToUpperFull':
/tmp/Python-3.6.5/Objects/unicodectype.c:252:(.text+0x6624): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x6698): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToLowerFull':
/tmp/Python-3.6.5/Objects/unicodectype.c:220:(.text+0x66dc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_ExtendedCase' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `_PyUnicode_ToFoldedFull':
/tmp/Python-3.6.5/Objects/unicodectype.c:268:(.text+0x6728): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(unicodectype.o): In function `gettyperecord':
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x677c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x67cc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_PyUnicode_TypeRecords' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/Objects/unicodectype.c:55:(.text+0x681c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setresgid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:5173:(.text+0x293c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setresuid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:5139:(.text+0x29f4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `posix_initgroups':
/tmp/Python-3.6.5/./Modules/posixmodule.c:6213:(.text+0x4b0c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setregid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:2789:(.text+0x4bf4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setegid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:2724:(.text+0x4ca8): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setgid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:2821:(.text+0x4d50): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setreuid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:2756:(.text+0x4df4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_seteuid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:2693:(.text+0x4ea8): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_setuid':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:2662:(.text+0x4f50): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_fchown':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:741:(.text+0x66c4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:741:(.text+0x66c8): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `posix_getgrouplist':
/tmp/Python-3.6.5/./Modules/posixmodule.c:6033:(.text+0x7b1c): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_lchown':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:780:(.text+0xa3a4): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:780:(.text+0xa3bc): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Gid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(posixmodule.o): In function `os_chown':
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:700:(.text+0xb038): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_Uid_Converter' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/Python-3.6.5/./Modules/clinic/posixmodule.c.h:700:(.text+0xb088): dangerous relocation: unsupported relocation
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(myreadline.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `PyOS_StdioReadline' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.6m.a(myreadline.o): In function `PyOS_Readline':
/tmp/Python-3.6.5/Parser/myreadline.c:319:(.text+0x43c): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
utils/python/bindings_python_3.6/CMakeFiles/jetson-utils-python-36.dir/build.make:257: recipe for target 'aarch64/lib/python/3.6/jetson_utils_python.so' failed
make[2]: *** [aarch64/lib/python/3.6/jetson_utils_python.so] Error 1
CMakeFiles/Makefile2:1130: recipe for target 'utils/python/bindings_python_3.6/CMakeFiles/jetson-utils-python-36.dir/all' failed
make[1]: *** [utils/python/bindings_python_3.6/CMakeFiles/jetson-utils-python-36.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dusty-nv** [comment]
> /usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_add_one_to_index_F' which may bind externally can not be used when making a shared object; recompile with -fPIC`

Hmm on my Jetson's, I don't have this `/usr/local/lib/libpython3.6m.a` library present

Can you try renaming it like suggested in this post?  https://stackoverflow.com/a/48009963
