### ISSUE TITLE
Drive AGX Xavier Support

### ISSUE THREAD

**Issue by osholsonel20** [dusty-nv/jetson-inference#1445]
I understand this doesn't have "Jetpack" on the device, but would there be some ways of modifying the codebase to support running on a drive device? Having trouble integrating the built in driveworks inference solutions so i'm looking into this instead

**Comment by dusty-nv** [comment]
Hi @osholsonel20, I haven't developed for the DRIVE platform before, so while I do believe some aspects are similar, I'm not sure of the changes required to support it.

**Comment by osholsonel20** [comment]
Sounds good, it has TensorRT 5.1 and Cuda-10.2. Do you know a branch that would suffice this req? I think the only hiccup I've had when running through the install directions was it really wanting me to have jetpack on the system. So if you have any ideas of how to "de-couple" that so it's just utilizing the relevant TensorRT version that'd work too!
