### ISSUE TITLE
no element "nvv4l2decoder"

### ISSUE THREAD

**Issue by KevinRK27** [dusty-nv/jetson-inference#1447]
I am able to run posenet example on jetson but i am unable to do it on my x64 ubuntu 20.04 pc if i use video file as input.
./posenet file://sample.mp4 --input-codec=h264
[gstreamer] initialized gstreamer, version 1.16.2.0
[gstreamer] gstDecoder -- creating decoder for sample.mp4
[gstreamer] gstDecoder -- Could not open resource for reading.
[gstreamer] gstDecoder -- pipeline string:
[gstreamer] filesrc location=sample.mp4 ! qtdemux ! queue ! h264parse ! nvv4l2decoder ! video/x-raw(memory:NVMM) ! nvvidconv ! video/x-raw ! appsink name=mysink
[gstreamer] gstDecoder -- failed to create pipeline
[gstreamer]    (no element "nvv4l2decoder")
[gstreamer] gstDecoder -- failed to create decoder for file://sample.mp4
posenet: failed to create input stream

how to fix no element nvv4l2decoder?

**Comment by zengjie617789** [comment]
I meet the same error, did you solve it ?
