### ISSUE TITLE
issue between gstreamer and jetson.utils 

### ISSUE THREAD

**Issue by caro266** [dusty-nv/jetson-inference#1452]
Hello,

I have a camera plugged on my jetson Nano and I would like to stream the result of my model.

First I wanted to change your "video-viewer.py" to test it, because my input is little bit different. I don't use openCv to capture the video, but one of my class do it and return a nparray.

![my-video-viewer](https://user-images.githubusercontent.com/75388660/177380292-7bab7e8b-402d-4691-99f3-713ecec65073.png)

When I launch my-video-viewer on the jetson Nano, I can see my camera with all the pretreatment I make in my class. it's OK.

But, on my computer, when I start the same program with the ssh and on the other console I try to get back the stream with gst, I have a mistake "The pipeline can't be create"

![RetourGst](https://user-images.githubusercontent.com/75388660/177380903-16557ab2-822c-4f5f-a1cc-c05506f9f80f.png)

I'm pretty sure it's pretty simple to fix, but not for me :).
Do you have an idea or did I miss a documentation which can help me?

Thanks a lot.

I hope my english was enough clear to be understand

**Comment by dusty-nv** [comment]
Hi @caro266, can you provide the console log of `my-video-viewer` while running under ssh?

If you are using `ssh -X` (X11 tunneling), I would try disabling that first.

**Comment by caro266** [comment]
Thank you for your quick answer.
I don't use ssh -X, just  ssh nano@192.168.10.10

![SSH](https://user-images.githubusercontent.com/75388660/177485986-1e1cffb0-40c1-464b-864b-2630f53315b3.png)
![SSH2](https://user-images.githubusercontent.com/75388660/177486021-b640c9c3-7d9c-4b96-995c-fee22c45c0f6.png)

**Comment by dusty-nv** [comment]
Hmm...unfortunately I don't see anything in the log which would indicate a problem.

If you check `ifconfig` of your Nano while it's streaming RTP, do you see the TX packets increasing?    Likewise on your PC side, do you see RX packets increasing?

**Comment by caro266** [comment]
I run the program from the Nano or from the PC via ssh, neither TX or RX increase. 
So the issue is with the pipeline? Do you think I have to install again something?

**Comment by dusty-nv** [comment]
How are you attempting to view the RTP stream on your PC?   Can you try it with GStreamer like shown under this section:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#viewing-rtp-remotely

**Comment by caro266** [comment]
I use this command :

gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM), width=3280, height=2464, format=NV12, framerate=30/1' ! nvoverlaysink

I saw a tuto where Nano send a sound via gstreamer, I'm going to test it

**Comment by caro266** [comment]
Hello,

How are you?
After some tests, I can receive pictures from my camera which is on my jetson Nano. So I can run my inference an jetson and stream the result on my PC. 

I have to put sudo at the beginning of my command line : 
sudo gst-launch-1.0 -v udpsrc port=1234  caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" !  rtph264depay ! decodebin ! videoconvert ! autovideosink

Thanks a lot for your answers and sorry to have disturbed you for so little
