### ISSUE TITLE
SyntaxError: future deature annotations is not defined

### ISSUE THREAD

**Issue by iotproductions** [dusty-nv/jetson-inference#1456]
Dear all,

I 'm trying to run the training examples (**Re-training on the Cat/Dog Dataset**) but I got problem as the below screenshot:
![Screenshot from 2022-07-14 19-31-59](https://user-images.githubusercontent.com/6419276/178984296-dc587079-aebb-4773-8cc7-22176bfd09cc.png)

Could you please let me know what is this errors ?
Thanks all !

**Comment by dusty-nv** [comment]
Hi @iotproductions, can you try running `pip3 install 'pillow<7'`?
