### ISSUE TITLE
Make problem

### ISSUE THREAD

**Issue by Patrick0920** [dusty-nv/jetson-inference#146]
/usr/bin/ld: warning: libcudnn.so.7, needed by /usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnSetLRNDescriptor'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnSetFilter4dDescriptor'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnGetRNNLinLayerMatrixParams'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnCreateConvolutionDescriptor'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnDestroyConvolutionDescriptor'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnSetTensorNdDescriptor'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../../lib/libnvinfer.so: undefined reference to `cudnnSetFilterNdDescriptor'

**Comment by XhqGlorry11** [comment]
@dusty-nv same problem here. I have installed cudnn in /usr/local/cuda-8.0. Any suggestions about what's going wrong?

**Comment by deksprime** [comment]
Something's really gone wrong with libnvinfer nowadays. I've been experiencing another problem related to libnvinfer and have stumbled upon this issue while I was searching for a solution in google. The problem I'm having is that I'm not able to install tensorRT2.1.2 since it looks for this libnvinfer3 and I really don't know how to install it.

**Comment by dusty-nv** [comment]
Is your Jetson TX1/TX2 running JetPack 3.1?   It should automatically install cuDNN and TensorRT 2.1 for you.

**Comment by deksprime** [comment]
my bad ... I was trying to install from the website with the deb package

**Comment by RoboEvangelist** [comment]
still. I used Jetpack 3.2, and I have the same probelm
