### ISSUE TITLE
Anybody make it past Posenet on jetson nano 4GB? How about the FPS?

### ISSUE THREAD

**Issue by formerlya** [dusty-nv/jetson-inference#1460]
I have tried trt_pose on nano,which is 10FPS.
I want to know the FPS about posenet.
Thanks！！

**Comment by dusty-nv** [comment]
@formerlya the posenet FPS on Nano should be similar to https://github.com/NVIDIA-AI-IOT/trt_pose#step-3---run-the-example-notebook

**Comment by formerlya** [comment]
Thanks for your timely response！
When I runing the model downloader
![image](https://user-images.githubusercontent.com/88373367/182542965-72e54f79-c158-4f85-9d6c-1bb389d7601d.png)
Unable to download due to network problem
But in [https://github.com/dusty-nv/jetson-inference/releases](https://github.com/dusty-nv/jetson-inference/releases)
I couldn't find module about pose.
Should I download all of them?

**Comment by dusty-nv** [comment]
Hi @formerlya, thanks for pointing these out - I've just uploaded the PoseNet models to that releases page on GitHub, so you should now be able to download them from there.

**Comment by formerlya** [comment]
@dusty-nv Thanks!
In my nano, the FPS is 15.
A little faster than [trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose).
And your answers to other questions have also helped me a lot~

**Comment by formerlya** [comment]
@dusty-nv Thanks!
In my nano, the FPS is 15.
A little faster than [trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose).
And your answers to other questions have also helped me a lot~
