### ISSUE TITLE
Convert Caffe --> ONNX

### ISSUE THREAD

**Issue by eanmikale** [dusty-nv/jetson-inference#1466]
@dusty-nv - Do you have any recommendations for cleanly converting a Caffe file? Is it easier to convert from Caffe to Caffe2? We really like ONNX. We have had issues converting our file. We know it is not corrupted can can run it on a Jetson as a caffe file. We just wanted to know what you personally use if you've ever had to do a clean conversion for a Caffe file after using DIGITS, for example? Thank you.

**Comment by dusty-nv** [comment]
Hmm I have not done this myself @eanmikale - basically I've moved all my training to PyTorch (no longer using DIGITS), and I export the ONNX directly from PyTorch checkpoints.

The models that I had trained in DIGITS were all of older/inferior DNN architectures anyways, so it was just better to move on to more updated stuff in PyTorch.  YMMV, but it does appear there are a variety of Caffe-to-ONNX converter tools on GitHub and PyPi.
