### ISSUE TITLE
FullScreen issues

### ISSUE THREAD

**Issue by maocaixia** [dusty-nv/jetson-inference#1467]

**Comment by maocaixia** [comment]
How to FullScreen to show the results of posenet.py?

**Comment by maocaixia** [comment]
@dusty-nv

**Comment by dusty-nv** [comment]
You could add the line `SetFullscreen(true);` to here:   https://github.com/dusty-nv/jetson-utils/blob/a2c1eefb3c30955d31ef1dcb49a6dc4c0f50b720/display/glDisplay.cpp#L374

Then re-run `make` and `sudo make install`
