### ISSUE TITLE
Can't restart Desktop GUI

### ISSUE THREAD

**Issue by namaws** [dusty-nv/jetson-inference#1469]
Hello,

I am using jetson nano 2GB developer kit to do re-train SSD mobile net with custom dataset.
However, when I try to disable the Desktop GUI, I can't restart the Desktop GUI.
My screen turn black and on the left top of my desktop, it seems that I can type command line, but I can't. 
I have to restart my jetson nano in order to restart the Desktop GUI. 

$ sudo init 3     // stop the desktop
// log your user back into the console
// run the PyTorch training scripts
$ sudo init 5     // restart the desktop

Thank you

**Comment by dusty-nv** [comment]
Hmm I am not sure, normally `sudo init 5` restarts the desktop.  In that case, I would just recommend rebooting the system as you have been doing - sorry for the inconvenience.
