### ISSUE TITLE
In posenet.py.how to judge specific keypoints if they exist and get their value

### ISSUE THREAD

**Issue by formerlya** [dusty-nv/jetson-inference#1470]
When I use the posenet.py.
I want to check if nose/left_eye in pose.Keypoints, and according to its value for further judgment.
①if "nose" in pose.Keypoints:
pose.Keypoints is a list, but it always thought it didn't exist.

②if pose.Keypoints[0][0]==nose
TypeError:'jetson.inference.poseNet.ObjectPose.Keypoint' object is not subscriptable.
Tried a lot.
……
……
I wonder if you can help me with the list element judgment^_^.
Thank you so much if you can.

**Comment by formerlya** [comment]
When I use pose.Keypoints[0].ID, it worked.
But except nose(0) and neck(17), how to judge them if they exist and get their value.
such as left_knee ……

**Comment by dusty-nv** [comment]
Hi @formerlya, below you can see a Python example of finding specific keypoints by their name:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/posenet.md#working-with-object-poses

**Comment by formerlya** [comment]
Thank you very much for your answer, I am a novice, thank you for your advice!

**Comment by formerlya** [comment]
left_wrist_idx = pose.FindKeypoint('left_wrist')
