### ISSUE TITLE
A power consumption in using TensorRT

### ISSUE THREAD

**Issue by MiniVanlab** [dusty-nv/jetson-inference#1472]
Maybe this is not the right place to ask this question.I have a problem when I use jetson nano to develop. I want to create a RIP（A sensor triggered by infrared light）camera. I hope it can operate with low power consumption when the RIP sensor is not activated，and when the sensor is activated ,Jetson nano can start the image recognition quickly to know what triggered the sensor.But it seems that if running the program after the sensor is activated , loading the retrain model takes a lot of time. So I load the models first in my Python program , and get the status of sensor after loading. However, after loading the models, Jetson nano always Operate at higher power consumption, although the sensor has not been triggered, which means recognition didn't start. What can I do to make it work at low power consumption after loading models?
 I would appreciate it if you could give me any help.

**Comment by dusty-nv** [comment]
Hi @MiniVanlab, you could manually change your Nano to 5W mode by running `sudo nvpmodel -m 1`

You can also keep an eye on the clocks with `sudo tegrastats`
