### ISSUE TITLE
A power problem in Jetson Nano

### ISSUE THREAD

**Issue by Wadaxivan** [dusty-nv/jetson-inference#1473]
When I ran my deep learning model last week, it worked well .Today when it was running,  its CPU temperature is too high and automatically shut down. Is there any way to check the cause of abnormal temperature?

**Comment by dusty-nv** [comment]
Hi @Wadaxivan, you may want to post your question about thermals to the Jetson Nano forums:  https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76

If you want to get a fan, until then you could always run your Nano in 5W power mode with `sudo nvpmodel -m 1`

**Comment by Wadaxivan** [comment]
OK! I am so sorry.
