### ISSUE TITLE
Models will not download through model downloader.

### ISSUE THREAD

**Issue by RoninHunter** [dusty-nv/jetson-inference#1479]
step 1: I clone repo
step 2: cd jetson-inference
step 3: docker/run.sh

When I run the above command and the model loader pops up, I select the models I want to use but every one of them gets a 

"Download Error"

My only option is to quit because retry does not thing but produce the error again.

The image downloaded perfect when doing a git clone so it can't be a connection problem.

Any thoughts?

**Comment by dusty-nv** [comment]
Hi @RoninHunter, I just ran the model downloader again from here, and was able to download the models without issue.   If you are in China they may block the URL.  In that case, there is a mirror of the models that you can manually download from here:  https://github.com/dusty-nv/jetson-inference/releases/tag/model-mirror-190618
