### ISSUE TITLE
Support Jetpack 5.0.2?

### ISSUE THREAD

**Issue by kwokkawai** [dusty-nv/jetson-inference#1486]
May I know if any docker version supports jetpack 5.0.2?

**Comment by dusty-nv** [comment]
Yes there are jetson-inference container for JP 5.0.2 on dockerhub.  You should just be able to do docker/run.sh and it will pull it and run it for you
________________________________
From: Paul Kwok ***@***.***>
Sent: Saturday, August 27, 2022 4:21:56 AM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] Support Jetpack 5.0.2? (Issue #1486)


May I know if any docker version supports jetpack 5.0.2?

**Comment by kwokkawai** [comment]
thanks, may i know if the docker used in this training have updated too?

https://catalog.ngc.nvidia.com/orgs/nvidia/teams/dli/containers/dli-nano-ai
DLI Getting Started with AI on Jetson Nano | NVIDIA NGC<https://catalog.ngc.nvidia.com/orgs/nvidia/teams/dli/containers/dli-nano-ai>
Course environment for the Deep Learning Institute (DLI) course, "Getting Started with AI on Jetson Nano".
catalog.ngc.nvidia.com



________________________________
