### ISSUE TITLE
Upload model from Nvidia TAO toolkit to jetson-inference detectnet ?

### ISSUE THREAD

**Issue by medphisiker** [dusty-nv/jetson-inference#1487]
Hello, 

I wanted to ask if it is possible to train a neural network detector using nVidia TAO (https://developer.nvidia.com/tao-toolkit). 
And use this neural network for detection with jetson-inference detectnet ?

**Comment by dusty-nv** [comment]
@medphisiker sorry for the delay - support for this was recently added for TAO detection models:
https://github.com/dusty-nv/jetson-inference/blob/master/docs/detectnet-tao.md
