### ISSUE TITLE
Git --recursive problems

### ISSUE THREAD

**Issue by Abner-01** [dusty-nv/jetson-inference#1488]
When I try to clone recursive the repository or when I use the option `git submodule update --init` I get:

``` remote error: upload-pack: not our ref 8e83c6f0ff5f0c7af5593561d38f07dd6e7bd254
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'python/training/detection', but it did not contain 8e83c6f0ff5f0c7af5593561d38f07dd6e7bd254. Direct fetching of that commit failed.
```
If I continue to build from source, I get the error `-- NumPy not found` . I've alredy installed numpy.

**Comment by One-star11** [comment]
I believe the changes made in 12hrs ago is pointing the submodule into a wrong link. I am trying to git in the older version.. hoping it to work..

**Comment by dusty-nv** [comment]
Sorry about that @Abner-01 @One-star11 - I'd forgotten to `git push` the `python/training/detection` submodule - my bad.

Please try pulling jetson-inference master again now and it should be working.
