### ISSUE TITLE
imagenet:  failed to initialize imageNet

### ISSUE THREAD

**Issue by lijoe123** [dusty-nv/jetson-inference#1498]
Hello, when i used the jetson xavier nx to run the command 
`./imagenet-console ./images/bird_0.jpg output.jpg`
it occur this problem:
![image](https://user-images.githubusercontent.com/86214036/190145237-f66f4d30-76d1-440c-8a5b-2699af22d70a.png)
![image](https://user-images.githubusercontent.com/86214036/190145360-2ff7b5c7-2dc4-4d72-990b-e229ae06a1d3.png)
**And this is my environment**:
![image](https://user-images.githubusercontent.com/86214036/190145568-ff2a6e9b-1969-47a5-b825-9b2110632bd0.png)
Thank you!!!!

**Comment by dusty-nv** [comment]
Hi @lijoe123, which specific Jetson Xavier NX and version of JetPack-L4T are you running?

Due to the `unknown embedded device detected` error message, I think you may need to upgrade your JetPack installation.

**Comment by lijoe123** [comment]
> Hi @lijoe123, which specific Jetson Xavier NX and version of JetPack-L4T are you running?
> 
> Due to the `unknown embedded device detected` error message, I think you may need to upgrade your JetPack installation.

Thank you for your answer. This is my jetpack version
![image](https://user-images.githubusercontent.com/86214036/190294354-ed775caf-eb57-4b9e-848b-6aae71bca5ed.png)

**Comment by dusty-nv** [comment]
Which variant of Jetson Xavier NX are you running?   If it's Jetson Xavier NX 16GB module, I think you need to upgrade JetPack version.
