### ISSUE TITLE
Jetson TK1 inference

### ISSUE THREAD

**Issue by charterscruz** [dusty-nv/jetson-inference#15]
Hi,

Not really sure if this is the best place to ask this but is there any change to use this repository on a TK1?
More generally, is there any change to deploy detectnet on a TK1?

Thanks in advance

**Comment by dusty-nv** [comment]
Hi there, the 64-bit TensorRT is not available for 32-bit TK1 unfortunately.   This repo would need to be modified to support Caffe backend also, which in theory is possible although a large TODO.
