### ISSUE TITLE
Bug : eval_ssd.py

### ISSUE THREAD

**Issue by leaf918** [dusty-nv/jetson-inference#1500]
in line 151,in file eval_ssd.py,the var device assigned to CPU,the inference will NOT work,
to fix it ,it should be stronger in line 37 in file ssd.py.
tks.
```
  timer.start("Load Model")
    net.load(args.trained_model)
    net = net.to(DEVICE)
    print(f'It took {timer.end("Load Model")} seconds to load the model.')
```

**Comment by Iongng198** [comment]
Hi,
I am also having problem with eval_ssd.py with the same lines with your. Do you know how to fix this problem?
Thank you

**Comment by leaf918** [comment]
plz ref my code block.
`class SSD(nn.Module):
    def __init__(self, num_classes: int, base_net: nn.ModuleList, source_layer_indexes: List[int],
                 extras: nn.ModuleList, classification_headers: nn.ModuleList,
                 regression_headers: nn.ModuleList, is_test=False, config=None, device=None):
        """Compose a SSD model using the given components.
        """
        super(SSD, self).__init__()

        self.num_classes = num_classes
        self.base_net = base_net
        self.source_layer_indexes = source_layer_indexes
        self.extras = extras
        self.classification_headers = classification_headers
        self.regression_headers = regression_headers
        self.is_test = is_test
        self.config = config

        # register layers in source_layer_indexes by adding them to a module list
        self.source_layer_add_ons = nn.ModuleList([t[1] for t in source_layer_indexes
                                                   if isinstance(t, tuple) and not isinstance(t, GraphPath)])
        if device:
            self.device = device
        else:
            self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        if is_test:
            self.config = config
            self.priors = config.priors.to(self.device)`
