### ISSUE TITLE
Failed to get the raw depth data from depth_field in DepthNet

### ISSUE THREAD

**Issue by howgie** [dusty-nv/jetson-inference#1502]
Failed to get the raw depth data from depth_field in DepthNet
It seems like a cudaToNumpy problem.
fllowing the code
```
net = jetson_inference.depthNet()
depth_field = net.GetDepthField()
depth_numpy = jetson_utils.cudaToNumpy(depth_field)
```
it turns out like
```
Traceback (most recent call last):
  File "inference.py", line 7, in <module>
    depth_numpy = jetson_utils.cudaToNumpy(depth_field)
Exception: jetson.utils -- cudaToNumpy() needs to use CUDA mapped memory as input (allocate with mapped=1)
```
In the depth_field class, mapped is False. How can I get the depth_numpy value?
Or is any way else to get the depth value.

**Comment by dusty-nv** [comment]
Hi @howgie, can you see if applying this fix works?   https://github.com/dusty-nv/jetson-inference/commit/980b1a454a057074683cdf358bf79a542903884f
