### ISSUE TITLE
Failed to build video-viewer

### ISSUE THREAD

**Issue by leeyunhome** [dusty-nv/jetson-inference#1504]
Hello @dusty-nv 

nvidia@nvidia-desktop:~/jetson-inference/utils/video/video-viewer$ make
Scanning dependencies of target video-viewer
[ 50%] Building CXX object CMakeFiles/video-viewer.dir/video-viewer.o
/home/nvidia/jetson-inference/utils/video/video-viewer/video-viewer.cpp:23:10: fatal error: videoSource.h: No such file or directory
 #include "videoSource.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/video-viewer.dir/build.make:62: recipe for target 'CMakeFiles/video-viewer.dir/video-viewer.o' failed
make[2]: *** [CMakeFiles/video-viewer.dir/video-viewer.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/video-viewer.dir/all' failed
make[1]: *** [CMakeFiles/video-viewer.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

How can I build this video-viewer?
Thank you.

**Comment by ligaz** [comment]
You can follow the instruction for building the whole project including the `video-viewer` [here](https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-repo-2.md#quick-reference). Did that work for you?
