### ISSUE TITLE
parse model two times

### ISSUE THREAD

**Issue by haozhaopop** [dusty-nv/jetson-inference#151]
When I try to run Resnet101 with Convolutional layer after RPROIFUSED layer, tensorrt stops because of different batch size, so I tried to read model two times, I run caffetoGIEModel function two times in main function in the sampleFasterrcnn, first one with pluginFactory for layer until RPROIFUSED layer, second one without pluginFactory for layer after RPROIFUSED layer until final fc layer, then the code stops at the moment when second function parsing the model, because of segmentation fault, so I am wondering if the that caffetoGIEModel function cannot apply two times in code.

**Comment by xonobo** [comment]
Do you use this anywhere in the code?

nvcaffeparser1::shutdownProtobufLibrary();
