### ISSUE TITLE
importing jetson.inference is depreciated.  Please 'import jetson.inference' instead

### ISSUE THREAD

**Issue by Michael-EVOL** [dusty-nv/jetson-inference#1511]
Following Hello AI world on jetson nano 2GB,

Trying to write the my-recognition.py example in python, and am told that: 
"importing jetson.inference is depreciated.  Please 'import jetson_inference' instead"
and
"importing jetson.utils is depreciated.  Please 'import jetson_utils' instead"

When I update the imports, I also update the call to load an image
from => jetson.utils.loadimage() 
to     => jetson_utils.loadimage() 

but receive the error message:
"jetson_utils has no attribute 'loadimage'"

Where might I find the updated attributes to call for the new import?

**Comment by dusty-nv** [comment]
Hi @Michael-EVOL, it's `jetson_utils.loadImage()`  (note the capitalization)

**Comment by Michael-EVOL** [comment]
Aha, that is what I thought it was going to be a capitalized version of the one I was using.  

Also I found that the function imagenet() became imageNet() in the new package.

Thank you @dusty-nv very much for your help with this issues.

**Comment by dusty-nv** [comment]
No problem - the function names haven't changed (i.e. it was always `imageNet`)
