### ISSUE TITLE
how can get yuv data？

### ISSUE THREAD

**Issue by mahxn0** [dusty-nv/jetson-inference#152]
hello,I want use gst-camera decode multi rtsp,there i meet a question that if use ConvertRGBA function,I found it occupied a much GPU，if I dont use this function, GPU occupied 0.so I want save Image from yuv data ,how can get the data ptr，thank you
`int main( int argc, char** argv )
{
	printf("gst-camera\n  args (%i):  ", argc);

	for( int i=0; i < argc; i++ )
		printf("%i [%s]  ", i, argv[i]);
		
	printf("\n");
	
		
	if( signal(SIGINT, sig_handler) == SIG_ERR )
		printf("\ncan't catch SIGINT\n");

	/*
	 * create the camera device
	 */
	gstCamera* camera = gstCamera::Create();
	
	if( !camera )
	{
		printf("\ngst-camera:  failed to initialize video device\n");
		return 0;
	}
	
	printf("\ngst-camera:  successfully initialized video device\n");
	printf("    width:  %u\n", camera->GetWidth());
	printf("   height:  %u\n", camera->GetHeight());
	printf("    depth:  %u (bpp)\n", camera->GetPixelDepth());
        if( !camera->Open() )
	{
		printf("\ngst-camera:  failed to open camera for streaming\n");
		return 0;
	}
	
	printf("\ngst-camera:  camera open for streaming\n");
	while(!signal_recieved)
	{
		void *imgCPU=NULL;
		void *imgCUDA=NULL;
		// get the latest frame
		if(!camera->Capture(&imgCPU,&imgCUDA,1000))
		{
			printf("\ngst-camera: failed to capture frame\n");
		}
		else
			printf("gst-camera:  recieved new frame  CPU=0x%p  GPU=0x%p\n",imgCPU,imgCUDA);
		
	 	uint32_t imgwidth=camera->GetWidth();
		uint32_t imgheight=camera->GetHeight();
		void *imgRGBA=NULL;
		camera->ConvertRGBA(imgCPU,&imgRGBA,true);
		saveImageRGBA(argv[1],(float4*)imgRGBA,imgwidth,imgheight,255.0f);//最后一个参数调节像素尺度0~1,0~255
		//CUDA(cudaNormalizeRGBA())
}	
	//shutdown the camera device
	if( camera != NULL )
	{
		delete camera;
		camera = NULL;
	}
`
//------------------------------------------------------------------------
Decode 4 channels rtsp,the gpu  used:
![default](https://user-images.githubusercontent.com/19154155/31872964-b08a9974-b7f2-11e7-9d10-003ffc00d38d.png)

**Comment by kanakiyab** [comment]
Hi @mahxn0 ,

I am struggling on the same problem. Have you found any solution to this? Please let me know.

Thanks,
Bhargav
