### ISSUE TITLE
cudaAllocMapped() failed to allocate memory

### ISSUE THREAD

**Issue by pchly** [dusty-nv/jetson-inference#1525]
I get image data from realsense, and then use the DetectNet of jetson-information for object recognition. I refer to the code in python/examples/cuda-from-cv.py, but the following errors often occur:
`rgb_image = cudaAllocMapped(img_width,img_height,format="rgb8")
Exception: jetson.utils -- cudaAllocMapped() failed to allocate memory`
Some of my codes are as follows：
`       image, depth_img_nomap, depth_img_colormap = realSenseSensor.getFrames()#get image from realsense
	img_width = realSenseSensor.color_width
	img_height = realSenseSensor.color_height
	rgb_image = cudaAllocMapped(img_width,img_height,format="rgb8")
	rgb_image = cudaFromNumpy(image,isBGR=False)
	detections = net.Detect(rgb_image,img_width,img_height)`
Please help me to find out where the problem is

**Comment by dusty-nv** [comment]
@pchly sorry for the delay - if this is still an issue, can you re-open it and let me know what the image dimensions you are trying to allocate are, and if there are any other related error messages in the console log?
