### ISSUE TITLE
Building the project from source

### ISSUE THREAD

**Issue by mohitg0292** [dusty-nv/jetson-inference#1528]
**Jetson Nano developer kit Specs:**
Jetson Nano 4GB kit with 16GB Memory card.
L4T version 32.6.1 [JetPack 4.6]
Ubuntu 18.04.5

**Errors:**
1. I'm getting errors in the command "cmake ../"
![CmakeError 1](https://user-images.githubusercontent.com/101650936/205452390-125183b2-a2c7-42b0-9573-9a8d077c7856.PNG)
![CmakeError 2](https://user-images.githubusercontent.com/101650936/205452391-8ae969ef-9887-4559-ade8-f65493834de2.PNG)
![CmakeError 3](https://user-images.githubusercontent.com/101650936/205452389-da43a7ad-8e04-42a5-8171-1f97edca8162.PNG)

2. In the step installpytorch.sh I'm getting Pytorch for Python 3.6 as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/101650936/205452444-0a753b29-6762-4740-8999-57af37b1b98c.png)
I tried to install pytorch for python 3.6 but it didn't complete because of memory issues.

3. Make commands also showed errors.
![image (1)](https://user-images.githubusercontent.com/101650936/205452504-81ed2adc-3e12-442e-840d-5a85a3df45a4.png)

Please suggest some solution.
Thank you.

**Comment by dusty-nv** [comment]
Hi Mohit, can you try running cmake again?  It should skip the dialogs this time

**Comment by mohitg0292** [comment]
Hi Dustin,
I'm getting the same errors after running the cmake command.

**Comment by dusty-nv** [comment]
Did you run cmake ../ from the build directory and did it complete successfully?
________________________________

**Comment by mohitg0292** [comment]
Yes I ran the the command "cmake ../" from build directory. But it completed with errors which I put screenshot above.

**Comment by dusty-nv** [comment]
OK, I see.  It appears that you do not have CUDA toolkit installed on your Jetson.  Did you use the SD card image or SDK Manager to flash it?

I believe you should able to do 'sudo apt-get install cuda-toolkit-*'
________________________________

**Comment by mohitg0292** [comment]
I have just run the command and it's still running. I'm not sure how the image is loaded into SD card. Could you please share if there's a way to check if the Jetson Developer Kit image is loaded into the memory card?
Also is 16GB SD card enough?

**Comment by dusty-nv** [comment]
16GB is small yes, so I would get a bigger one eventually
________________________________

**Comment by mohitg0292** [comment]
The command you mentioned got incompleted because of space issues.
![image](https://user-images.githubusercontent.com/101650936/205469868-d6822147-9f7e-490e-9a4e-d2c420643a02.png)

I would also increase the memory size as you suggested.

**Comment by mohitg0292** [comment]
Hi!

So I just realized that the Ubuntu OS is installed in internal memory which is around 15GB. I'm not able to use SD card, it's not showing even with "df -Th" command. Not sure why. 
Do you think this project can only be run in SD card? Because the internal memory got full by trying different methods to fix the errors and now even after removing the project, the memory is still full.

Mohit

**Comment by dusty-nv** [comment]
> I'm not able to use SD card, it's not showing even with "df -Th" command. Not sure why.

Hi @mohitg0292, I would try using the ubuntu GUI disk tool and make sure your SD card is formatted as ext3/ext4 and is setup to auto-mount.



> Do you think this project can only be run in SD card? Because the internal memory got full by trying different methods to fix the errors and now even after removing the project, the memory is still full.

I've run it before in 16GB + JetPack, but yes JetPack already takes up a lot of space.

**Comment by ligaz** [comment]
@mohitg0292 You can [this guide](https://nvidia-ai-iot.github.io/jetson-min-disk/intro.html) from Nvidia on how to minimizing Jetson disk usage. Hope this helps.
