### ISSUE TITLE
Using Kinect2 with the JETSON TX2

### ISSUE THREAD

**Issue by robotlinker** [dusty-nv/jetson-inference#153]
Hi,

Instead of using the onboard camera, i am working on using the Kinect2 to stream the video.
I used i**ai_kinect2** [driver](https://github.com/code-iai/iai_kinect2) to get Kinect image as ROS messages, then use [**ros-virtual-cam** ](https://github.com/lucasw/ros-virtual-cam)package to bind the ROS message to /dev/video1.
However, I get the problem of image format YV12 is not supported, when running the imagenet demo.
Any experiences using Kinect2 with Jetson TX2?
Thank you!

**Comment by dusty-nv** [comment]
Hi, here is a JetsonHacks article about using Kinect2 with Jetson TX1 (TX2 should be similar):

http://www.jetsonhacks.com/2016/07/11/ms-kinect-v2-nvidia-jetson-tx1/

Are you able to use libfreenect2 to interface with the Kinect2?
