### ISSUE TITLE
run detectnet.py use own trained model in jetson nano board issue:

### ISSUE THREAD

**Issue by fa00fa** [dusty-nv/jetson-inference#1537]
![image](https://user-images.githubusercontent.com/70007690/209641448-243c040d-2948-4480-9c9e-62cf7b75e91a.png)
the argument "--network"="ssd-mobilenet.onnx"
i found The target of detection is still the original pre-model target and I am the target that  I want to detect the water cup

**Comment by dusty-nv** [comment]
@fa00fa sorry for the delay - try using `--model=ssd-mobilenet.onnx`, or there is now a dedicated detectNet API for loading custom models without using the command-line:

https://github.com/dusty-nv/jetson-inference/blob/022e240a96a20bd17a06dd7060fccf98f1667227/python/examples/detectnet.py#L57
