### ISSUE TITLE
Is there a way to delete this module completely?

### ISSUE THREAD

**Issue by venugopalreddt** [dusty-nv/jetson-inference#1539]
Hey. I am moving my object recognition to a new AGX Xavier and currently don't need it in my Jetson nano. Is there a way to entirely delete this from my nano? 

P.S: Sorry if this is a stupid doubt, I am very new to linux and python.

**Comment by dusty-nv** [comment]
Hi @venugopalreddt, yes you can delete the following paths:

* `/usr/local/lib/libjetson-inference.so`
* `/usr/local/lib/libjetson-utils.so`
* `/usr/lib/python3.6/dist-packages/Jetson`
* `/usr/lib/python3.6/dist-packages/jetson*`
* `/usr/local/share/jetson-*`
* the related files under `/usr/local/bin` 
* the folder you clone the jetson-inference repo to
