### ISSUE TITLE
Editing detected.py code to show a line on video feed

### ISSUE THREAD

**Issue by Kant01354** [dusty-nv/jetson-inference#1541]
Hi sir,
I want to show a line on the video camera feed in the detectnet.pt code. And once an object is detected above that line, only then I want to show it as detected.
Can you please suggest how to perform these (or somewhat similar ) changes in the detectnet code. 
Or if you could guide me with some similar changes to detectnet code and how to perform and compile the code and run it.  For instance showing a text overlay over the video feed while it's doing object detection, then also I'll learn myself and try.
Thanks

**Comment by dusty-nv** [comment]
Hi @Kant01354, for drawing shapes/lines/ect on the image, see here:   https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-image.md#drawing-shapes

Also, see imagenet.py for an example of drawing text.
