### ISSUE TITLE
How to check the centroid of detected object.

### ISSUE THREAD

**Issue by Kant01354** [dusty-nv/jetson-inference#1542]
Dear sir,

How to print the centroid of the detected objects rectangular bounding box ? Is there any function already for the same ?

**Comment by dusty-nv** [comment]
Hi @Kant01354, you can use the detectNet.Detection.Center() function from C++ or Python to get the centroid:

https://github.com/dusty-nv/jetson-inference/blob/9ee9a950a80fbc7597d7e78a7ba0a282e85fae78/c/detectNet.h#L147

However I don't have it implemented to draw the centroid.  You could modify the detectNet::Overlay() function in C++ if you wanted to add that.

**Comment by Kant01354** [comment]
Sir I tried this in detectnet.py code :-

```

	# print the detections
	print("detected {:d} objects in image".format(len(detections)))

	for detection in detections:
		print(detection)
		print (detectNet.Detection.Center() )

	# render the image
	output.Render(img)
```

But it crashed with the error -
_print (detectNet.Detection.Center() )
TypeError 'getset_descriptor' object is not callable_

**Comment by dusty-nv** [comment]
Hi @Kant01354, do this instead:

``` python
for detection in detections:
     print(detection)
     print (detection.Center)
```
