### ISSUE TITLE
Does TensorRT apply only to high-performance GPUs

### ISSUE THREAD

**Issue by Essenlin** [dusty-nv/jetson-inference#155]
Does TensorRT apply only to high-performance GPUs?

**Comment by psyhtest** [comment]
TensorRT works perfectly well for TX1 e.g. see this [Jupyter notebook](https://github.com/dividiti/ck-caffe-nvidia-tx1/blob/master/script/caffe-tensorrt/ck-caffe-nvidia-tx1-with-tensorrt.20170429.ipynb).
