### ISSUE TITLE
Settings for training monocular depth estimation

### ISSUE THREAD

**Issue by jsshin98** [dusty-nv/jetson-inference#1554]
Hi Dusty,

Your project page gave me a lot of help on implementing several vision tasks on Jetson AGX Orin.
I have also checked the performance of monocular depth estimation.

I want to train my own custom model for monocular depth estimation, but I cannot find any settings for it.
Can you explain me the version of mobilenet and the training dataset you used to train the MobileNet for depth estimation?

Also, I will be really appreciated if you give me some tips on training monocular depth estimation to mimic the performance of provided pretrained model.

Thanks,
Jisu

**Comment by dusty-nv** [comment]
Hi @jsshin98, IIRC this was where I got the monodepth model from:   https://github.com/dwofk/fast-depth

I don't believe I was ever able to train one as good as they were able to...

**Comment by jsshin98** [comment]
Thanks! :)
