### ISSUE TITLE
Object Detection (SSD-Mobilenet)

### ISSUE THREAD

**Issue by TanJohn1604** [dusty-nv/jetson-inference#1561]
Dear dusty-nv, 
I am following https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-ssd.md
How can I visualize architecture of this model SSD-MobileNet? Because I want to demonstrate this model from layer to layer and understand what happen to the input image.

thank you so much.

**Comment by dusty-nv** [comment]
Hi @TanJohn1604, I'm not sure how you would do that, but my guess is it would best be done in PyTorch

**Comment by TanJohn1604** [comment]
Thank you for your answer.
So how can i find architecture of this model SSD-MobileNet

**Comment by sezer-muhammed** [comment]
You can use netron to visualise onnx format of the model I guess
