### ISSUE TITLE
Are there any flownet example in Python?

### ISSUE THREAD

**Issue by jet-c-21** [dusty-nv/jetson-inference#1564]
Is it possible to implement optical flow inference in Python? Some thing like this: https://github.com/NVIDIA/flownet2-pytorch

Cuz I found a file named [flowNet.cpp](https://github.com/dusty-nv/jetson-inference/blob/master/c/experimental/flowNet.cpp) in the repo.

**Comment by dusty-nv** [comment]
@jet-c-21 this never made it out of the experimental stage for me due to performance reasons, and I don't believe that I ever implemented the Python bindings for it.  It might be easiest for you to just try using torch2trt with the flownet2-pytorch scripts from Python.
