### ISSUE TITLE
Not able to load .onnx files in detectnet.py

### ISSUE THREAD

**Issue by SaTz1483** [dusty-nv/jetson-inference#1566]
Hey @dusty-nv how do I use a custom model i trained on detection algorithm.
When i give my model .onnx path as input to the network  argument it throws me this error.

![IMG_20230220_194635.jpg](https://user-images.githubusercontent.com/93349594/220131302-c8c90fcc-e730-4527-882e-e9588628513f.jpg)

The output,

![IMG_20230220_194241.jpg](https://user-images.githubusercontent.com/93349594/220131141-1a4c99f2-2651-4d69-ac89-165c8a09a023.jpg)

Also it's import jetson_utils in the GitHub repo and jetson.utils in cloned repo there is some discrepancy, cuz it says in the python file in the GitHub reop that if i uncomment that line i can load .onnx files into the Python file as well, but i get an error saying module detectNet not found

**Comment by dusty-nv** [comment]
Hi @SaTz1483, it looks like you need to set the other command-line parameters for loading custom model, like the following:

``` bash
detectnet --model=models/fruit/ssd-mobilenet.onnx --labels=models/fruit/labels.txt --input-blob=input_0 --output-cvg=scores --output-bbox=boxes
```

Also it says it can't find the model file that you specified, so double-check it exists.

**Comment by SaTz1483** [comment]
@dusty-nv I'm actually trying to train a custom dataset that has a resolution of 4208x3120 and its taking ridiculously long. Is there any way of optimizing this? 
Does resolution play a role in training time?

**Comment by SaTz1483** [comment]
Hey @dusty-nv
Could you help me out with this?


 I'm actually trying to train a custom dataset that has a resolution of 4208x3120 and its taking ridiculously long. Is there any way of optimizing this? 
Does resolution play a role in training time?
