### ISSUE TITLE
PreProcess input means and how to modify them

### ISSUE THREAD

**Issue by sezer-muhammed** [dusty-nv/jetson-inference#1567]
Hi,

In preprocess I need to make inputs between 0 to 1 just by dividing it to 255 in order to use yolo model.

```
	else if( IsModelType(MODEL_ONNX) )
	{
		// SSD (PyTorch / ONNX)
		if( CUDA_FAILED(cudaTensorNormMeanRGB(input, format, width, height,
									   mInputs[0].CUDA, GetInputWidth(), GetInputHeight(), 
									   make_float2(0.0f, 1.0f), 
									   make_float3(0.5f, 0.5f, 0.5f),
									   make_float3(0.5f, 0.5f, 0.5f), 
									   GetStream())) )
		{
			LogError(LOG_TRT "detectNet::Detect() -- cudaTensorNormMeanRGB() failed\n");
			return false;
		}
	}
```

I guess this is the function that I should modify.

What does these inputs mean?
I Guess make_float2 decides the min and max values.
But I did not understand the rest?

How can I just map my image data to 0-1 without and normalizing operations?

**Comment by dusty-nv** [comment]
Hi @sezer-muhammed, the pre-processing functions you can call are found here:  https://github.com/dusty-nv/jetson-inference/blob/master/c/tensorConvert.h

That first float2 argument is the range of the values - it's already configured to map the image data to [0,1]

The float3 is the mean pixel value which is subtracted from each pixel (set this to `make_float3(0,0,0)` to disable it).  The second float3 is the std deviation.   If you want to disable these you can just use the other `cudaTensorNormRGB()` function instead which doesn't have mean/stddev

**Comment by sezer-muhammed** [comment]
Thanks!
