### ISSUE TITLE
/lib64/ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by gahangandi11** [dusty-nv/jetson-inference#1568]
when I execute the cmake ../ command , I have the following error

/lib64/ld-linux-x86-64.so.2: No such file or directory
 please help me to resolve this

**Comment by dusty-nv** [comment]
Are you attempting to build this on x86?   I've only done that in docker container

**Comment by gahangandi11** [comment]
yes and I am not using docker. I am following these steps here
https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-repo-2.md

**Comment by dusty-nv** [comment]
Technically this repo only supports Jetson/aarch64.   I have beta support for x86 in docker.  There are two many different distro's for x86 for me to feasibly support bare-metal on x86.
