### ISSUE TITLE
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/local/cuda-11.4/bin/nvdisasm: no space left on device. See 'docker run --help'.

### ISSUE THREAD

**Issue by gahangandi11** [dusty-nv/jetson-inference#1569]
when I run the docker/run.sh command , I am getting the following error. 

docker: failed to register layer: Error processing tar file(exit status 1): write /usr/local/cuda-11.4/bin/nvdisasm: no space left on device.
See 'docker run --help'.

But when I check the space using df -h, I see that I have space 

Filesystem             Size  Used Avail Use% Mounted on
/dev/mmcblk0p1    28G   21G  5.4G  80% /
none                      7.3G     0  7.3G   0% /dev
tmpfs                     7.3G   18M  7.3G   1% /dev/shm
tmpfs                     1.5G   70M  1.4G   5% /run
tmpfs                      5.0M  4.0K  5.0M   1% /run/lock
tmpfs                      7.3G     0  7.3G   0% /sys/fs/cgroup
/dev/mmcblk0p40   63M   75K   63M   1% /opt/nvidia/esp
tmpfs                     1.5G   24K  1.5G   1% /run/user/124
tmpfs                     1.5G   88K  1.5G   1% /run/user/1000

How do I solve this error

**Comment by dusty-nv** [comment]
It says you have 5.4GB free space left, and that's not big enough for the jetson-inference container.  I would recommend adding external storage if you can and changing the location of your docker data root.
