### ISSUE TITLE
What's the correct way to uninstall jetson-inference

### ISSUE THREAD

**Issue by jet-c-21** [dusty-nv/jetson-inference#1574]
I follow this way to build jetson-inference:
```
sudo apt-get update
sudo apt-get install git cmake libpython3-dev python3-numpy
git clone --recursive https://github.com/dusty-nv/jetson-inference
cd jetson-inference
mkdir build
cd build
cmake ../
make -j$(nproc)
sudo make install
sudo ldconfig
```
And how can I completely uninstall it?

**Comment by dusty-nv** [comment]
@jet-c-21 you have to `sudo rm` the relevant files from:

* `/usr/local/bin`
* `/usr/local/include`
* `/usr/lib/python3.8/dist-packages`  (or `python3.6` if you're on JetPack 4)

**Comment by Bear528** [comment]
> @jet-c-21 you have to `sudo rm` the relevant files from:
> 
> * `/usr/local/bin`
> * `/usr/local/include`
> * `/usr/lib/python3.8/dist-packages`  (or `python3.6` if you're on JetPack 4)

relevant files is? or delect all files?
