### ISSUE TITLE
How to make inference for custom trained model weights from YoloV5 using CSI camera?

### ISSUE THREAD

**Issue by Rusali28** [dusty-nv/jetson-inference#1582]
Hello @dusty-nv ,
I have used yolov5 and custom trained it on Roboflow dataset, so now I have my separate custom weights file. Can you please help me how I can make my own jetson-inference file for it using CSI camera?

**Comment by dusty-nv** [comment]
Hi @Rusali28, I don't have support built-in for YOLO in the jetson-inference library and detectNet.   There are too many different YOLO for me to support.   Here is a github with YOLOv5 and TensorRT though:   https://github.com/BlueMirrors/Yolov5-TensorRT
