### ISSUE TITLE
Failed to save model checksum error

### ISSUE THREAD

**Issue by polatztrk** [dusty-nv/jetson-inference#1584]
While i try this line of code:
`polat@polat-desktop:~/jetson-inference/build/aarch64/bin$ ./detectnet-console.py images/peds_0.jpg output_0.jpg`

it works but gave me this error:
`[TRT]    failed to save model checksum to networks/SSD-Mobilenet-v2/ssd_mobilenet_v2_coco.uff.sha256sum
`
and because of that error every time i use `detectnet-console.py` it take at least 5 minute long.
What should i do?

**Comment by polatztrk** [comment]
I tried but still gave me the same error.

**Comment by polatztrk** [comment]
Hi @dusty-nv, I tried but still gave me the same error.

**Comment by dusty-nv** [comment]
Are you able to do an `rm -rf ~/jetson-inference/data/networks/SSD-Mobilenet-v2` ?

What does `ls -ll ~/jetson-inference/data/` and `ls -ll ~/jetson-inference/data/networks` show?

**Comment by polatztrk** [comment]
I run this code :`rm -rf ~/jetson-inference/data/networks/SSD-Mobilenet-v2`
and then i run `detectnet-console.py` but still the same error.
And this is the output after i run `ls -ll ~/jetson-inference/data/` and `ls -ll ~/jetson-inference/data/networks` :
![Screenshot from 2023-03-24 18-26-39](https://user-images.githubusercontent.com/66801019/227569808-7909b74e-04d6-4c60-80e6-638120737fab.png)

**Comment by dusty-nv** [comment]
OK, your folder permissions seem to be fine.   Can you post more of the terminal log about the errors than just ` failed to save model checksum to networks/SSD-Mobilenet-v2/ssd_mobilenet_v2_coco.uff.sha256sum` ?   There should be more diagnostic info above it

Also, what does ` sha256sum --version` show for you?   Does the jetson-inference docker container work for you?

**Comment by polatztrk** [comment]
I install the jetson-inference from the source, should i install it from the docker container ? 
This is the screenshot above the error:
![Screenshot from 2023-03-24 19-28-28](https://user-images.githubusercontent.com/66801019/227585027-8541cbbf-4952-465e-a69d-ba8245c603ad.png)

And this is `sha256sum --version`:

![Screenshot from 2023-03-24 19-18-22](https://user-images.githubusercontent.com/66801019/227585513-a99d7e31-89b6-49fd-9931-b421e8e4cf8c.png)

**Comment by dusty-nv** [comment]
> should i install it from the docker container ?

I just wanted to see if you experienced the same error inside the docker container.   So try doing `cd ~/jetson-inference && docker/run.sh`, then re-run detectnet

Also, if you use detectnet instead of detectnet-console.py, does it make the error?  How about if you ran `sudo detectnet` ?

**Comment by polatztrk** [comment]
I tried all of them now but still gave me the same error.

**Comment by dusty-nv** [comment]
OK, I'm sorry, I don't know why this happens for you.  Try commenting out these lines of `jetson-inference/c/tensorNet.cpp` (lines 1655-1666)

https://github.com/dusty-nv/jetson-inference/blob/22ce041897a5c672ec23a4d80768e9cfef45fc5a/c/tensorNet.cpp#L1655

``` cpp
// validate that the checksum matches the original model
	char cmd[PATH_MAX * 2 + 256];
	snprintf(cmd, sizeof(cmd), "echo \"$(cat %s) %s\" | %s --check --status", checksum_path, model_path, CHECKSUM_TYPE);  // https://superuser.com/a/1468626
	
	LogVerbose(LOG_TRT "%s\n", cmd);
	
	const int result = system(cmd);
	
	if( result != 0 )
	{
		LogVerbose(LOG_TRT "model did not match checksum %s (return code %i)\n", checksum_path, result);
		return false;
	}
```

then re-run `make && sudo make install` from your build dir

**Comment by polatztrk** [comment]
I tried again but gave me the same error. 
In the beginning of the terminal log  i have these:
![Screenshot from 2023-03-25 10-34-18](https://user-images.githubusercontent.com/66801019/227704014-03cdbf6d-cea5-4022-8cc9-57fcd7f8b71a.png)
Also sometimes `System throttled due to Over-current` warning came up. Are one of these can be a problem?

**Comment by dusty-nv** [comment]
If you are still getting the checksum error when loading model, double-check that you commented it out in the code and re-ran 'sudo make install'

This should enable you to skip the engine generation after its done once
