### ISSUE TITLE
Jetson-inference on Jetson Orin NX

### ISSUE THREAD

**Issue by AleBasso80** [dusty-nv/jetson-inference#1586]
Hello,
in the readme file it is stated that the repo can be used on an AGX Orin. 

What about Orin NX? Is it supported at the moment? If not, is there a plan to do it in a near future?

Thanks!

**Comment by dusty-nv** [comment]
@AleBasso80 I haven't actually ran it on an Orin NX, but yes it should work fine.  If you run into any issues please let me know.

**Comment by AleBasso80** [comment]
@dusty-nv many thanks, I'll try as soon as I get one. 
I keep you informed.
Cheers
