### ISSUE TITLE
docs/detectnet-tao.md broken link

### ISSUE THREAD

**Issue by joeysantana3** [dusty-nv/jetson-inference#1589]
At the end of the [docs/detectnet-tao.md](https://github.com/dusty-nv/jetson-inference/blob/master/docs/detectnet-tao.md) page, there is a link:

<p>Next | <b><a href="detectnet-tracking.md">Object Tracking</a></b>

When following the link, you receive a 404:

`The 'dusty-nv/jetson-inference' repository doesn't contain the 'docs/detectnet-tracking.md' path in 'master'.`

**Comment by dusty-nv** [comment]
Hi @joeysantana3, sorry about that, it's fixed now.
