### ISSUE TITLE
Jetson Nano 2GB Unable to Visualize Output

### ISSUE THREAD

**Issue by btj2** [dusty-nv/jetson-inference#1590]
Hi there, We are currerntly running the object detection script and we can se the detections in the command prompt showing the confidence and inference latency but we cannot see the actual output image with the bounding boxes. We followed the rocket systems youtube video (Training SSD Mobilenet) which uses your tutorial repository. I am wondering if this is a hardware issue or some configuration that is not setup correctly.

Thanks!

**Comment by dusty-nv** [comment]
Hi @btj2, do you have a physical display attached to your Jetson?    If you run the video-viewer tool on your camera or video input, do you see the OpenGL window?
