### ISSUE TITLE
Could not find any implementation for node, linux laptop

### ISSUE THREAD

**Issue by bulldogc** [dusty-nv/jetson-inference#1591]
Hi I am trying to get this package working on a linux laptop running Quadro M1200 Mobile running Ubuntu 20.  I believe I have gotten through the CUDA and tensorRT installs correctly. I have downloaded, built, and installed  the jetson-interface package successfully but when I try to run the imagenet test commands I am getting errors from the classifier. Any help would be appreciated.

The error in question is 
`[TRT]    10: Could not find any implementation for node conv1/7x7_s2 + conv1/relu_7x7.
[TRT]    10: [optimizer.cpp::computeCosts::3873] Error Code 10: Internal Error (Could not find any implementation for node conv1/7x7_s2 + conv1/relu_7x7.)
[TRT]    device GPU, failed to build CUDA engine
[TRT]    device GPU, failed to load networks/bvlc_googlenet.caffemodel
[TRT]    failed to load networks/bvlc_googlenet.caffemodel
[TRT]    imageNet -- failed to initialize.
imagenet:  failed to initialize imageNet
`

I am attaching a dump of the entire execution log as well.
[error.txt](https://github.com/dusty-nv/jetson-inference/files/11089938/error.txt)

**Comment by dusty-nv** [comment]
Hi @bulldogc, I'm not sure that the latest TensorRT supports Maxwell-generation GPUs anymore, you might need to try an older version of TensorRT:    https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix

Or you could try installing the NVIDIA Container Runtime on your PC, and running `docker/run.sh` from jetson-inference dir.  It will run a docker container that I built for x86 that already has CUDA/cuDNN/TensorRT/PyTorch pre-installed.   I use it on an Ubuntu laptop with a GeForce 1070M card.
