### ISSUE TITLE
Camera-Capture for directory of Images.

### ISSUE THREAD

**Issue by IsaiahOdunze** [dusty-nv/jetson-inference#1594]
Hello. I think this will be a quick issue to solve. I have been using the camera capture tool with a live camera feed to train detection models, but I think it would be more convenient for me if I could take pictures somewhere else and then just load the directory of images. How would I do this? Does camera-capture only work for live video feeds? If so, is there a tool that works for static images where I can load in images and put the bounding boxes? Thank you.

**Comment by dusty-nv** [comment]
Hi @IsaiahOdunze, yes that camera-capture tool only works for live video feeds - for annotating existing images/video, I'd recommend using [CVAT](https://www.cvat.ai/) tool and exporting from it to Pascal VOC format.
