### ISSUE TITLE
Encountered an error when I was running sudo make install 

### ISSUE THREAD

**Issue by Troyechild** [dusty-nv/jetson-inference#1595]
cmake ../ 
make
sudo make install
This is the code I executed during deployment,Then I had an error at the end
####################################################
CMake Error at utils/python/bindings_python_2.7/cmake_install.cmake:89 (file):
  file INSTALL cannot find
  "/home/troyechild/jetson-inference/utils/python/bindings/../python/jetson".
Call Stack (most recent call first):
  utils/python/cmake_install.cmake:74 (include)
  utils/cmake_install.cmake:380 (include)
  cmake_install.cmake:128 (include)
####################################################
I ignored this question, but I had more problems later,When I was running detectnet.py, I encountered the following error.
ModuleNotFoundError:No module named 'jetson'
I hope to get your timely reply, because I am not very proficient in English，So I might be a little bit off
。

**Comment by dusty-nv** [comment]
Hi @Troyechild, is your disk formatted by NTFS by chance?    It should be ext3/ext4

**Comment by Troyechild** [comment]
> Hi @Troyechild, is your disk formatted by NTFS by chance? It should be ext3/ext4

This is the fourth time I've reburned the jetpack, and each time I formatted it before burning it, but it wasn't formatted in use

**Comment by Troyechild** [comment]
> Hi @Troyechild, is your disk formatted by NTFS by chance? It should be ext3/ext4
I just checked my disk format and it is indeed Ext4

**Comment by dusty-nv** [comment]
OK thanks - are you able to run detectnet.py from within the docker container ok?  https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-docker.md

**Comment by Troyechild** [comment]
> OK thanks - are you able to run detectnet.py from within the docker container ok? https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-docker.md
I have no other time to change the method, I will have a technology competition soon, I have solved the problem, I copied my missing files from other finished computers to finish this thing, thank you!
