### ISSUE TITLE
is it possible to directly load a torch tensor?

### ISSUE THREAD

**Issue by Yiming0416** [dusty-nv/jetson-inference#1597]
Hi,

Thanks for your great work! I am wondering if there is a way to directly load the input image from torch tensor? 

I saw in `jeston-utils` you can convert cuda image to pytorch tensor. Is there a way to convert pytorch tensor to cuda image?

**Comment by dusty-nv** [comment]
I haven't entirely been able to figure that out yet but have some ideas based on torch.tensor.data_ptr() , or torch's implementation of __cuda_array_interface__

For the time being, I would continue using the numpy/ndarray route.
________________________________
From: Yiming Zhou ***@***.***>
Sent: Friday, April 7, 2023 5:51:31 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] is it possible to directly load a torch tensor? (Issue #1597)


Hi,

Thanks for your great work! I am wondering if there is a way to directly load the input image from torch tensor?

I saw in jeston-utils you can convert cuda image to pytorch tensor. Is there a way to convert pytorch tensor to cuda image?

**Comment by dusty-nv** [comment]
@Yiming0416 support for this has been added in https://github.com/dusty-nv/jetson-utils/commit/c692b89f5716e01823ff177e286eba6986bc4c6a
