### ISSUE TITLE
Three example detection network models (ped-100,multiped-500,facenet-120) are not available

### ISSUE THREAD

**Issue by aiilab** [dusty-nv/jetson-inference#16]
Hi, I am running this demo code. In the DetectNet section, the pretrained detection network models(ped-100,multiped-500,facenet-120) are needed. However, the download links are invalid. Are there any other ways to download the pre-trained models?
    thanks!
eric

**Comment by dusty-nv** [comment]
Hi, I checked the links again and they are still up.   Are you able to access below?

[https://drive.google.com/uc?export=download&id=0BwYxpotGWRNOUmtGdGIyYjlEbTA](https://drive.google.com/uc?export=download&id=0BwYxpotGWRNOUmtGdGIyYjlEbTA)

**Comment by AAAyag** [comment]
it's ok now! thx
