### ISSUE TITLE
NvInfer.h: No such file or directory for L4T Nvidia containers

### ISSUE THREAD

**Issue by ervgan** [dusty-nv/jetson-inference#1603]
Hello,

I have tried compiling my TensorRT c++ code with the following containers: 
- nvcr.io/nvidia/l4t-base:r32.7.1
- nvcr.io/nvidia/l4t-tensorrt:r8.2.1-runtime
- nvcr.io/nvidia/l4t-cuda:10.2.460-runtime

Because I need TensorRT 8.2.1 and Cuda 10.2 which are compatible with L4T 32.7.1 included in Jetpack 4.6. However, everytime I try to compile my code, I get the error:
`NvInfer.h: No such file or directory `

I have tried using nvcr.io/nvidia/l4t-cuda:10.2.460-runtime as a base image, then installing the TensorRT libraries such as libnvinfer-dev, libnvinfer8, etc in my Dockerfile but the libraries are not found using this container. However, everything gets installed if I use the Cuda 11.4 base image but Cuda 11.4 is not compatible with my host image which is running on L4T 32.7 with Cuda 10.2

Why does it seem that TensorRT 8.2.1 is not compatible with Cuda 10.2 for arm64 architecture (impossible to download on the TensorRT download page) even though they are part of the same JetPack 4.6?

Is there any way to solve this issue?

Many Thanks!

**Comment by ervgan** [comment]
Hi Dustin, this is actually what I had at the beginning. I had TensorRT installed in my base image and then I ran l4t-base container with --runtime nvidia but I had the NvInfer.h missing. That's why I started trying to install it at the container level in a new DockerFile, Do you know what might be the issue? I am using Yocto as my base image, maybe the problem comes from there?

**Comment by dusty-nv** [comment]
> Do you know what might be the issue? I am using Yocto as my base image, maybe the problem comes from there?

@ervgan I'm not sure how using Yocto would impact it or if you still have the NVIDIA Container Runtime properly installed with the CSV files that mount the libraries.  Closing this issue since it's unrelated to jetson-inference - would recommend posting this to the Jetson forums if it's still an issue for you.
