### ISSUE TITLE
I cant install nvidia driver

### ISSUE THREAD

**Issue by TheMasterRoot** [dusty-nv/jetson-inference#161]
i was trying to instal nvidia-375 driver in my jetson tx1 but i could not find any driver in apt install

> $ sudo apt-get install nvidia-375
> $ sudo reboot

how can i install it ?? some one could help me:??

**Comment by dusty-nv** [comment]
Hi MasterRoot, nvidia-375 driver is meant for installing only on the host PC running DIGITS.  The ARM64 NVIDIA drivers are automatically installed to your Jetson by JetPack-L4T.


-------- Original message --------
