### ISSUE TITLE
confused about code

### ISSUE THREAD

**Issue by LiuZhenshun** [dusty-nv/jetson-inference#1617]
At your cpp source code "tensorNet.cpp" line 105 in function "isInt8Enabled", why it check "float16" instead of "int8" ?

**Comment by dusty-nv** [comment]
Thanks @LiuZhenshun, just fixed this in commit https://github.com/dusty-nv/jetson-inference/commit/501f96b5ee5924c20389f940c519323338c92afd

Fortunately, it appears that function was only used for logging purposes and didn't impact any runtime aspects.  Thanks for reporting it!
