### ISSUE TITLE
PoseNet overlay redrawing the frame

### ISSUE THREAD

**Issue by F1rrel** [dusty-nv/jetson-inference#1624]
When manually calling `poseNet::Overlay` function with specifying different input and output images, [the input image is copied into output frame after each call to a drawing function](https://github.com/dusty-nv/jetson-utils/blob/f19108b58be8d5ffe40ef471010ea8e7af4d9eeb/cuda/cudaDraw.cu#L218). 

In `detectNet::Overlay`, this is solved by [copying the input image to the output image](https://github.com/dusty-nv/jetson-inference/blob/master/c/detectNet.cpp#L984) before drawing into it. Same should be done for `poseNet::Overlay`.

jetson-inference branch: master

**Comment by dusty-nv** [comment]
Thanks @F1rrel, fixed this in commit https://github.com/dusty-nv/jetson-inference/commit/022e240a96a20bd17a06dd7060fccf98f1667227
