### ISSUE TITLE
failed to detect using docker

### ISSUE THREAD

**Issue by jonyzhang2023** [dusty-nv/jetson-inference#1635]
Hi , thanks for nano great examples.
But when I use docker/run.sh , I can use video-viewer then, but when I use detect /dev/video0 or imagenet , I cannot get output, the console always output like this  : 
![image](https://user-images.githubusercontent.com/50441823/236512717-2831f2d8-8017-47f1-8569-1082c02a260f.png)
did i do something wrong?

**Comment by dusty-nv** [comment]
Hi @jonyzhang2023 - let that run until the program actually starts - TensorRT is optimizing the model (it does that the first time you load each model).   Then the optimized TensorRT engine is saved to disk, and when you start detectnet the next time it will load in just a few seconds.

**Comment by jonyzhang2023** [comment]
cool thanks for your kindness help, forgive my stupid question lol.
