### ISSUE TITLE
CSI CAMERA ISSUE UNDER YOLOV7

### ISSUE THREAD

**Issue by akhandvaibhav17** [dusty-nv/jetson-inference#1638]
My team was trying to run YOLOv7 detect.py file on jetson nano. After giving the command "python3 detect.py source -0 weights yolov7.pt" the CSI Camera launches with warning "unable to get camera fps" and shows green screen. The is no issue with the camera as "nvgstcapture" command is working fine. Please help finding the solution to the issue. 
![WhatsApp Image 2023-05-09 at 13 26 36 (3)](https://github.com/dusty-nv/jetson-inference/assets/72245505/4184d4cc-32f4-4b1b-82ab-91e57da4b801)
![WhatsApp Image 2023-05-09 at 13 26 36](https://github.com/dusty-nv/jetson-inference/assets/72245505/7afbad3a-e970-4372-bad2-7e86ed627e3e)
![WhatsApp Image 2023-05-09 at 13 27 13](https://github.com/dusty-nv/jetson-inference/assets/72245505/010ede66-aebc-45fb-a0a1-5c8096087446)
![WhatsApp Image 2023-05-09 at 13 26 36 (2)](https://github.com/dusty-nv/jetson-inference/assets/72245505/b1d56fd2-29d0-4210-8034-d6813e26749a)

**Comment by dusty-nv** [comment]
@akhandvaibhav17 it looks like you are using OpenCV video capture and YOLOv7 detect.py code is not from this repo, I would suggest that you follow up on the Jetson Nano forums:  https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76

At a glance, you are having OpenCV capture video from `/dev/video0` (V4L2), whereas for MIPI CSI camera you should provide cv2.VideoCapture() with a GStreamer pipeline that uses nvarguscamerasrc element:   https://github.com/JetsonHacksNano/CSI-Camera/blob/master/simple_camera.py

**Comment by gaumh** [comment]
Hello, How did you solve this problem?
Because I have the same problem, I would like to trouble you to answer it again, Thank you!

**Comment by akhandvaibhav17** [comment]
Well, this problem wasn't solved though any of the solutions mentioned on internet. Instead we switched to a USB camera in place of a CSI camera and it worked properly. We couldn't find out the issue with CSI camera but it might be that the camera is defective or it can't handle the required fps.
