### ISSUE TITLE
cmake build error when building cpp object

### ISSUE THREAD

**Issue by chad-Ant** [dusty-nv/jetson-inference#1643]
The only change I made was within the CMakeList.txt file:
`106 find_package(VPI 2.0)`
to
`106 find_package(VPI 1.0)`
Below is my current system info:
![Screenshot from 2023-05-15 15-55-10](https://github.com/dusty-nv/jetson-inference/assets/53463752/0f16b0a4-324f-4b60-8636-033cf2ef2e84)

These are the log from command `cmake .//` and `make -j4`
[premake_log.txt](https://github.com/dusty-nv/jetson-inference/files/11475903/premake_log.txt)
[make_log.txt](https://github.com/dusty-nv/jetson-inference/files/11475904/make_log.txt)

I'm pretty sure it's not because of the `-j4` flag because I tried `-j1` before and the error is at the same place. So, any help here is appreciated!

**Comment by dusty-nv** [comment]
> The only change I made was within the CMakeList.txt file:
> `106 find_package(VPI 2.0)`
> to
> `106 find_package(VPI 1.0)`

@chad-Ant you should leave that as `find_package(VPI 2.0)` because the code uses features in VPI 2.0 that are not in VPI 1.0  (hence the build errors you are getting)

Or does it also not build for you with the original CMakeLists?

**Comment by chad-Ant** [comment]
Indeed, building without VPI was a success. So I'll use the original version of CMakeList then. Quick question, would it break the demo if I can't use VPI?

**Comment by dusty-nv** [comment]
> Quick question, would it break the demo if I can't use VPI?

@chad-Ant no, the only thing VPI is currently used for is an experimental KLT object tracker
