### ISSUE TITLE
RGBA as input of Faster-RCNN

### ISSUE THREAD

**Issue by jsmlay** [dusty-nv/jetson-inference#165]
Hi, all,
I'm combining Faster-RCNN (demo on TX2) and jetson-inference detectnet-camera to realize a real time detection application. The faster demo accept an ppm input as while as detectnet read in an (transfered) RGBA float* on GPU. I don't know if its ok if i treat the RGBA directly, with im_info(camera_h, camera_w, 1), as input of Faster net. The combination reports no error but detect nothing.
Thanks!

**Comment by linux-devil** [comment]
RGBA is different format as compared to PPM, you need to store pixels properly in the variable and then send it for detection .
