### ISSUE TITLE
libcudla.so.1 trouble while "make"

### ISSUE THREAD

**Issue by ElenaSkrebneva** [dusty-nv/jetson-inference#1653]
Hei,
I have another problem with "make"-command trying to build the project from source. I already tried to clone the repo twice and "make" still gets stuck with the same mistake: 
"/usr/bin/ld: warning: libcudla.so.1, needed by /usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so, not found (try using -rpath or -rpath-link)"
Any ideas about this?

**Comment by dusty-nv** [comment]
@ElenaSkrebneva which Jetson and version of JetPack-L4T are you running?   

Do you have CUDA Toolkit installed?   That library should be found under `/usr/local/cuda/lib64`

``` bash
ls -ll /usr/local/cuda/lib64/libcudla*
lrwxrwxrwx 1 root root     13 Sep 14  2022 /usr/local/cuda/lib64/libcudla.so -> libcudla.so.1
lrwxrwxrwx 1 root root     17 Sep 14  2022 /usr/local/cuda/lib64/libcudla.so.1 -> libcudla.so.1.0.0
-rw-r--r-- 1 root root 179792 Sep 14  2022 /usr/local/cuda/lib64/libcudla.so.1.0.0
```

If not, try doing `sudo apt-get update && sudo apt-get install cuda-toolkit-*`
