### ISSUE TITLE
What is libcudla?

### ISSUE THREAD

**Issue by ervgan** [dusty-nv/jetson-inference#1658]
I can see a new library libcudla in Jetpack 5.x, what exactly is it? I cannot find any documentation on it. Is it just a new name for libcuda?

Thanks!

**Comment by dusty-nv** [comment]
@ervgan it's a low-level driver for the Deep Learning Accelerator (DLA) engines that only Jetson Xavier + Orin have.   JetPack 5 only supports Xavier and Orin.  https://github.com/dusty-nv/jetson-inference/issues/1657#issuecomment-1568451248

**Comment by ervgan** [comment]
Thanks!
