### ISSUE TITLE
imageNet processing flow

### ISSUE THREAD

**Issue by SantiaSantia** [dusty-nv/jetson-inference#1664]
Hello Dusty

I failed looking for the field member `mStream` assignment of tensorNet object. Would you please help pointing out where is it?

Searched place so far:
- I found `enqueueV2(mBindings, mStream, NULL)` function inside the Classify function:
https://github.com/dusty-nv/jetson-inference/blob/08767dfd98056edf0317fbe30415f72ca654b13d/examples/imagenet/imagenet.cpp#LL155C95-L155C95
- I assume `mBinding` was holding the pointers of input and output buffer, `mStream `was holding the pointer to the entrance of engine. 
- in the tensorNet.cpp I found `void tensorNet::SetStream( cudaStream_t stream )`, where `mStream = stream`. 
- in the tensorNet.cpp I found `LoadEngine(engineStream, engineSize, input_blobs, output_blobs, NULL, device, stream)`. I guess parameter `engineStream `is the pointer to the CudaEngine inferred from the model, it should be passed to mStream after serialization somewhere. Does the assumption correct?

**Comment by dusty-nv** [comment]
> * in the tensorNet.cpp I found `void tensorNet::SetStream( cudaStream_t stream )`, where `mStream = stream`

Hi @SantiaSantia, yes that is the one.   There is also `tensorNet::CreateStream()` which will create a new CUDA stream and call `tensorNet::SetStream()` on it.   These are only used if you want to process the model on an alternate CUDA stream.   By default the models are processed on the NULL stream (i.e. the CUDA stream that all GPU kernels get enqueued to by default)

**Comment by SantiaSantia** [comment]
@dusty-nv Hi Dusty
Is it correct to understand the general flow like this:

- In an imageNet instance, when the Classify method was called, it uses `execute` function like `nvinfer1::IExecutionContext::executeV2(void *const * 	bindings)` to do the inference.
- We need to feed `execute` function with pointers to input and output buffer which was held by the field parameter `mBindings`.
- The pointer to the serialized engine is stored inside mContext, which would be used inside `execute`.
- Then the `execute` would take image data following the input pointer; pass the data to the entrance of serialized engine; pass the result to where the output pointer indicates when the inference was finished.

My major confusions now is that:

1. Is it true that the entrance of serialized engine was hold by `mContext`. 
2. Anywhere I could find the documentations for filed parameters like `mContext`, `mBindings` etc.
3. Is it possible to read code inside `execute`.

Thank you for your time.

**Comment by dusty-nv** [comment]
@SantiaSantia that is roughly correct, except that the TensorRT IExecutionContext instance is created from the deserialized ICudaEngine which internally stores the representation/weights of the network topology.

I would recommend consulting the TensorRT documentation for lower-level information about the different objects and model builder/execution flow:

* https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html
* https://docs.nvidia.com/deeplearning/tensorrt/api/index.html#api

**Comment by SantiaSantia** [comment]
@dusty-nv I would check the documents and post my understanding later.
Grateful here. 👍
