### ISSUE TITLE
Stream from vlan interface possible?

### ISSUE THREAD

**Issue by seb2189** [dusty-nv/jetson-inference#1682]
Is there a way to get a camera RTP stream via vlan? Analogue to this gst command I would like to use the video-viewer or any other net.

`gst-launch-1.0 -v udpsrc multicast-iface=veth10 uri=udp://239.192.10.100:5100 auto-multicast=true caps="application/x-rtp,encoding-name=H264,payload=96" ! rtpjitterbuffer ! rtph264depay ! h264parse ! video/x-h264,stream-format=byte-stream,alignment=au ! avdec_h264 ! clutterautovideosink sync=false async=false`

Using `video-viewer.py --input-codec=h264 rtp://239.192.10.100:5100 rtsp://@:1234/my_output --headless` results in timeouts like `[gstreamer] gstDecoder::Capture() -- a timeout occurred waiting for the next image buffer`

**Comment by dusty-nv** [comment]
@seb2189 you can modify the gstreamer pipeline that jetson-utils constructs for RTP input here:

https://github.com/dusty-nv/jetson-utils/blob/f0bff5c502f9ac6b10aa2912f1324797df94bc2d/codec/gstDecoder.cpp#LL585C1-L585C1

you can try adding your multicast options there.   Then re-run `make && sudo make install`
