### ISSUE TITLE
Python Package Cannot Install in docker container

### ISSUE THREAD

**Issue by SJavad** [dusty-nv/jetson-inference#1694]
@dusty-nv 
Hi, dusty 🖐
I Trained a model from my own dataset and use it to docker the container on Jetson TX1.
it is completely successful on the docker container when I run the detection mode and predict with the built-in camera on board...
But I want to use the Basler camera to capture frames and detect objects

in yolov5 I wrote the code that capture the video frames from the Basler camera and make predictions.
this block of code needs the pypylon package to install on python3 for using the Basler camera.
I download the pypylon package from pypi.org and install it with the pip command.
this package installs successfully and works. BUT Just in Yolov5...
this is the block of code that I used to use the Basler camera and make detection:
```python
import yaml
from pypylon import pylon
import cv2
import torch
import time

# conecting to the first available camera
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

print("Create Camera Instance: # Find CAMERA \n")
# Grabing Continusely (video) with minimal delay
camera.StartGrabbing(pylon.GrabStrategy_LatestImageOnly) 
converter = pylon.ImageFormatConverter()
print("ImageFormatConverter # Convert Image Format BGR8 \n ")
# converting to opencv bgr format
converter.OutputPixelFormat = pylon.PixelType_BGR8packed
converter.OutputBitAlignment = pylon.OutputBitAlignment_MsbAligned

print("Loading Model: # .pt model \n")
model = torch.hub.load('.', 'custom',"..\\FinalModels\\3060MG500.pt", "data.yaml", source="local")
print("Config Model Prameters: # confidence-thresh, IOU and YAML \n")

model_yaml_file = ".\\data\\coco.yaml"
with open(model_yaml_file) as yaml_file:
    yaml_data = yaml.safe_load(yaml_file)

model.names = yaml_data["names"]
model.conf = 0.85
model.iou = 0.45

print("Create VideoWriter Instance: # Video-Wrtie Class \n")
VideoWriter = cv2.VideoWriter("ResultRUN.avi", cv2.VideoWriter_fourcc(*"MJPG"),10,(640,640))


while camera.IsGrabbing():
    now_time = time.time()
    grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
    if grabResult.GrabSucceeded():
        # Access the image data
        image1 = converter.Convert(grabResult)
        image = image1.GetArray()
    grabResult.Release()

    results = model(image) # pass the camera frame and make prediction
    print(results)
    results.render() # show results
    
    cv2.imshow("Detection",image)

    VideoWriter.write(image)
    if cv2.waitKey(20) == ord("q"):
        break
    
    
# Releasing the resource    
camera.StopGrabbing()
cv2.destroyAllWindows()

```
###  1-Try running the model with a Basler camera in Container:
I use the detecnet.py python code for connecting to the camera and making predictions. but I have a problem...
I can't install Pypylon in a docker container. it always gives me an error that says (this package does not exist for this platform) or ( this package does not compatible with the Python version). the wheel file is the same as the file outside of the docker container.
but when I want to install the Pypylon package inside the container. it gives me an error.

**Comment by dusty-nv** [comment]
@SJavad can you try upgrading pip in container first to see if that allows you to install it?   `python3 -m pip install --upgrade pip`

What's the wheel file you were able to install it with before, or was it done via pip?

**Comment by SJavad** [comment]
> @SJavad can you try upgrading pip in container first to see if that allows you to install it?   `python3 -m pip install --upgrade pip`
> 
> What's the wheel file you were able to install it with before, or was it done via pip?

When I try to install outside the container, it is ok
- I try to upgrading my pip before installing with pip , but doesn't work...
My wheel file is downloaded from pypi and it's name is: pypylon-1.9.0-cp36-cp36m-manylinux-aarch64.whl 
This file successfully installed outside the container...

**Comment by dusty-nv** [comment]
What does `pip3 --version` show for you outside of the container, and inside the container?   My guess is that the pip3 inside the container still isn't updated to support the manylinux distribution
