### ISSUE TITLE
version of caffe being benchmarked

### ISSUE THREAD

**Issue by weishengchong** [dusty-nv/jetson-inference#17]
Hi,
for Caffe mentioned in readme's chart below, may I know which Caffe branch it is referring to?

![figure_2-1](https://cloud.githubusercontent.com/assets/17609244/19568669/078d2e02-9725-11e6-994b-5a462e3bde47.png)

I think it is not Nvidia's experimental/fp16 [Caffe branch ](https://github.com/NVIDIA/caffe/tree/experimental/fp16 ) mentioned in [Tx1 white paper](https://www.nvidia.com/content/tegra/embedded-systems/pdf/jetson_tx1_whitepaper.pdf). 
This is because above graph shows for Googlenet batch1@fp16, above 51fps is 1.6x faster than 33fps in table below extracted from [Tx1 white paper](https://www.nvidia.com/content/tegra/embedded-systems/pdf/jetson_tx1_whitepaper.pdf) 
![picture1](https://cloud.githubusercontent.com/assets/17609244/19568758/6c786c96-9725-11e6-9c9d-fc226fd34484.png)

Thank you.

**Comment by dusty-nv** [comment]
The caffe branch was experimental/fp16 and max clocks. There had been JetPack/cuDNN/OS updates since initial Jetson TX1 launch.

**Comment by dusty-nv** [comment]
Also, see issue [https://github.com/dusty-nv/jetson-inference/issues/9](9) for updated nvcaffe install instructions for JetPack 2.3 / Ubuntu 16.04.  Thanks!

**Comment by weishengchong** [comment]
Thanks!
