### ISSUE TITLE
how can I know the resource GPU

### ISSUE THREAD

**Issue by tzhang2014** [dusty-nv/jetson-inference#173]
Hi,
   How can I know each program takes up the GPU memory, like command that nvidia-smi，I know the command ,sudo ./tegrastats ， but i cannot konw the value of GPU memory！

**Comment by dusty-nv** [comment]
Hi @tzhang2014  , please refer to `cudaMemGetInfo()` function here:

http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g376b97f5ab20321ca46f7cfa9511b978

You can add it to your program and print it out, or make a daemon program that calls it in the background.
