### ISSUE TITLE
Issue Changing gstCamera pipeline

### ISSUE THREAD

**Issue by MonkeyWithAComputer** [dusty-nv/jetson-inference#174]
In gstCamera.cpp I am trying to change the pipeline that is used for capturing the image. I set the mLaunchStr to "udpsrc port=[Port] ! tsparse ! tsdemux ! queue ! h264parse ! omxh264dec ! appsink name=mysink"
and changed the default resolution in gstCamera.h. When I run the "./detectnet-camera coco-bottle" command i get 1 frame being displayed in the gui and then a segmentation fault. I'm assuming I have my data formatted incorrectly. Anyone know how to fix the issue?

Thanks!

The following pipeline works in command line:
` gst-launch-1.0 udpsrc port=[Port] ! tsparse !  tsdemux ! queue ! h264parse ! omxh264dec ! nveglglessink -e`

Console output:
`./detectnet-camera coco-bottle
detectnet-camera
  args (2):  0 [./detectnet-camera]  1 [coco-bottle]  

[gstreamer] initialized gstreamer, version 1.8.3.0
[gstreamer] gstreamer decoder pipeline string:
udpsrc port=1111 ! tsparse ! tsdemux ! queue ! h264parse ! omxh264dec ! appsink name=mysink

detectnet-camera:  successfully initialized video device
    width:  720
   height:  480
    depth:  12 (bpp)

detectNet -- loading detection network model from:
          -- prototxt    networks/DetectNet-COCO-Bottle/deploy.prototxt
          -- model       networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel
          -- input_blob  'data'
          -- output_cvg  'coverage'
          -- output_bbox 'bboxes'
          -- mean_pixel  0.000000
          -- threshold   0.500000
          -- batch_size  2

[GIE]  TensorRT version 2.1, build 2102
[GIE]  attempting to open cache file networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel.2.tensorcache
[GIE]  loading network profile from cache... networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel.2.tensorcache
[GIE]  platform has FP16 support.
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel loaded
[GIE]  CUDA engine context initialized with 3 bindings
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel input  binding index:  0
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel input  dims (b=2 c=3 h=640 w=640) size=9830400
[cuda]  cudaAllocMapped 9830400 bytes, CPU 0x102a00000 GPU 0x102a00000
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel output 0 coverage  binding index:  1
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel output 0 coverage  dims (b=2 c=1 h=40 w=40) size=12800
[cuda]  cudaAllocMapped 12800 bytes, CPU 0x103400000 GPU 0x103400000
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel output 1 bboxes  binding index:  2
[GIE]  networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel output 1 bboxes  dims (b=2 c=4 h=40 w=40) size=51200
[cuda]  cudaAllocMapped 51200 bytes, CPU 0x103600000 GPU 0x103600000
networks/DetectNet-COCO-Bottle/snapshot_iter_59700.caffemodel initialized.
[cuda]  cudaAllocMapped 16 bytes, CPU 0x103800000 GPU 0x103800000
maximum bounding boxes:  6400
[cuda]  cudaAllocMapped 102400 bytes, CPU 0x103a00000 GPU 0x103a00000
[cuda]  cudaAllocMapped 25600 bytes, CPU 0x10360c800 GPU 0x10360c800
default X screen 0:   1920 x 1080
[OpenGL]  glDisplay display window initialized
[OpenGL]   creating 720x480 texture
loaded image  fontmapA.png  (256 x 512)  2097152 bytes
[cuda]  cudaAllocMapped 2097152 bytes, CPU 0x103c00000 GPU 0x103c00000
[cuda]  cudaAllocMapped 8192 bytes, CPU 0x103403200 GPU 0x103403200
[gstreamer] gstreamer transitioning pipeline to GST_STATE_PLAYING
[gstreamer] gstreamer changed state from NULL to READY ==> mysink
[gstreamer] gstreamer changed state from NULL to READY ==> omxh264dec-omxh264dec0
[gstreamer] gstreamer changed state from NULL to READY ==> h264parse0
[gstreamer] gstreamer changed state from NULL to READY ==> queue0
[gstreamer] gstreamer changed state from NULL to READY ==> tsdemux0
[gstreamer] gstreamer changed state from NULL to READY ==> mpegtsparse2-0
[gstreamer] gstreamer changed state from NULL to READY ==> udpsrc0
[gstreamer] gstreamer changed state from NULL to READY ==> pipeline0
[gstreamer] gstreamer changed state from READY to PAUSED ==> omxh264dec-omxh264dec0
[gstreamer] gstreamer changed state from READY to PAUSED ==> h264parse0
[gstreamer] gstreamer stream status CREATE ==> src
[gstreamer] gstreamer changed state from READY to PAUSED ==> queue0
[gstreamer] gstreamer changed state from READY to PAUSED ==> tsdemux0
[gstreamer] gstreamer stream status ENTER ==> src
[gstreamer] gstreamer changed state from READY to PAUSED ==> mpegtsparse2-0
[gstreamer] gstreamer stream status CREATE ==> src
[gstreamer] gstreamer changed state from READY to PAUSED ==> udpsrc0
[gstreamer] gstreamer changed state from READY to PAUSED ==> pipeline0
[gstreamer] gstreamer stream status ENTER ==> src
[gstreamer] gstreamer msg new-clock ==> pipeline0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> omxh264dec-omxh264dec0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> h264parse0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> queue0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> tsdemux0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> mpegtsparse2-0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> udpsrc0
[gstreamer] gstreamer msg element ==> mpegtsparse2-0
[gstreamer] gstreamer msg element ==> mpegtsparse2-0
[gstreamer] gstreamer msg element ==> tsdemux0
[gstreamer] gstreamer msg element ==> mpegtsparse2-0

detectnet-camera:  camera open for streaming
NvMMLiteOpen : Block : BlockType = 261 
TVMR: NvMMLiteTVMRDecBlockOpen: 7907: NvMMLiteBlockOpen 
NvMMLiteBlockCreate : Block : BlockType = 261 
TVMR: cbBeginSequence: 1223: BeginSequence  720x480, bVPR = 0
TVMR: LowCorner Frequency = 100000 
TVMR: cbBeginSequence: 1622: DecodeBuffers = 7, pnvsi->eCodec = 4, codec = 0 
TVMR: cbBeginSequence: 1693: Display Resolution : (720x480) 
TVMR: cbBeginSequence: 1694: Display Aspect Ratio : (640x480) 
TVMR: cbBeginSequence: 1762: ColorFormat : 5 
TVMR: cbBeginSequence:1776 ColorSpace = NvColorSpace_YCbCr601
TVMR: cbBeginSequence: 1904: SurfaceLayout = 3
TVMR: cbBeginSequence: 2005: NumOfSurfaces = 14, InteraceStream = 0, InterlaceEnabled = 0, bSecure = 0, MVC = 0 Semiplanar = 1, bReinit = 1, BitDepthForSurface = 8 LumaBitDepth = 8, ChromaBitDepth = 8, ChromaFormat = 5
TVMR: cbBeginSequence: 2007: BeginSequence  ColorPrimaries = 2, TransferCharacteristics = 2, MatrixCoefficients = 2
Allocating new output: 720x480 (x 14), ThumbnailMode = 0
OPENMAX: HandleNewStreamFormat: 3464: Send OMX_EventPortSettingsChanged : nFrameWidth = 720, nFrameHeight = 480 
[gstreamer] gstreamer decoder onPreroll

detectnet-camera:  failed to capture frame
detectnet-camera:  failed to convert from NV12 to RGBA
detectNet::Detect( 0x(nil), 720, 480 ) -> invalid parameters
[cuda]   cudaNormalizeRGBA((float4*)imgRGBA, make_float2(0.0f, 255.0f), (float4*)imgRGBA, make_float2(0.0f, 1.0f), camera->GetWidth(), camera->GetHeight())
[cuda]      invalid device pointer (error 17) (hex 0x11)
[cuda]      /home/nvidia/jetson-inference/detectnet-camera/detectnet-camera.cpp:248
[cuda]   registered 5529600 byte openGL texture for interop access (720x480)
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104600000 GPU 0x104600000
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x10467ea00 GPU 0x10467ea00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x1046fd400 GPU 0x1046fd400
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x10477be00 GPU 0x10477be00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104800000 GPU 0x104800000
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x10487ea00 GPU 0x10487ea00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x1048fd400 GPU 0x1048fd400
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x10497be00 GPU 0x10497be00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104a00000 GPU 0x104a00000
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104a7ea00 GPU 0x104a7ea00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104afd400 GPU 0x104afd400
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104b7be00 GPU 0x104b7be00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104c00000 GPU 0x104c00000
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104c7ea00 GPU 0x104c7ea00
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104cfd400 GPU 0x104cfd400
[cuda]  cudaAllocMapped 518400 bytes, CPU 0x104d7be00 GPU 0x104d7be00
[cuda]   gstreamer camera -- allocated 16 ringbuffers, 518400 bytes each
[gstreamer] gstreamer msg element ==> mpegtsparse2-0
[gstreamer] gstreamer msg element ==> tsdemux0
[gstreamer] gstreamer msg stream-start ==> pipeline0
[gstreamer] gstreamer stream status CREATE ==> src
[gstreamer] gstreamer stream status ENTER ==> src
[gstreamer] gstreamer mysink missing gst_tag_list_to_string()
[cuda]   gstreamer camera -- allocated 16 RGBA ringbuffers
0 bounding boxes detected
Segmentation fault (core dumped)
`

**Comment by plieningerweb** [comment]
Maybe check the network input size and a required resize of the steam
