### ISSUE TITLE
Auto Detect Webcam & Wifi settings 

### ISSUE THREAD

**Issue by GirishPawar1999** [dusty-nv/jetson-inference#1763]
I am using jetson Orion nano along with the mobilenet SSD V2 , for detection of the humans. Below are the 2 cases for which i am stuck.

1. The algorithm works fine. Is there any python script example to identify the no of webcams connected to the jetson Orion, and their camera I'd  like '/dev/video0'

2. Is there any python script example to push the jetson Orion Acess Point wifi mode , along with the wifi settings like IP address , subnet, gateway .I tried using submodule , which works great for getting and setting the basic wifi with ssid and password but unable to configure the wifi of jetson nano for IP, subnet , gateway settings .

Pls do help me out if any one has better approach, for the above issued to be resolved.
Thanks

**Comment by dusty-nv** [comment]
Cross-post from https://forums.developer.nvidia.com/t/python-script-to-detection-of-webcams-wifi-settings/276344
