### ISSUE TITLE
Jetpack 6.0-b52 needs missing dustynv/jetson-inference:r36.2.0

### ISSUE THREAD

**Issue by plecluse** [dusty-nv/jetson-inference#1766]
Hello,
Just did a fresh install of latest Jetpack (19 dec 2023)

user@ubuntu:~/jetson-inference$ ./docker/run.sh
ARCH:  aarch64
reading L4T version from /etc/nv_tegra_release
L4T BSP Version:  L4T R36.2.0
CONTAINER_IMAGE:  dustynv/jetson-inference:r36.2.0
DATA_VOLUME:      --volume /home/user/jetson-inference/data:/jetson-inference/data --volume /home/user/jetson-inference/python/training/classification/data:/jetson-inference/python/training/classification/data --volume /home/user/jetson-inference/python/training/classification/models:/jetson-inference/python/training/classification/models --volume /home/user/jetson-inference/python/training/detection/ssd/data:/jetson-inference/python/training/detection/ssd/data --volume /home/user/jetson-inference/python/training/detection/ssd/models:/jetson-inference/python/training/detection/ssd/models --volume /home/user/jetson-inference/python/www/recognizer/data:/jetson-inference/python/www/recognizer/data
V4L2_DEVICES:     --device /dev/video0  --device /dev/video1
Unable to find image 'dustynv/jetson-inference:r36.2.0' locally
docker: Error response from daemon: manifest for dustynv/jetson-inference:r36.2.0 not found: manifest unknown: manifest unknown.

Indeed **r36.2.0** _missing_ https://hub.docker.com/r/dustynv/jetson-inference/tags 0 can you please push it ?

Additional info:
cat /etc/nv_tegra_release
# R36 (release), REVISION: 2.0, GCID: 34956989, BOARD: generic, EABI: aarch64, DATE: Thu Nov 30 19:03:58 UTC 2023

root@ubuntu:~# apt-cache show nvidia-jetpack
Package: nvidia-jetpack
Version: 6.0-b52

**Comment by dusty-nv** [comment]
Hi @plecluse, please try again now, I have pushed `dustynv/jetson-inference:r36.2.0`

**Comment by plecluse** [comment]
Hi @dusty-nv , confirmed as working now – many thanks for your quick support - closing

**Comment by lars-nagel** [comment]
@dusty-nv Thank you for the new docker interface! It works with `docker/run.sh`.
Unfortunately, when I run `~/Repos/jetson-inference$ docker/run.sh --ros=humble`, I the issue appears again:

```
user@ubuntu:~/Repos/jetson-inference$ docker/run.sh --ros=humble
ARCH:  aarch64
reading L4T version from /etc/nv_tegra_release
L4T BSP Version:  L4T R36.2.0
CONTAINER_IMAGE:  dustynv/ros:humble-pytorch-l4t-r36.2.0
ROS_DISTRO:       humble
DATA_VOLUME:      --volume /home/user/Repos/jetson-inference/data:/jetson-inference/data --volume /home/user/Repos/jetson-inference/python/training/classification/data:/jetson-inference/python/training/classification/data --volume /home/user/Repos/jetson-inference/python/training/classification/models:/jetson-inference/python/training/classification/models --volume /home/user/Repos/jetson-inference/python/training/detection/ssd/data:/jetson-inference/python/training/detection/ssd/data --volume /home/user/Repos/jetson-inference/python/training/detection/ssd/models:/jetson-inference/python/training/detection/ssd/models --volume /home/user/Repos/jetson-inference/python/www/recognizer/data:/jetson-inference/python/www/recognizer/data
V4L2_DEVICES:     --device /dev/video0  --device /dev/video1
Unable to find image 'dustynv/ros:humble-pytorch-l4t-r36.2.0' locally
docker: Error response from daemon: manifest for dustynv/ros:humble-pytorch-l4t-r36.2.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```
