### ISSUE TITLE
Trying to combine road_following program with detectnet program jetson nano jetracer

### ISSUE THREAD

**Issue by CamRoni1339** [dusty-nv/jetson-inference#1770]
@dusty-nv 

Hello, 

I am trying to combine your detectnet program with a road_rollowing program for the jetson nano jetracer. The road_following program uses csiCamera and detectnet uses gStreamer so it has been a little bit of a struggle trying to combine them into one. Below is the code for each program, the combined program, and the error message I receive when trying to run it. 

<img width="650" alt="Screenshot 2024-01-02 203228" src="https://github.com/dusty-nv/jetson-inference/assets/145303868/c0004cab-89e0-4fdb-9ef1-cd33b749d9c8">
<img width="370" alt="image rec loop" src="https://github.com/dusty-nv/jetson-inference/assets/145303868/3aaa56bf-3a27-4318-89f0-450a053f871f">
<img width="295" alt="an attempt was made" src="https://github.com/dusty-nv/jetson-inference/assets/145303868/c7a71d1e-62da-4e07-adf4-4073f03da1ef">
<img width="700" alt="the stupid error" src="https://github.com/dusty-nv/jetson-inference/assets/145303868/2582da38-b66f-4d0d-afdf-31ef6d2f57f6">

I am trying to combine the programs so I can make the car stop whenever it recognizes a stop sign. Any help with fixing this would be much appreciated.

Thank you so much.

**Comment by dusty-nv** [comment]
Hi @CamRoni1339, try calling `cudaFromNumpy()` followed by `cudaConvertColor()` on the image returned by cv2 `camera.read()` before passing it to `net.Detect()`.   No idea what passing camera.cap to net.Detect() would do.

* https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-image.md#converting-from-numpy-arrays
* https://github.com/dusty-nv/jetson-utils/blob/master/python/examples/cuda-from-cv.py

**Comment by CamRoni1339** [comment]
@dusty-nv 

Hello, 

I'm sorry to be asking what has to be simple questions but I am new to this and am not very good at it. I have tried calling cudafromnumpy() and cudaconvertcolor(), but I end up getting the error shown below. I'm sure that I am just simply not calling it correctly, so if you could show me how to do that, that would be great.

<img width="255" alt="new" src="https://github.com/dusty-nv/jetson-inference/assets/145303868/dfcd920a-f316-45eb-baee-fc9f2273ddc4">


Thank you so much for your time.

**Comment by CamRoni1339** [comment]
UPDATE

I figured out the format for cudaFromNumpy, but if you could show me what to do for cudaConvertColor that would be great.

Thank you so much for you time again.

**Comment by dusty-nv** [comment]
@CamRoni1339 see this example that I had linked to above that shows the use of cudaFromNumpy/cudaConvertColor to convert an OpenCV image:

https://github.com/dusty-nv/jetson-utils/blob/master/python/examples/cuda-from-cv.py

**Comment by CamRoni1339** [comment]
Thank you so much for the help! I have gotten to work.
