### ISSUE TITLE
Torch model support?

### ISSUE THREAD

**Issue by mescarra** [dusty-nv/jetson-inference#179]
I have been training torch models with DIGITS for some time now and I want to use them in jetson-inference. I could not find any torch2caffe model converter supporting every layer I use.

Are the any plans on supporting torch models in the near future?

Thanks a lot.

**Comment by dusty-nv** [comment]
Hi @mescarra , the roadmap for TensorRT is to import via `onnx` shared format, however I don't believe legacy torch will be supporting it.  PyTorch will, though.
