### ISSUE TITLE
nvidia-375 driver not built in kernel & error with cuda make  

### ISSUE THREAD

**Issue by pammelang** [dusty-nv/jetson-inference#180]
I can install the driver using `sudo apt-get install nvidia-375` and successfully reboot, but `lsmod | grep nvidia` returns nothing. 

when I try installing again I get 
`Reading package lists... Done`
`Building dependency tree  `     
`Reading state information... Done`
`nvidia-375 is already the newest version (384.98-0ubuntu0~gpu16.04.1).`
`The following packages were automatically installed and are no longer required:`
  `libdc1394-22 libgtkglext1 linux-headers-4.4.0-72`
  `linux-headers-4.4.0-72-generic linux-image-4.4.0-72-generic`
`  linux-image-extra-4.4.0-72-generic`
`Use 'sudo apt autoremove' to remove them.`
`0 upgraded, 0 newly installed, 0 to remove and 168 not upgraded.`
   

I noticed that I had nvidia-384 in 'usr/lib' and tried the whole 
`sudo apt-get purge nvidia*`
`sudo add-apt-repository ppa:graphics-drivers/ppa` 
`sudo apt update`
`sudo apt install nvidia-375`
 and rebooted but it gives the same exact above error. 

also with cuda, when i do `sudo make`, I go into a loop of errors of roughly 
`
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/cuda-8.0/samples/3_Imaging/HSOpticalFlow'
make[1]: Entering directory '/usr/local/cuda-8.0/samples/3_Imaging/dxtc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/cuda-8.0/samples/3_Imaging/dxtc'
make[1]: Entering directory '/usr/local/cuda-8.0/samples/3_Imaging/cudaDecodeGL'
`
which finishes with 
`/usr/bin/ld: cannot find -lnvcuvid`
`collect2: error: ld returned 1 exit status`
`Makefile:381: recipe for target 'cudaDecodeGL' failed`
`make[1]: *** [cudaDecodeGL] Error 1`
`make[1]: Leaving directory '/usr/local/cuda-8.0/samples/3_Imaging/cudaDecodeGL'`
`Makefile:52: recipe for target '3_Imaging/cudaDecodeGL/Makefile.ph_build' failed`
`make: *** [3_Imaging/cudaDecodeGL/Makefile.ph_build] Error 2`

I tried following some suggestions online and changing the variable ` UBUNTU_PKG_NAME = "nvidia-367"` to ` UBUNTU_PKG_NAME = "nvidia-375"` in the file '/usr/local/cuda-8.0/samples/3_Imaging/cudaDecodeGL/findgllib.mk', but I still get the same error. It's probably something to do with my driver, isn't it?

**Comment by annsonic** [comment]
I had this same issue and resolve it by modifying UBUNTU_PKG_NAME = "nvidia-375" to "nvidia-390".
Because my system installed "nvidia-390" driver.
(I found this fact when looked up /usr/lib/ directory)
