### ISSUE TITLE
How to convert data into BCHW format

### ISSUE THREAD

**Issue by lofyol** [dusty-nv/jetson-inference#1807]
Thank you for the great work of the author.  After resizing with jetson_utils, how do I convert the HWC format to BCHW format data?

**Comment by dusty-nv** [comment]
Hi @lofyol , this is done with the kernels in `c/tensorConvert.cu`, although these aren't usually exposed API's:

https://github.com/dusty-nv/jetson-inference/blob/master/c/tensorConvert.cu

**Comment by lofyol** [comment]
Thank you.  Is there a conversion interface for python?

**Comment by lofyol** [comment]
@dusty-nv Thank you. Is there a conversion interface for python?

**Comment by dusty-nv** [comment]
No, I don't expose those to python:  you could try `torch.as_tensor()` and just do it in PyTorch:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-image.md#cuda-array-interface

**Comment by lofyol** [comment]
OK，thank you~
