### ISSUE TITLE
Why you delete the deconv layer in FCN?

### ISSUE THREAD

**Issue by milk-bottle-liyu** [dusty-nv/jetson-inference#182]
Hi, I am new with TensorRT. I read the official post which says the TensorRT supprot deconvolution. I also tried on my Tx2 with the official TensorRT example giexec resulting in a failure "not support deconvolution groups". So I wound whether is it a version problem or there is something different between deconvolutiong groups and deconvolution.
Thank you!

**Comment by seeyouagain111** [comment]
hi, have you fix this problem , i use pytorch to TensorRT,my model has bilinear upsample layer. but there is a error，tenrsorRT cant support upsample，can you help me？
