### ISSUE TITLE
choose network precision as float32

### ISSUE THREAD

**Issue by gaochuanchao** [dusty-nv/jetson-inference#1826]
I am currently doing network profiling. When I run the inferencing model imagenet with jetson nano, the default precision option is FP16. Is there a way for me to manually set the precision option as FP32 for python applications?
<img width="365" alt="image" src="https://github.com/dusty-nv/jetson-inference/assets/22146315/4e441235-7eb8-45de-8a5c-711959f8157e">

**Comment by dusty-nv** [comment]
@gaochuanchao sorry I don't believe I have exposed the python API for that, however you can try changing this code to the following and recompiling/reinstalling jetson-inference:

https://github.com/dusty-nv/jetson-inference/blob/644f5158a55a7f313f4d43b57ad3ed109fcbf9ab/c/tensorNet.cpp#L544

```
# change to this instead
return TYPE_FP32;
```
