### ISSUE TITLE
how to get networks/FlowNet-320x240/flownets.onnx

### ISSUE THREAD

**Issue by newforrestgump001** [dusty-nv/jetson-inference#1829]
Hi @dusty-nv , I want to use flownet, but can't find networks/FlowNet-320x240/flownets.onnx，where can I download it？Thank you  a lot !

**Comment by dusty-nv** [comment]
@newforrestgump001 https://nvidia.box.com/shared/static/3dpg3hkme7kvkneix3nmqeaqzs0agmyy.onnx

no idea if this still works, been years, and it never made it out of the experimental branch.  plus there are surely better optical flow DNNs these days

**Comment by newforrestgump001** [comment]
Sincere thanks for you @dusty-nv ，I wonder is there a URL contains all the onnx used in jetson-inference? for example, flownets in different scale, depthnet etc.
