### ISSUE TITLE
Is it possible to run Stereo Depth DNN on a Jetson Orin Nano?

### ISSUE THREAD

**Issue by lida2003** [dusty-nv/jetson-inference#1856]
Just follow up the quesiton https://github.com/dusty-nv/jetson-inference/issues/1340

Is it possible to run Stereo Depth DNN on a Jetson Orin Nano, which is up to 40T?

And the last code comit date is 6 years from now, https://github.com/NVIDIA-AI-IOT/redtail/tree/master/stereoDNN. Any news?

**Comment by dusty-nv** [comment]
Yes, Isaac ROS has these, would recommend looking into those.

________________________________
From: Daniel Li ***@***.***>
Sent: Thursday, May 30, 2024 6:55:26 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] Is it possible to run Stereo Depth DNN on a Jetson Orin Nano? (Issue #1856)


Just follow up the quesiton #1340<https://github.com/dusty-nv/jetson-inference/issues/1340>

Is it possible to run Stereo Depth DNN on a Jetson Orin Nano, which is up to 40T?

**Comment by lida2003** [comment]
Yeah, I'm glad it has some progress on ArduCopter. Thanks @dusty-nv
