### ISSUE TITLE
imagenet can't work as readme says, see attached log

### ISSUE THREAD

**Issue by lida2003** [dusty-nv/jetson-inference#1858]
[test.log](https://github.com/user-attachments/files/15523869/test.log) with latest code on v6.0 Linux36.3

All kinds of prints, and I didn't think this prints are OK. Anyone knows why?

**Comment by dusty-nv** [comment]
Hi @lida2003 , unfortunately your log got truncated - can you try posting the full one, along with the command-line you used to run it and with any errors you encountered?

**Comment by lida2003** [comment]
Yes, really need to wait for a while. sometimes 40mins, even longer.
