### ISSUE TITLE
Question: How to get the FPS if the display is disabled?

### ISSUE THREAD

**Issue by bkanaki** [dusty-nv/jetson-inference#186]
Hello dusty-nv,

I am using this repo code for object detection and I am able to get an FPS of ~12. This is, of course, visible on a display but I want to deploy this system remotely and I won't be able to use the display. I also imagine if I disable the display by setting **glDisplay** to **NULL**, I may possibly get a little bit more FPS. Do you think this is correct? If so, could you suggest a way to get it even with no display?

Thanks,
Bhargav

**Comment by dusty-nv** [comment]
Hi Bhargav, you may want to time the execution of the network (whether you are using `imageNet`, `detectNet`, or `segNet` primitive).  This will allow you derive the raw FPS of the network, without considering the display.   Alternatively you can call [`tensorNet::EnableProfiler()`](https://github.com/dusty-nv/jetson-inference/blob/e12e6e64365fed83e255800382e593bf7e1b1b1a/tensorNet.h#L96) on any of the above primitives, which will enable layer timings within TensorRT.   See this code in `imagenet-console` sample for an example of doing that:  

https://github.com/dusty-nv/jetson-inference/blob/e12e6e64365fed83e255800382e593bf7e1b1b1a/imagenet-console/imagenet-console.cpp#L60
