### ISSUE TITLE
Caffe 0.16 support with DIGITS 6

### ISSUE THREAD

**Issue by laghai** [dusty-nv/jetson-inference#191]
I'm asking for this specifically, although it appears several other issues were also caused by incompatibility with Caffe 0.16, which is the version used with DIGITS 6 AMI.

What is involved in making Detectnet work with Caffe 0.16?

**Comment by dusty-nv** [comment]
TensorRT can load .caffemodel trained by caffe-0.15.   When a future release of TensorRT includes compatability with caffe-0.16 and newer, we can migrate the tutorial to the version you mention.
