### ISSUE TITLE
Still not able to fetch facenet and ped 100 pretrained weights

### ISSUE THREAD

**Issue by ashish230897** [dusty-nv/jetson-inference#197]
We cannot find the pretrained weights of facenet and ped-100. Can you please provide the same.
Thanks

**Comment by dusty-nv** [comment]
Hi, are you able to manually download from nvidia.box.com like in the [`CMakePreBuild.sh`](https://github.com/dusty-nv/jetson-inference/blob/master/CMakePreBuild.sh) script?   If not can you access it from over VPN?
