### ISSUE TITLE
6 GB is not enough? 

### ISSUE THREAD

**Issue by aprentis** [dusty-nv/jetson-inference#199]
Hi! 

I have a 6Gb 1060 card, and followed manual from this repo to train DetectNet. 
I`ve used Batch size 2 and Accumulation 5 as it stated here(https://github.com/dusty-nv/jetson-inference#selecting-detectnet-batch-size) but DIGITS says that my GPU is out of memory. 
Whats wrong? 
Thanks in advance. 
![screenshot from 2018-02-19 11-07-58](https://user-images.githubusercontent.com/17255184/36367884-c4ca357c-1565-11e8-8748-2d1290705b56.png)
![screenshot from 2018-02-19 11-08-09](https://user-images.githubusercontent.com/17255184/36367905-de00b80e-1565-11e8-834a-f63271f02d75.png)

![screenshot from 2018-02-19 11-08-33](https://user-images.githubusercontent.com/17255184/36367898-d3389400-1565-11e8-9cf1-5a146fb79cd0.png)
![screenshot from 2018-02-19 11-08-23](https://user-images.githubusercontent.com/17255184/36367900-d7275240-1565-11e8-83fc-6d732471fb3d.png)
![screenshot from 2018-02-19 11-10-30](https://user-images.githubusercontent.com/17255184/36367926-f15e3be2-1565-11e8-9e3e-2e45b337bcc4.png)

**Comment by dusty-nv** [comment]
Is your 6GB GPU card also used as primary display?   If so, what is the framebuffer resolution/size?   Linux may be consuming extra memory from the card for display purposes.  Alternatively to operating in headless mode, try adjusting the batch size and accumulation to consume less memory.
