### ISSUE TITLE
detectnet-camera output?

### ISSUE THREAD

**Issue by dchock10** [dusty-nv/jetson-inference#203]
Hello,
I am working on a project that uses detectnet for autonomous flight. In order to move forward, I need to figure out where the output of detectnet-camera is. I successfully followed the tutorial to train a neural network and get it transported to my jetson tx2. I tested the network with the onboard camera and was able to modify it to use my personal camera. My question now is, where can I find the output the the detectnet-camera? I'm hoping it is in the form of a gstreamer pipeline. I'm hoping to find a stream of output in the form of the the bounding boxes, but if anyone knows where I can find it, please help.
Thanks!

**Comment by dusty-nv** [comment]
Hi @dchock10 , `detectnet-camera` sample uses the [`detectNet`](https://github.com/dusty-nv/jetson-inference/blob/master/detectNet.h) class and the [`detectNet::Detect()`](https://github.com/dusty-nv/jetson-inference/blob/e12e6e64365fed83e255800382e593bf7e1b1b1a/detectNet.h#L133) function to find the list of bounding boxes.  In your application you will want to operate off this list of bounding boxes, as opposed to simply drawing them to the screen like in `detectnet-camera` sample.
