### ISSUE TITLE
Error when porting faster-rcnn trained with Coco into TensorRt

### ISSUE THREAD

**Issue by Luyang1125** [dusty-nv/jetson-inference#209]
I got the following error when porting faster-rcnn trained with Coco into TensorRt:

_sample_fasterRCNN_debug: NvPluginFasterRCNN.cu:81: virtual void nvinfer1::plugin::RPROIPlugin::configure(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, int): Assertion `inputDims[0].d[0] == (2 * A) && inputDims[1].d[0] == (4 * A)' failed._

It seems the dimension is mismatched. 

The model trained with Coco is different with the one trained with Pascal VOC(Default model used in the sampleFasterRCNN project). The number of output class label is 81 instead of 21. And the number of anchors used in the coco model increases from 9 to 12.

Due to these differences, I made the following changes in the sampleFasterRCNN project:

Change **OUTPUT_CLS_SIZE to 81** to match the label of Coco dataset.
Change **anchorsScaleCount to 4** and **anchorsScales to {4.0f, 8.0f, 16.0f, 32.0f}**.
Change the **num_output** of **rpn_cls_score** and **rpn_bbox_pred** layers in the prototxt to **24** and **48**.
Change the **num_output** of **cls_score** and **bbox_pred** layers in the prototxt to **81** and **324**.

The model I used is the pretrained Faster RCNN from this link: https://github.com/rbgirshick/py-faster-rcnn/tree/master/models

Besides, I also find a similar question asked in the Nvidia Forum, but nobody reply... https://devtalk.nvidia.com/default/topic/1016199/gpu-accelerated-libraries/using-tensorrt-2-1-with-my-own-trained-caffemodel/

Please help!

**Comment by dusty-nv** [comment]
Hi @Luyang1125 , are you using a Jetson TX1/TX2 by chance?  You may want to post your question on the DevTalk TX1 or TX2 boards, those are active.   Closing this issue here as Faster-RCNN isn't in scope of the tutorial and I am not an expert on it, sorry.
