### ISSUE TITLE
id's of classes in multiped-500 model

### ISSUE THREAD

**Issue by kylehounslow** [dusty-nv/jetson-inference#21]
@dusty-nv in the original.prototxt for the multiped-500 model it looks like there are 5 classes. In your example you reference pedestrians and luggage - what are the other 3 classes?
Also, is this multi-class dataset available if we wish to fine tune the model?
Thanks for the useful examples.

**Comment by dusty-nv** [comment]
The other 3 classes are mapped to pedestrian, they are unused.
