### ISSUE TITLE
Installing new Gstream version 1.1.14

### ISSUE THREAD

**Issue by ZeroCool11000** [dusty-nv/jetson-inference#211]
I am trying to install a new version of gstream on nvidia jetson tx2 (https://gstreamer.freedesktop.org/releases/1.14/ )

but it is a little bit confusion because it needs also libmirprotobuf,
because i also upgraded to protobuf 3.5.1 which is newer than the protobuf version which is used in libmirprotobuf so compiling gstreamer failes. Its really annyoing how to get a new version of libmirprotobuf because this one has diverse links to other libraries. 

Best regards.

**Comment by dusty-nv** [comment]
Hi @ZeroCool11000 , we are still internally testing the `1.14` version of GStreamer before supporting it in JetPack-L4T.
