### ISSUE TITLE
CUDA error -  failed to build CUDA engine

### ISSUE THREAD

**Issue by groot-1313** [dusty-nv/jetson-inference#214]
I am using an NVIDIA Jetson TX2, with Jetpack 3.1 and Tensorrt 3 installed. No other version of tensorrt exists on the TX2. 

Upon running `./imagenet-console orange_0.jpg output_0.jpg`, I get the following error:

> [GIE]  TensorRT version 3.0, build 3000
[GIE]  attempting to open cache file networks/bvlc_alexnet.caffemodel.2.tensorcache
[GIE]  cache file not found, profiling network model
[GIE]  platform has FP16 support.
[GIE]  loading networks/alexnet.prototxt networks/bvlc_alexnet.caffemodel
[GIE]  retrieved output tensor 'prob'
[GIE]  configuring CUDA engine
[GIE]  building CUDA engine
[GIE]  cudnnEngine.cpp (55) - Cuda Error in initializeCommonContext: 4
[GIE]  failed to build CUDA engine
failed to load networks/bvlc_alexnet.caffemodel
failed to load networks/bvlc_alexnet.caffemodel
imageNet -- failed to initialize.
imagenet-console:   failed to initialize imageNet

What needs to be done to resolve this?

**Comment by flbeck** [comment]
I currently have the same issue, however on a PC with a Quadro M2000 GPU and TensorRT version 2.1

**Comment by miunyhyr** [comment]
I currently have the same issue  on Jetson TX2 with JetPack 3.2. and TensorRT version 3.0.4

**Comment by miunyhyr** [comment]
[GIE]  TensorRT version 3.0.4, build 3004
[GIE]  attempting to open cache file networks/bvlc_alexnet.caffemodel.2.tensorcache
[GIE]  cache file not found, profiling network model
[GIE]  platform has FP16 support.
[GIE]  loading networks/alexnet.prototxt networks/bvlc_alexnet.caffemodel
[GIE]  failed to retrieve tensor for output 'prob'
[GIE]  configuring CUDA engine
[GIE]  building CUDA engine
[GIE]  Network must have at least one input and one output
[GIE]  failed to build CUDA engine
failed to load networks/bvlc_alexnet.caffemodel
failed to load networks/bvlc_alexnet.caffemodel
imageNet -- failed to initialize.
imagenet-console:   failed to initialize imageNet


I am using an NVIDIA Jetson TX2, with Jetpack 3.2 and Tensorrt 3 installed. No other version of tensorrt exists on the TX2. And i have the same issue with you.

**Comment by dusty-nv** [comment]
The error looks like corrupted alexnet.prototxt or alexnet.caffemodel, it cannot find the output layer "prob".  Van you try re-downloading and confirming the your prototxt has that layer name?

-------- Original message --------

**Comment by daohu527** [comment]
Could you pls tell me some way to print out the debug message?
> [GIE] TensorRT version 3.0, build 3000
[GIE] attempting to open cache file networks/bvlc_alexnet.caffemodel.2.tensorcache
[GIE] cache file not found, profiling network model
[GIE] platform has FP16 support.
[GIE] loading networks/alexnet.prototxt networks/bvlc_alexnet.caffemodel
[GIE] retrieved output tensor 'prob'

**Comment by dusty-nv** [comment]
Hi @daohu527 , you don't have an error in the log - does it load if you let it run for a few minutes?

Also it appears that you are running an older version of the project repo - if you are also running an older version of JetPack, that's ok, but if you are running a newer version of JetPack you may want to re-clone the project from master to get the latest updates.
