### ISSUE TITLE
Is MJPEG camera format supported?

### ISSUE THREAD

**Issue by vusdo** [dusty-nv/jetson-inference#215]
The uvc camera supports 120 fps with MJPEG 640x480 resolution.

detect-camera seems to convert only YUV-> RGBA.

Is it possible to convert from MJPG to RGBA?

Give me tips to speed things up.

`
ss << "v4l2src device=/dev/video" << mV4L2Device << " ! ";
ss << "image/jpeg, width=(int)" << mWidth << ", height=(int)" << mHeight << " ! ";
ss << "jpegdec !";
ss << "appsink name=mysink";
`

Thanks..

**Comment by dusty-nv** [comment]
Hi @vusdo , you may wish to use `nvjpegdec`, which is hardware-accelerated.  
Please refer to the [L4T Accelerated GStreamer Guide](https://developer.nvidia.com/embedded/dlc/l4t-accelerated-gstreamer-guide-28-2-ga) for more information.
