### ISSUE TITLE
Can the Jetson-inference be compiled for both CPU and GPU of Jetson TX2?

### ISSUE THREAD

**Issue by Pratosha-29** [dusty-nv/jetson-inference#221]
Hi , 
We are running Jetson-inference on NVIDIA JETSON TX2 board using TensorRT .
We have modified the code to meet certain requirements lying lane overlays, CAN transmission etc.
When there is no pedestrian for detection the algorithm runs at 15fps.
When it detects an object it slows down to 3-4fps.
Is there a way to compile the code or make changes such that functions can be split to run between CPU and GPU?
Or 
Is there any method to increase the FPS even when objects are detected?
@dusty-nv - inputs please!

**Comment by dusty-nv** [comment]
Linking to the DevTalk threads:

https://devtalk.nvidia.com/default/topic/1031867/increase-fps-of-jetson-inference-using-complete-utilisation-of-cpu-gpu/

https://devtalk.nvidia.com/default/topic/1032054/running-jetson-inference-completely-on-either-gpu-single-cpu-core/
