### ISSUE TITLE
How to compile for desktop GPUs ?

### ISSUE THREAD

**Issue by ZeroCool11000** [dusty-nv/jetson-inference#222]
Are there any CMakesFiles for compiling dusty interference for desktops GPUs because with my 1080 Ti i am getting invalid device function something like that: 

[cuda]   cudaGetLastError()
[cuda]      invalid device function (error 8) (hex 0x08)
[cuda]      /home/ddk/ddk-repo/jetson-inference/imageNet.cu:50
[cuda]   cudaPreImageNet((float4*)rgba, width, height, mInputCUDA, mWidth, mHeight, make_float3(104.0069879317889f, 116.66876761696767f, 122.6789143406786f))
[cuda]      invalid device function (error 8) (hex 0x08)
[cuda]      /home/ddk/ddk-repo/jetson-inference/imageNet.cpp:146

Any guess how to adapt the CMakeFile ?

Best regards.

**Comment by dusty-nv** [comment]
Hi @ZeroCool11000, you need to add your GPU's compute capability to the CMakeLists file at this line here:   https://github.com/dusty-nv/jetson-inference/blob/e12e6e64365fed83e255800382e593bf7e1b1b1a/CMakeLists.txt#L37
