### ISSUE TITLE
Please add DetectNet-COCO- for  Cell Phone?

### ISSUE THREAD

**Issue by 307509256** [dusty-nv/jetson-inference#224]
I'm the beginner about  caffe&jetson.  

I want to detect Cell Phone，but the mAP of bvlc_googlenet or alexnet is unsatisfactory，  Can you give me the model of Cell Phone using COCO, such as DetectNet-COCO-CellPhone.tar.gz

I try to use digits, but is diffcult to me.

Thank you very much!  @dusty-nv

**Comment by 307509256** [comment]
maybe you can give us the url, above the whole caffemodel of COCO （80 class ) @dusty-nv

**Comment by dusty-nv** [comment]
It appears that MS COCO has cell phone class:  [http://cocodataset.org/#explore](http://cocodataset.org/#explore)
Perhaps someone from the community has used it and can share their model.

**Comment by 307509256** [comment]
@dusty-nv
that will be diffcult to find it.
COCO have 80 classes, you offer 4 classes  only(Bottle, Dog,Airplane,Chair ). 
it's not enough.
