### ISSUE TITLE
Edge detection using opengl function

### ISSUE THREAD

**Issue by Raj7kumar7** [dusty-nv/jetson-inference#233]
Hello
Is it possible to do edge detection on camera input using opengl.If yes,Can u share the code??

**Comment by dusty-nv** [comment]
There are various OpenGL shaders implementing edge filters available if you search “GLSL edge detection”, like Sobel filter, Canny, ect.  However it is probably easier to integrate with this repo if using CUDA.   VisionWorks and NPP (NVIDIA Performance Primitives) have build-in functions for performing edge detection that use CUDA underneath.  Is there a particular reason that it needs to be OpenGL?

**Comment by Raj7kumar7** [comment]
No ,not necessary Opengl . When using this repo,how can we integrate edge detection on camera input using VisionWorks and NPP ??Which  build-in functions will help in doing so??
