### ISSUE TITLE
change font color and disable fps rate in the imagenet_camera

### ISSUE THREAD

**Issue by Patrick-Woo** [dusty-nv/jetson-inference#237]
hi dusty-nv,

I can successfully run imagenet_camera with c920 webcam. 

I would like to know how can I change the font color in the frames and disable fps rate showing in the title of window.

thank you.

**Comment by BourbonCreams** [comment]
In jetson-inference/imagenet-camera/imagenet-camera.cpp on line 178 you see
`display->SetTitle(str)`  // Comment this line if you don't want to see the title of the Window, i.e. no FPS
Where str is what you see on line 176. You can play with it to get what you want but if you just want to disable the fps rate on the title of the window then comment out line 178.
