### ISSUE TITLE
OpenCV conversion from imgCPU to Mat function 

### ISSUE THREAD

**Issue by Pratosha-29** [dusty-nv/jetson-inference#240]
Hi @dusty-nv ,
Added some lines to jetson-inference to perform lane detection .
while( !signal_recieved )
	{
		void* imgCPU  = NULL;
		void* imgCUDA = NULL;

		cv:: Mat reg(720, 1080, CV_8UC3);
		if( !camera->Capture(&imgCPU, &imgCUDA, 1000) )
			printf("\ndetectnet-camera:  failed to capture frame\n");

		// convert from YUV to RGBA
		void* imgRGBA = NULL;
		
		if( !camera->ConvertRGBA(imgCUDA, &imgRGBA) )
			printf("detectnet-camera:  failed to convert from NV12 to RGBA\n");

	strcpy((char*)reg.data,(char *)imgCPU);
	imshow("reg",reg);	

The output for reg is throwing half of the image data as shown in the link below.
![reg](https://user-images.githubusercontent.com/35485809/41019485-83e4f130-697c-11e8-9cab-00af9b14e076.png)
.
How to convert imgCPU to Mat format for further processing?
Thanks .

**Comment by laksh-lp** [comment]
were you able to solve this ? even i wanted to convert this to mat image and was unable to do so ..

**Comment by komms** [comment]
@Pratosha-29  Did you solve this problem of converting imgCPU to cv::Mat ?

**Comment by dusty-nv** [comment]
See this post - https://github.com/dusty-nv/jetson-inference/issues/241#issuecomment-656773777
