### ISSUE TITLE
in  cmakeprebuild.sh script, download this files failed.exp:bvlc_alexnet. Caffemoalexdel net. Prototxt bvlc_googlenet. Caffemodel googlenet. Prototxt

### ISSUE THREAD

**Issue by liuwen-nj** [dusty-nv/jetson-inference#242]
in  cmakeprebuild.sh script, download this files failed.exp:bvlc_alexnet. Caffemoalexdel net. Prototxt bvlc_googlenet. Caffemodel googlenet. Prototxt.
error show: 
--2016-02-12 06:12:12--  https://nvidia.box.com/shared/static/zb8i3zcg39sdjjxfty7o5935hpbd64y4.gz
Resolving nvidia.box.com (nvidia.box.com)... 107.152.25.197
Connecting to nvidia.box.com (nvidia.box.com)|107.152.25.197|:443... connected.
WARNING: cannot verify nvidia.box.com's certificate, issued by ‘CN=GeoTrust RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Issued certificate not yet valid.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://nvidia.app.box.com/shared/static/zb8i3zcg39sdjjxfty7o5935hpbd64y4.gz [following]
--2016-02-12 06:12:13--  https://nvidia.app.box.com/shared/static/zb8i3zcg39sdjjxfty7o5935hpbd64y4.gz
Resolving nvidia.app.box.com (nvidia.app.box.com)... 8.7.198.45
Connecting to nvidia.app.box.com (nvidia.app.box.com)|8.7.198.45|:443... failed: Connection timed out.
Retrying.

then, Is there any other way to download these files?
thank you very much.

**Comment by delldu** [comment]
--2018-07-27 09:45:39--  https://nvidia.app.box.com/shared/static/5j264j7mky11q8emy4q14w3r8hl5v6zh.caffemodel
Resolving nvidia.app.box.com (nvidia.app.box.com)... 59.24.3.173
Connecting to nvidia.app.box.com (nvidia.app.box.com)|59.24.3.173|:443... failed: Connection timed out.
Retrying.
