### ISSUE TITLE
object detection in lidar data

### ISSUE THREAD

**Issue by Raj7kumar7** [dusty-nv/jetson-inference#253]
Hello
I m new to deep learning stuffs.I want to know whether object detection is possible in lidar files ?

Thank you

**Comment by ArtlyStyles** [comment]
yes, there are papers about how to feed lidar data to deep learning neural network for object detection.

**Comment by Raj7kumar7** [comment]
Hello @ArtlyStyles  Can you provide me some  useful links as there are far to many documents on internet and i am little confused which one to go for?
Thank you for your support

**Comment by xmglin** [comment]
I am also interested on object detection in lidar data.
