### ISSUE TITLE
Semantic labelling

### ISSUE THREAD

**Issue by Raj7kumar7** [dusty-nv/jetson-inference#256]
Hello
How can i do the semantic labeling around detected objects?

**Comment by yeyicheng** [comment]
@Raj7kumar7 Did you find the solution? Thank you.

**Comment by Raj7kumar7** [comment]
@yeyicheng no .I did not find

**Comment by yeyicheng** [comment]
@Raj7kumar7 I found the solution.

I am using detectnet-camera.py. So in the code, 
```
img, width, height = camera.CaptureRGBA(zeroCopy=1)
for detection in detections:
    imgNumpy = jetson.utils.cudaToNumpy(img, width, height, 4)
    cv2.putText(imgNumpy, className, (int(detection.Left, detection.Top), 0, 2, (0, 0, 0),thickness=5)
```

**Comment by Raj7kumar7** [comment]
@yeyicheng Let me try it once.thanks for the info.
