### ISSUE TITLE
Parrallel Models

### ISSUE THREAD

**Issue by eanmikale** [dusty-nv/jetson-inference#262]
Dusty,
Any guidance on getting two custom models to run parallel for increased accuracy and diversity? Thanks again.

**Comment by dusty-nv** [comment]
Hi @eanmikale , you can create two individual `imageNet`, `detectNet`, or `segNet` instances loaded with separate networks and process them as you wish.

**Comment by eanmikale** [comment]
@dusty-nv - Would this create two windows? How would we get both networks to separately pull from both models, yet come up with one inferencing accuracy percentage on one camera? Or would the better route be to use two cameras? Thank you!

**Comment by eanmikale** [comment]
Thank you!
