### ISSUE TITLE
Low accuracy inference outputs...

### ISSUE THREAD

**Issue by eanmikale** [dusty-nv/jetson-inference#263]
@dusty-nv - Also having issue with training model. Accuracy is in 80's as you see below. Training on four Titan V's. Batch sizes is 4, and validation percentage is 10%, but have also tried 25%, with no changes. Also compressing pictures via Squash. Accuracy level for top five inferences are as follows (3.08%, 3.08%, 3.07%, 3.07%, and 3.07%). We have cleaned our jobs folder and tried again, as well as rebuilding DIGITS, but are still getting these results. Any assistance would be appreciated. Thanks again. 

![digitsissue](https://user-images.githubusercontent.com/25436318/45231056-7e5f2700-b290-11e8-90c2-73edc81392d7.jpg)

**Comment by perronj2** [comment]
I'm having the same issue, I believe it could be due to a significant amount of broken links in imagenet. The decrease in sample size will decrease accuracy of the inference... The links really need to be updated.

**Comment by perronj2** [comment]
@dusty-nv I have been waiting approval for close to a year....

**Comment by dusty-nv** [comment]
I was able to find a copy on Academic Torrents (for your research purposes only)
________________________________

**Comment by perronj2** [comment]
@dusty-nv Thanks for the info!
