### ISSUE TITLE
How to run detectnet-camera on OpenCV captured frame instead of gstreamer?

### ISSUE THREAD

**Issue by doruksonmez** [dusty-nv/jetson-inference#265]
Hi, I'm trying to get detectnet-camera run on frames captured by OpenCV instead GStreamer. Till now, I can see the frames taken by OpenCV (with imshow) however it keeps print "0 bounding boxes detected" on the terminal. What can be th problem? I'm not changing anything but taking the frames from the camera using OpenCV.

**Comment by aviontics** [comment]
Having same issue
