### ISSUE TITLE
how to use imagenet-console with multiple images?

### ISSUE THREAD

**Issue by ClaudioMor** [dusty-nv/jetson-inference#278]
Hi,
I used imagenet-console with my custom lite version of VGG16 trained on cifar10 and it worked fine.
Now i would like to use imagenet-console con a subset of 1000 in order to obtain top5 classification of each images and then calculate fps for this operation. By the chance, are there any example of modify imagenet-console?

This is the command to run imagenet-console with one image:

cd ~/jetson-inference/build/aarch64/bin
NET=networks/miniVggNet
./imagenet-console airplane_00001.jpg airplane_test.jpg \
--prototxt=$NET/deploy_3_miniVggNet.prototxt \
--model=$NET/snapshot_3_miniVggNet__iter_40000.caffemodel \
--labels=$NET/labels.txt \
--input_blob=data \
--output_blob=prob

thank you!

**Comment by dusty-nv** [comment]
Hi @ClaudioMor , please refer to this post:   https://devtalk.nvidia.com/default/topic/1044417/how-to-use-imagenet-console-with-multiple-images-/#5298750
