### ISSUE TITLE
Failed to run detectnet-console with DLA_0 device

### ISSUE THREAD

**Issue by leopard02** [dusty-nv/jetson-inference#279]
**Jetson, OS:**
Linux jetson-0423318033018 4.9.108-tegra #1 SMP PREEMPT Fri Sep 28 22:03:31 PDT 2018 aarch64 aarch64 aarch64 GNU/Linu
jetpack 4.1.1 with tensorRT 5.0

**Describe the problem**
When I run the **detectnet-console** with **DLA_0** device, the TRT reported that "**_[TRT] device DLA_0, failed to build CUDA engine_**"

**Full log:**
detectNet -- loading detection network model from:
-- prototxt ./networks/facenet-120/deploy.prototxt
-- model ./networks/facenet-120/snapshot_iter_24000.caffemodel
-- input_blob 'data'
-- output_cvg 'coverage'
-- output_bbox 'bboxes'
-- mean_pixel 0.000000
-- threshold 0.500000
-- batch_size 2

[TRT] TensorRT version 5.0.0
[TRT] desired precision specified for DLA_0: FASTEST
[TRT] requested fasted precision for device DLA_0 without providing valid calibrator, disabling INT8
[TRT] native precisions detected for DLA_0: FP32, FP16, INT8
[TRT] selecting fastest native precision for DLA_0: FP16
[TRT] attempting to open engine cache file ./networks/facenet-120/snapshot_iter_24000.caffemodel.2.0.DLA_0.FP16.engine
[TRT] cache file not found, profiling network model on device DLA_0
[TRT] device DLA_0, loading ./networks/facenet-120/deploy.prototxt ./networks/facenet-120/snapshot_iter_24000.caffemodel
[TRT] retrieved Input tensor "data": 3x450x450
[TRT] retrieved Output tensor "coverage": 1x28x28
[TRT] retrieved Output tensor "bboxes": 4x28x28
[TRT] device DLA_0, configuring CUDA engine
[TRT] device DLA_0, building FP16: ON
[TRT] device DLA_0, building INT8: OFF
[TRT] device DLA_0, building CUDA engine
_**[TRT] ../builder/cudnnBuilder2.cpp (689) - Misc Error in buildSingleLayer: 1 (Unable to process layer.)
[TRT] ../builder/cudnnBuilder2.cpp (689) - Misc Error in buildSingleLayer: 1 (Unable to process layer.)**_
[TRT] device DLA_0, failed to build CUDA engine
device DLA_0, failed to load ./networks/facenet-120/snapshot_iter_24000.caffemodel
detectNet -- failed to initialize.
detectnet-console: failed to initialize detectNet

### How do i to fix it?

**Comment by dusty-nv** [comment]
Currently the networks AlexNet, GoogleNet, ResNet-50, and LeNet have been validated on DLA for JetPack 4.1.1 DP.  DetectNet is not yet supported on DLA.  Do you have GPU fallback enabled?

https://devtalk.nvidia.com/default/topic/1044439/jetson-agx-xavier/failed-to-run-detectnet-console-with-dla_0-device/post/5299225/#5299225
