### ISSUE TITLE
Caffe Parser: ReLU negative slope is not supported

### ISSUE THREAD

**Issue by vusdo** [dusty-nv/jetson-inference#289]
./detectnet-console dog_1.jpg output_1.jpg yolov3

[TRT]  TensorRT version 4.0.2
[TRT]  desired precision specified for GPU: FASTEST
[TRT]  requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]  native precisions detected for GPU:  FP32, FP16
[TRT]  selecting fastest native precision for GPU:  FP16
[TRT]  attempting to open engine cache file networks/yolov3-tiny/yolov3-tiny.caffemodel.2.1.GPU.FP16.engine
[TRT]  cache file not found, profiling network model on device GPU
[TRT]  device GPU, loading networks/yolov3-tiny/yolov3-tiny_trt.prototxt networks/yolov3-tiny/yolov3-tiny.caffemodel

> Caffe Parser: ReLU negative slope is not supported
> error parsing layer type ReLU index 3

[TRT]  device GPU, failed to parse caffe network
device GPU, failed to load networks/yolov3-tiny/yolov3-tiny.caffemodel
detectNet -- failed to initialize.
detectnet-console:   failed to initialize detectNet

transformed yolov3-tiny into caffemodel.
ex:) https://github.com/marvis/pytorch-caffe-darknet-convert

The above error appears. Help me.

**Comment by VeryVery** [comment]
TensorRT will support Leaky relu from v5.1

see
https://devtalk.nvidia.com/default/topic/1050649/relu-negative-slope-is-not-supported-in-resnet34/?offset=9
