### ISSUE TITLE
Missing Super-Resolution-BSD500

### ISSUE THREAD

**Issue by tolysz** [dusty-nv/jetson-inference#295]
Is there a way to get `network/Super-Resolution-BSD500/super_resolution_bsd500.onnx`?

**Comment by dusty-nv** [comment]
Hi @tolysz , you can download it from https://nvidia.box.com/shared/static/a99l8ttk21p3tubjbyhfn4gh37o45rn8.gz

I just set it up to be downloaded automatically by the repo in commit [`05790c`](https://github.com/dusty-nv/jetson-inference/commit/05790c5537a05d06750ed9a669ceec944ea85c84).
