### ISSUE TITLE
Support for Jetson TK1

### ISSUE THREAD

**Issue by djebm2** [dusty-nv/jetson-inference#3]
Can I install and run the program on Jetson TK1 ?

**Comment by dusty-nv** [comment]
TensorRT isn't supported on TK1 because of the older CUDA and lack of 64-bit support, so unfortunately this repo is only for Jetson TX1 currently.

**Comment by djebm2** [comment]
Why does TensorRT need 64 bits supports if the Deep Learning instructions have lower precision ? thank you.

**Comment by dusty-nv** [comment]
That's regarding compiling the build and the memory address management, not the ALU precision.  JetPack for TX1 is also only providing 64-bit in the future (starting with Ubuntu 16.04 included in newly-released [JetPack 2.3](https://developer.nvidia.com/embedded/jetpack)).
