### ISSUE TITLE
why do you loop 10 times in superres-console.cpp?

### ISSUE THREAD

**Issue by lu-hongwei** [dusty-nv/jetson-inference#304]
there is a loop in here. I removed it and cannot see any difference in the up-scaled output image.

https://github.com/dusty-nv/jetson-inference/blob/master/superres-console/superres-console.cpp#113

/*
	 * upscale image with network
	 */
	for( int i=0; i < 10; i++ )

**Comment by dusty-nv** [comment]
Hi @lu-hongwei , the loop is just for profiling purposes to get a more accurate performance number.  Feel free to remove the loop without any impact to the image output.
