### ISSUE TITLE
Segmentation fault  running imagenet-console on jetson nano

### ISSUE THREAD

**Issue by IIMKB** [dusty-nv/jetson-inference#308]
I am trying to run  the jetson-inference samples on jetson nano.  Running the imagenet-console test app results in the following error:

[TRT]  device GPU, building CUDA engine (this may take a few minutes the first time a network is loaded)
Segmentation fault

`
$ sudo ./imagenet-console orange_0.jpg output_0.jpg
imagenet-console
  args (3):  0 [./imagenet-console]  1 [orange_0.jpg]  2 [output_0.jpg]  

imageNet -- loading classification network model from:
         -- prototxt     networks/googlenet.prototxt
         -- model        networks/bvlc_googlenet.caffemodel
         -- class_labels networks/ilsvrc12_synset_words.txt
         -- input_blob   'data'
         -- output_blob  'prob'
         -- batch_size   2

[TRT]  TensorRT version 5.0.6
[TRT]  detected model format - caffe  (extension '.caffemodel')
[TRT]  desired precision specified for GPU: FASTEST
[TRT]  requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]  native precisions detected for GPU:  FP32, FP16
[TRT]  selecting fastest native precision for GPU:  FP16
[TRT]  attempting to open engine cache file networks/bvlc_googlenet.caffemodel.2.1.GPU.FP16.engine
[TRT]  cache file not found, profiling network model on device GPU
[TRT]  device GPU, loading networks/googlenet.prototxt networks/bvlc_googlenet.caffemodel
[TRT]  failed to retrieve tensor for Output "prob"
[TRT]  device GPU, configuring CUDA engine
[TRT]  device GPU, building FP16:  ON
[TRT]  device GPU, building INT8:  OFF
[TRT]  device GPU, building CUDA engine (this may take a few minutes the first time a network is loaded)
Segmentation fault
`
Can someone please suggest me what all things i can solve this issues

**Comment by IIMKB** [comment]
Thanks for replying.
I have downloaded the new  `bvlc_googlenet.caffemodel`.
But the `Segmentation faul`t still occurs. 
Can you give me some other suggestions?
Thank you very much for your help.

**Comment by dusty-nv** [comment]
Hi @IIMKB, can you try the steps from this post?

https://devtalk.nvidia.com/default/topic/1049144/jetson-nano/imagenet-console-application-not-working-properly/post/5328776/#5328776

**Comment by FredXu1990** [comment]
I have also met this problem, and I have tried the above solutions. However, it doesn't make sense, could you give me some other suggestions? Thanks a lot.

**Comment by kaijunzhan** [comment]
I have similar issue but rather getting segmentation fault - nano just crashed. reinstalled / re-image still crash

**Comment by liurongfang** [comment]
I have same problem,but it be resolved after re-download caffmodel.hope this can help you

**Comment by hvacking** [comment]
hi ,in china, this url is not available. can i use https://github.com/dusty-nv/jetson-inference/releases to download the ' bvlc_googlenet.caffemodel '?

**Comment by dusty-nv** [comment]
Yes, you can use that mirror URL.  Are you able to access the mirror URL from China?
________________________________

**Comment by hvacking** [comment]
yes ,i can access to mirror URL of github.
but when we proceed the install, all the process stopped at this step. And some essential fold is not exit,such as 'aarch64' folder.
how do i fix this problem?

![11](https://user-images.githubusercontent.com/28031945/60103924-0a482e00-9793-11e9-8bc6-2275721189fb.gif)
![333](https://user-images.githubusercontent.com/28031945/60104004-2ea40a80-9793-11e9-9ce3-0caa7ec6eaae.gif)

**Comment by dusty-nv** [comment]
Try running "cmake ../" again.  Then "make" and "sudo make install"
________________________________

**Comment by hvacking** [comment]
hi ,i tried several times, but all stops at connect nivida.app.box.com ，when i interrupt the the process. i can not find the aarch64 folder under builder folder.

**Comment by dusty-nv** [comment]
OK, go into CMakePreBuild.sh and comment out all the wget commands.  Then run cmake ../ and make.
________________________________

**Comment by martynoconnor** [comment]
I have the same same problem. If I call imagenet-console.py, I get "Segmentation fault (core dumped)" - this is from a clean install following the github instructions to the letter, using an image downloaded an hour ago.

**Comment by dusty-nv** [comment]
@martynoconnor does your log look the same as [above](https://github.com/dusty-nv/jetson-inference/issues/308#issue-430811734)?

Were you able to download the models ok from the script?   If your log looks the same as above, it means your googlenet model is corrupted - so try deleting and re-downloading them.

**Comment by sdcharle** [comment]
For me (also running on a nano), console works, but the camera version gives a Segmentation Fault:

[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> nvvconv0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> capsfilter0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> nvarguscamerasrc0
[gstreamer] gstreamer msg stream-start ==> pipeline0
GST_ARGUS: Creating output stream
CONSUMER: Waiting until producer is connected...
GST_ARGUS: Available Sensor modes :
Segmentation fault (core dumped)
