### ISSUE TITLE
jetson-inference detectnet-camera can not using training model?

### ISSUE THREAD

**Issue by BrainyBeeLy** [dusty-nv/jetson-inference#31]
Dgits training model success. https://github.com/NVIDIA/DIGITS
using : cuda8.0 , caffe, digits5;
GoogleNet model
jetson-inference  detectnet-camera can not using this model, error follow: 

[GIE] attempting to open cache file vehicle/snapshot_iter_21120.caffemodel.tensorcache
[GIE] cache file not found, profiling network model
[GIE] platform has FP16 support.
[GIE] loading vehicle/deploy.prototxt vehicle/snapshot_iter_21120.caffemodel
**[GIE] failed to retrieve tensor for output 'coverage'
[GIE] failed to retrieve tensor for output 'bboxes'**
[GIE] configuring CUDA engine
[GIE] building CUDA engine

**Comment by dusty-nv** [comment]
Hi there, can you post the deploy.prototxt?   Thank you.

**Comment by BrainyBeeLy** [comment]
[deploy.prototxt](E:\saveStorage\20170121-172331-8693_epoch_30.0)

**Comment by BrainyBeeLy** [comment]
> 
[deploy.txt](https://github.com/dusty-nv/jetson-inference/files/721598/deploy.txt)

**Comment by adithya-p** [comment]
@BrainyBeeLy @dusty-nv @lukeyeager

Did you find a way to fix this? Can you please help me with the same? This issue has been closed even though there are no answers. No answers, but duplicate questions and the comment section ends in a loop in which one points to the other.

**Comment by scottire** [comment]
@BrainyBeeLy @dusty-nv @lukeyeager @adithya-p
Has anyone found a solution to this? 
I am having the same issue. The lack of error message is confusing, it has completely stalled with no indication of why. 
Here is my [deploy.prototxt](https://github.com/dusty-nv/jetson-inference/files/2219530/deploy.txt)
