### ISSUE TITLE
Instructions in segnet-patches.md seems wrong

### ISSUE THREAD

**Issue by ruanjiandong** [dusty-nv/jetson-inference#314]
According to segnet-patches.md, we need to "change pad: 100 to pad: 0". Is it required for TensorRT 4.x? In my experiment, TensorRT 4.x seems happy with pad == 100. Note: value 0 is harmful for my data set. The result was completely wrong for certain input. I got correct result with value 100.

**Comment by dusty-nv** [comment]
Hi @ruanjiandong, with newer TensorRT, yes `pad == 100` does work, however it is a bit slower.  So keep it at 100 if you want.
