### ISSUE TITLE
fpv-deploy-colors.txt not found

### ISSUE THREAD

**Issue by tedhuang96** [dusty-nv/jetson-inference#315]
I got stucked at the step FCN-Alexnet Patches for TensorRT. I was asked to copy fpv-deploy-colors.txt and put it into the model snapshot folder, but I cannot find the file anywhere in the dataset https://nvidia.box.com/shared/static/ft9cc5yjvrbhkh07wcivu5ji9zola6i1.gz -O NVIDIA-Aerial-Drone-Dataset.tar.gz. All I can find are fav-labels.txt and fav-training-colors.txt.

**Comment by AlexPasqua** [comment]
@tedhuang96 Hi, did you find that file in the end? I have the same problem

**Comment by AlexPasqua** [comment]
I have the same problem, but I used `fav-training-colors.txt` instead of `fav-deploy-colors.txt` and it seems to work.
