### ISSUE TITLE
Detectnet : coverage value over 1 for the pednet model

### ISSUE THREAD

**Issue by ChadyNassar** [dusty-nv/jetson-inference#319]
when using pednet model to detect pedestrians on images, the coverage value can be superior to 1.
Here an example :
$ cd ~/jetson-inference/build/aarch64/bin
$ ./detectnet-console peds-001.jpg output.jpg pednet
The result is :
3 bounding boxes detected
detected obj 0  class #0 (person)  confidence=0.932617
bounding box 0  (1466.601562, 71.323242)  (1769.531250, 937.617188)  w=302.929688  h=866.293945
detected obj 1  class #0 (person)  confidence=1.555664
bounding box 1  (434.414062, 50.097656)  (1057.031250, 961.611328)  w=622.617188  h=911.513672
detected obj 2  class #0 (person)  confidence=1.718750
bounding box 2  (1043.437500, 65.390625)  (1442.812500, 1017.509766)  w=399.375000  h=952.119141
detectnet-console:  writing 1920x1080 image to 'output.jpg'
detectnet-console:  successfully wrote 1920x1080 image to 'output.jpg'

**Comment by nkhdiscovery** [comment]
Would you please also see #558 ?

I am confused.
