### ISSUE TITLE
Applying imageNet to a avi file

### ISSUE THREAD

**Issue by skprasadu** [dusty-nv/jetson-inference#324]
Hello Dusty,

I have seen web postings where they have mentioned that we can use  filesrc to get the frame Capture and pass that to imageNet. I tried this few few days, with no luck.

I also went to gstCamera and modified the buildLaunchStr and put this as below,

"filesrc location=cars.avi ! videoparse width=1920 height=1080 framerate=30/1 format=2 ! appsink name=mysink"

But once I run the imagenet-camera, I get this error "failed to convert from NV12 to RGBA"

Now I am stuck. Can you help me? A working code will help a lot.

Krishna

**Comment by dusty-nv** [comment]
Hi Krishna, I think the issue is that you are missing the GStreamer elements in your pipeline to parse the AVI file and decode it.  Check out the Decoding examples from the NVIDIA L4T GStreamer User Guide for examples of that.
________________________________

**Comment by skprasadu** [comment]
This was a good pointer, it worked, the gstreamer pipeline is as below, just in case if it is useful to others,

"filesrc location=<avi file> ! avidemux name=demux ! decodebin ! videoconvert ! videoscale ! appsink name=mysink"

**Comment by devshank3** [comment]
> "filesrc location="avi file" ! avidemux name=demux ! decodebin ! videoconvert ! videoscale ! appsink name=mysink"


Where should we update this code ?
and any ways to modify imagenet-camera to take in internal video file as mp4 as such in the net
