### ISSUE TITLE
TX1 make fail my-recognition

### ISSUE THREAD

**Issue by sbow** [dusty-nv/jetson-inference#325]
Had to add following line to CMakeLists.txt:
         add_compile_options(-std=c++11) 
prior to line "cuda_add_executable(my-recognition my-recognition.cpp)" 

-- make error below: --
[ 50%] Building CXX object CMakeFiles/my-recognition.dir/my-recognition.cpp.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:54,
                 from /usr/local/include/jetson-inference/tensorNet.h:30,
                 from /usr/local/include/jetson-inference/imageNet.h:27,
                 from /home/nvidia/git/nano_mv/my-recognition/my-recognition.cpp:2:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/local/include/jetson-inference/tensorNet.h:30:0,
                 from /usr/local/include/jetson-inference/imageNet.h:27,
                 from /home/nvidia/git/nano_mv/my-recognition/my-recognition.cpp:2:
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsHW::DimsHW()’:
/usr/include/aarch64-linux-gnu/NvInfer.h:165:23: error: ‘DimensionType’ is not a class or namespace
   type[0] = type[1] = DimensionType::kSPATIAL;
                       ^
.........
......
...

**Comment by nuanxinqing** [comment]
making my-recognition on TX2 also ran into the same problem have solved by your method
