### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by mescarra** [dusty-nv/jetson-inference#33]
Just a follow-up on support for batch processing discussed in this topic:
https://devtalk.nvidia.com/default/topic/969035/jetson-tx1/embedded-deep-learning-with-jetson-mdash-nvidia-webinar/post/5060249/#5060249

**Comment by nPellejero** [comment]
Hi, I met the same issue. It would be of great help to have some insight on this. Thank you in advance.

**Comment by dusty-nv** [comment]
Hi there, which imaging primitive would you prefer be outfitted with batching first?   imageNet, detectNet, or segNet?

**Comment by mescarra** [comment]
Hello Dustin!

imageNet would be the best choice, since what we want is to classify small patches taken from a regular grid out of a big picture, so it would be useful to have an example of the classification task.

Thanks in advance

**Comment by dusty-nv** [comment]
Thanks for explaining your use-case, that sounds useful.  I will add it as soon as I can - my wife is due with twins any minute now...  And eventually I will add it to all three imaging primitives.

**Comment by mescarra** [comment]
Wow! Congratulations Dustin! Big day today hehe
Thank you very much for you help!

**Comment by corti-forkworks** [comment]
Hello, any news about this new feature? It would be very helpful for me as well. Thank you very much!!

**Comment by dkopljar** [comment]
@dusty-nv Any progress on this batch processing feature?

**Comment by rockkingjy** [comment]
@dusty-nv I need this too, exactly the same as mescarra said, any news? Or point out a way to do this, I will do it by myself if it's possible.

**Comment by rockkingjy** [comment]
@mescarra @corti-forkworks @dkopljar I've done this. Thanks. Check link: https://github.com/rockkingjy/jetson-inference-batch

**Comment by romzie** [comment]
@dusty-nv Any update on an official feature?

**Comment by BAILOOL** [comment]
@dusty-nv @romzie any update?
