### ISSUE TITLE
~/jetson_clocks.sh and Nano?

### ISSUE THREAD

**Issue by thovoll** [dusty-nv/jetson-inference#331]
The docs reference ~/jetson_clocks.sh which doesn't seem to be available on Nano. Is that correct? If so, would be good to update the docs.

**Comment by thovoll** [comment]
For example here: https://github.com/dusty-nv/jetson-inference/blob/master/docs/detectnet-camera-2.md

**Comment by dusty-nv** [comment]
It is now just jetson_clocks
No need for the ~/  or the .sh
Thanks for the heads-up on the docs!

**Comment by thovoll** [comment]
Ok, thanks! Found it. Is there a way to turn the clocks back down?

**Comment by dusty-nv** [comment]
To do that, first you would have needed to run:

jetson_clocks --store

Then run jetson_clocks to maximize, and when you want to turn the clocks back down, run:

jetson_clocks --restore

Assuming you didn’t run it with --store first, reboot and the system will be back to normal.  Then you can run --store

**Comment by thovoll** [comment]
Yes, that's what I ended up doing. Thanks!
