### ISSUE TITLE
Slow Jetson nano

### ISSUE THREAD

**Issue by ymk201** [dusty-nv/jetson-inference#333]
is there anyone who can explain why jetson nano is so slow?

i have wrote the code below.
i have a ip camera which supports rtsp.
when i run below python3 code, the video stream on my nano is look so good.
it seems like slow motion video.

targetCam = 'rtsp://*'

widnowWidth     = 1920
windowHeight    = 1080
windowRatio     = 0.5
windowSize = (int(widnowWidth*windowRatio), int(windowHeight*windowRatio))

cap = cv2.VideoCapture(targetCam)
cv2.namedWindow('main', cv2.WINDOW_NORMAL)
cv2.resizeWindow('main',windowSize)

while(cap.isOpened()):
    ret, frame = cap.read()
    
    cv2.imshow('main', frame)
    
    if cv2.waitKey(20) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

rtsp spec. : 2560 X 1920 @ 30 fps w/ h.264
this rtsp server works well.
i have tested under vlc player and run the same code above with my laptop.

**Comment by dusty-nv** [comment]
Hi @ymk201 , recommend posting your question to the [Jetson Nano forum](https://devtalk.nvidia.com/default/board/371/jetson-nano/) since it is unrelated to the code from `jetson-inference` repo.
