### ISSUE TITLE
The Jetson Nano crashes regurlary when running the live camera demo ./detect-camera

### ISSUE THREAD

**Issue by vlschmidt** [dusty-nv/jetson-inference#334]
The behaviour is a little bit sporadic, sometimes the demo will run for quite a long time, on other occassions it crashes right after starting. It almost always crashes when I open another window in Ubuntu. What is the reason for these crashes, are there any ways around this. 

I'm sorry if I am posting this in the wrong forum, but I couldn't find a better place as I'm not sure if this is a hardware or a software issue.

**Comment by dusty-nv** [comment]
Hi vlschmidt, can you try putting your board in 5W mode and see if that helps?

sudo nvpmodel -m 1

If it doesn't crash in 5W mode, that means it's a power supply issue, and perhaps you can try a 4A DC barrel jack adapter.
________________________________

**Comment by vlschmidt** [comment]
Thank you! This helped. I did not need a 4A DV barrel adapter. My 5V, 2A usb power adapter worked fine.

**Comment by Foratog** [comment]
The  command worked for me with my %V, 2A usb power adapter as well thank you so much...

**Comment by cydu123** [comment]
I have the same problem. It's a annoying issue. I'm using 4A DC barrel jack adapter.

**Comment by dusty-nv** [comment]
@cydu123 does the issue still happen in 5W mode?  If so, then it is related to power supply's stability, even if it is barrel jack adapter.

**Comment by Kaju-Bubanja** [comment]
I also have sporadic crashes changing the power mode from MAXN to 5W did not really help.
