### ISSUE TITLE
bash: ./imagenet-camera: No such file or directory

### ISSUE THREAD

**Issue by Santhosh1509** [dusty-nv/jetson-inference#337]
Beginner here, following the tutorial **[Running the Live Camera Recognition Demo](https://github.com/dusty-nv/jetson-inference/blob/master/docs/imagenet-camera-2.md)**

when i run ` ./imagenet-camera googlenet`

I get this line

> bash: ./imagenet-camera: No such file or directory

any help?

**Comment by dusty-nv** [comment]
Hi there, is your terminal in <dir-where-installed>/jetson-inference/build/aarch64/bin ?   Did the project compile successfully?  Can you list the output of "ls" command - thanks.
________________________________

**Comment by Santhosh1509** [comment]
I ran the command outside the directory where the build was made.
It does run inside the build directory
Would be nice if the tutorial would be more specific, as it would be helpful for a newbee like me
Thank you @dusty-nv
