### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by ArtlyStyles** [dusty-nv/jetson-inference#341]
Do we have already trained object detection/localization and segnet model I can use directly on Jetson tx2?

**Comment by dusty-nv** [comment]
Yes, see the Hello AI World section of the tutorial.  imageNet, detectNet, and segNet each come with pre-trained models to use.
________________________________

**Comment by ArtlyStyles** [comment]
DO you have tensorflow model?

**Comment by dusty-nv** [comment]
Yes for detectNet, there are `ssd-mobilenet-v1`, `ssd-mobilenet-v2`, and `ssd-inception-v2` models.  They are currently found in the python dev branch:

`git clone -b python https://github.com/dusty-nv/jetson-inference`
