### ISSUE TITLE
ImportError: No module named jetson

### ISSUE THREAD

**Issue by Santhosh1509** [dusty-nv/jetson-inference#342]
Followed 
[Building the Project from Source](https://github.com/dusty-nv/jetson-inference/blob/python/docs/building-repo-2.md)

Did

>$ sudo apt-get install git cmake
> $ git clone https://github.com/dusty-nv/jetson-inference
> $ cd jetson-inference
> $ git submodule update --init

guess i forgot to do this in the first time during the build
> $ sudo apt-get install libpython3-dev python3-numpy

> $ cd jetson-inference    # omit if pwd is already jetson-inference from above
> $ mkdir build
> $ cd build
> $ cmake ../

> $ make
> $ sudo make install

I can't find `jetson.inference` and `jetson.utils` inside `/usr/lib/python3.6/dist-packages`

This is what i can see inside after running `ls /usr/lib/python3.6/dist-packages`

> graphsurgeon                  tensorrt                    uff
> graphsurgeon-0.3.2.dist-info  tensorrt-5.0.6.3.dist-info  uff-0.5.5.dist-info

tried to deleting `rm -rf jetson-inference` reinstall with all the following steps
Yet No `jetson.inference` and `jetson.utils` inside `/usr/lib/python3.6/dist-packages`
What is going wrong? Have i missed any step in between?

**Comment by dusty-nv** [comment]
Is the Python 2.7 version working?

If you forgot to install libpython3-dev initially, re-run "cmake ../" and "sudo make install"
________________________________

**Comment by Santhosh1509** [comment]
I did as you suggested `cmake ../` and `sudo make install` inside new `build`

Content of the dist-packages of all the python

    ls /usr/lib/python2.7/dist-packages

> asn1crypto                                numpy-1.13.3.egg-info
> asn1crypto-0.24.0.egg-info                pip
> attr                                      pip-9.0.1.egg-info
> attrs-17.4.0.egg-info                     pkg_resources
> cairo                                     pluggy
> _cffi_backend.aarch64-linux-gnu.so        pluggy-0.6.0.egg-info
> Crypto                                    py
> cryptography                              py-1.5.2.egg-info
> cryptography-2.1.4.egg-info               pycairo-1.16.2.egg-info
> cv2.aarch64-linux-gnu.so                  pycrypto-2.6.1.egg-info
> dbus                                      pygobject-3.26.1.egg-info
> _dbus_bindings.aarch64-linux-gnu.so       pygtkcompat
> _dbus_glib_bindings.aarch64-linux-gnu.so  pygtk.pth
> easy_install.py                           pygtk.py
> easy_install.pyc                          pygtk.pyc
> enum                                      _pytest
> enum34-1.1.6.egg-info                     pytest-3.3.2.egg-info
> funcsigs                                  pytest.py
> funcsigs-1.0.2.egg-info                   pytest.pyc
> gi                                        pyxdg-0.25.egg-info
> glib                                      README
> gobject                                   secretstorage
> gps                                       SecretStorage-2.3.1.egg-info
> gps-3.17.egg-info                         setuptools
> graphsurgeon                              setuptools-39.0.1.egg-info
> graphsurgeon-0.3.2.dist-info              six-1.11.0.egg-info
> gtk-2.0                                   six.py
> idna                                      six.pyc
> idna-2.6.egg-info                         talloc.aarch64-linux-gnu.so
> ipaddress-1.0.17.egg-info                 tensorrt
> ipaddress.py                              tensorrt-5.0.6.3.dist-info
> ipaddress.pyc                             uff
> keyring                                   uff-0.5.5.dist-info
> keyring-10.6.0.egg-info                   unity_lens_photos-1.0.egg-info
> keyrings                                  wheel
> keyrings.alt-3.0.egg-info                 wheel-0.30.0.egg-info
> lsb_release.py                            xdg
> numpy

    ls /usr/lib/python3.6/dist-packages

> graphsurgeon                  tensorrt                    uff
> graphsurgeon-0.3.2.dist-info  tensorrt-5.0.6.3.dist-info  uff-0.5.5.dist-info

    ls /usr/lib/python3/dist-packages

> apport
> apport_python_hook.py
> apt
> aptdaemon
> apt_inst.cpython-36m-aarch64-linux-gnu.so
> apt_inst.pyi
> apt_pkg.cpython-36m-aarch64-linux-gnu.so
> apt_pkg.pyi
> aptsources
> AptUrl
> apturl-0.5.2.egg-info
> asn1crypto
> asn1crypto-0.24.0.egg-info
> beautifulsoup4-4.6.0.egg-info
> blinker
> blinker-1.4.egg-info
> Brlapi-0.6.6.egg-info
> brlapi.cpython-36m-aarch64-linux-gnu.so
> bs4
> cairo
> certifi
> certifi-2018.1.18.egg-info
> _cffi_backend.cpython-36m-aarch64-linux-gnu.so
> chardet
> chardet-3.0.4.egg-info
> Crypto
> cryptography
> cryptography-2.1.4.egg-info
> cups.cpython-36m-aarch64-linux-gnu.so
> cupshelpers
> cupshelpers-1.0.egg-info
> cv2.cpython-36m-aarch64-linux-gnu.so
> dateutil
> dbus
> _dbus_bindings.cpython-36m-aarch64-linux-gnu.so
> _dbus_glib_bindings.cpython-36m-aarch64-linux-gnu.so
> deb822.py
> debconf.py
> debian
> debian_bundle
> defer
> defer-1.0.6.egg-info
> distro_info-0.18ubuntu0.18.04.1.egg-info
> distro_info.py
> distro_info_test
> DistUpgrade
> easy_install.py
> feedparser-5.2.1.egg-info
> feedparser_debian
> feedparser.py
> gi
> google
> html5lib
> html5lib-0.999999999.egg-info
> httplib2
> httplib2-0.9.2.egg-info
> HweSupportStatus
> idna
> idna-2.6.egg-info
> janitor
> jwt
> keyring
> keyring-10.6.0.egg-info
> keyrings
> keyrings.alt-3.0.egg-info
> LanguageSelector
> language_selector-0.1.egg-info
> language_support_pkgs.py
> launchpadlib
> launchpadlib-1.10.6.egg-info
> lazr
> lazr.restfulclient-0.13.5.egg-info
> lazr.uri-1.0.3.egg-info
> louis
> louis-3.5.0.egg-info
> lsb_release.py
> lxml
> lxml-4.2.1.egg-info
> macaroonbakery
> macaroonbakery-1.1.3.egg-info
> mako
> Mako-1.0.7.egg-info
> markupsafe
> MarkupSafe-1.0.egg-info
> nacl
> numpy
> numpy-1.13.3.egg-info
> NvidiaDetector
> oauth
> oauth-1.0.1.egg-info
> oauthlib
> oauthlib-2.0.6.egg-info
> orca
> pip
> pip-9.0.1.egg-info
> pkg_resources
> problem_report.py
> protobuf-3.0.0.egg-info
> pyatspi
> __pycache__
> pycairo-1.16.2.egg-info
> pycrypto-2.6.1.egg-info
> pycups-1.9.73.egg-info
> pygobject-3.26.1.egg-info
> pygtkcompat
> PyJWT-1.5.3.egg-info
> pymacaroons
> pymacaroons-0.13.0.egg-info
> PyNaCl-1.1.2.egg-info
> pyrfc3339
> pyRFC3339-1.0.egg-info
> python_apt-1.6.4.egg-info
> python_dateutil-2.6.1.egg-info
> python_debian-0.1.32.egg-info
> pytz
> pytz-2018.3.egg-info
> pyxdg-0.25.egg-info
> PyYAML-3.12.egg-info
> Quirks
> README.txt
> requests
> requests-2.18.4.egg-info
> requests_unixsocket
> requests_unixsocket-0.1.5.egg-info
> secretstorage
> SecretStorage-2.3.1.egg-info
> setuptools
> setuptools-39.0.1.egg-info
> simplejson
> simplejson-3.13.2.egg-info
> six-1.11.0.egg-info
> six.py
> softwareproperties
> speechd
> speechd_config
> ssh_import_id
> ssh_import_id-5.7.egg-info
> systemd
> systemd_python-234.egg-info
> system_service-0.3.egg-info
> UbuntuDrivers
> ubuntu_drivers_common-0.0.0.egg-info
> UbuntuSystemService
> unattended_upgrades-0.1.egg-info
> unity_scope_calculator-0.1.egg-info
> unity_scope_chromiumbookmarks-0.1.egg-info
> unity_scope_colourlovers-0.1.egg-info
> unity_scope_devhelp-0.1.egg-info
> unity_scope_firefoxbookmarks-0.1.egg-info
> unity_scope_manpages-0.1.egg-info
> unity_scope_openclipart-0.1.egg-info
> unity_scope_texdoc-0.1.egg-info
> unity_scope_tomboy-0.1.egg-info
> unity_scope_virtualbox-0.1.egg-info
> unity_scope_yelp-0.1.egg-info
> unity_scope_zotero-0.1.egg-info
> unohelper.py
> uno.py
> UpdateManager
> urllib3
> urllib3-1.22.egg-info
> wadllib
> wadllib-1.3.2.egg-info
> webencodings
> webencodings-0.5.egg-info
> wheel
> wheel-0.30.0.egg-info
> xdg
> xkit
> xkit-0.0.0.egg-info
> yaml
> _yaml.cpython-36m-aarch64-linux-gnu.so
> zope
> zope.interface-4.3.2.egg-info
> zope.interface-4.3.2-nspkg.pth

No `jetson` anywhere.

What's going wrong?

**Comment by dusty-nv** [comment]
From your original message, it doesn't look like you cloned the `python` branch.  It is still in development, so for now clone it like this:

`$ git clone -b python https://github.com/dusty-nv/jetson-inference`

**Comment by Santhosh1509** [comment]
@dusty-nv Thank you

    find / -type d -name "jetson" -print 2>/dev/null

> /usr/lib/python2.7/dist-packages/jetson
> /usr/lib/python3.6/dist-packages/jetson

I am new to this, it would be convenient for others like me if you could edit [Building the Project from Source](https://github.com/dusty-nv/jetson-inference/blob/python/docs/building-repo-2.md) for python.

**Comment by csmanu** [comment]
When I run './my-recognition.py polar_bear.jpg' as explained under the "Coding Your Own Image Recognition Program (Python)" section, I get the following error:
`./my-recognition.py polar_bear.jpg
Traceback (most recent call last):
  File "./my-recognition.py", line 3, in <module>
    import jetson.inference
ModuleNotFoundError: No module named 'jetson'`

Python version: 3.6.9
OS: Ubuntu 18.04 LTS
Platform: NVIDIA Jetson Nano

As suggested in [](https://devtalk.nvidia.com/default/topic/1068718/jetson-nano/error-when-trying-to-run-hello-ai-world/) , I tried re-installing jetson-inference. I also have checked for the files "jetson.inference" and "jetson.utils" and they exist under "/usr/lib/python3.6/dist-packages/jetson".

Appreciate help. Thanks in advance.

**Comment by dusty-nv** [comment]
Can you try running it as:  python3 my-recognition.py

If you run an interactive python3 interpreter, are you able to import jetson.inference ?
________________________________

**Comment by csmanu** [comment]
When I run,
$ python3 my-recognition.py polar_bear.jpg

I get the following error:
Traceback (most recent call last):
  File "./my-recognition.py", line 3, in <module>
    import jetson.inference
ModuleNotFoundError: No module named 'jetson'

**Comment by dusty-nv** [comment]
Hmm.  If you run an interactive python3 interpreter/shell, are you able to import jetson.inference ?

Are there any files under your `/usr/lib/python3.6/dist-packages/jetson` ?

**Comment by csmanu** [comment]
> Hmm. If you run an interactive python3 interpreter/shell, are you able to import jetson.inference ?
> 
> Are there any files under your `/usr/lib/python3.6/dist-packages/jetson` ?

`Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jetson.inference
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jetson' `

I find the following files listed under `/usr/lib/python3.6/dist-packages/jetson`
inference  
__init__.py  
utils

**Comment by moresandeep** [comment]
@dusty-nv and @csmanu I ran into this issue today. It turns out I have multiple python3 installations the latest one being 3.8. So, my python3 references to 3.8. All the libs for jetson are installed under 3.6 (don't know why) but when I run the program using python3.6 (as opposed to just python3) I no longer get this error.

**Comment by federicolucca** [comment]
Same problem. But i haven't any folder `/jetson` in any `/dist-packages`. i have under python3.6 a folder with `Jetson` ,with uppercase, with a subfolder `GPIO`

**Comment by silent-code** [comment]
If using a virtual environment, you have to copy these files after the sudo ldconfig:

cp  /usr/lib/python3.6/dist-packages/jetson_inference_python.so /home/.virtualenvs/dl4cv/lib/python3.6/site-packages/jetson_inference_python.so

cp  /usr/lib/python3.6/dist-packages/jetson_utils_python.so     /home/.virtualenvs/dl4cv/lib/python3.6/site-packages/jetson_utils_python.so

**Comment by CalebBates** [comment]
Hello! I have Ubuntu 18.04 LTS and I am using a Jetson TX2

I am getting the following error:
ModuleNotFoundError: No module named 'Jetson'

I run the following command:
sudo pip3 install Jetson

I get the following  errors:
1. Could not find a version that satisfies the requirement Jetson (from versions: none)
2. No matching distribution found for Jetson

What could be possible solutions for fixing the No module named 'Jetson' error?

Thanks for the help!

**Comment by CalebBates** [comment]
I am getting the following error:

ModuleNotFoundError: No module named 'Jetson'

How can I fix this?

Thanks!

**Comment by maximofn** [comment]
> From your original message, it doesn't look like you cloned the `python` branch. It is still in development, so for now clone it like this:
> 
> `$ git clone -b python https://github.com/dusty-nv/jetson-inference`

Doing this and recompiling it fixed it for me

**Comment by maximofn** [comment]
Hi @dusty-nv, using the master branch I had the same problem, I had to download the python branch

**Comment by sprakashdash** [comment]
@dusty-nv Is there a way to link the jetson inference module to the latest python. I am using python 3.8

**Comment by dusty-nv** [comment]
> @dusty-nv Is there a way to link the jetson inference module to the latest python. I am using python 3.8

Hi @sprakashdash, add `3.8` to these lines:

* https://github.com/dusty-nv/jetson-inference/blob/6cf3b12f503d64903ca1e77d4c5474d9b1513a4c/python/CMakeLists.txt#L11
* https://github.com/dusty-nv/jetson-utils/blob/def4a04d023960781a44f9cd97fd1464093becf0/python/CMakeLists.txt#L11

Also make sure you have the dev libraries installed for python3.8 and numpy for 3.8

**Comment by Laowai01** [comment]
I had this issue and the problem was build the jetson inference repository without adding the path of cuda in .bashrc. adding path and doing cmake again solved the issue.

**Comment by CornelisKuijpers** [comment]
I had the same issue, issue was my mounted drive was in incorrect format I had to format it to EXT4 then the build was correct
