### ISSUE TITLE
How to download segnet pre-trained model

### ISSUE THREAD

**Issue by ArtlyStyles** [dusty-nv/jetson-inference#343]
In the "Hello AI tutorial" segnet, page, it said "In addition to the aerial model from this tutorial, the repo also includes pre-trained models on other segmentation datasets, including Cityscapes, SYNTHIA, and Pascal-VOC.". But I am not sure how to download pre-trained "Cityscapes" model. Can anyone help?

**Comment by dusty-nv** [comment]
See the python branch of the repo.  It has a tool which will download it for you.
________________________________

**Comment by ArtlyStyles** [comment]
Sorry, I could not find it. Could you point me the file to download the trained model with Cityscapes data?

**Comment by dusty-nv** [comment]
To clone the python branch:  `git clone -b python https://github.com/dusty-nv/jetson-inference`

To manually download the Cityscapes models, see [`https://github.com/dusty-nv/jetson-inference/releases`](https://github.com/dusty-nv/jetson-inference/releases)
