### ISSUE TITLE
Inference from different layers - feature extraction

### ISSUE THREAD

**Issue by Source82** [dusty-nv/jetson-inference#354]
Hi, 
Please how can one edit the imagenet classification sample code to output features from intermediate layers, i.e. instead of the class probabilities.
Thanks

**Comment by Source82** [comment]
solved by myself. Thanks

**Comment by deaffella** [comment]
> solved by myself. Thanks

hi! I have encountered the same problem and can't find a solution.
could you show me your solution to extract features from the intermediate layers?

**Comment by Sycarol** [comment]
Hi I have the same problem too, will you please share your solution?

**Comment by dusty-nv** [comment]
It would involve editing jetson-inference/c/imageNet.cpp to specify more output layers - like here:

https://github.com/dusty-nv/jetson-inference/blob/0fd4a76101be5c9af4723a9e8376018dfa462be4/c/imageNet.cpp#L138

There is another overload of tensorNet::LoadNetwork() to use that accepts an array of output layer names:

https://github.com/dusty-nv/jetson-inference/blob/0fd4a76101be5c9af4723a9e8376018dfa462be4/c/tensorNet.h#L237
