### ISSUE TITLE
jetson.utils.cudaToNumpy not working as expected 

### ISSUE THREAD

**Issue by Santhosh1509** [dusty-nv/jetson-inference#356]
[https://github.com/dusty-nv/jetson-utils/blob/master/python/examples/cuda-to-numpy.py#LC44](url)

    array = jetson.utils.cudaToNumpy(cuda_mem, opt.width, opt.height, opt.depth)

Try to save the image giving black image, so tried to plot the array getting converted using matplotlib

    plt.imshow(array)

It gave me a blank image with this in the terminal

> Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

Saw a solution [here](https://stackoverflow.com/questions/49643907/clipping-input-data-to-the-valid-range-for-imshow-with-rgb-data-0-1-for-floa#answer-51255361)

    plt.imshow((array * 255).astype(np.uint8))

This is the image i am able to get, which is wrong

![Figure_1](https://user-images.githubusercontent.com/50985246/60946206-42ab4880-a30b-11e9-8c99-a7c1ea59c907.png)

This is the image getting saved
![img_ssd_iv2_1](https://user-images.githubusercontent.com/50985246/60946129-02e46100-a30b-11e9-8ae1-3926de9a1ec2.jpg)

What is going wrong?

[Posted here also](https://github.com/dusty-nv/jetson-utils/issues/7)

**Comment by Santhosh1509** [comment]
My bad 

    array = jetson.utils.cudaToNumpy(img, width, height,4)

depth is always 4

**Comment by erivera1802** [comment]
Hi, 
could you tell me, what is img in your case?
I try to convert the output of camera.CaptureRGBA but I got an error. 
```
img, width, height = camera.CaptureRGBA()
numpyImg  = jetson.utils.cudaToNumpy(img,width,height,4)
```

**Comment by olelukoje** [comment]
@erivera1802, try this:
```
camera.CaptureRGBA(zeroCopy=1)
```

**Comment by erivera1802** [comment]
> 
> 
> @erivera1802, try this:
> 
> ```
> camera.CaptureRGBA(zeroCopy=1)
> ```

Thanks! it worked!

**Comment by jtiscione** [comment]
What does zeroCopy=1 mean?

**Comment by dusty-nv** [comment]
It means to use zeroCopy memory (mapped CPU/GPU memory) to store the image, instead of GPU-only memory

**Comment by HerrAskin** [comment]
Hi, all! I'm sorry, but I don't understand why I have to read an image from the cuda-memory (cudaToNumpy), cut out the area, and convert it back to the cuda (cudaFromNumpy)... Can't you just define the memory area to work with? The essence of the problem is that when the neural network is working, the entire frame is processed first, the object is detected, and then the neural network works only in this area... Converting to and from an array will take a very long time.

**Comment by HerrAskin** [comment]
Dastin, say me please! In https://github.com/dusty-nv/jetson-utils/tree/master/cuda there are cudaCrop files. Is there any way I can use them for my task? I'm working on a jetson AGX Xavier. If this is possible, we would like a small example of using it in python.
