### ISSUE TITLE
How to train googlenet or inception-v4 with transfering learning

### ISSUE THREAD

**Issue by Alphonses** [dusty-nv/jetson-inference#358]
Hi, @dusty-nv ,I have some trouble at Classifying Images with ImageNet
     I want to train googlenet or inception-v4 with transfering learning,but trapping in confusion  with right corresponding Custom Network.
   Can you give some samples or some tips,sincere thanks！

**Comment by Alphonses** [comment]
I have already done it.

**Comment by Darcyzh** [comment]
请问你是怎么解决的呀，学习一下😄。（你这头像不错😁）
