### ISSUE TITLE
Multi-class Object Detection Models trained with DIGITS??

### ISSUE THREAD

**Issue by vxgu86** [dusty-nv/jetson-inference#362]
how to do Multi-class Object Detection Models??
asking this question because I found training Multi-class Object Detection Models so difficult(maybe sth was wrong with my config) with DIGITS.
did I missing something, cause I could not even train a two-objects detection model effectively with DIGITS.

**Comment by agoila** [comment]
Please refer to similar posts [here](https://github.com/NVIDIA-AI-IOT/jetson-trashformers/wiki/Single-and-Multi-Class-Object-Detection) and [here](https://lesterlo.wordpress.com/2017/05/10/train-multiple-classes-in-detectnet/).

**Comment by vxgu86** [comment]
thanks

**Comment by vxgu86** [comment]
> Please refer to similar posts [here](https://github.com/NVIDIA-AI-IOT/jetson-trashformers/wiki/Single-and-Multi-Class-Object-Detection) and [here](https://lesterlo.wordpress.com/2017/05/10/train-multiple-classes-in-detectnet/).

does this make sense for the segmentation model？
