### ISSUE TITLE
C++ example code make error

### ISSUE THREAD

**Issue by darcyzhc** [dusty-nv/jetson-inference#364]
I'm doing [Hello AI world](https://github.com/dusty-nv/jetson-inference#hello-ai-world) step by step.
But when I do [Coding Your Own Image Recognition Program (C++)](https://github.com/dusty-nv/jetson-inference/blob/master/docs/imagenet-example-2.md#building-the-example) I'm stucked.
The `cmake .` output is OK as below(I've done this before):
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/nvidia/my-recognition

But when I run `make`, the error arose:
> nvidia@tegra-ubuntu:~/my-recognition$ make
[ 50%] Building CXX object CMakeFiles/my-recognition.dir/my-recognition.cpp.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:54,
                 from /usr/local/include/jetson-inference/tensorNet.h:30,
                 from /usr/local/include/jetson-inference/imageNet.h:27,
                 from /home/nvidia/my-recognition/my-recognition.cpp:2:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/local/include/jetson-inference/tensorNet.h:30:0,
                 from /usr/local/include/jetson-inference/imageNet.h:27,
                 from /home/nvidia/my-recognition/my-recognition.cpp:2:
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsHW::DimsHW()’:
/usr/include/aarch64-linux-gnu/NvInfer.h:210:29: error: ‘DimensionType’ is not a class or namespace
         type[0] = type[1] = DimensionType::kSPATIAL;
                             ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsHW::DimsHW(int, int)’:
/usr/include/aarch64-linux-gnu/NvInfer.h:222:29: error: ‘DimensionType’ is not a class or namespace
         type[0] = type[1] = DimensionType::kSPATIAL;
                             ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsCHW::DimsCHW()’:
/usr/include/aarch64-linux-gnu/NvInfer.h:299:19: error: ‘DimensionType’ is not a class or namespace
         type[0] = DimensionType::kCHANNEL;
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:300:29: error: ‘DimensionType’ is not a class or namespace
         type[1] = type[2] = DimensionType::kSPATIAL;
                             ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsCHW::DimsCHW(int, int, int)’:
/usr/include/aarch64-linux-gnu/NvInfer.h:313:19: error: ‘DimensionType’ is not a class or namespace
         type[0] = DimensionType::kCHANNEL;
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:314:29: error: ‘DimensionType’ is not a class or namespace
         type[1] = type[2] = DimensionType::kSPATIAL;
                             ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsNCHW::DimsNCHW()’:
/usr/include/aarch64-linux-gnu/NvInfer.h:407:19: error: ‘DimensionType’ is not a class or namespace
         type[0] = DimensionType::kINDEX;
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:408:19: error: ‘DimensionType’ is not a class or namespace
         type[1] = DimensionType::kCHANNEL;
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:409:29: error: ‘DimensionType’ is not a class or namespace
         type[2] = type[3] = DimensionType::kSPATIAL;
                             ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In constructor ‘nvinfer1::DimsNCHW::DimsNCHW(int, int, int, int)’:
/usr/include/aarch64-linux-gnu/NvInfer.h:423:19: error: ‘DimensionType’ is not a class or namespace
         type[0] = DimensionType::kINDEX;
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:424:19: error: ‘DimensionType’ is not a class or namespace
         type[1] = DimensionType::kCHANNEL;
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:425:29: error: ‘DimensionType’ is not a class or namespace
         type[2] = type[3] = DimensionType::kSPATIAL;
                             ^
/usr/include/aarch64-linux-gnu/NvInfer.h: At global scope:
/usr/include/aarch64-linux-gnu/NvInfer.h:498:5: error: ‘int64_t’ does not name a type
     int64_t count;      //!< The number of weights in the array.
     ^
/usr/include/aarch64-linux-gnu/NvInfer.h:1387:26: error: ‘uint32_t’ has not been declared
     virtual void setAxes(uint32_t axes) = 0;
                          ^
/usr/include/aarch64-linux-gnu/NvInfer.h:1394:13: error: ‘uint32_t’ does not name a type
     virtual uint32_t getAxes() const = 0;
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2147:13: error: ‘int32_t’ does not name a type
     virtual int32_t getLayerCount() const = 0; //< Get the layer count of the R
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2148:13: error: ‘int32_t’ does not name a type
     virtual int32_t getHiddenSize() const = 0; //< Get the hidden size of the R
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2149:13: error: ‘int32_t’ does not name a type
     virtual int32_t getMaxSeqLength() const = 0; //< Get the maximum sequence l
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2150:13: error: ‘int32_t’ does not name a type
     virtual int32_t getDataLength() const = 0; //< Get the maximum data length
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2335:12: error: use of enum ‘PluginFormat’ without previous declaration
 enum class PluginFormat: uint8_t
            ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2335:24: error: expected unqualified-id before ‘:’ token
 enum class PluginFormat: uint8_t
                        ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2343:20: error: ‘PluginFormat’ was not declared in this scope
 inline int EnumMax<PluginFormat>()
                    ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2343:12: error: template-id ‘EnumMax<<expression error> >’ for ‘int nvinfer1::EnumMax()’ does not match any template declaration
 inline int EnumMax<PluginFormat>()
            ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2481:48: error: ‘PluginFormat’ has not been declared
     virtual bool supportsFormat(DataType type, PluginFormat format) const = 0;
                                                ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2499:129: error: ‘PluginFormat’ has not been declared
 int nbInputs, const Dims* outputDims, int nbOutputs, DataType type, PluginForma
                                                                     ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2626:32: error: ‘uint32_t’ has not been declared
     virtual void setReduceAxes(uint32_t reduceAxes) = 0;
                                ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2633:13: error: ‘uint32_t’ does not name a type
     virtual uint32_t getReduceAxes() const = 0;
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2855:32: error: ‘uint32_t’ has not been declared
     virtual void setReduceAxes(uint32_t reduceAxes) = 0;
                                ^
/usr/include/aarch64-linux-gnu/NvInfer.h:2862:13: error: ‘uint32_t’ does not name a type
     virtual uint32_t getReduceAxes() const = 0;
             ^
/usr/include/aarch64-linux-gnu/NvInfer.h:3401:80: error: ‘uint32_t’ has not been declared
  IReduceLayer* addReduce(ITensor& input, ReduceOperation operation, uint32_t re
                                                                     ^
/usr/include/aarch64-linux-gnu/NvInfer.h:3427:74: error: ‘uint32_t’ has not been declared
 irtual ITopKLayer* addTopK(ITensor& input, TopKOperation op, int k, uint32_t re
                                                                     ^
/usr/include/aarch64-linux-gnu/NvInfer.h:3534:51: error: ‘int32_t’ has not been declared
     virtual IRNNv2Layer *addRNNv2(ITensor &input, int32_t layerCount, int32_t h
                                                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:3534:71: error: ‘int32_t’ has not been declared
   virtual IRNNv2Layer *addRNNv2(ITensor &input, int32_t layerCount, int32_t hid
                                                                     ^
/usr/include/aarch64-linux-gnu/NvInfer.h:3534:91: error: ‘int32_t’ has not been declared
 r *addRNNv2(ITensor &input, int32_t layerCount, int32_t hiddenSize, int32_t max
                                                                     ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In member function ‘virtual nvinfer1::CalibrationAlgoType nvinfer1::IInt8EntropyCalibrator::getAlgorithm()’:
/usr/include/aarch64-linux-gnu/NvInfer.h:3943:57: error: ‘CalibrationAlgoType’ is not a class or namespace
     virtual CalibrationAlgoType getAlgorithm() { return CalibrationAlgoType::kE
                                                         ^
/usr/include/aarch64-linux-gnu/NvInfer.h: In member function ‘virtual nvinfer1::CalibrationAlgoType nvinfer1::IInt8LegacyCalibrator::getAlgorithm()’:
/usr/include/aarch64-linux-gnu/NvInfer.h:3958:57: error: ‘CalibrationAlgoType’ is not a class or namespace
     virtual CalibrationAlgoType getAlgorithm() { return CalibrationAlgoType::kL
                                                         ^
In file included from /usr/local/include/jetson-inference/tensorNet.h:30:0,
                 from /usr/local/include/jetson-inference/imageNet.h:27,
                 from /home/nvidia/my-recognition/my-recognition.cpp:2:
/usr/include/aarch64-linux-gnu/NvInfer.h: At global scope:
/usr/include/aarch64-linux-gnu/NvInfer.h:4020:28: error: ‘allocate’ declared as a ‘virtual’ field
     virtual void* allocate(uint64_t size, uint64_t alignment, uint32_t flags) =
                            ^
/usr/include/aarch64-linux-gnu/NvInfer.h:4020:19: error: expected ‘;’ at end of member declaration
     virtual void* allocate(uint64_t size, uint64_t alignment, uint32_t flags) =
                   ^
/usr/include/aarch64-linux-gnu/NvInfer.h:4020:37: error: expected ‘)’ before ‘size’
     virtual void* allocate(uint64_t size, uint64_t alignment, uint32_t flags) =
                                     ^
In file included from /usr/local/include/jetson-inference/imageNet.h:27:0,
                 from /home/nvidia/my-recognition/my-recognition.cpp:2:
/usr/local/include/jetson-inference/tensorNet.h: In member function ‘virtual void tensorNet::Logger::log(nvinfer1::ILogger::Severity, const char*)’:
/usr/local/include/jetson-inference/tensorNet.h:405:20: error: ‘Severity’ is not a class or namespace
    if( severity != Severity::kINFO /*|| mEnableDebug*/ )
                    ^
CMakeFiles/my-recognition.dir/build.make:62: recipe for target 'CMakeFiles/my-recognition.dir/my-recognition.cpp.o' failed
make[2]: *** [CMakeFiles/my-recognition.dir/my-recognition.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/my-recognition.dir/all' failed
make[1]: *** [CMakeFiles/my-recognition.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have finished all the previous step, including `$ sudo make install` in [Compiling the Project](https://github.com/dusty-nv/jetson-inference/blob/python/docs/building-repo-2.md#compiling-the-project). 

My board system is Ubuntu 16.04 LTS aarch64, my board is Jetson TX2, and the version of JetPack I used is 3.3.

Could you give me a suggestion to solve this problem?  @dusty-nv 

More info:
> > nvidia@tegra-ubuntu:/usr/local/include$ ll
> total  16
> drwxr-xr-x  4    root  root 4096  Jul  15  19:54  ./
> drwxr-xr-x  11  root  root 4096  Jul  15  13:59  ../
> drwxr-xr-x  2    root  root 4096  Jul  15  20:37  jetson-inference/
> drwxr-xr-x  2    root  root 4096  Jul  15  20:37jetson-utils/

**Comment by dusty-nv** [comment]
Hi @Darcyzh , can you try adding this line of code to line 7 of your `my-recognition/CMakeLists.txt` file?

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wno-write-strings")`
