### ISSUE TITLE
Does this package support Caffe model only?

### ISSUE THREAD

**Issue by ghost** [dusty-nv/jetson-inference#371]
Does this package support tensorflow?

**Comment by dusty-nv** [comment]
It supports Caffe, ONNX, and TensorFlow UFF
________________________________

**Comment by ArtlyStyles** [comment]
Is this considered TensorFlow UFF? https://github.com/MaybeShewill-CV/lanenet-lane-detection

**Comment by ArtlyStyles** [comment]
@dusty-nv could you please let me know if tensorflow ckpt is UFF and can be used for this package? Or how can I convert ckpt to UFF?
