### ISSUE TITLE
Run another model outside this project in parallel

### ISSUE THREAD

**Issue by yichengye310** [dusty-nv/jetson-inference#381]
Hi, I am using detectNet-camera.py to detect objects. And I am using code in another project (https://github.com/AaronFan1992/jetson_nano_demo) to recognize faces in the frame using TensorFlow. Is it possible to run the two models in parallel?

Thank you!

**Comment by dusty-nv** [comment]
Yes, you could launch another thread to run your other model in parallel.  Or run them in a pipeline serially.
________________________________

**Comment by yeyicheng** [comment]
@dusty-nv Could you show me some code example please? I am new to this. Thank you.

**Comment by dusty-nv** [comment]
I dont have one of that specific scenario with TF.  What I would start with, is just call the jetson.inference model and your TensorFlow model from the same script (same thread). Both utilize the GPU and likely will get serialized in the end anyways (although if there is CPU processing in TensorFlow model, that could benefit from running in a separate thread).  So you could start with them both in a single thread (same script).
________________________________

**Comment by yeyicheng** [comment]
@dusty-nv I tried to add the TensorFlow detection code right before `display.RenderOnce(img, width, height)`, but it does not seem to work. The system freezed and I have to restart.
```
while display.IsOpen():
	# capture the image
	img, width, height = camera.CaptureRGBA()

	# detect objects in the image (with overlay)
	detections = net.Detect(img, width, height)

	# print the detections
	print("detected {:d} objects in image".format(len(detections)))

	for detection in detections:
		print(detection)

	# render the image
	display.RenderOnce(img, width, height)

	# update the title bar
	display.SetTitle("{:s} | Network {:.0f} FPS".format(opt.network, 1000.0 / net.GetNetworkTime()))

	# synchronize with the GPU
	if len(detections) > 0:
		jetson.utils.cudaDeviceSynchronize()

	# print out performance info
	net.PrintProfilerTimes()
```

**Comment by yeyicheng** [comment]
Actually I want to detect objects and faces in one window. Anyone can give an example?
