### ISSUE TITLE
Jetson nano - save video with OpenCV (python)

### ISSUE THREAD

**Issue by SlickJackson** [dusty-nv/jetson-inference#390]
Hello and a nice evening,

I tried to save a stream of images with 

`fourcc = cv2.VideoWriter_fourcc(*'XVID')`
`writerX = cv2.VideoWriter('output.avi',fourcc, 8, (hight, width))`

...but instead of using :
`cap = cv2.VideoCapture(0)`
`writerX.write(cap)`

I tried to use the streamed image from:
`img, width, height = camera.CaptureRGBA(zeroCopy=1)`
`writerX.write(img)`
...it seems not to be the right format. I get the following error:
TypeError: Expected cv::UMat for argument 'image'

It is just my aim to save not only a picture, but a video of x seconds if a special event is happening (classified by ResNet)

...eventually someone has an answer to this Problem. I could not find any solution.

Thanks!

**Comment by yilmazmuhammed** [comment]
Solved directly [here](https://forums.developer.nvidia.com/t/how-to-save-video-with-2-camera-pi-with-jeston-nano/145882) with nvarguscamerasrc.
https://forums.developer.nvidia.com/t/how-to-save-video-with-2-camera-pi-with-jeston-nano/145882
