### ISSUE TITLE
Using udpsink or appsink with for detectnet-camera

### ISSUE THREAD

**Issue by aviontics** [dusty-nv/jetson-inference#393]
Unsure this is an issue or support request.

I would like to be able to add appsink or udpsink for the gstcamera in ./detectnet-camera so I can stream data to udp port.

Where can I make this change. I looked into the gstCamera files. There were some clues but unsure how to make it work. 

Please help!!!!

**Comment by dusty-nv** [comment]
Do you want to do the inferencing also, or do you just want to stream a camera over the network?   See the L4T Accelerated Gstreamer User Guide for example camera pipelines that you can run independently.

**Comment by aviontics** [comment]
Dusty-nv
Thanks for the fast response. 

I want to use it with detectnet-camera code, which I was able to make work with 2 cameras and successfully converted data to opencv mat, for further rprocessing.

I want to be able to stream using udpsink/appsink after processing the image data.

**Comment by aviontics** [comment]
Got it working with video writer. 

VideoWriter videoout("appsrc ! videoconvert ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 ! jpegenc ! rtpjpegpay ! udpsink host=192.168.0.5 port=5600",CAP_GSTREAMER,0,30,Size(640,480),true);

Seems to automatically get data from the opened camera from gstCamera.

Next is to output opencv transformed image instead of just feed from camera.

**Comment by dusty-nv** [comment]
OK, glad you got it working.  Thanks Cromwell.
________________________________
