### ISSUE TITLE
tensorNet::LoadNetwork Seg Faults

### ISSUE THREAD

**Issue by jetsonhacks** [dusty-nv/jetson-inference#4]
When running the imagenet-camera example, the program seg faults. It appears to be in the call:

imageNet.cpp
imageNet::init -
   tensorNet::LoadNetwork

Where the LoadNetwork function is called with NULL. Replacing the NULL with an empty string ("")  allows the program to run.

Configuration:
L4T 24.2
CUDA 8.0
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.2)

**Comment by dusty-nv** [comment]
Thanks Jim!   I just fixed the issue in commit [09f2a48](https://github.com/dusty-nv/jetson-inference/commit/09f2a48e7dc9f3c225b41474df691597c1815215).
