### ISSUE TITLE
Does this repo support jet pack 3.1 with TensorRT 2.1, cuDNN 6.0?

### ISSUE THREAD

**Issue by ArtlyStyles** [dusty-nv/jetson-inference#405]

**Comment by dusty-nv** [comment]
Hi Artly, try the L4T-R28.1 branch:  https://github.com/dusty-nv/jetson-inference/tree/L4T-R28.1

**Comment by ArtlyStyles** [comment]
Is there an example about how to use Tensorflow uff model with this repo?

**Comment by dusty-nv** [comment]
I do not believe TensorRT 2.1 supported TensorFlow UFF models, you would need to upgrade to newer version.
