### ISSUE TITLE
use tensorrt to accelerate siamRPN network

### ISSUE THREAD

**Issue by JensenHJS** [dusty-nv/jetson-inference#407]
Whether tensorrt can accelerate siamRPN network？SiamRPN network is a target tracking algorithm. It includes a Alexnet subnetwork and a RPN subnetwork.  There is only a fewer layers of SiamRPN

**Comment by dusty-nv** [comment]
Hi @JensenHJS, you would want to check if all the layers are supported by TensorRT:

https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#layers-matrix

**Comment by GOBish** [comment]
Hi - I am also trying to get a Siam network for tracking running on the Jetson Xavier Nx. So far I have only been able to run it with pytorch and it runs fairly slowly, only ~4 FPS, even with 99% GPU load. Any suggestions?

**Comment by JensenHJS** [comment]
No,I don't solve this problem. I just start learn how to use trt When I raise this question.  I know that somebody has realized trt to accelerate siamrpn. But maybe it is difficult.  I run siamrpn with pytorch in the tx2，it is about 25 fps. maybe you can use other lightweight backbone ， backbone of alexnet

**Comment by GOBish** [comment]
Do you have a link to the code you used? I tried SiamRPN with pytorch and am only getting framerates of under 8 FPS.
thank you.

**Comment by JensenHJS** [comment]
https://github.com/STVIR/pysot

**Comment by GOBish** [comment]
I am getting ~14-18FPS using SiamRPN with the alexnet backbone on a Xavier nx, which is dissapointing. 
Perhaps it is the webcam.

**Comment by ShirGrinblat** [comment]
@JensenHJS @GOBish  Any solution? I'm trying to convert [https://github.com/STVIR/pysot](url) into TensorRT without any success.
