### ISSUE TITLE
error hwile loading shared libraries

### ISSUE THREAD

**Issue by hunshencinao** [dusty-nv/jetson-inference#408]
![微信图片_20190906075933](https://user-images.githubusercontent.com/52437444/64391763-8ce74680-d07c-11e9-83af-b61f9a629de4.jpg)
help!!!

**Comment by dusty-nv** [comment]
Try with a ./ in front of the imagenet-console command, or try `sudo ldconfig` first. Also could try `sudo make install` if you have not.

**Comment by hunshencinao** [comment]
> Try with a ./ in front of the imagenet-console command, or try `sudo ldconfig` first. Also could try `sudo make install` if you have not.

I have solved it by add a ./ ,Thanks!
