### ISSUE TITLE
Not an issue, more a question

### ISSUE THREAD

**Issue by bobogumizelka** [dusty-nv/jetson-inference#411]
In 'Re-training on Cat/Dog Dataset imagenet-console.py example is used with parameters:

imagenet-console.py --model=cat_dog/resnet18.onnx --input_blob=input_0 --output_blob=output_0 --labels=$DATASET/labels.txt $DATASET/test/cat/01.jpg cat.jpg

How is that possible, if there are no 'model', 'input_blob', 'output_blob' in imagenet_console scrip: https://github.com/dusty-nv/jetson-inference/blob/master/python/examples/imagenet-console.py?

**Comment by dusty-nv** [comment]
Hi @bobogumizelka, note that the command line arguments are also passed to the `imageNet` class when it is created:

https://github.com/dusty-nv/jetson-inference/blob/99ecf1f41b47b6d4f8fb848963f4c6517cfa82c3/python/examples/imagenet-console.py#L53

These extra command line arguments are parsed inside of `imageNet` implementation for consistency and simplicity of the programs across Python and C++.

**Comment by bobogumizelka** [comment]
Thank you very much for a quick answer! I checked it out, and now it's all clear :)

**Comment by bobogumizelka** [comment]
Now I'm loading the detectNet like this: det = jetson.inference.detectNet('facenet') 
Is there a way to check is the net is loaded properly? When I pass an image (loaded with opencv, converted with cudaFromNumpy()) I get an exception:
Exception: jetson.inference -- detectNet.Detect() encountered an error classifying the image
Same image passed to:
net = jetson.inference.imageNet('googlenet',
                                ['--model=resnet18.onnx', 
                                 '--input_blob=input_0', 
                                 '--output_blob=output_0', 
                                 '--labels=labels.txt'])
works fine. That's why I would like to check if the network is loaded properly.

**Comment by dusty-nv** [comment]
The program would output any errors loading the detectNet model at the time you instantiated the detectNet object.   Can you post your code and terminal log?

You should be passing a 4-channel RGBA image from OpenCV to `cudaFromNumpy()`.  `cudaFromNumpy()` doesn't change the number of dimensions (although it will convert it to float), and detectNet expects a 4-channel image.

**Comment by bobogumizelka** [comment]
Yes, it was 3-channel image problem. Thanks!

**Comment by MichiBe91** [comment]
Hello,

I have the problem that I don't know how to load a custom trained model (like in the tutorial videos: Jetson AI Fundamentals - S3E5) with a python script. With using the flags in the console it is no problem. But how can I write the flags directly in a script. Please See my example below:

`
import jetson.inference
import jetson.utils

net = jetson.inference.detectNet("ssd-mobilenet.onnx", ["model=pathToModel/ssd-mobilenet.onnx", "labels=pathToLabels/labels.txt", "input-blob=input_0", "output-cvg=scores", "output-bbox=boxes"])

camera = jetson.utils.videoSource("csi://0")

display = jetson.utils.videoOutput()

while True:
    img = camera.Capture()
    detections = net.Detect(img)
    display.Render(img)
    display.SetStatus("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))`

I hope somebody can help me. Thank you :)

**Comment by MichiBe91** [comment]
Hello, 

I found a solution:

`net = jetson.inference.detectNet(argv=["--model=pathToModel/ssd-mobilenet.onnx", "--labels=pathToLabels/labels.txt", "--input-blob=input_0", "--output-cvg=scores", "--output-bbox=boxes"], threshold=0.5)`

**Comment by luispaulino1989** [comment]
> Hello,
> 
> I found a solution:
> 
> `net = jetson.inference.detectNet(argv=["--model=pathToModel/ssd-mobilenet.onnx", "--labels=pathToLabels/labels.txt", "--input-blob=input_0", "--output-cvg=scores", "--output-bbox=boxes"], threshold=0.5)`

Hello,

Im trying to do the same, but not work:

net = jetson.inference.detectNet(argv=["--model=/home/luis/jetson-inference/python/training/detection/ssd/models/frutas/ssd-mobilenet.onnx", "--labels=/home/luis/jetson-inference/python/training/detection/ssd/models/frutas/labels.txt", "--input-blob=input_0", "--output-cvg=scores", "--output-bbox=boxes"], threshold=0.5)

Exception: jetson.inference -- detectNet failed to load network

Do  you know what happen?

This model work good in the console.

**Comment by MichiBe91** [comment]
Mhh - strange. Maybe you could try it with double slash (//). You could also try to load the model from the same folder as your script. So you can be sure that there is no mistake in the path.

**Comment by Lyns01** [comment]
Hi @MichiBe91, I had the same doubt and your answer helped me thank you.

**Comment by AlperGith** [comment]
@Lyns01 Hey, i need your help

**Comment by AlperGith** [comment]
net = jetson.inference.detectNet(argv=["--model=/jetson-inference/python/training/detection/ssd/models/Khas/ssd-mobilenet.onnx","--labels=/jetson-inference/python/training/detection/ssd/models/Khas/labels.txt","--input-blob=input_0","--output-cvg=scores","--output-bbox=boxes"],threshold=0.5) I solved this issue by just strating path from /jetson-inference/...
