### ISSUE TITLE
segnet-camera is working but doesn't do any segmentation

### ISSUE THREAD

**Issue by brash6** [dusty-nv/jetson-inference#412]
Hi, 
When I run segnet-console whith FCN-Alexnet-Cityscapes-SD or FCN-Alexnet-Pascal-VOC, it works fine. 
But when I run segnet-camera with exactly the same parameters, the live stream windows appears and work but without doing any segmentation of the environment. 

Furthermore, I have to run segnet-console and segnet-camera without this line : `--output_blob=score_fr`. Because when I keep this line, I have the following error :

 `segNet -- loading segmentation network model from:
       -- prototxt:   /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/deploy.prototxt
       -- model:      /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/snapshot_iter_2756640.caffemodel
       -- labels:     /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/cityscapes-labels.txt
       -- colors:     /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/cityscapes-deploy-colors.txt
       -- input_blob  'data'
       -- output_blob 'score_fr'
       -- batch_size  1

[TRT]   TensorRT version 5.0.6
[TRT]   loading NVIDIA plugins...
[TRT]   completed loading NVIDIA plugins.
[TRT]   detected model format - caffe  (extension '.caffemodel')
[TRT]   desired precision specified for GPU: FASTEST
[TRT]   requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]   native precisions detected for GPU:  FP32, FP16
[TRT]   selecting fastest native precision for GPU:  FP16
[TRT]   attempting to open engine cache file /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/snapshot_iter_2756640.caffemodel.1.1.GPU.FP16.engine
[TRT]   loading network profile from engine cache... /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/snapshot_iter_2756640.caffemodel.1.1.GPU.FP16.engine
[TRT]   device GPU, /home/wifibot/jetson-inference/data/networks/FCN-Alexnet-Cityscapes-SD/snapshot_iter_2756640.caffemodel loaded
[TRT]   device GPU, CUDA engine context initialized with 2 bindings
[TRT]   binding -- index   0
               -- name    'data'
               -- type    FP32
               -- in/out  INPUT
               -- # dims  3
               -- dim #0  3 (CHANNEL)
               -- dim #1  512 (SPATIAL)
               -- dim #2  1024 (SPATIAL)
[TRT]   binding -- index   1
               -- name    'score_fr_21classes'
               -- type    FP32
               -- in/out  OUTPUT
               -- # dims  3
               -- dim #0  21 (CHANNEL)
               -- dim #1  10 (SPATIAL)
               -- dim #2  26 (SPATIAL)
[TRT]   binding to input 0 data  binding index:  0
[TRT]   binding to input 0 data  dims (b=1 c=3 h=512 w=1024) size=6291456
[TRT]   binding to output 0 score_fr  binding index:  -1
[TRT]   binding to output 0 score_fr  dims (b=1 c=0 h=0 w=0) size=0
[TRT]   failed to alloc CUDA mapped memory for tensor output, 0 bytes
segNet -- failed to initialize.
segnet-console:   failed to initialize segnet
`
Do you have any idea of why segnet-camera doesn't do segmentation ?

**Comment by dusty-nv** [comment]
Hi @brash6 , I have recently been updating the models for segNet, can you check out the `pytorch` branch of `jetson-inference`?

https://github.com/dusty-nv/jetson-inference/tree/pytorch

See the new built-in models based on FCN-ResNet18 which provide better performance.  They should also be working with the camera program.
