### ISSUE TITLE
Python example using OpenCV image

### ISSUE THREAD

**Issue by rosshemsley** [dusty-nv/jetson-inference#413]
Are there any examples using Python to feed OpenCV images instead of reading files?

Context is that I have a program receiving a stream of OpenCV images (in a Ros node) and I would like to run detection.

Ideally, re-using as many resources between calls as possible.

Currently the API that only takes files means I have to round-trip to the disk, which is quite expensive.

**Comment by alexabstreiter** [comment]
First, you need to convert your image to RGBA. So if your image input is and numpy array and in RGB you can do this:
input_image = cv2.cvtColor(input, cv2.COLOR_RGB2RGBA).astype(np.float32)

Next, we have to move the image to CUDA:
input_image = jetson.utils.cudaFromNumpy(input_image)

After that, the prediction works:
predictions = net.Detect(input_image, input.shape[1], input.shape[0])

**Comment by Totemi1324** [comment]
And how to convert it back to Numpy-image?

**Comment by alexabstreiter** [comment]
You can use `jetson.utils.cudaToNumpy` for that.

**Comment by Kmarconi** [comment]
Hi, I was wondering if you had encountered any issues with the cudaToNumpy function ? When i'm using it to display my image with detections on it, I always have a white image with some blue or purple shape on it... Any guess ?

Regards :)

**Comment by Totemi1324** [comment]
Make sure you convert your images into the correct color scheme and data type because CUDA handles it differently (RGBA with float32).
In my code, I want to analyze images taken by OpenCV (which are in BGR) so I need to write:
```
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA).astype(np.float32)
img = jetson.utils.cudaFromNumpy(img)
detections = net.Detect(img, 1280, 720)
img = jetson.utils.cudaToNumpy(img, 1280, 720, 4)
img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB).astype(np.uint8)
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
```
Hope this helps

**Comment by Kmarconi** [comment]
Thanks, worked as I wanted :)

**Comment by tlhcelik** [comment]
> Make sure you convert your images into the correct color scheme and data type because CUDA handles it differently (RGBA with float32).
> In my code, I want to analyze images taken by OpenCV (which are in BGR) so I need to write:
> 
> ```
> img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
> img = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA).astype(np.float32)
> img = jetson.utils.cudaFromNumpy(img)
> detections = net.Detect(img, 1280, 720)
> img = jetson.utils.cudaToNumpy(img, 1280, 720, 4)
> img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB).astype(np.uint8)
> img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
> ```
> 
> Not worked in my project

**Comment by Totemi1324** [comment]
@tlhcelik Could you please specify what problem you are encountering? Then perhaps we can give you some help.
