### ISSUE TITLE
Fresh install has no LD_LIBRARY_PATH set

### ISSUE THREAD

**Issue by JetForMe** [dusty-nv/jetson-inference#416]
I just installed the latest (as of this writing) jetson nano OS on an SD card and booted my Nano. I then came here to try to find a demo to run and went through the steps for [Hello AI World](https://github.com/dusty-nv/jetson-inference). Upon completion, I tried running a few of the installed apps listed in the `build/examples` directory. They were unable to load due to being unable to find `libjetson-utils.so`, which I verified was installed in `/usr/local/lib`.

Setting `LD_LIBRARY_PATH` to `/usr/local/lib` seems to have fixed this issue, but perhaps your disk image should have that set already (or your build instructions should mention that). Thanks!

**Comment by dusty-nv** [comment]
sudo ldconfig can also do the trick, which is already supposed to be run during make install.  I will add a note to the docs, thanks!
________________________________
