### ISSUE TITLE
detectnet-console --network

### ISSUE THREAD

**Issue by alanmcivor1959** [dusty-nv/jetson-inference#418]
If you run detectnet-console in the jetson-inference/build/aarch64/bin/ with a --network argument it works fine. If you run it in another directory it fails with errors like this

[TRT]   binding to output 1 bboxes  dims (b=1 c=4 h=28 w=28) size=12544
device GPU, /home/alan/hello_ai_world/jetson-inference/build/aarch64/bin/networks/facenet-120/snapshot_iter_24000.caffemodel initialized.
detectNet -- number object classes:   1
detectNet -- maximum bounding boxes:  784
detectNet -- loaded 1 class info entries
detectNet -- number of object classes:  1
[image] failed to find file 'facenet'
failed to load image 'facenet'

The above is on a Jetson TX2

**Comment by dusty-nv** [comment]
Can you try doing 'sudo make install' and then running the program without specifying a path (i.e. just detectnet-console <args>)
________________________________

**Comment by alanmcivor1959** [comment]
I did a 'make install' and tried again without the path. The result was exactly the same.

**Comment by dusty-nv** [comment]
Can you provide the command line you are using?
________________________________

**Comment by dslarm** [comment]
Hi - this never worked, no matter which directory you used.
CommandLine::getPosition doesn't increment i again when removing the first (--network) argument (or any argument..) - it should.

**Comment by dusty-nv** [comment]
Can you try using `--network=pednet` instead of `--network pednet`?

**Comment by omartin2010** [comment]
I just hit the same issue, and the same fix works. I'm not sure why it makes a difference, as I've used argparse many times and never used '=' signs with it...
