### ISSUE TITLE
jetson.utils.gstCamera.captureRGBA fails on built-in TX2 camera

### ISSUE THREAD

**Issue by AGenchev** [dusty-nv/jetson-inference#423]
Here there's example how to build cam recognition with python, the source:
```
import jetson.inference
import jetson.utils

net = jetson.inference.detectNet("ssd-mobilenet-v2", threshold=0.5)
camera = jetson.utils.gstCamera(1280, 720, "/dev/video0")  # using V4L2
display = jetson.utils.glDisplay()

while display.IsOpen():
        img, width, height = camera.CaptureRGBA()
```
This fails on JetsonTX2 Ubuntu18 updated to the last Jetpack, etc
The problem is in the gst filters:
```
[gstreamer] gstCamera onEOS
[gstreamer] gstreamer v4l2src0 ERROR Internal data stream error.
[gstreamer] gstreamer Debugging info: gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
```

**Comment by dusty-nv** [comment]
Can you try changing "/dev/video0" to "0"?
________________________________

**Comment by AGenchev** [comment]
Ya so quisk !!!! 
Yes, it works now :-) Many thanks !

**Comment by dusty-nv** [comment]
No problem - glad you got it working.  BTW, using "0" means to use the first onboard CSI camera interface instead of V4L2.
________________________________

**Comment by AGenchev** [comment]
Oh, now I understand - we can connect up to 6 CSI cameras there. 
The image of the built-in one is flipped though. I could get it straight with `! nvvidconv flip-method=0 ! ` converter filter in the g-streamer pipeline. If we could do this in utils.gstCamera would be nice also.

**Comment by dusty-nv** [comment]
There is the flip-method set in gstCamera.cpp source file, you just need to change it there and recompile and then do sudo make install again.
________________________________

**Comment by AGenchev** [comment]
thanks, I saw it:
```
  if NV_TENSORRT_MAJOR > 1 && NV_TENSORRT_MAJOR < 5      // if JetPack 3.1-3.3 (different flip-method)
        const int flipMethod = 0;                       // Xavier (w/TRT5) camera is mounted inverted
  #else
        const int flipMethod = 2;
  #endif  
```
but how could you know I can deal with C++ ?!
