### ISSUE TITLE
How to use detectnet-camera.py with pre-built custom Onnx model?

### ISSUE THREAD

**Issue by Tylersuard** [dusty-nv/jetson-inference#433]
Hello!  I really enjoy your tutorials, especially the one about re-training a neural network.  I had no idea it was that easy!

I trained my own model using a separate software.  I exported that model in Tensorflow, Onnx, and Tensorflow Lite format.  I'm unsure how to go about using one of these models with the detectnet-camera.py file, as all of the --network options have no file extension.  How would I do this?

Thank you!

**Comment by dusty-nv** [comment]
Hi Tyler, glad you enjoyed it!

The first thing to test, would be if TensorRT can load your ONNX model.  You can easily test that with the trt-exec tool, found in /usr/src/tensorrt/bin

If it loads, you would need to modify detectNet.cpp to perform the needed pre-processing (generally applying mean subtraction, std deviation, and CHW format - the same pre-processing as done during training / validation). Also will need the post-processing code for interpreting the output layers.
________________________________

**Comment by Tylersuard** [comment]
Ok great!  I will test the model as suggested.  However, I created the model using Azure Custom Vision, which does everything automatically and I have no idea what preprocessing or post-processing was applied to the model. Any recommendations for me there?

I’m basically just hoping to use my exported model on the Nano with 20fps inference speed, like in the demos. Thank you!
