### ISSUE TITLE
detectnet_camera what(): CHECK failed: (index) < (current_size_): Aborted (core dumped)

### ISSUE THREAD

**Issue by pacejohn** [dusty-nv/jetson-inference#436]
Hello,

I have trained a caffe object detection model using a different software (IBM Power AI Vision).  When I try to run the following:

./detectnet-camera --model /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel --prototxt /home/pace/jetson-inference/data/networks/PAIV/test.prototxt --class_labels /home/pace/jetson-inference/data/networks/PAIV/classname.txt --camera=/dev/video0

I get the following error:

[TRT]   attempting to open engine cache file /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel.1.1.GPU.FP16.engine
[TRT]   cache file not found, profiling network model on device GPU
[TRT]   device GPU, loading /home/pace/jetson-inference/data/networks/PAIV/test.prototxt /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel
[libprotobuf FATAL /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/externals/protobuf/aarch64/10.0/include/google/protobuf/repeated_field.h:1078] CHECK failed: (index) < (current_size_):
terminate called after throwing an instance of 'google_private::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_):
Aborted (core dumped)

I never creates the .engine file like it does with the other models the first time I run them.  For example when I first ran DetectNet-COCO-Dog, it created snapshot_iter_38600.caffemodel.1.1.GPU.FP16.engine.  So I'm guessing the error occurs when converting the model into TensorRT format, so there is something wrong with the caffe model that PAIV exported.  I do not know how to find the information, though, since the error is pretty vague.  I'm not sure where error log files are located or I would look at them.  

I can paste in any of the files you may need or put them in Dropbox if that would help.   The full output is below.

Thanks in advance.

pace@pace-jetson:~/jetson-inference/build/aarch64/bin$ ./detectnet-camera --model /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel --prototxt /home/pace/jetson-inference/data/networks/PAIV/test.prototxt --class_labels /home/pace/jetson-inference/data/networks/PAIV/classname.txt --camera=/dev/video0
[gstreamer] initialized gstreamer, version 1.14.5.0
[gstreamer] gstCamera attempting to initialize with GST_SOURCE_NVARGUS, camera /dev/video0
[gstreamer] gstCamera pipeline string:
v4l2src device=/dev/video0 ! video/x-raw, width=(int)1280, height=(int)720, format=YUY2 ! videoconvert ! video/x-raw, format=RGB ! videoconvert !appsink name=mysink
[gstreamer] gstCamera successfully initialized with GST_SOURCE_V4L2, camera /dev/video0

detectnet-camera:  successfully initialized camera device
    width:  1280
   height:  720
    depth:  24 (bpp)

detectNet -- loading detection network model from:
          -- prototxt     /home/pace/jetson-inference/data/networks/PAIV/test.prototxt
          -- model        /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel
          -- input_blob   'data'
          -- output_cvg   'coverage'
          -- output_bbox  'bboxes'
          -- mean_pixel   0.000000
          -- mean_binary  NULL
          -- class_labels /home/pace/jetson-inference/data/networks/PAIV/classname.txt
          -- threshold    0.500000
          -- batch_size   1

[TRT]   TensorRT version 5.1.6
[TRT]   loading NVIDIA plugins...
[TRT]   Plugin Creator registration succeeded - GridAnchor_TRT
[TRT]   Plugin Creator registration succeeded - NMS_TRT
[TRT]   Plugin Creator registration succeeded - Reorg_TRT
[TRT]   Plugin Creator registration succeeded - Region_TRT
[TRT]   Plugin Creator registration succeeded - Clip_TRT
[TRT]   Plugin Creator registration succeeded - LReLU_TRT
[TRT]   Plugin Creator registration succeeded - PriorBox_TRT
[TRT]   Plugin Creator registration succeeded - Normalize_TRT
[TRT]   Plugin Creator registration succeeded - RPROI_TRT
[TRT]   Plugin Creator registration succeeded - BatchedNMS_TRT
[TRT]   completed loading NVIDIA plugins.
[TRT]   detected model format - caffe  (extension '.caffemodel')
[TRT]   desired precision specified for GPU: FASTEST
[TRT]   requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]   native precisions detected for GPU:  FP32, FP16
[TRT]   selecting fastest native precision for GPU:  FP16
[TRT]   attempting to open engine cache file /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel.1.1.GPU.FP16.engine
[TRT]   cache file not found, profiling network model on device GPU
[TRT]   device GPU, loading /home/pace/jetson-inference/data/networks/PAIV/test.prototxt /home/pace/jetson-inference/data/networks/PAIV/23ba8fbe-b645-42cc-b551-e16d98e5debc.caffemodel
[libprotobuf FATAL /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/externals/protobuf/aarch64/10.0/include/google/protobuf/repeated_field.h:1078] CHECK failed: (index) < (current_size_):
terminate called after throwing an instance of 'google_private::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_):
Aborted (core dumped)

**Comment by dusty-nv** [comment]
You could try running the model with trt-exec first to test that TensorRT is able to load the model.  It can be found under /usr/src/tensorrt/bin
________________________________

**Comment by pacejohn** [comment]
Same error using trt-exec.  I'll keep investigating on my end.  Let me know if you think of anything else.
