### ISSUE TITLE
Running the Live Camera Recognition Demo (Broken)

### ISSUE THREAD

**Issue by callen5914** [dusty-nv/jetson-inference#446]
I attempted to follow this guide and I get an error. The camera module seems to fail and the terminal hangs. I am running the latest JetPack and cloned the latest of this repo. I have zero experience with the TX2 at this point so I am merely following the guides.

What sort of methods can I use to provide valuable debug data?

Cheers

**Comment by Anthony-Jacques** [comment]
I had similar behaviour when I accidentally omitted the camera parameters - by default it uses the MIPI camera, but I guess you don't have anything connected there? I'm guessing you need --camera=/dev/video0  (and correct width/height parameters for your camera), since this fixed it for me.
