### ISSUE TITLE
download-models.sh does not download Inception v4

### ISSUE THREAD

**Issue by Anthony-Jacques** [dusty-nv/jetson-inference#448]
If you use the download-models.sh script, you cannot download the Inception v4 model by selecting option 11.

I believe this is because of a copy+paste error in the case statement which means it will get installed with option 8.

See https://github.com/dusty-nv/jetson-inference/blob/87b5a8814a60e860709b35f3f774907c249db081/tools/download-models.sh#L690

**Comment by ST0RMTiger** [comment]
You are right, thank you! Please edit file and update the code in the repository (I'm brand new to github : ))
