### ISSUE TITLE
trained custom SSD-Inception-v2 in tf, how to get it in uff model and deploy on jetson nano

### ISSUE THREAD

**Issue by vxgu86** [dusty-nv/jetson-inference#450]
trained custom SSD-Inception-v2 in tf,  the model format is not uff, how to convert this?
get it in uff model and deploy on jetson nano

**Comment by revrr** [comment]
train a mobilenet or inceptionV2 model using tensorflow 1.13.1 and then follow this repo to convert to UFF

https://github.com/AastaNV/TRT_object_detection

after that I just replace the .uff model at /usr/local/bin/networks/SSD-Mobilenet-v2
make sure to delete the old .uff.1.1.GPU.FP16.engine
