### ISSUE TITLE
DetectNet COCO-Dog Train Example doesnt draws all bounding boxes

### ISSUE THREAD

**Issue by bronstein87** [dusty-nv/jetson-inference#464]
Hello, i'm new in digits and deep learning.I have learned detectnet to detect dogs according jetson-inference guide and then i saw that it doesn't find all bounding boxes on test images with few dogs. But as i can see from coverage and bbox visualization it can do that (look at pictures). What i'm doing wrong? Probably i should change some threshold, but where?
![Снимок экрана от 2019-12-12 11-45-28](https://user-images.githubusercontent.com/17082585/70713016-33835900-1cf6-11ea-9a63-0bc43c563b7a.png)
![Снимок экрана от 2019-12-12 11-45-08](https://user-images.githubusercontent.com/17082585/70713026-38480d00-1cf6-11ea-9f9f-0baf1145935d.png)
![Снимок экрана от 2019-12-12 11-48-09](https://user-images.githubusercontent.com/17082585/70713033-3b42fd80-1cf6-11ea-83d0-5e2eb82f6960.png)
![Снимок экрана от 2019-12-12 11-48-28](https://user-images.githubusercontent.com/17082585/70713038-3da55780-1cf6-11ea-988f-4cd20638e6aa.png)

**Comment by dusty-nv** [comment]
Hi @bronstein87 , I'm not sure how to change the threshold in DIGITS, but the detectnet-console and detectnet-camera programs have a --threshold argument which you can set from the command line (the default threshold being 0.5)
