### ISSUE TITLE
Does this repo supports Jestson 4.2?

### ISSUE THREAD

**Issue by SusmithaGadagottu** [dusty-nv/jetson-inference#465]
Hi,

I have executed make command on this package and received below error. There was no problem with CMake. Error is seen only with make.
I am running this on TX2 with Jetson 4.2 version. Does it support Jetson 4.2?
Do you know any applications similar to this one that I can run on Jetson 4.2?

[ 33%] Linking CXX shared library ../aarch64/lib/libjetson-utils.so
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
utils/CMakeFiles/jetson-utils.dir/build.make:741: recipe for target 'aarch64/lib/libjetson-utils.so' failed
make[2]: *** [aarch64/lib/libjetson-utils.so] Error 1
CMakeFiles/Makefile2:854: recipe for target 'utils/CMakeFiles/jetson-utils.dir/all' failed
make[1]: *** [utils/CMakeFiles/jetson-utils.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Thanks
Susmitha

**Comment by dusty-nv** [comment]
Hi @SusmithaGadagottu, yes it should build on JetPack 4.2.  It is possible that your OpenGL libraries got reconfigured from a previous package.  Can you check your symlinks by running the command below?

```bash
$ ls -ll /usr/lib/aarch64-linux-gnu/libGL.so*
lrwxrwxrwx 1 root root     14 May 10  2019 /usr/lib/aarch64-linux-gnu/libGL.so -> libGL.so.1.0.0
lrwxrwxrwx 1 root root     14 May 10  2019 /usr/lib/aarch64-linux-gnu/libGL.so.1 -> libGL.so.1.0.0
-rw-r--r-- 1 root root 972968 May 10  2019 /usr/lib/aarch64-linux-gnu/libGL.so.1.0.0
```
