### ISSUE TITLE
[GIE] Error parsing layer type Deconvolution index 379 

### ISSUE THREAD

**Issue by Jia-HongHenryLee** [dusty-nv/jetson-inference#47]
Can everyone help me how to solve this following error when i want to use deconvolution layer?

i see the following website, it shows that GIE supports deconvolution layer, but i try to add deconvolution layer to my prototxt and build the new caffe model whose format is not like goolgenet, alexnet and detectnet. I get this error.

https://devblogs.nvidia.com/parallelforall/production-deep-learning-nvidia-gpu-inference-engine/

[GIE]  loading pvaNetClassifier.prototxt pvanet_frcnn_iter_100000.caffemodel
Caffe Parser: groups are not supported for deconvolutions
error parsing layer type Deconvolution index 379
[GIE]  failed to parse caffe network

Thank you very much.

**Comment by Jia-HongHenryLee** [comment]
Thank everyone. i find the developer document about GIE. This document is located in your deployment device (e.g. jetson TX1). The path is /usr/share/doc/gie. 
Solution: The version one of GIE don't support the groups parameter of deconvolution layer.

**Comment by lbin** [comment]
Hi @Jia-HongHenryLee , could you tell me what is the `groups parameter of deconvo layer`?

**Comment by Jia-HongHenryLee** [comment]
Hi @lbin , you can visit the following website. it can solve your question.
http://stackoverflow.com/questions/40872914/caffe-what-does-the-group-param-mean

**Comment by lbin** [comment]
Thanks for the reference, @Jia-HongHenryLee !
This `group` param confused me. My segmentation model has deconv layer, and  I find the default value of the group is `1`, and the model can be load by GIE. Unfortunately,  my result is totally wrong.
By the way, this model in caffe could get right results.

**Comment by Jia-HongHenryLee** [comment]
@lbin  yes, because TensorRT(GIE) don't support the group parameter of deconvolution layer. so said. i think that the second version of Tensor RT maybe will support it.

**Comment by Jia-HongHenryLee** [comment]
you can try to modify segnet which is in jetson-inference to let it have the same accuracy with your version

**Comment by lbin** [comment]
@Jia-HongHenryLee Thanks for the kindly reply. Now I am doing my work based on the Caffe.

**Comment by Jia-HongHenryLee** [comment]
@lbin  You're welcome.
