### ISSUE TITLE
How to grab detected object's label

### ISSUE THREAD

**Issue by LookiePookie** [dusty-nv/jetson-inference#471]
I'm trying to get the label of the object that the net is detecting if anyone can help, it will be very appreciated. :D

**Comment by LookiePookie** [comment]
`self.img, self.width, self.height = self.camera.CaptureRGBA()
detections = self.net.Detect(self.img, self.width, self.height, "box,label,conf")`

From this code im assuming the label is part of the detections list, but i dont understand how to grab it.

**Comment by Dwaynekj** [comment]
try   `net.GetClassDesc(detection.ClassID)` where `detection` is an element in `detections`

**Comment by LookiePookie** [comment]
yeah that worked the class id was what i needed. Thank you for the quick response!
