### ISSUE TITLE
Extract model file error

### ISSUE THREAD

**Issue by gxj98** [dusty-nv/jetson-inference#472]
When extracting the model :
`tar -zxvf ResNet-18.tar.gz`
There comes an error
```
ResNet-18
ResNet-18/train. prototxt 
ResNet-18/ResNet mean. binaryproto 
ResNet-18/solver. prototxt 
ResNet-18/deploy. prototxt 
ResNet-18/ResNet-18. caffemodel 
tar:Skipping to next header 

gzip:stdin:unexpected end of file 
tar:child returned status 1
tar:Error is not recoverable:exiting now
```

**Comment by dusty-nv** [comment]
Hi @Xiangjun-Gao, does the corruption still occur if you try downloading the model again?

Alternatively, you could try downloading the model from the mirror here:  https://github.com/dusty-nv/jetson-inference/releases

I just confirmed that I was able to download & extract it successfully.
