### ISSUE TITLE
How to Produce a grayscale binary segmentation mask ？

### ISSUE THREAD

**Issue by FengBob** [dusty-nv/jetson-inference#473]
There are 2 methods in segNet.h，show below:
![image](https://user-images.githubusercontent.com/27957744/72057988-519aa400-330a-11ea-9a5d-7c2e5acfe498.png)
I try to used the first method in python,  but failed. I want to know how to input the first parameter to distinguish the two methods in python?

**Comment by FengBob** [comment]
> There are 2 methods in segNet.h，show below:
![image](https://user-images.githubusercontent.com/27957744/72057779-e94bc280-3309-11ea-8d01-c33051eca316.png)
I try to used the first method, but failed. I want to know how to input the first parameter to distinguish the two methods?

**Comment by hanzhi713** [comment]
It seems that there's no binding function in https://github.com/dusty-nv/jetson-inference/blob/master/python/bindings/PySegNet.cpp
