### ISSUE TITLE
How to run ImageNet to classify image WITHOUT tensorRT

### ISSUE THREAD

**Issue by hyh807** [dusty-nv/jetson-inference#477]
I followd [this](https://github.com/dusty-nv/jetson-inference/blob/master/docs/imagenet-console-2.md) repo and run the demo of imageNet successfully. But I'm wondering how speed-up does TensorRT do. Is there any way to DISABLE tensorRT on this example, if not, how to run without tensorRT and compare the speed-up of tensorRT on image classification. thanks.

**Comment by dusty-nv** [comment]
Hi @hyh807, the repo does not use other backends for inferencing such as Caffe, PyTorch, TensorFlow, ect (only TensorRT).  To compare the performance, you would need to run the models separately through their native frameworks.
