### ISSUE TITLE
Flipped output frames.

### ISSUE THREAD

**Issue by DoriHp** [dusty-nv/jetson-inference#480]
Thanks for great work. I tried your repo, everything work fine, except one. When program show processed frame, it was flipped like this: 
![Screenshot from 2020-01-20 08-16-02](https://user-images.githubusercontent.com/44353216/72692452-9b7f5780-3b5e-11ea-9263-ffeee2492e72.png)

But when I try this repo: https://github.com/NVIDIA-AI-IOT/jetcam, which also read frame using gstreamer, that error didn't happend. How can I resolve it?

**Comment by DoriHp** [comment]
@dusty-nv

**Comment by dusty-nv** [comment]
Hi @DoriHp , try changing the `flip-method` parameter to 0 here:  https://github.com/dusty-nv/jetson-utils/blob/798c416c175d509571859c9290257bd5cce1fd63/camera/gstCamera.cpp#L416

Then build/install jetson-inference again:

```bash
cd /path/to/your/jetson-inference/build
make
sudo make install
```

**Comment by DoriHp** [comment]
Thank for your reply

**Comment by AI-Guru** [comment]
Would it be possible to have flip-method as a parameter for instantiating the camera? This way no one would have to recompile :D
