### ISSUE TITLE
How to use gige camera?

### ISSUE THREAD

**Issue by woojinKwon** [dusty-nv/jetson-inference#481]
I wanna use external gige camera instead of MIPI. I can connect gige camere with jetson tx2, but can't make SegNet recognize the gige. how to do it?

**Comment by dusty-nv** [comment]
Hi @woojinKwon , there is a fork of jetson-inference that has been modified to use GigEVision camera here:  https://github.com/Abaco-Systems/jetson-inference-gv

This fork was forked before I introduced segNet, so if you wanted to use segNet with GigEVision camera, you would need to take the GigEVision modifications from this fork and merge them back with master.  I recommend testing the fork with your camera model on one of the other programs (like imageNet or detectNet) before doing so.

Also, is your gige camera using the GigEVision standard, or is it an IP camera?  If the later, you would likely need to use an SDK or driver from the camera vendor.
