### ISSUE TITLE
Cmake not Detecting Virtual Environment (venv)

### ISSUE THREAD

**Issue by navyjosh** [dusty-nv/jetson-inference#482]
I'm using Jetson Nano, following the build from source instructions. However, I decided to use a venv.

I'm using virtualenv with virtualenvwrapper and when I run cmake, it is only installing python modules to /usr/lib/python* whereas my venv is not being detected and no python modules are being installed to the venv dir.

I made sure to activate the venv, and I check that the venv is in $PATH.

**Comment by dusty-nv** [comment]
Hi @navyjosh , you could try changing the `PYTHON_BINDING_INSTALL_DIR` here:   https://github.com/dusty-nv/jetson-inference/blob/8846dcb274ff812880ef7bf9d42eb1dd75c9e7b7/python/bindings/CMakeLists.txt#L52

**Comment by Kmarconi** [comment]
Hi,

Sorry for re-opening this issue but even after making the change in the python binding CmakeList file (and compiling from source successfully) , I'm still not able to import the jetson module in my virtualenv's python. Any other file which should change ?

Regards

**Comment by shubhamsidhwa** [comment]
Was this issue resolved  ? I am facing the same issue

**Comment by Kmarconi** [comment]
If I remember well, I had to add the lib path my bashrc file :)

**Comment by shubhamsidhwa** [comment]
Which bashrc file ?

**Comment by shubhamsidhwa** [comment]
set(PYTHON_BINDING_INSTALL_DIR /usr/lib/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}/dist-packages)  : I did this change as suggested by dusty-nv above

**Comment by iliesaya** [comment]
don't forget to also update the file : utils/python/bindings/CMakeLists.txt
in my case I replaced with : set(PYTHON_BINDING_INSTALL_DIR /home/jetson/.virtualenvs/py3flask/lib/python3.6/site-packages)

**Comment by abbasitaher** [comment]
I changed the python binding CmakeList file and everything went okay but when I imported jetson.utils this error occurs:

import jetson.utils
  File "path/to/venv/lib/python3.6/site-packages/jetson/utils/__init__.py", line 4, in <module>
    from jetson_utils_python import *
ImportError: dynamic module does not define module export function (PyInit_jetson_utils_python)

**Comment by abbasitaher** [comment]
I managed to solve the problem. Remove or rename jetson_utils_python and jetson_inference_python.so under path/to/venv/lib/python3.6/site-packages. Then:
$ cd path/to/venv/lib/python3.6/site-packages
$ sudo ln -s /usr/lib/python3.6/dist-packages/jetson_inference_python.so
$ sudo ln -s /usr/lib/python3.6/dist-packages/jetson_utils_python.so

ps: if you couldn't find the files under  /usr/lib/ try  /usr/local/lib/
