### ISSUE TITLE
Why is the pixelwise prediction unavailable in SegNet?

### ISSUE THREAD

**Issue by woojinKwon** [dusty-nv/jetson-inference#489]
Hi. @dusty-nv  thank you for your reply for my former question.
I'm doing semantic segmentation referring to "Semantic Segmentation with SegNet" with external Camera. Doing several segmentation at several images, I realize that the minimun unit of prediction is not one pixel but box with many pixels. In my knowledge, segnet's dense prediction is for pixel-wise labeling. Is the deconvolution layer deleted? I want to know why i can't derive pixel-wise labeling and how to do it. I sincerely wanna do pixel-wise prediction with smooth line not box like attached image. 

![image_box_predict](https://user-images.githubusercontent.com/56062594/73423564-d3ad4400-436f-11ea-816a-ee942eeae7d8.png)

And I also wonder that how can I view onnx file as graph in my jetson tx2 (arm64 architecture). I realized the program "Netron" which can do the function but is only for amd64". is there any solutions?

I hope any helpful answer. thank you

**Comment by dusty-nv** [comment]
>  I want to know why i can't derive pixel-wise labeling and how to do it. I sincerely wanna do pixel-wise prediction with smooth line not box like attached image.

Hi @woojinKwon , it looks like your image is using point (nearest-neighbor) filtering mode.  Instead try linear filtering mode (launch the program with `--filter-mode=linear`).  That will use bilinear upsampling to make a smooth segmentation overlay like the images here:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/segnet-camera-2.md

> And I also wonder that how can I view onnx file as graph in my jetson tx2 (arm64 architecture).

Check out this `onnx_validate.py` script, it will print the ONNX graph.  Note that you will need to install the `onnx` package with `pip/pip3` (depending on your desired Python version) to run it.
