### ISSUE TITLE
model-specific fps

### ISSUE THREAD

**Issue by gpqls** [dusty-nv/jetson-inference#497]
There are many models for facial recognition, as shown here. I will use Jetson TX2 among them. I want to know the model fps at Jetson. Because I want to use the best performance model available at Jetson TX2.  Please let me know how to investigate this or if you have a model to recommend. Thanks.

**Comment by dusty-nv** [comment]
Hi @gpqls , if you run the models through one of the programs in jetson-inference, it will print out the time to the console log that it takes to process the network with TensorRT.
