### ISSUE TITLE
Change precision

### ISSUE THREAD

**Issue by benzispawn** [dusty-nv/jetson-inference#498]
Hi,
How can I change the precision on segnet-console? I want in INT8.

Thanks in advance

**Comment by bronstein87** [comment]
hi. as i can see there is no way to do it throw the segnet-console because it uses constructor without precision parameter, you can make your own example using differen constructor (look at /home/nvidia/jetson-inference/c/segNet.h)
```
segNet* segNet::Create( const char* prototxt, const char* model, const char* labels_path, const char* colors_path, 
				    const char* input_blob, const char* output_blob, uint32_t maxBatchSize,
				    precisionType precision, deviceType device, bool allowGPUFallback )
```
