### ISSUE TITLE
Case sensitive filename

### ISSUE THREAD

**Issue by qazs** [dusty-nv/jetson-inference#500]
I noticed the packages generated are capitalized:
<pre>
$:/usr/lib/python2.7/dist-packages/Jetson$ ls
GPIO  Inference  __init__.py  Utils
</pre>
but the file import names are lowercase.

<pre>
import jetson.inference
import jetson.utils
</pre>

Hence I have to manually change the import filename for it to work. Any workaround this?

**Comment by dusty-nv** [comment]
Are they not also installed under `/usr/lib/python2.7/dist-packages/jetson` ?

This should automatically occur here:   https://github.com/dusty-nv/jetson-inference/blob/8846dcb274ff812880ef7bf9d42eb1dd75c9e7b7/python/bindings/CMakeLists.txt#L57
