### ISSUE TITLE
jetson.utils.cudaToNumpy() fails with "failed to get array pointer from PyCapsule container"

### ISSUE THREAD

**Issue by jtiscione** [dusty-nv/jetson-inference#509]
```
import jetson.utils

camera = jetson.utils.gstCamera(1280, 720)
img, width, height = camera.CaptureRGBA()
numpyArray = jetson.utils.cudaToNumpy(img, width, height, 4)
```

Prints "Exception: jetson.utils -- cudaToNumpy() failed to get array pointer from PyCapsule container"

**Comment by dusty-nv** [comment]
Try `camera.CaptureRGBA(zeroCopy=True)` instead.  This will enable CPU access so `cudaToNumpy()` should be able to use it

**Comment by jtiscione** [comment]
OK I have another question. If I run this:
```
import jetson.utils
camera = jetson.utils.gstCamera(1280, 720)
img, width, height = camera.CaptureRGBA(zeroCopy=1)
jetson.utils.saveImageRGBA('/home/jetson/test.png', img, width, height)
```
If I then run `npArray=jetson.utils.cudaToNumpy(img, width, height)` and show it with matplotlib, I can see the image.

If I omit the zeroCopy=1 argument in camera.CaptureRGBA(), saveImageRGBA() prints "failed to get input image pointer from PyCapsule container". It looks like saveImageRGBA() is broken.

**Comment by dusty-nv** [comment]
You need gstCamera.CaptureRGBA(zeroCopy=1) for saveImageRGBA because it needs the data on the CPU to save it.
________________________________

**Comment by jtiscione** [comment]
Yes but it's saving a blank image if I do that.

**Comment by dusty-nv** [comment]
Try inserting a call to jetson.utils.cudaDeviceSynchronize() before you call saveImageRGBA()
________________________________

**Comment by jtiscione** [comment]
Trying this:
```
import jetson.utils
camera = jetson.utils.gstCamera(1280, 720)
img, width, height = camera.CaptureRGBA(zeroCopy=1)
jetson.utils.cudaDeviceSynchronize()
jetson.utils.saveImageRGBA('test.png', img, width, height)
```
Ubuntu's default Image Viewer app still displays test.png as a blank/transparent image.

**Comment by jtiscione** [comment]
This is the same issue that was reported in https://github.com/dusty-nv/jetson-inference/issues/383 where someone else who didn't realize they needed zeroCopy=1 in CaptureRGBA() filed an issue, and once that was made clear, another person ran into the subsequent problem with saveImageRGBA()saving blank images.

Since this is not about cudaToNumpy() or CaptureRGBA() anymore I'll close this issue and file a new one specifically about saveImageRGBA- since invoking cudaDeviceSynchronize() doesn't seem to fix the problem.
