### ISSUE TITLE
jetson.utils.saveImageRGBA() saves blank images

### ISSUE THREAD

**Issue by jtiscione** [dusty-nv/jetson-inference#512]
I'm running these 5 lines of Python with a Raspberry Pi camera:
```
import jetson.utils
camera = jetson.utils.gstCamera(1280, 720)
img, width, height = camera.CaptureRGBA(zeroCopy=1)
jetson.utils.cudaDeviceSynchronize()
jetson.utils.saveImageRGBA('test.png', img, width, height)
```
This code saves a blank image in test.png.

I can then convert img to a numpy array with jetson.utils.cudaToNumpy() and view the image with matplotlib, so it IS in there.

**Comment by jackthecoder23** [comment]
@jtiscione 
One solution I found was simply to save the image as a .jpg instead of a .png.
I changed the last line to:
`jetson.utils.saveImageRGBA('test.jpg',img,width,height)`
and it worked perfectly.
Hope this helps!
-Jack
