### ISSUE TITLE
I need filesrc function

### ISSUE THREAD

**Issue by maponarooo** [dusty-nv/jetson-inference#513]
I am very pleased with the jetson-inference framework and am using it. 
Really Thank you. 
Recently I'm trying to object detection from a video file.
So I have tried find the function I could not find that. Like a GstgetCamera()...
I want to know how can I find it or have to modify source?

**Comment by dusty-nv** [comment]
Hi @maponarooo, see this thread:   https://devtalk.nvidia.com/default/topic/1071209/jetson-nano/detectnet-video-/post/5427509/#5427509

**Comment by maponarooo** [comment]
> Hi @maponarooo, see this thread: https://devtalk.nvidia.com/default/topic/1071209/jetson-nano/detectnet-video-/post/5427509/#5427509

Wow! It is what I looking for. Thanks a lot~~~
