### ISSUE TITLE
Converting cv::Mat  to float*

### ISSUE THREAD

**Issue by efedoganay** [dusty-nv/jetson-inference#514]
Hi, I am getting a video stream from udp on Jetson Nano and I implemented it by VideoCapture function. To be able to detect objects, I need to convert cv::Mat to float*. Look at the code below for more detail. 

(modifying detectnet-camera.cpp)

`cap.read(frame);`
 `cv::cvtColor(frame, frame, cv::COLOR_BGR2RGBA);`
 ` float* imgRGBA = frame.ptr<float>(0);`
 ` detectNet::Detection* detections = NULL;`
  `const int numDetections = net->Detect(imgRGBA, camera->GetWidth(), camera->GetHeight(), 
  &detections, overlayFlags);`

This code seems not working. Any suggestions?

**Comment by lilin531** [comment]
Have you solved this issue?

**Comment by dusty-nv** [comment]
Sorry for the delay - you need to copy the memory to GPU first.  See this post:  https://github.com/dusty-nv/jetson-inference/issues/129#issuecomment-324130091
