### ISSUE TITLE
Typo in download-models.sh

### ISSUE THREAD

**Issue by AFIDclan** [dusty-nv/jetson-inference#520]
When attempting to download cityscapes_2048x1024 I got: `./download-models.sh: line 721: download_fcn_resnet18_cityscapes_2048x512: command not found`
It looks like there was a typo, and line 721 needs to be changed from:
`download_fcn_resnet18_cityscapes_2048x512` to `download_fcn_resnet18_cityscapes_2048x1024`

Thanks for the amazing repo!

**Comment by dusty-nv** [comment]
Woops, sorry about that, thanks for letting me know @AFIDclan.

Just fixed it in master with commit [`62d926`](https://github.com/dusty-nv/jetson-inference/commit/62d92621402c7b02556669f65a4d10c0ff454a30).
