### ISSUE TITLE
jetson-inference/c/tensorNet.cpp:509:83: error: ‘kVERBOSE’ is not a member of ‘nvinfer1::ILogger::Severity’    if( !parser->parseFromFile(modelFile.c_str(), (int)nvinfer1::ILogger::Severity::kVERBOSE) )

### ISSUE THREAD

**Issue by toilandmoil** [dusty-nv/jetson-inference#527]

**Comment by dusty-nv** [comment]
Hi @toilandmoil , this should be fixed by commit [`ac508d`](https://github.com/dusty-nv/jetson-inference/commit/ac508df0690ccd0ccc008d2e7b5799773c609f43)

Please try pulling from master again, and let me know if you still have an issue compiling.
