### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop. under build folder

### ISSUE THREAD

**Issue by xiaoliwe** [dusty-nv/jetson-inference#537]
![Annotation 2020-03-29 145821](https://user-images.githubusercontent.com/9930176/77843619-7f88d980-71d1-11ea-99c9-e8c6807a9a07.png)

Hardware : NV Jetson Nano 
OS : Ubuntu 18.04 LTS

so , i'm not sure that how to solve it ,And  cannot find any makefiles in build/ folder .

**Comment by Dadirri-101** [comment]
I have encountered the same difficulties as you, have you solved it?

**Comment by Dadirri-101** [comment]
Hi,I have encountered the same difficulties as you, have you solved it?

**Comment by fredafredaf** [comment]
somehelp plz

**Comment by ayushgupta9198** [comment]
Hi all ,

**This issue was solved by me you can find the solution in my profile**

Thanks for your time
