### ISSUE TITLE
Save a video after detection

### ISSUE THREAD

**Issue by elementdl** [dusty-nv/jetson-inference#552]
Hi @dusty-nv ,

I'm trying to use ssd-mobilenet-v2 with a pre-recorded video, and I want to save it with the detections.
My problem is I don't know how to save it after the detections. 
I'm trying to use VideoWriter, but it accepts a specific variable.
I start with your code from "Coding Your Own Object Detection Program", 
I know that VideoWriter accept a variable a the same type as "frame".
But I don't know how to have this type after the detections applied.
I saw that the variable transforms like this :
frame -/cv2.cvtcolor/-> frame_rgba-/cudaToNumpy/->img-/net.detect/->img

So I suppose that I can obtain the right type with the help of img.
I tried to ues cudaToNumpy but I got an error : 

File "my_detection_video.py", line 36, in <module>
    newf = jetson.utils.cudaToNumpy(img)
Exception: jetson.utils -- cudaToNumpy() failed to parse args tuple

Here's my code : 

`
import cv2
import numpy as np
import jetson.inference
import jetson.utils

#chargement du model de detection d'objets, ici ssd-mobilenet-v2
net = jetson.inference.detectNet("ssd-mobilenet-v2", threshold=0.5)
width = 1920
height = 1080

#connexion a la video que l'on veut
vid = cv2.VideoCapture('/home/expleoynmouv/Documents/projet/videos/pieton.mp4')
vid.set(cv2.CAP_PROP_FRAME_WIDTH, width )
vid.set(cv2.CAP_PROP_FRAME_HEIGHT, height )

writerX = cv2.VideoWriter('ssd_pieton.avi',cv2.VideoWriter_fourcc(*'MJPG'), 30.0, (width, height))

#opengl : librairie graphique, permet ici un affichage qui persiste jusqu'a l'arret du programme
display = jetson.utils.glDisplay()
while display.IsOpen():
	
	#
	ret, frame = vid.read()

	frame_rgba = cv2.cvtColor(frame, cv2.COLOR_BGR2RGBA).astype(np.float32)

	img = jetson.utils.cudaFromNumpy(frame_rgba)
	
	#detection de classes
	detections = net.Detect(img, width, height)

	#affichage et detail 
	display.RenderOnce(img, width, height)
	display.SetTitle("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))
	
	newf = jetson.utils.cudaToNumpy(img)
	writerX.write(newf)
`

Sincerely,

**Comment by leandrovrabelo** [comment]
Hi,

I believe that you need more convertions to save the file, I tried this with a file that I have and it worked well:

`import cv2
import numpy as np
import jetson.inference
import jetson.utils

#chargement du model de detection d'objets, ici ssd-mobilenet-v2
net = jetson.inference.detectNet("ssd-mobilenet-v2", threshold=0.5)

#connexion a la video que l'on veut
vid = cv2.VideoCapture('/home/leandrovrabelo/Vídeos/IMG_4909.MOV')
width = int(vid.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(vid.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*'H264')
writerX = cv2.VideoWriter('/home/leandrovrabelo/Vídeos/infer.mp4', fourcc, 30.0, (width, height))

#opengl : librairie graphique, permet ici un affichage qui persiste jusqu'a l'arret du programme
display = jetson.utils.glDisplay()
while display.IsOpen():

    ret, frame = vid.read()
    frame_rgba = cv2.cvtColor(frame, cv2.COLOR_BGR2RGBA).astype(np.float32)
    print('RGBA shape', frame_rgba.shape)
    img = jetson.utils.cudaFromNumpy(frame_rgba)

    #detection de classes
    detections = net.Detect(img, width, height)

    #affichage et detail 
    display.RenderOnce(img, width, height)
    display.SetTitle("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))

    # Converting image to save the video
    conversion1 = jetson.utils.cudaToNumpy(img, width, height, 4)        
    conversion2 = cv2.cvtColor(conversion1, cv2.COLOR_RGBA2RGB).astype(np.uint8)
    conversion3 = cv2.cvtColor(conversion2, cv2.COLOR_RGB2BGR)

    if ret == True:
        writerX.write(conversion3)

vid.release()   
writerX.release()
cv2.destroyAllWindows()`
