### ISSUE TITLE
Unable to convert resnet18 ONNX model to TensorRT Engine

### ISSUE THREAD

**Issue by mbufi** [dusty-nv/jetson-inference#554]
Hello @dusty-nv 
I trained a sample resnet18/resnet50 model with the repo and successfully converted it to onnx format.

Then I wanted to use it in my code: 
```
net = jetson.inference.imageNet('googlenet',
['--model=resnet18.onnx',
'--input_blob=input_0',
'--output_blob=output_0',
'--labels=labels.txt'])
```

and was met with the following: 

> nvidia@nvidia:~/ai/algorithms/jetson_inference$ python3 imagenet-opencv.py 
> jetson.inference.__init__.py
> jetson.inference -- initializing Python 3.6 bindings...
> jetson.inference -- registering module types...
> jetson.inference -- done registering module types
> jetson.inference -- done Python 3.6 binding initialization
> jetson.utils.__init__.py
> jetson.utils -- initializing Python 3.6 bindings...
> jetson.utils -- registering module functions...
> jetson.utils -- done registering module functions
> jetson.utils -- registering module types...
> jetson.utils -- done registering module types
> jetson.utils -- done Python 3.6 binding initialization
> SYSTEM ARG ['imagenet-opencv.py']
> jetson.inference -- PyTensorNet_New()
> jetson.inference -- PyImageNet_Init()
> jetson.inference -- imageNet loading network using argv command line params
> jetson.inference -- imageNet.__init__() argv[0] = '--model=resnet18.onnx'
> jetson.inference -- imageNet.__init__() argv[1] = '--input_blob=input_0'
> jetson.inference -- imageNet.__init__() argv[2] = '--output_blob=output_0'
> jetson.inference -- imageNet.__init__() argv[3] = '--labels=labels.txt'
> 
> imageNet -- loading classification network model from:
>          -- prototxt     (null)
>          -- model        resnet18.onnx
>          -- class_labels labels.txt
>          -- input_blob   'input_0'
>          -- output_blob  'output_0'
>          -- batch_size   1
> 
> [TRT]   TensorRT version 5.1.6
> [TRT]   loading NVIDIA plugins...
> [TRT]   Plugin Creator registration succeeded - GridAnchor_TRT
> [TRT]   Plugin Creator registration succeeded - NMS_TRT
> [TRT]   Plugin Creator registration succeeded - Reorg_TRT
> [TRT]   Plugin Creator registration succeeded - Region_TRT
> [TRT]   Plugin Creator registration succeeded - PriorBox_TRT
> [TRT]   Plugin Creator registration succeeded - Normalize_TRT
> [TRT]   Plugin Creator registration succeeded - RPROI_TRT
> [TRT]   Plugin Creator registration succeeded - BatchedNMS_TRT
> [TRT]   Could not register plugin creator:  FlattenConcat_TRT in namespace: 
> [TRT]   Plugin Creator registration succeeded - CropAndResize
> [TRT]   Plugin Creator registration succeeded - Proposal
> [TRT]   Plugin Creator registration succeeded - BatchTilePlugin_TRT
> [TRT]   completed loading NVIDIA plugins.
> [TRT]   detected model format - ONNX  (extension '.onnx')
> [TRT]   desired precision specified for GPU: FASTEST
> [TRT]   requested fasted precision for device GPU without providing valid calibrator, disabling INT8
> [TRT]   native precisions detected for GPU:  FP32, FP16, INT8
> [TRT]   selecting fastest native precision for GPU:  FP16
> [TRT]   attempting to open engine cache file resnet18.onnx.1.1.GPU.FP16.engine
> [TRT]   cache file not found, profiling network model on device GPU
> [TRT]   device GPU, loading /usr/bin/ resnet18.onnx
> ----------------------------------------------------------------
> Input filename:   resnet18.onnx
> ONNX IR version:  0.0.4
> Opset version:    9
> Producer name:    pytorch
> Producer version: 1.1
> Domain:           
> Model version:    0
> Doc string:       
> ----------------------------------------------------------------
> WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (3, 224, 224)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (7, 7), strides: (2, 2), padding: (3, 3), dilations: (1, 1), numOutputs: 64
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (64, 112, 112)
> [TRT]   123:Conv -> (64, 112, 112)
> [TRT]   124:BatchNormalization -> (64, 112, 112)
> [TRT]   125:Relu -> (64, 112, 112)
> [TRT]   126:MaxPool -> (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 64
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (64, 56, 56)
> [TRT]   127:Conv -> (64, 56, 56)
> [TRT]   128:BatchNormalization -> (64, 56, 56)
> [TRT]   129:Relu -> (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 64
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (64, 56, 56)
> [TRT]   130:Conv -> (64, 56, 56)
> [TRT]   131:BatchNormalization -> (64, 56, 56)
> [TRT]   132:Add -> (64, 56, 56)
> [TRT]   133:Relu -> (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 64
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (64, 56, 56)
> [TRT]   134:Conv -> (64, 56, 56)
> [TRT]   135:BatchNormalization -> (64, 56, 56)
> [TRT]   136:Relu -> (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 64
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (64, 56, 56)
> [TRT]   137:Conv -> (64, 56, 56)
> [TRT]   138:BatchNormalization -> (64, 56, 56)
> [TRT]   139:Add -> (64, 56, 56)
> [TRT]   140:Relu -> (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (2, 2), padding: (1, 1), dilations: (1, 1), numOutputs: 128
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (128, 28, 28)
> [TRT]   141:Conv -> (128, 28, 28)
> [TRT]   142:BatchNormalization -> (128, 28, 28)
> [TRT]   143:Relu -> (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 128
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (128, 28, 28)
> [TRT]   144:Conv -> (128, 28, 28)
> [TRT]   145:BatchNormalization -> (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (64, 56, 56)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (1, 1), strides: (2, 2), padding: (0, 0), dilations: (1, 1), numOutputs: 128
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (128, 28, 28)
> [TRT]   146:Conv -> (128, 28, 28)
> [TRT]   147:BatchNormalization -> (128, 28, 28)
> [TRT]   148:Add -> (128, 28, 28)
> [TRT]   149:Relu -> (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 128
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (128, 28, 28)
> [TRT]   150:Conv -> (128, 28, 28)
> [TRT]   151:BatchNormalization -> (128, 28, 28)
> [TRT]   152:Relu -> (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 128
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (128, 28, 28)
> [TRT]   153:Conv -> (128, 28, 28)
> [TRT]   154:BatchNormalization -> (128, 28, 28)
> [TRT]   155:Add -> (128, 28, 28)
> [TRT]   156:Relu -> (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (2, 2), padding: (1, 1), dilations: (1, 1), numOutputs: 256
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (256, 14, 14)
> [TRT]   157:Conv -> (256, 14, 14)
> [TRT]   158:BatchNormalization -> (256, 14, 14)
> [TRT]   159:Relu -> (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 256
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (256, 14, 14)
> [TRT]   160:Conv -> (256, 14, 14)
> [TRT]   161:BatchNormalization -> (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (128, 28, 28)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (1, 1), strides: (2, 2), padding: (0, 0), dilations: (1, 1), numOutputs: 256
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (256, 14, 14)
> [TRT]   162:Conv -> (256, 14, 14)
> [TRT]   163:BatchNormalization -> (256, 14, 14)
> [TRT]   164:Add -> (256, 14, 14)
> [TRT]   165:Relu -> (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 256
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (256, 14, 14)
> [TRT]   166:Conv -> (256, 14, 14)
> [TRT]   167:BatchNormalization -> (256, 14, 14)
> [TRT]   168:Relu -> (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 256
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (256, 14, 14)
> [TRT]   169:Conv -> (256, 14, 14)
> [TRT]   170:BatchNormalization -> (256, 14, 14)
> [TRT]   171:Add -> (256, 14, 14)
> [TRT]   172:Relu -> (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (2, 2), padding: (1, 1), dilations: (1, 1), numOutputs: 512
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (512, 7, 7)
> [TRT]   173:Conv -> (512, 7, 7)
> [TRT]   174:BatchNormalization -> (512, 7, 7)
> [TRT]   175:Relu -> (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 512
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (512, 7, 7)
> [TRT]   176:Conv -> (512, 7, 7)
> [TRT]   177:BatchNormalization -> (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (256, 14, 14)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (1, 1), strides: (2, 2), padding: (0, 0), dilations: (1, 1), numOutputs: 512
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (512, 7, 7)
> [TRT]   178:Conv -> (512, 7, 7)
> [TRT]   179:BatchNormalization -> (512, 7, 7)
> [TRT]   180:Add -> (512, 7, 7)
> [TRT]   181:Relu -> (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 512
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (512, 7, 7)
> [TRT]   182:Conv -> (512, 7, 7)
> [TRT]   183:BatchNormalization -> (512, 7, 7)
> [TRT]   184:Relu -> (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:771: Convolution input dimensions: (512, 7, 7)
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:835: Using kernel: (3, 3), strides: (1, 1), padding: (1, 1), dilations: (1, 1), numOutputs: 512
> [TRT]   /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/release/5.1/parsers/onnxOpenSource/builtin_op_importers.cpp:836: Convolution output dimensions: (512, 7, 7)
> [TRT]   185:Conv -> (512, 7, 7)
> [TRT]   186:BatchNormalization -> (512, 7, 7)
> [TRT]   187:Add -> (512, 7, 7)
> [TRT]   188:Relu -> (512, 7, 7)
> [TRT]   189:GlobalAveragePool -> (512, 1, 1)
> [TRT]   190:Constant -> 
> [TRT]   191:Shape -> (4)
> WARNING: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> Successfully casted down to INT32.
> While parsing node number 69 [Gather -> "192"]:
> --- Begin node ---
> input: "191"
> input: "190"
> output: "192"
> op_type: "Gather"
> attribute {
>   name: "axis"
>   i: 0
>   type: INT
> }
> 
> --- End node ---
> ERROR: onnx2trt_utils.hpp:277 In function convert_axis:
> [8] Assertion failed: axis >= 0 && axis < nbDims
> [TRT]   failed to parse ONNX model 'resnet18.onnx'
> [TRT]   device GPU, failed to load resnet18.onnx
> [TRT]   failed to load resnet18.onnx
> [TRT]   imageNet -- failed to initialize.
> jetson.inference -- imageNet failed to load built-in network 'googlenet'
> PyTensorNet_Dealloc()
> Traceback (most recent call last):
>   File "imagenet-opencv.py", line 66, in <module>
>     '--labels=labels.txt'])
> Exception: jetson.inference -- imageNet failed to load network
> double free or corruption (!prev)
> Aborted (core dumped)
> 

Do you know what could be the problem?

**Comment by dusty-nv** [comment]
Hi, there is a patch for this in my torchvision fork, in the v0.3.0 branch.  You can either install my branch or cherry-pick the resnet fix for it.
________________________________

**Comment by mbufi** [comment]
Thanks @dusty-nv ! Before I go off to attempt, is there a quick command for doing this? Or something in the tutorials that I missed?
