### ISSUE TITLE
Could not capture RTSP camera

### ISSUE THREAD

**Issue by ledaiduongvnth** [dusty-nv/jetson-inference#560]
Device: Jetson nano
TensorRT: 7.1.0-1
Cuda: 10.2
`NvMMLiteOpen : Block : BlockType = 261 

NVMEDIA: Reading vendor.tegra.display-size : status: 6 

NvMMLiteBlockCreate : Block : BlockType = 261 

NvMMLiteOpen : Block : BlockType = 261 

NVMEDIA: Reading vendor.tegra.display-size : status: 6 

NvMMLiteBlockCreate : Block : BlockType = 261 `

The program get static and does not show the camera. I guess may be an incompatibility between gtsCamera and Cuda version.

**Comment by Neltherion** [comment]
Were You able to solve this problem?
