### ISSUE TITLE
Masks And Detection on Inference 

### ISSUE THREAD

**Issue by muhammadabdullah34907** [dusty-nv/jetson-inference#562]
Hi Everyone & @dusty-nv ,
I have successfully tested segmentation using usb cam and masks overlay and detection seems working fine on output frames but I am unable to get the masks and detection as return which I want to use it for post processing.

I have checked the API reference link for segnet as well and it says all the functions such as 
net.Overlay(img_overlay, width, height, opt.filter_mode)
net.Mask(img_mask, width/2, height/2, opt.filter_mode)
etc
https://rawgit.com/dusty-nv/jetson-inference/pytorch/docs/html/python/jetson.inference.html#segNet

Almost all function's having None as returned type. So, please any help to get the detection boxes and masks points as return type ?

I have seen there's option in object detection but there is so far couldn't find any option in segmentation. 

I will be very thank you. 

FileName: segnet-camera.py.

net = jetson.inference.segNet(opt.network, sys.argv)

net.SetOverlayAlpha(opt.alpha)

img_overlay = jetson.utils.cudaAllocMapped(opt.width * opt.height * 4 * ctypes.sizeof(ctypes.c_float))
img_mask = jetson.utils.cudaAllocMapped(opt.width/2 * opt.height/2 * 4 * ctypes.sizeof(ctypes.c_float))

camera = jetson.utils.gstCamera(opt.width, opt.height, opt.camera)
display = jetson.utils.glDisplay()

while display.IsOpen():
	img, width, height = camera.CaptureRGBA()

	net.Process(img, width, height, opt.ignore_class)

	net.Overlay(img_overlay, width, height, opt.filter_mode)
	net.Mask(img_mask, width/2, height/2, opt.filter_mode)

	display.BeginRender()
	display.Render(img_overlay, width, height)
	display.Render(img_mask, width/2, height/2, width)
	display.EndRender()

	display.SetTitle("{:s} | Network {:.0f} FPS".format(opt.network, net.GetNetworkFPS()))

**Comment by craston** [comment]
It is possible to access masks by using the segmentation buffers, defined [here](https://github.com/dusty-nv/jetson-inference/blob/397509f77adbac0ea74345d9fbe9c650f4e23727/python/examples/segnet_utils.py#L29).
You can then directly by using `mask = buffers.mask` after this [line](https://github.com/dusty-nv/jetson-inference/blob/397509f77adbac0ea74345d9fbe9c650f4e23727/python/examples/segnet.py#L77).
To convert the cudaImage to numpy array, you can use `mask_np = jetson.utils.cudaToNumpy(mask)`
