### ISSUE TITLE
Please make it clear that a special patched version of Torchvision is required

### ISSUE THREAD

**Issue by gituuu** [dusty-nv/jetson-inference#589]
For DIGITS, please make it clear that a special patched version of Torchvision is required. It looks like it is the normal 0.3.0 version but it is not and it would be really helpful if you made it clear on this page:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-repo.md

**Comment by dusty-nv** [comment]
Hi @gituuu - thanks for your feedback, I will do that.  Note the forked version is automatically installed by the script during `cmake` configuration, and if you are on the latest JetPack 4.4 the forked torchvision is no longer required and the upstream version of torchvision is installed.

**Comment by gituuu** [comment]
Great. I am waiting for 4.4 to be "stable" before I move to it. I think it is only "developer preview" at the moment.
