### ISSUE TITLE
Find object location in Python

### ISSUE THREAD

**Issue by msts35** [dusty-nv/jetson-inference#591]
Hi Dustin, 

I want to get the locations of the objects that the system found in the image for object counting , however I could not find the right way to pull location variables from C++ source code.

Could you please give me advice about how to do that ?

**Comment by dusty-nv** [comment]
The list of detection structs returned by detectNet.Detect includes members for the coordinates.  See detectNet.Detection class under here:

https://rawgit.com/dusty-nv/jetson-inference/python/docs/html/python/jetson.inference.html#detectNet
________________________________

**Comment by msts35** [comment]
thank you man , you are hero
