### ISSUE TITLE
Jetson Nano Wi-Fi Connection

### ISSUE THREAD

**Issue by tabaddor** [dusty-nv/jetson-inference#596]
Hello, 

I have flashed my SD Card for the Jetson Nano, and upon booting, it does not seem as if the computer is connected to the Internet. All dependencies and installations like sudo, python, git, etc are all pre-installed (I can view them with `$ sudo --version`, for example), but it is not connected to the Internet, thus I am unable to build the project from source.

How do I go about connecting the Nano to the Internet?

**Comment by gituuu** [comment]
This question doesn't belong here. Post it on the Jetson Nano forums instead:
https://devtalk.nvidia.com/default/board/371/jetson-nano/
