### ISSUE TITLE
glibconfig.h: No such file or directory

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [dusty-nv/jetson-inference#6]
hi, @dusty-nv, when i make, i meet this problem, but i can't fix it, can you do me a favor?
```
/usr/include/glib-2.0/glib/gtypes.h:32:24: fatal error: glibconfig.h: No such file or directory
```
thanks.

**Comment by zimenglan-sysu-512** [comment]
i chance "/usr/include/glib-2.0" to "/usr/lib/x86_64-linux-gnu/glib-2.0/include", so it can make it successfully.

**Comment by sonichy** [comment]
sudo cp /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/glibconfig.h

**Comment by walterzhaoJR** [comment]
gcc `pkg-config --cflags glib-2.0` test.c `pkg-config --libs glib-2.0`

**Comment by saveriomiroddi** [comment]
> sudo cp /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/glibconfig.h

this worked (thanks!), however, I think a more idiomatic approach would be to use a symlink (`sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/`).

**Comment by pphhss** [comment]
> gcc `pkg-config --cflags glib-2.0` test.c `pkg-config --libs glib-2.0`
> 
> it's useful



> gcc `pkg-config --cflags glib-2.0` test.c `pkg-config --libs glib-2.0`
> 
> it's useful

Thank!!!

**Comment by anselmobattisti** [comment]
At vistual studio code in the "Include path" of C compiler i needed to place the lines in this excatly oder:

`${workspaceFolder}/**
/usr/include/glib-2.0/**
/usr/include/gstreamer-1.0/**`

the /** is important to do recursive search in the folders

**Comment by vlad-iancu** [comment]
> sudo cp /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/glibconfig.h

Mine was in `/usr/lib/glib-2.0/include`

**Comment by messiasv** [comment]
> > sudo cp /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/glibconfig.h
> 
> this worked (I had the same problem on a different VS Code project), however, I think a more idiomatic approach would be to use a symlink (`sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/`).



In my case, I was using a Raspberry Pi Zero W (which has an armv6l architecture), so I used the following symlink:
`sudo ln -s /usr/lib/arm-linux-gnueabihf/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/`
