### ISSUE TITLE
Compiling the Project(Hello AI world) erro with Makefile:117: recipe for target 'install' failed make: *** [install] Error 1

### ISSUE THREAD

**Issue by DabinGreat** [dusty-nv/jetson-inference#606]
Hi @dusty-nv ：
        I am compiling this project（Hello AI world） according to your installation documentation, but when I run to the `sudo make install`， the following error is generated, so I would like to ask what caused it and what should i do next? Thank you!

`Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/jetson-inference/detectNet.h
-- Installing: /usr/local/include/jetson-inference/homographyNet.h
-- Installing: /usr/local/include/jetson-inference/imageNet.h
-- Installing: /usr/local/include/jetson-inference/segNet.h
-- Installing: /usr/local/include/jetson-inference/superResNet.h
-- Installing: /usr/local/include/jetson-inference/tensorNet.h
-- Installing: /usr/local/include/jetson-inference/imageNet.cuh
-- Installing: /usr/local/include/jetson-inference/randInt8Calibrator.h
-- Installing: /usr/local/lib/libjetson-inference.so
-- Set runtime path of "/usr/local/lib/libjetson-inference.so" to ""
-- Installing: /usr/local/share/jetson-inference/cmake/jetson-inferenceConfig.cmake
-- Installing: /usr/local/share/jetson-inference/cmake/jetson-inferenceConfig-noconfig.cmake
-- Installing: /usr/local/bin/imagenet-console
-- Set runtime path of "/usr/local/bin/imagenet-console" to ""
-- Installing: /usr/local/bin/imagenet-camera
-- Set runtime path of "/usr/local/bin/imagenet-camera" to ""
-- Installing: /usr/local/bin/detectnet-console
-- Set runtime path of "/usr/local/bin/detectnet-console" to ""
-- Installing: /usr/local/bin/detectnet-camera
-- Set runtime path of "/usr/local/bin/detectnet-camera" to ""
-- Installing: /usr/local/bin/segnet-console
-- Set runtime path of "/usr/local/bin/segnet-console" to ""
-- Installing: /usr/local/bin/segnet-camera
-- Set runtime path of "/usr/local/bin/segnet-camera" to ""
-- Installing: /usr/local/bin/superres-console
-- Set runtime path of "/usr/local/bin/superres-console" to ""
-- Installing: /usr/local/bin/homography-console
-- Set runtime path of "/usr/local/bin/homography-console" to ""
-- Installing: /usr/local/bin/homography-camera
-- Set runtime path of "/usr/local/bin/homography-camera" to ""
-- Installing: /usr/local/bin/camera-capture
-- Set runtime path of "/usr/local/bin/camera-capture" to ""
-- Installing: /usr/local/include/jetson-utils/XML.h
-- Installing: /usr/local/include/jetson-utils/commandLine.h
-- Installing: /usr/local/include/jetson-utils/filesystem.h
-- Installing: /usr/local/include/jetson-utils/mat33.h
-- Installing: /usr/local/include/jetson-utils/pi.h
-- Installing: /usr/local/include/jetson-utils/rand.h
-- Installing: /usr/local/include/jetson-utils/timespec.h
-- Installing: /usr/local/include/jetson-utils/gstCamera.h
-- Installing: /usr/local/include/jetson-utils/v4l2Camera.h
-- Installing: /usr/local/include/jetson-utils/gstDecoder.h
-- Installing: /usr/local/include/jetson-utils/gstEncoder.h
-- Installing: /usr/local/include/jetson-utils/gstUtility.h
-- Installing: /usr/local/include/jetson-utils/cudaFont.h
-- Installing: /usr/local/include/jetson-utils/cudaMappedMemory.h
-- Installing: /usr/local/include/jetson-utils/cudaNormalize.h
-- Installing: /usr/local/include/jetson-utils/cudaOverlay.h
-- Installing: /usr/local/include/jetson-utils/cudaRGB.h
-- Installing: /usr/local/include/jetson-utils/cudaResize.h
-- Installing: /usr/local/include/jetson-utils/cudaUtility.h
-- Installing: /usr/local/include/jetson-utils/cudaWarp.h
-- Installing: /usr/local/include/jetson-utils/cudaYUV.h
-- Installing: /usr/local/include/jetson-utils/glDisplay.h
-- Installing: /usr/local/include/jetson-utils/glTexture.h
-- Installing: /usr/local/include/jetson-utils/glUtility.h
-- Installing: /usr/local/include/jetson-utils/imageIO.h
-- Installing: /usr/local/include/jetson-utils/loadImage.h
-- Installing: /usr/local/include/jetson-utils/devInput.h
-- Installing: /usr/local/include/jetson-utils/devJoystick.h
-- Installing: /usr/local/include/jetson-utils/devKeyboard.h
-- Installing: /usr/local/include/jetson-utils/Endian.h
-- Installing: /usr/local/include/jetson-utils/IPv4.h
-- Installing: /usr/local/include/jetson-utils/NetworkAdapter.h
-- Installing: /usr/local/include/jetson-utils/Socket.h
-- Installing: /usr/local/include/jetson-utils/Event.h
-- Installing: /usr/local/include/jetson-utils/Mutex.h
-- Installing: /usr/local/include/jetson-utils/Process.h
-- Installing: /usr/local/include/jetson-utils/Thread.h
-- Installing: /usr/local/lib/libjetson-utils.so
-- Installing: /usr/local/share/jetson-utils/cmake/jetson-utilsConfig.cmake
-- Installing: /usr/local/share/jetson-utils/cmake/jetson-utilsConfig-noconfig.cmake
-- Installing: /usr/local/bin/camera-viewer
-- Set runtime path of "/usr/local/bin/camera-viewer" to ""
-- Installing: /usr/local/bin/gl-display-test
-- Set runtime path of "/usr/local/bin/gl-display-test" to ""
-- Installing: /usr/local/bin/camera-viewer.py
-- Installing: /usr/local/bin/cuda-from-numpy.py
-- Installing: /usr/local/bin/cuda-to-numpy.py
-- Installing: /usr/local/bin/gl-display-test.py
-- Installing: /usr/lib/python2.7/dist-packages/jetson_utils_python.so
-- Set runtime path of "/usr/lib/python2.7/dist-packages/jetson_utils_python.so" to ""
-- Up-to-date: /usr/lib/python2.7/dist-packages/Jetson
-- Up-to-date: /usr/lib/python2.7/dist-packages/Jetson/Utils
-- Installing: /usr/lib/python2.7/dist-packages/Jetson/Utils/__init__.py
-- Installing: /usr/lib/python2.7/dist-packages/Jetson/__init__.py
CMake Error at utils/python/bindings_python_2.7/cmake_install.cmake:89 (file):
  file INSTALL cannot find
  "/home/nano01/jetson-inference/utils/python/bindings/../python/jetson".
Call Stack (most recent call first):
  utils/python/cmake_install.cmake:58 (include)
  utils/cmake_install.cmake:229 (include)
  cmake_install.cmake:128 (include)

Makefile:117: recipe for target 'install' failed
make: *** [install] Error 1 `

**Comment by surefyyq** [comment]
Hi @DabinGreat , how did you solve this issue, please?
