### ISSUE TITLE
ProfilerTimes may be wrong

### ISSUE THREAD

**Issue by msts35** [dusty-nv/jetson-inference#608]
Hi , 
When i test the model with net.PrintProfilerTimes() it gives me 40FPS, however when I put time.time at the start and end of the while loop and calculate the difference it gives me 10FPS , which one is true ? 
does not the speed of the loop represent the speed?

**Comment by dusty-nv** [comment]
Hi @msts35, `net.PrintProfileTimes()` prints out the times it takes for DNN inferencing, including pre/post-processing of the tensors.   The main loop may include other things, like camera aquisition, image loading, rendering, ect.  `glDisplay.GetFPS()` shows the speed of rendering.

**Comment by leandrovrabelo** [comment]
Using the module: from datetime import datetime

I use:
start = datetime.now().time()
inference()
end = datetime.now().time()

The difference show exactly what `net.PrintProfileTimes()` shows.

**Comment by msts35** [comment]
Thank you dustin and leandro, it lets me be disappointed.

So the program just gives me 10 frame with prediction at a second, am I right?

**Comment by dusty-nv** [comment]
On your setup, yes - perhaps your camera is only running at 10 FPS.

**Comment by msts35** [comment]
When I measure the image loading function, it takes 0.06ms but the network just use 0.03ms, so the bottleneck is loading image, isn't it funny a DNN is working faster than the process of loading a frame :) Reducing image quality makes smoother but just 5 fps improvement at 360p, is there any available way to load images faster?

**Comment by msts35** [comment]
thank you for mapping, I think to check if detection[n].left or top are negative value then make them 0 also if top+height or left+width bigger than resolution then decrease the height or width to fit resolution  of frame, is it logical?

I dont want to pass detected object, if it is possible
