### ISSUE TITLE
Clarification for Tutorial YouTube Video

### ISSUE THREAD

**Issue by inandi2015** [dusty-nv/jetson-inference#614]
It would be nice if this demo (https://www.youtube.com/watch?v=bcM5AQSAzUY&feature=youtu.be) could have a caption or description clarification that an onboard camera requires "0" or "1" rather than "/dev/video1" for example for specifying the camera module in one of the Python script lines since that only works for a USB camera. I had trouble following this at first since there was no demonstration of an onboard camera. I only realized going slow through the tutorial that a USB webcam was used since it wasn't clearly mentioned, and there was luckily an issue covering this with a Raspberry Pi Camera (https://github.com/dusty-nv/jetson-inference/issues/504). Thanks!

**Comment by dusty-nv** [comment]
Hi Iman, sorry about that, I had thought I called that out in the video but apparently it wasn't very clear.  Here is some documentation that describes it:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/detectnet-camera-2.md

Also you can run detectnet-camera (or imagenet-camera / segnet-camera) with the --help flag to get similar info.
________________________________
