### ISSUE TITLE
Jetson Nano G- Streamer Issue \\ Blocksize: 261

### ISSUE THREAD

**Issue by Oakshot** [dusty-nv/jetson-inference#615]
Good Morning,

I have a new Jetson Nano with the Jetpack 4,3.
For my detections i will use my RTSP Cams.
When I will crate a Pipeline with g streamer I became a error.

----
jetson@jetson-desktop:~$ gst-launch-1.0 rtspsrc location=rtsp://192.168.178.30:8554/live0.264 latency=200 ! rtph264depay ! h264parse ! nvv4l2decoder ! nvvidconv ! video/x-raw, format=BGRx, ! identity drop-allocation=true ! tee ! v4l2sink device=/dev/video0
Setting pipeline to PAUSED ...
Opening in BLOCKING MODE 
Opening in BLOCKING MODE 
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://192.168.178.30:8554/live0.264
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 

(gst-launch-1.0:7061): GStreamer-CRITICAL **: 07:54:59.236: gst_mini_object_unref: assertion 'mini_object != NULL' failed
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 

 ------------------

v4l2loopback is Installed.

Have any a idea to fix this?

**Comment by Neltherion** [comment]
Were you able to solve this problem?`
