### ISSUE TITLE
jetson.utils -- failed to free CUDA mapped memory with cudaFreeHost()

### ISSUE THREAD

**Issue by wrz57661** [dusty-nv/jetson-inference#617]
hi dustin,

I want to use two models in one project. One of them is ssd-mobilenetv2. But when they were put in the same py file,something went wrong.
However,the two models run normally in different py files simultaneously on the same nano board. How to solve this problem? Here are the information. Thank you!
Besides,when they are put in on py file, only one model needs to be run at a time.It still went wrong.

    detections = detect_model.Detect(img, 500, 343, "labels,conf")
Exception: jetson.inference -- detectNet.Detect() encountered an error classifying the image
jetson.utils -- freeing CUDA mapped memory
[cuda]  cudaFreeHost(ptr)
[cuda]     unspecified launch failure (error 4) (hex 0x04)
[cuda]     /home/waveshare/jetson-inference/utils/python/bindings/PyCUDA.cpp:121
jetson.utils -- failed to free CUDA mapped memory with cudaFreeHost()

**Comment by estratos** [comment]
I have the same issue 
`while True:
    _,frame=cam.read()
    if frame is not None:
       img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGBA).astype(np.float16)

    else:
        print("Error opening stream.. frame output is None ")
        cam.release()
        cv2.destroyAllWindows()
    	break 
    img=jetson.utils.cudaFromNumpy(img)
    classID, confidence =net.Classify(img, width, height)
    item=''`

[TRT]   networks/ResNet-18/ResNet-18.caffemodel loaded
imageNet -- loaded 1000 class info entries
networks/ResNet-18/ResNet-18.caffemodel initialized.
jetson.utils -- cudaFromNumpy()  ndarray dim 0 = 480
jetson.utils -- cudaFromNumpy()  ndarray dim 1 = 640
jetson.utils -- cudaFromNumpy()  ndarray dim 2 = 4
[TRT]   cudnnEngine.cpp (496) - Cuda Error in execute: 4
[TRT]   cudnnEngine.cpp (496) - Cuda Error in execute: 4
[TRT]   imageNet::Process() -- failed to execute TensorRT network
[TRT]   imageNet::Process() failed
Traceback (most recent call last):
  File "detect-model.py", line 53, in <module>
    classID, confidence =net.Classify(img, width, height)
Exception: jetson.inference -- imageNet.Classify() encountered an error classifying the image
jetson.utils -- freeing CUDA mapped memory
[cuda]  cudaFreeHost(ptr)
[cuda]     unspecified launch failure (error 4) (hex 0x04)
[cuda]     /home/nvidia/Downloads/jetson-inference/utils/python/bindings/PyCUDA.cpp:121
jetson.utils -- failed to free CUDA mapped memory with cudaFreeHost()
PyTensorNet_Dealloc()
[TRT]   runtime.cpp (21) - Cuda Error in free: 4
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
Aborted (core dumped)
