### ISSUE TITLE
invalid PyTorch version selected:  PyTorch python36 

### ISSUE THREAD

**Issue by wurongyuan** [dusty-nv/jetson-inference#639]
ubuntu 16.04
default python version --3.5
and I change the version to 3.6.9.
Then I run the ./install-pytorch.sh, it goes error.

**Comment by dusty-nv** [comment]
> ubuntu 16.04

Hi @wurongyuan , are you running this on your Jetson?   This script is for Jetson, not PC.

Also, this script is for JetPack 4.2 or newer (i.e. Ubuntu 18.04 on Jetson)

**Comment by wurongyuan** [comment]
Thank you.
