### ISSUE TITLE
Docker development support

### ISSUE THREAD

**Issue by mhs-achyut** [dusty-nv/jetson-inference#647]
Hello @dusty-nv I understand that jetson-inference is built for jetson devices. However I am trying to leverage the [jetson-containers](https://github.com/idavis/jetson-containers) repo to develop for my jetson device and was trying to run the example my-recognition app on an emulated jax container. I encountered the following error

```
root@969befaaa8f5:/opt/jetson-inference/examples/my-recognition/build# ./my-recognition ../black_bear.jpg 
NvRmPrivGetChipIdLimited: Could not read Tegra chip id/rev 
Expected on kernels without fuse support, using Tegra K1
NvRmPrivGetChipPlatform: Could not read platform information 
Expected on kernels without fuse support, using silicon
[image] loaded '../black_bear.jpg'  (800x656, 3 channels)
libnvrm_gpu.so: NvRmGpuLibOpen failed
[cuda]      unknown error (error 30) (hex 0x1E)
[cuda]      /opt/jetson-inference/build/aarch64/include/jetson-utils/cudaMappedMemory.h:51
[image] loadImage() -- failed to allocate 1574400 bytes for image '../black_bear.jpg'
failed to load image '../black_bear.jpg'
```

Is there a way I can run GPU inference examples using this sort of docker environment while developing for jetson? I am guessing we might need to copy some copy files from jetson-agx device itself and map them while running the docker container. Please let me know.

Thanks,
Achyut

**Comment by dusty-nv** [comment]
Hi Achyut, yes you would need to run on an actual Jetson device, you wouldn't be able to emulate these as the hardware engines of Jetson can't be emulated (GPU, camera ports, video encoders/decoders, ect)

On Jetson, the CUDA drivers and L4T drivers are mounted into docker containers at runtime:  https://github.com/NVIDIA/nvidia-docker/wiki/NVIDIA-Container-Runtime-on-Jetson#mount-plugins

**Comment by dusty-nv** [comment]
I do believe some folks have compiled jetson-inference on Linux x86, if you are just loading image files (like `my-recognition` does), that could work if you have an NVIDIA GPU in your PC (and CUDA/TensorRT installed).   It wouldn't be emulating a Jetson device, but it could allow you to run it at least.   Or you could get a $99 Jetson Nano to get started with natively, the code is the same as it is for Xavier.

**Comment by mhs-achyut** [comment]
I ended up developing on the Jetson AGX itself. However, I tried to run the jetson-inference on Linux x86 machine with no luck. 

```
./my-recognition black_bear.jpg 
[image] loaded 'black_bear.jpg'  (800x656, 3 channels)

imageNet -- loading classification network model from:
         -- prototxt     networks/googlenet.prototxt
         -- model        networks/bvlc_googlenet.caffemodel
         -- class_labels networks/ilsvrc12_synset_words.txt
         -- input_blob   'data'
         -- output_blob  'prob'
         -- batch_size   1

[TRT]    TensorRT version 7.0.0
[TRT]    loading NVIDIA plugins...
[TRT]    Plugin creator registration succeeded - ::GridAnchor_TRT
[TRT]    Plugin creator registration succeeded - ::NMS_TRT
[TRT]    Plugin creator registration succeeded - ::Reorg_TRT
[TRT]    Plugin creator registration succeeded - ::Region_TRT
[TRT]    Plugin creator registration succeeded - ::Clip_TRT
[TRT]    Plugin creator registration succeeded - ::LReLU_TRT
[TRT]    Plugin creator registration succeeded - ::PriorBox_TRT
[TRT]    Plugin creator registration succeeded - ::Normalize_TRT
[TRT]    Plugin creator registration succeeded - ::RPROI_TRT
[TRT]    Plugin creator registration succeeded - ::BatchedNMS_TRT
[TRT]    Could not register plugin creator:  ::FlattenConcat_TRT
[TRT]    Plugin creator registration succeeded - ::CropAndResize
[TRT]    Plugin creator registration succeeded - ::DetectionLayer_TRT
[TRT]    Plugin creator registration succeeded - ::Proposal
[TRT]    Plugin creator registration succeeded - ::ProposalLayer_TRT
[TRT]    Plugin creator registration succeeded - ::PyramidROIAlign_TRT
[TRT]    Plugin creator registration succeeded - ::ResizeNearest_TRT
[TRT]    Plugin creator registration succeeded - ::Split
[TRT]    Plugin creator registration succeeded - ::SpecialSlice_TRT
[TRT]    Plugin creator registration succeeded - ::InstanceNormalization_TRT
[TRT]    detected model format - caffe  (extension '.caffemodel')
[TRT]    desired precision specified for GPU: FASTEST
[TRT]    requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]    native precisions detected for GPU:  FP32, INT8
[TRT]    selecting fastest native precision for GPU:  FP32
[TRT]    attempting to open engine cache file /usr/local/bin/networks/bvlc_googlenet.caffemodel.1.1.7000.GPU.FP32.engine
[TRT]    loading network plan from engine cache... /usr/local/bin/networks/bvlc_googlenet.caffemodel.1.1.7000.GPU.FP32.engine
[TRT]    device GPU, loaded /usr/local/bin/networks/bvlc_googlenet.caffemodel
[TRT]    Deserialize required 1224219 microseconds.
[TRT]    Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
[TRT]    
[TRT]    CUDA engine context initialized on device GPU:
[TRT]       -- layers       66
[TRT]       -- maxBatchSize 1
[TRT]       -- workspace    0
[TRT]       -- deviceMemory 24653824
[TRT]       -- bindings     2
[TRT]       binding 0
                -- index   0
                -- name    'data'
                -- type    FP32
                -- in/out  INPUT
                -- # dims  3
                -- dim #0  3 (SPATIAL)
                -- dim #1  224 (SPATIAL)
                -- dim #2  224 (SPATIAL)
[TRT]       binding 1
                -- index   1
                -- name    'prob'
                -- type    FP32
                -- in/out  OUTPUT
                -- # dims  3
                -- dim #0  1000 (SPATIAL)
                -- dim #1  1 (SPATIAL)
                -- dim #2  1 (SPATIAL)
[TRT]    
[TRT]    binding to input 0 data  binding index:  0
[TRT]    binding to input 0 data  dims (b=1 c=3 h=224 w=224) size=602112
[TRT]    binding to output 0 prob  binding index:  1
[TRT]    binding to output 0 prob  dims (b=1 c=1000 h=1 w=1) size=4000
[TRT]    
[TRT]    device GPU, /usr/local/bin/networks/bvlc_googlenet.caffemodel initialized.
[TRT]    imageNet -- loaded 1000 class info entries
[TRT]    imageNet -- networks/bvlc_googlenet.caffemodel initialized.
[cuda]      no kernel image is available for execution on the device (error 48) (hex 0x30)
[cuda]      /home/achyut/projects/jetson-inference/c/tensorConvert.cu:81
[cuda]      no kernel image is available for execution on the device (error 48) (hex 0x30)
[cuda]      /home/achyut/projects/jetson-inference/c/imageNet.cpp:450
[TRT]    imageNet::PreProcess() -- cudaTensorMeanBGR() failed
[TRT]    imageNet::Classify() -- tensor pre-processing failed
failed to classify image
```

**Comment by prefpkg21** [comment]
> I ended up developing on the Jetson AGX itself. However, I tried to run the jetson-inference on Linux x86 machine with no luck.
> 
> ```
> ./my-recognition black_bear.jpg 
> [image] loaded 'black_bear.jpg'  (800x656, 3 channels)
> 
> imageNet -- loading classification network model from:
>          -- prototxt     networks/googlenet.prototxt
>          -- model        networks/bvlc_googlenet.caffemodel
>          -- class_labels networks/ilsvrc12_synset_words.txt
>          -- input_blob   'data'
>          -- output_blob  'prob'
>          -- batch_size   1
> 
> [TRT]    TensorRT version 7.0.0
> [TRT]    loading NVIDIA plugins...
> [TRT]    Plugin creator registration succeeded - ::GridAnchor_TRT
> [TRT]    Plugin creator registration succeeded - ::NMS_TRT
> [TRT]    Plugin creator registration succeeded - ::Reorg_TRT
> [TRT]    Plugin creator registration succeeded - ::Region_TRT
> [TRT]    Plugin creator registration succeeded - ::Clip_TRT
> [TRT]    Plugin creator registration succeeded - ::LReLU_TRT
> [TRT]    Plugin creator registration succeeded - ::PriorBox_TRT
> [TRT]    Plugin creator registration succeeded - ::Normalize_TRT
> [TRT]    Plugin creator registration succeeded - ::RPROI_TRT
> [TRT]    Plugin creator registration succeeded - ::BatchedNMS_TRT
> [TRT]    Could not register plugin creator:  ::FlattenConcat_TRT
> [TRT]    Plugin creator registration succeeded - ::CropAndResize
> [TRT]    Plugin creator registration succeeded - ::DetectionLayer_TRT
> [TRT]    Plugin creator registration succeeded - ::Proposal
> [TRT]    Plugin creator registration succeeded - ::ProposalLayer_TRT
> [TRT]    Plugin creator registration succeeded - ::PyramidROIAlign_TRT
> [TRT]    Plugin creator registration succeeded - ::ResizeNearest_TRT
> [TRT]    Plugin creator registration succeeded - ::Split
> [TRT]    Plugin creator registration succeeded - ::SpecialSlice_TRT
> [TRT]    Plugin creator registration succeeded - ::InstanceNormalization_TRT
> [TRT]    detected model format - caffe  (extension '.caffemodel')
> [TRT]    desired precision specified for GPU: FASTEST
> [TRT]    requested fasted precision for device GPU without providing valid calibrator, disabling INT8
> [TRT]    native precisions detected for GPU:  FP32, INT8
> [TRT]    selecting fastest native precision for GPU:  FP32
> [TRT]    attempting to open engine cache file /usr/local/bin/networks/bvlc_googlenet.caffemodel.1.1.7000.GPU.FP32.engine
> [TRT]    loading network plan from engine cache... /usr/local/bin/networks/bvlc_googlenet.caffemodel.1.1.7000.GPU.FP32.engine
> [TRT]    device GPU, loaded /usr/local/bin/networks/bvlc_googlenet.caffemodel
> [TRT]    Deserialize required 1224219 microseconds.
> [TRT]    Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
> [TRT]    
> [TRT]    CUDA engine context initialized on device GPU:
> [TRT]       -- layers       66
> [TRT]       -- maxBatchSize 1
> [TRT]       -- workspace    0
> [TRT]       -- deviceMemory 24653824
> [TRT]       -- bindings     2
> [TRT]       binding 0
>                 -- index   0
>                 -- name    'data'
>                 -- type    FP32
>                 -- in/out  INPUT
>                 -- # dims  3
>                 -- dim #0  3 (SPATIAL)
>                 -- dim #1  224 (SPATIAL)
>                 -- dim #2  224 (SPATIAL)
> [TRT]       binding 1
>                 -- index   1
>                 -- name    'prob'
>                 -- type    FP32
>                 -- in/out  OUTPUT
>                 -- # dims  3
>                 -- dim #0  1000 (SPATIAL)
>                 -- dim #1  1 (SPATIAL)
>                 -- dim #2  1 (SPATIAL)
> [TRT]    
> [TRT]    binding to input 0 data  binding index:  0
> [TRT]    binding to input 0 data  dims (b=1 c=3 h=224 w=224) size=602112
> [TRT]    binding to output 0 prob  binding index:  1
> [TRT]    binding to output 0 prob  dims (b=1 c=1000 h=1 w=1) size=4000
> [TRT]    
> [TRT]    device GPU, /usr/local/bin/networks/bvlc_googlenet.caffemodel initialized.
> [TRT]    imageNet -- loaded 1000 class info entries
> [TRT]    imageNet -- networks/bvlc_googlenet.caffemodel initialized.
> [cuda]      no kernel image is available for execution on the device (error 48) (hex 0x30)
> [cuda]      /home/achyut/projects/jetson-inference/c/tensorConvert.cu:81
> [cuda]      no kernel image is available for execution on the device (error 48) (hex 0x30)
> [cuda]      /home/achyut/projects/jetson-inference/c/imageNet.cpp:450
> [TRT]    imageNet::PreProcess() -- cudaTensorMeanBGR() failed
> [TRT]    imageNet::Classify() -- tensor pre-processing failed
> failed to classify image
> ```

What TensorRT version are you running? I looks like you are missing some plugins.
