### ISSUE TITLE
How to resize captured RTSP stream to smaller resolution using videoSource

### ISSUE THREAD

**Issue by mmatesic01** [dusty-nv/jetson-inference#648]
Hi,
Can we use an argument with RTSP stream to resize the captured stream to smaller resolution size?
Is there an "args" list to see what can we use?

Thanks.

**Comment by dusty-nv** [comment]
You should be able to use --input-width=x and --input-height=y

You can see the args by running program with --help.  Also the Camera Streaming and Multimedia page from the docs has examples.
________________________________

**Comment by mmatesic01** [comment]
Thank you.
