### ISSUE TITLE
net.Detect - Anyway to change overlay "box"  into a "line bordered" shape

### ISSUE THREAD

**Issue by mmatesic01** [dusty-nv/jetson-inference#651]
Is there a way to change "net.Detect(img, overlay=opt.overlay)" overlay "box" into a "line bordered" shape?
Thanks.

**Comment by dusty-nv** [comment]
I initially tried this, but for some reason it was buggy drawing the lines in my CUDA kernels vs. filled rect.   So for now it is filled rect.

**Comment by leandrovrabelo** [comment]
Why don't you try using OpenCV? something like this:

import cv2 

for i in range(len(detections)):

        img = cv2.rectangle(img, 
                                        (int(detections[i].Left), int(detections[i].Top)),
                                        (int(detections[i].Right), int(detections[i].Bottom)),
                                        detections[i].ClassID, 1)

**Comment by dusty-nv** [comment]
cv2 doesn't use GPU, so I don't want to use it in the master codeline.

But you could skip the overlay (`overlay=none`) and render your own with cv2.

**Comment by mmatesic01** [comment]
I already did that with cv2. 
I just hoped that I could eliminate cv2 out of the code and do the rectangle with jetson-inference.
Oh, well...

**Comment by firststep-dev** [comment]
You can use the following to show an outline, instead of a solid fill box: `--overlay=line`

Overlay options to choose from include: `box`, `lines`, `labels`, `conf`, and `none`

Reference: https://github.com/dusty-nv/jetson-inference/blob/master/docs/detectnet-console-2.md
