### ISSUE TITLE
How to save video processing on detectnet

### ISSUE THREAD

**Issue by Sgomes14843** [dusty-nv/jetson-inference#666]
Hello, I am using this code so that my model can process video instead of just images on the detectnet, it works but I can only see it while processing. How do I get him to record this video with the bounding boxes and results in an .mp4 file?
![Screenshot from 2020-07-31 00-13-04](https://user-images.githubusercontent.com/60934040/88983337-a3b11000-d2c2-11ea-809c-13bc4aeaa7f2.png)

**Comment by dusty-nv** [comment]
Hi @Sgomes14843 , add `videos/my_output.mp4` to the end of your command line.

**Comment by Sgomes14843** [comment]
Hi
![Screenshot from 2020-07-31 02-13-37](https://user-images.githubusercontent.com/60934040/89042681-398a8080-d33f-11ea-8f95-b3bffcf047d4.png)
, first thanks for responding.
I tried this but the output is like a text file instead of video. Do you know what it might be?

**Comment by Sgomes14843** [comment]
> Hi @Sgomes14843 , add `videos/my_output.mp4` to the end of your command line.
Hi, first thanks for responding.
I tried this but the output is like a text file instead of video. Do you know what it might be?
![Screenshot from 2020-07-31 02-13-37](https://user-images.githubusercontent.com/60934040/89042912-a00f9e80-d33f-11ea-8a0d-65a57a5549ae.png)

**Comment by Sgomes14843** [comment]
> Hi @Sgomes14843 , add `videos/my_output.mp4` to the end of your command line.

Hi, first thanks for responding.
I tried this but the output is like a text file instead of video. Do you know what it might be?
![Screenshot from 2020-07-31 02-13-37](https://user-images.githubusercontent.com/60934040/89042959-b4539b80-d33f-11ea-97d0-cf147dd4a92b.png)

**Comment by dusty-nv** [comment]
I think it loos like the text file icon shortly after the video has been created, before Ubuntu recognizes it.

If you try to open the video in a video player, does it play?

**Comment by Sgomes14843** [comment]
> I think it loos like the text file icon shortly after the video has been created, before Ubuntu recognizes it.
> 
> If you try to open the video in a video player, does it play?


If you open it in the video player it doesn't give and gives this error and if it opens as a notepad it is empty, there is nothing in the file
![Screenshot from 2020-07-31 01-23-28](https://user-images.githubusercontent.com/60934040/89058449-39967a80-d357-11ea-992d-c74f70ea9399.png)

**Comment by dusty-nv** [comment]
Can you provide the command line that you ran along with the terminal output?

Did the process shutdown gracefully when you either closed the GUI window or pressed Ctrl+C?

**Comment by Sgomes14843** [comment]
The command line:
`python3 detectnet.py --model=models/cars/ssd-mobilenet.onnx --labels=models/cars/labels.txt \
          --input-blob=input_0 --output-cvg=scores --output-bbox=boxes \
            videos/f1.mp4   videos/my_output.mp4`
Yes the process closed properly when i close the GUI or press CRTL + C
Here's what it says on the terminal when I close the GUI or press CTRL + C

**Comment by dusty-nv** [comment]
Hmm, well it appears to be running correctly.  If you run `ls -ll videos/my_output.mp4`, does it also show a size of 0 bytes?

**Comment by Sgomes14843** [comment]
Yes
![Screenshot from 2020-07-31 19-31-05](https://user-images.githubusercontent.com/60934040/89065908-6ef59500-d364-11ea-9f39-b8e9d9b29097.png)

**Comment by dusty-nv** [comment]
I can't seem to tell why it's doing that, sorry.   Can you try removing the backslashes (`\`) from your command line to see if that makes a difference:

```bash
python3 detectnet.py --model=models/cars/ssd-mobilenet.onnx --labels=models/cars/labels.txt  --input-blob=input_0 --output-cvg=scores --output-bbox=boxes  videos/f1.mp4 videos/my_output.mp4
```

Also can you try running the C++ version of the application?

```bash
detectnet --model=models/cars/ssd-mobilenet.onnx --labels=models/cars/labels.txt  --input-blob=input_0 --output-cvg=scores --output-bbox=boxes  videos/f1.mp4 videos/my_output.mp4
```

Failing that, please post the full text log of the programming running so I can look it over - thanks.

**Comment by Sgomes14843** [comment]
Unfortunately none of these lines of code worked.
How do i do the full text log of the programming running ?

**Comment by dusty-nv** [comment]
You can either copy it from your terminal into a text file, or launch the program like this with `| tee log.txt` to write the log:

```bash
detectnet --model=models/cars/ssd-mobilenet.onnx --labels=models/cars/labels.txt  --input-blob=input_0 --output-cvg=scores --output-bbox=boxes  videos/f1.mp4 videos/my_output.mp4 | tee log.txt
```

**Comment by Sgomes14843** [comment]
Thanks for teaching how to do this, here's the log file
[log.txt](https://github.com/dusty-nv/jetson-inference/files/5008723/log.txt)

**Comment by dusty-nv** [comment]
Thank you, I didn't identify any errors that jumped out at me.   But maybe try saving a different video format - `my_output.mkv` instead of `my_output.mp4`.   Does that help?

Also, it occurred to me to try a more regular input resolution instead of 854x480, like 640x480 (just as a test):

```bash
detectnet --model=models/cars/ssd-mobilenet.onnx --labels=models/cars/labels.txt  --input-blob=input_0 --output-cvg=scores --output-bbox=boxes --input-width=640 --input-height=480 videos/f1.mp4 videos/my_output.mkv
```

**Comment by Sgomes14843** [comment]
It worked, yeah!!!
Thank you so much for all your help and the time you spent
And I tested it with .mp4 and it worked so the problem was the resolution.

**Comment by dusty-nv** [comment]
Aha, ok - glad you got it working.  That is strange, is seems the encoder didn't like that resolution but didn't output any messages/warnings about it.  I will have to remember that...
