### ISSUE TITLE
Can Jetson support 3D convolution?

### ISSUE THREAD

**Issue by Ricardoluffy** [dusty-nv/jetson-inference#667]
I have a behavior recognition project, which is based on 3D convolution.
I would like to ask whether the Jetson  supports 3D convolution?

**Comment by dusty-nv** [comment]
Hi @Ricardoluffy , sure, you can run 3D conv in PyTorch, TensorFlow, ect.   Sometimes the memory usage of networks 3D convolution can get bigger, so you will want to check how much memory the network uses against how much memory your Jetson board has.

TensorRT also supports 3D convolution, see here:   https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#layers-matrix
