### ISSUE TITLE
Error while running my-detection.py [OpenGL] failed to create X11 Window. | jetson.utils -- no output streams, creating fake null output

### ISSUE THREAD

**Issue by tanueihorng** [dusty-nv/jetson-inference#669]
Hi! 

Anyone knows why i got this error while runing the python script ?
How can i solve it ? Thanks a lot!!!

![ERROR1](https://user-images.githubusercontent.com/61866167/89247661-6a6cfd00-d640-11ea-8b10-1a091daf8cda.png)
![error2](https://user-images.githubusercontent.com/61866167/89247673-70fb7480-d640-11ea-8fae-54b1ec2da051.png)
![error3](https://user-images.githubusercontent.com/61866167/89247675-72c53800-d640-11ea-9d5f-90b8d7f5f324.png)
![error4](https://user-images.githubusercontent.com/61866167/89247679-748efb80-d640-11ea-8cf4-dec09fc90742.png)

[FULLerror.txt](https://github.com/dusty-nv/jetson-inference/files/5019820/FULLerror.txt)

`import jetson.inference
import jetson.utils

net = jetson.inference.detectNet("ssd-inception-v2", threshold=0.4)
camera = jetson.utils.videoSource("rtsp://root:leadSingtel@192.168.8.120:554/axis-media/media.amp", argv=['--input-codec=h264'])
display = jetson.utils.videoOutput("display://0") # 'my_video.mp4' for file

while display.IsStreaming():
	img = camera.Capture()
	detections = net.Detect(img)
	display.Render(img)
	display.SetStatus("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))
`

**Comment by Rbara00** [comment]
Ive been having the same exact problem, did you figure it out?

**Comment by feimiao888** [comment]
Refer to #619, a temporary workaround is to move **import jetson.inference** after the line jetson.utils.videoOutput

**Comment by ngzhongcai** [comment]
Is this issue being worked at? I am trying to crop out detected images, and convert them to numpy arrays, using the jetson.utils methods. Above temporary solution precludes me from doing so.
