### ISSUE TITLE
re-training with custom voc dataset

### ISSUE THREAD

**Issue by silent-code** [dusty-nv/jetson-inference#672]
I was able to get the ssd detection re-training pipeline working with the open image dataset using the **train_ssd.py** script. Thanks so much. Really helpful! 

Now I've created a custom annotated dataset in PASCAL VOC format using the [labelImg](https://github.com/tzutalin/labelImg) app, as suggested. However, I don't have a clear idea how to correctly prepare the data for training and evaluation. For example, do we need to maually create the various .csv files similar to the ones that were created using the **open_images_downloader.py** script located in the /ssd/data subfolder?

**Comment by dusty-nv** [comment]
The CSV's are only for the open_images type of dataset.   labelImg should output a directory structure in the format of Pascal VOC dataset that should already be ready to use.

**Comment by silent-code** [comment]
Thank you.
