### ISSUE TITLE
imagnet fails to load

### ISSUE THREAD

**Issue by JVTEAM** [dusty-nv/jetson-inference#680]
[TRT]   coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[TRT]   INVALID_STATE: std::exception
[TRT]   INVALID_CONFIG: Deserialize the cuda engine failed.
[TRT]   device GPU, failed to create CUDA engine
[TRT]   failed to load networks/bvlc_googlenet.caffemodel
[TRT]   imageNet -- failed to initialize.
imagenet-console:   failed to initialize imageNet

**Comment by dusty-nv** [comment]
Hi @JVTEAM , delete your `bvlc_googlenet.*.engine` file and re-run - it should be found under:   `jetson-inference/data/networks`

For example, mine is `jetson-inference/data/networks/bvlc_googlenet.caffemodel.1.1.7103.GPU.FP16.engine`

Delete that, and then try running the program again.  It will re-build the engine for your updated version of TensorRT.

**Comment by JVTEAM** [comment]
That worked.  What needs to be deleted for detectnet?

**Comment by dusty-nv** [comment]
It depends on which model you are using.  Go into the models subfolder under `jetson-inference/data/networks/*` and delete all the `.engine` files.

**Comment by JVTEAM** [comment]
There's only one .engine and that's the one that just got rebuilt.  Detectnet and segnet are failing in similar fashion.
