### ISSUE TITLE
Issue with custom detection

### ISSUE THREAD

**Issue by w1ngedshadow** [dusty-nv/jetson-inference#690]
Hello NVIDIA, Im new to Jetson Nano and Linux so I decided to make my own detection dataset. I did all as in the tutorial (Collecting your own Detection Datasets) and got my own model (ssd-mobilenet.onxx). But when i try to run detectnet.py with my custom model (via this command: detectnet.py --model=models/mymodel/ssd-mobilenet.onnx --labels=models/mymodel/labels.txt \ --input-blob=input_0 --output-cvg=scores --output-bbox=boxes \ csi://0) jetson is trying to load model and crashes. And all time I am working with detectnet.py I have error  [TRT] Could not register plugin creator - ::FlattenConcat_TRT version 1, maybe it causes this? But with this error detectnet.py works pertfectly with default network (ssd-mobilenet-v2). What I have to do to fix this issues? Thanks

**Comment by w1ngedshadow** [comment]
@dusty-nv Is my question incorrect or I shared with you unreadable log? Thank you

**Comment by mnatsirm** [comment]
hi @w1ngedshadow , i also have the same issue when running detectnet.py on my custom model

**Comment by dusty-nv** [comment]
Sorry for the delay - can you run it with the C++ detectnet program?   For some reason, --input-blob --output-cvg and --output-bbox aren't parsing.  Could you try using underscore, i.e. --input_blob=abc --output_cvg=123 --output_bbox=xyz

**Comment by w1ngedshadow** [comment]
> Sorry for the delay - can you run it with the C++ detectnet program? For some reason, --input-blob --output-cvg and --output-bbox aren't parsing. Could you try using underscore, i.e. --input_blob=abc --output_cvg=123 --output_bbox=xyz

Hello, I got successful result with static image (c++ and python). Thank you for help!
But when i tried to run live camera (detectnet --model=models/myBModel/ssd-mobilenet.onnx --labels=models/myBModel/labels.txt  --input_blob=input_0 --output_bbox=boxes csi://0) with my custom model I got this new error:
URI -- invalid resource or file path:  cvg=scores
[video]  videoOptions -- failed to parse output resource URI (cvg=scores)
[video]  videoOutput -- failed to parse command line options
detectnet:  failed to create output stream

And if I run it with python (detectnet.py) I have no red errors in console, camera window hasnt open.

**Comment by w1ngedshadow** [comment]
I finally solved all problems with my custom detection. It  correctly works with static image and live stream. I think reason was in incorrect console commands.
Correct commands here.
`detectnet --model=models/myBModel/ssd-mobilenet.onnx --labels=models/myBModel/labels.txt  --input-blob=input_0 --output-cvg=scores --output-bbox=boxes input.jpg output.jpg`
or
`detectnet.py --model=models/myBModel/ssd-mobilenet.onnx --labels=models/myBModel/labels.txt  --input-blob=input_0 --output-cvg=scores --output-bbox=boxes input.jpg output.jpg
`
And for live detection I used my-detection.py example with my own network (modified "net = " string)
`net = jetson.inference.detectNet(argv=["--model=/home/user/jetson-inference/python/training/detection/ssd/models/myModel/ssd-mobilenet.onnx", "--labels=/home/user/jetson-inference/python/training/detection/ssd/models/myModel/labels.txt", "--input-blob=input_0", "--output-cvg=scores", "--output-bbox=boxes"], threshold=0.5)`

**Comment by mplaxman** [comment]
can you help me for same problem i tried all your commands ?
