### ISSUE TITLE
inference output value check

### ISSUE THREAD

**Issue by jh1113** [dusty-nv/jetson-inference#697]
Hello
I have a question.

Questions arose while using segnet-camera.py
The network uses the basic network, fcn-resnet18-cityscapes. 

The output value of the classes in question, i.e. wonder what percentage of the basis there is in judging an object as a car.

I also wonder how you can know these output values.

Thank you

**Comment by dusty-nv** [comment]
Hi @jh1113 , the confidence values aren't exposed via an API.   I'm not sure if softmax layer is applied in the FCN networks or not.

Here is the code where the argmax is picked:

https://github.com/dusty-nv/jetson-inference/blob/4e6b7ff37935a9bc64271119f42cd25366ce8c79/c/segNet.cpp#L763
