### ISSUE TITLE
RTP stream: How to view

### ISSUE THREAD

**Issue by TomAtWork** [dusty-nv/jetson-inference#699]
Has anyone a hint how to setup and view a rtp stream ? I tried  something like (that works with mp4 file output):
./detectnet-console --input-codec=h264 --output-codec=h264 --input-width=640 --input-height=352 --output-width=640 --output-height=352 --headless rtsp://192.168.111.104:8554 rtp://192.168.111.105:1234

and checked with wireshark that rtp data arrives at the destination, but VLC does not show any output (just shows the busy animation)?

Thanks in advance
Tom

**Comment by h3retek** [comment]
Hi,

Please have a look at this amazing repository.

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md
