### ISSUE TITLE
several boxes around same object

### ISSUE THREAD

**Issue by linukc** [dusty-nv/jetson-inference#703]
Hi. I create custom detectnet model (python) with my test dataset (60 photo). Is this problem (on the picture)
 linked with small dataset size? Have we got a instrument for avoiding boxes overlay or i have to wright my own? I don't want use box with highest score, because several object can be on the scene at the same time.
![Безымянный](https://user-images.githubusercontent.com/35877675/91749015-92149e00-ebc9-11ea-86d0-fe09cd1a0b77.png)

**Comment by berkantay** [comment]
What is the number of classes? After the transfer learning is done script mentions the number of classes according to labeling? It might be because of multipe classes pointing same object.

**Comment by linukc** [comment]
I have only one class in my model.

**Comment by linukc** [comment]
okay, all what i needed was method for non-maximum suppression.
