### ISSUE TITLE
Is it possible to train with rtx 3080 graphics card? I wonder if it fits the architecture that rtx introduces.

### ISSUE THREAD

**Issue by ingbeeedd** [dusty-nv/jetson-inference#712]
please answer my question..

**Comment by dusty-nv** [comment]
Yes, it can run CUDA/cuDNN/ect, and the pytorch training codes run on Linux PC as well.  you will need to install PyTorch following pytorch.org, not the jetson installer on PC.

Also you do not need to clone the entire jetson-inference repo on PC, you can just clone my pytorch submodules:

* https://github.com/dusty-nv/pytorch-classification
* https://github.com/dusty-nv/pytorch-ssd

**Comment by ingbeeedd** [comment]
Is the content that you mentioned only applied to rtx 30 or rtx series?

**Comment by dusty-nv** [comment]
It would be essentially any CUDA-capable GPU, so any of the relatively recent ones.  I personally use a 1070 for training in my laptop.   If it has >= 8GB VRAM that is nice.   Probably I wouldn't go less than 6GB VRAM for a training GPU.
