### ISSUE TITLE
How can I build the inference and utils modules for pyenv

### ISSUE THREAD

**Issue by maxsmadt** [dusty-nv/jetson-inference#714]
Hi,

I am using pyenv to manage my python versions (and also manually built OpenCV with CUDA support). I would like to ask how I can correctly build the jetson inference and utils modules for those environments?

**Comment by LewsTherin511** [comment]
Did you ever solve this? I'm having the same issue (using conda environment, but that shouldn't be a problem).
I ran the whole building procedure successfully, and I can use detectnet from the system python installation, but when switching to another virtual environment I get the error

    "ModuleNotFoundError: No module named 'jetson'"

**Comment by dusty-nv** [comment]
Let's continue this topic in the new thread here:  https://github.com/dusty-nv/jetson-inference/issues/1285
