### ISSUE TITLE
ModuleNotFoundError: No module named 'mhp_utils'

### ISSUE THREAD

**Issue by ThinkPig826** [dusty-nv/jetson-inference#722]
When i train my network, the error as follows.
~jetson-inference/python/training/segmentation$ python train.py --model-dir=LV-MHP-v1 ~/AI/LV-MHP-v1
pytorch-segmentation/datasets/__init__.py
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    from datasets.mhp import MHPSegmentation
  File "/home/yijiahe/AI/jetson-inference/python/training/segmentation/datasets/mhp.py", line 6, in <module>
    from mhp_utils import mhp_image_list
ModuleNotFoundError: No module named 'mhp_utils'

#################
But i do not find any package named 'mhp_utils'.

Environment:
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
Cuda compilation tools, release 10.2, V10.2.89

**Comment by dusty-nv** [comment]
Hi ThinkPig826, the file is in the repo under datasets/mhp_utils.py

I believe I run this with python3

**Comment by ThinkPig826** [comment]
thank you !
