### ISSUE TITLE
I want to know what COCO version.

### ISSUE THREAD

**Issue by hjlee9182** [dusty-nv/jetson-inference#725]
I know that COCO has 2 version (2014,2017).
So what version was used training in this repository?

**Comment by dusty-nv** [comment]
The SSD-Inception model is COCO 2017.

I believe SSD-Mobilenet is COCO 2014, but not certain.

The models were generated from:   https://github.com/AastaNV/TRT_object_detection
________________________________

**Comment by hjlee9182** [comment]
Thanks!

**Comment by hjlee9182** [comment]
@dusty-nv 

All of Classification model was trained ImageNet dataset ?
