### ISSUE TITLE
I wonder that why this model fps is lower than 'jetson becnhmarks' model?

### ISSUE THREAD

**Issue by hjlee9182** [dusty-nv/jetson-inference#731]
![image](https://user-images.githubusercontent.com/46337218/93728999-82eba380-fbfd-11ea-9bf2-96e241117548.png)

In this image from https://developer.nvidia.com/embedded/jetson-benchmarks

I'm running this repo and check model fps.
ssd-mobilenet-v1( this repo)'s fps is almost 10 , But that image ssd-mobilenet-v1's fps is almost 40.

Is it normal situation? if not how to develop to high fps?

**Comment by dusty-nv** [comment]
This is 90 class MS COCO model, whereas the other one was using fewer classes (37 I think)

With SSD-Mobilenet-v2 (COCO) you should get 22-25 FPS on Nano.
________________________________

**Comment by hjlee9182** [comment]
@dusty-nv 
Now I'm running on MAXN.
any other control to develop that?
