### ISSUE TITLE
I have a question for IMAGENET.

### ISSUE THREAD

**Issue by hjlee9182** [dusty-nv/jetson-inference#734]
I want to know about information for IMAGENET data that is trained this repo's classification model.

![image](https://user-images.githubusercontent.com/46337218/93853899-aee75180-fcef-11ea-9c85-6377ad546129.png)

I found a lot of IMAGENET, so I ask for you about version of IMAGENET.

**Comment by dusty-nv** [comment]
The pre-trained Googlenet model that comes with this project was trained on ILSVRC 2012.

**Comment by hjlee9182** [comment]
@dusty-nv 

Thank U!
