### ISSUE TITLE
SegNet - not AlexNet-based models?

### ISSUE THREAD

**Issue by LorenaGdL** [dusty-nv/jetson-inference#74]
Hello Dustin,

First of all, thank you for a great repository to get started with the Jetson platform. 

One question: is the SegNet inference only supporting Alexnet-based models? Are you planning on supporting other networks (such as VGG)? The pre-trained models on Alexnet are quite disappointing for now

**Comment by asmaa4may** [comment]
hi , if you have an algorithm for SegNet based alexnet i need it
