### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by RoboIndustries** [dusty-nv/jetson-inference#75]
When I built it on the Ubuntu 16.04, constantly got this error:

[ 56%] Built target jetson-inference
[ 59%] Building CXX object imagenet-console/CMakeFiles/imagenet-console.dir/imagenet-console.cpp.o
[ 62%] Linking CXX executable ../x86_64/bin/imagenet-console
**//usr/local/lib/libgstbase-1.0.so.0: undefined reference to `gst_element_message_full_with_details'
//usr/local/lib/libgstbase-1.0.so.0: undefined reference to `gst_make_element_message_details'**
collect2: error: ld returned 1 exit status
imagenet-console/CMakeFiles/imagenet-console.dir/build.make:101: recipe for target 'x86_64/bin/imagenet-console' failed
make[2]: *** [x86_64/bin/imagenet-console] Error 1
CMakeFiles/Makefile2:122: recipe for target 'imagenet-console/CMakeFiles/imagenet-console.dir/all' failed
make[1]: *** [imagenet-console/CMakeFiles/imagenet-console.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

It seems relate to the gstreamer, but I had no issue in the Ubuntu 14.04. Any suggestion will be highly appreciated.
Leon

**Comment by dusty-nv** [comment]
This log looks like jetson-inference being compiled on the x86_64 host.  However it’s intended to be built on the Jetson.
Some folks have succeeded in getting it compiled for host, however.   In this case your error is related to gstreamer.  I’m not sure what’s up with the versions, see:  https://mail.gnome.org/archives/desktop-devel-list/2017-February/msg00017.html
Perhaps you could try commenting out usage of gst_element_message_full_with_details() in jetson-inference code and see if it builds?

**Comment by iamblue** [comment]
+1

**Comment by iamblue** [comment]
I build it in tx2 has same problem

**Comment by dusty-nv** [comment]
Can you try commenting out the gstreamer logging function from the missing symbol and set if it builds?

It builds here in TX1, TX2 with latest JetPack.


-------- Original message --------

**Comment by dusty-nv** [comment]
Hi guys, support for TensorRT2 is working now in master with commit [e40bd6](https://github.com/dusty-nv/jetson-inference/commit/e40bd6abe9f07992f65dffeaa19e4d32eef78778)

For backwards compatibility, it's still building for previous JetPack's still on TensorRT1 using some macros I added. There were no outward-facing changes to the vision primitive APIs themselves.
