### ISSUE TITLE
Problems cloning jetson--interference

### ISSUE THREAD

**Issue by pjdervan** [dusty-nv/jetson-inference#753]
Hi,

I'm having problems cloning jetson-inference:

desktop:~$ git clone --recursive https://github.com/dusty-nv/jetson-inference
Cloning into 'jetson-inference'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (108/108), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

Does anyone have similar problems?

**Comment by dusty-nv** [comment]
Hmm I just tried re-cloning and didn't have an issue.

https://www.githubstatus.com/ is not showing a current outage.

**Comment by pjdervan** [comment]
OK. Thank you for checking. Must be a problem at mine end.

**Comment by ilackner** [comment]
Hi I'm getting a similar issue. 
Cloning into 'jetson-inference'...
fatal: unable to access 'https://github.com/dusty-nv/jetson-inference/': Could not resolve host: github.com

**Comment by dusty-nv** [comment]
@ilackner can you clone any github repo?   Maybe github was down for a time when you tried before.
