### ISSUE TITLE
Feeding different base model for transfer learning 

### ISSUE THREAD

**Issue by berkantay** [dusty-nv/jetson-inference#756]
I succesfully completed your demo. Now I want to change my algorithm from mobilenet ssd to faster-rcnn. I have a .pth file for that. How can I use that?

**Comment by dusty-nv** [comment]
I haven't tried Faster-RCNN or confirmed that it's ONNX export works with PyTorch (and that it's ONNX import works with TensorRT)

Also there is pre/post-processing implemented for each network architecture inside detectNet.cpp:

* https://github.com/dusty-nv/jetson-inference/blob/022739abc7631fa853ae63550ec091cd838b2105/c/detectNet.cpp#L729
* https://github.com/dusty-nv/jetson-inference/blob/022739abc7631fa853ae63550ec091cd838b2105/c/detectNet.cpp#L815

This code is to get the input image in the right tensor format, and to interpret the network outputs correctly (i.e. the bounding boxes, confidences, ect)
