### ISSUE TITLE
Some questions about the deploy precision of jetson.

### ISSUE THREAD

**Issue by Seakia** [dusty-nv/jetson-inference#76]
Hi, I used the digits platform to train one classified model and this model achieves one good performance such as the following pic.
![train_processure](https://cloud.githubusercontent.com/assets/9548796/25799381/5644defc-3417-11e7-96ec-85a4636a9a4c.png)

But when I deploy the caffemodel and prototxt file on tx2, the inference results are not good. 

And I do not do any modify and I only copy caffemodel, prototxt file, mean.binaryproto and label files and so on which are downloaded from digits to tx2 board and I load these files using the imageNet::Create function.

Do I have some error for the deployment? Do I need to modify somethings before using them? 

Or is it precision problem? As far as I know, tx2 is FP16 precision. Does the FP16 stand for using two bytes for 'float' type? So can it not achieve same good result as digits platform used on PC due to this fact?

My native is not English and the grammar maybe not accurate, and sorry for it. 

Thank you for your help.

**Comment by sulthanashafi** [comment]
Have you got it rectified?Iam also having the same problem that jetson not performing that well as if DIGITS do.Do anyone help me,solve it.

**Comment by Seakia** [comment]
I didn't solve it. I run caffe library on board. And The FPS of running caffe is close to running tensorRT for my codes.
