### ISSUE TITLE
Object detection, one box instead of several boxes overlapping?

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#760]
Hi,
Great tutorial. I have finished the custom object detection. And I am working on using two servos to track the object.
When an object is detected, it is often to have 2-3 green boxes instead of one. Is there anyway to see just one box?

Here is what I am doing for the servo tracking.
In the code of detectnet.py
for detection in detections:
I use detection.Area to find the smallest area and use the centre point to track the object. Not sure why it is jumpy...
I need to set the pixel tolerance(object centre point - window centre point) to 100 in order to make the servo stop shaking...

Thanks.

**Comment by dusty-nv** [comment]
Hi @AK51 , you can try decreasing the clustering intersection threshold on this line:

https://github.com/dusty-nv/jetson-inference/blob/501491767ad0127ee2905dcfedace1d7c07b8f2f/c/detectNet.h#L477

If you lower it, it will merge more overlapping bounding boxes.   If you raise it, it will merge less overlapping bounding boxes.

After you change it, run this to recompile:

``` bash
$ cd jetson-inference/build
$ make
$ sudo make install
```

**Comment by AK51** [comment]
Yes, it is working. Thx for your help.
