### ISSUE TITLE
bash: cd: jetson-inference/: no such file or directory

### ISSUE THREAD

**Issue by chrisTopp84** [dusty-nv/jetson-inference#769]
Hi,
I tried to follow your instructions but at the very beginning a problem occurs. 

> bash: cd: jetson-inference/: no such file or directory

Maybe it's because of the image I downloaded? (jetson-nano-4gb-jp441-sd-card-image)
I downloaded it from this page:
https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write

Or do I simply have to use a different directory?

Best regards
chris

**Comment by dusty-nv** [comment]
BTW when you see "cd jetson-inference/" it means to cd into the directory that you cloned the repo into.
________________________________
