### ISSUE TITLE
Run detectNet for different imagesize without resizing image

### ISSUE THREAD

**Issue by csadom** [dusty-nv/jetson-inference#77]
A trained detectnet  have a given imagesize as an input (if the input image is larger or smaller, detectnet resizes them). It is set in the begenning in the deploy.prototxt, as input_shape. If it is set to different size, ot works prorperly too since there is no fully connected layer in the detectnet. However, if it is reset, the network have to rebuild, which is long time, and i would like to run detectnet for different random size in short time. Is there any soluiton to solved this problem? Can I change something in order to not resize image in the begenning od detection?

Thanks

**Comment by dusty-nv** [comment]
Hi, instead of resize you could crop. But somehow the input has to match dimension to the network.

**Comment by qingzew** [comment]
@csadom I have the same problem, have you solve it
