### ISSUE TITLE
Mounting swap - make change persistent

### ISSUE THREAD

**Issue by chrisTopp84** [dusty-nv/jetson-inference#770]
Hi,

this is not a problem but a question. I'm not used to mount a swap space.

There is one command to make the change persistent. Does it mean that the swap space is "active" for everything I do on the jetson-nano? I think that this could be helpful from time to time.
Could you make me a littel smarter :)

Thanks in advance.

**Comment by dusty-nv** [comment]
Hi Chris, yes when you add your swap to /etc/fstab it will be automatically mounted after reboots and will be active for all processes in the system.
________________________________

**Comment by chrisTopp84** [comment]
Hi Dusty,

many thanks for the information :)
