### ISSUE TITLE
TensorRT Optimization

### ISSUE THREAD

**Issue by berkantay** [dusty-nv/jetson-inference#772]
Hello Dustin,

I am planning to use benefits of TensorRT on my JetsonTX2 Board. And I saw that you have used TensorRT on https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-ssd.md#processing-images-with-tensorrt . But I did not understand where exactly use this engine?

**Comment by dusty-nv** [comment]
Hi @berkantay , if you look at the source code of this repo under the `jetson-inference/c/` directory, that code uses TensorRT to run the models.   In particular, you can find a lot of the TensorRT code in [tensorNet.cpp](https://github.com/dusty-nv/jetson-inference/blob/master/c/tensorNet.cpp)
