### ISSUE TITLE
Performing transfer learning on other models

### ISSUE THREAD

**Issue by berkantay** [dusty-nv/jetson-inference#773]
Can we perform transfer learning other than mobilenet ssd?

**Comment by dusty-nv** [comment]
Hi @berkantay, the upstream pytorch-ssd has SSD/SSD-Lite implementations of MobileNetV1, MobileNetV2, and VGG, but I have not tested the others.

**Comment by dusty-nv** [comment]
You can certainly use PyTorch for training lots of other models, but the code would come from outside of this project.
