### ISSUE TITLE
Jetson-inference/build/aarch64 / bin/python program cannot run

### ISSUE THREAD

**Issue by wujianzhang1237** [dusty-nv/jetson-inference#774]
Jetson-inference/build/aarch64 / bin/python program cannot run，Show this error，ModuleNotFoundError: No module named 'jetson.inference'。Since the download speed of git clone in my foreign country is slow, I upload git clone package in window system to Jetson Nano via SSH.Is the module missing due to this reason?

**Comment by dusty-nv** [comment]
Hmm - are you able to run one of the C++ programs?

It should be fine to download a zip archive of the repo from GitHub, copy the zip to your Nano, and then extract the zip on your Nano.   

From your `jetson-inference/build` directory, did you run `sudo make install` and `sudo ldconfig`?   You may want to try those again.   

Does it work with python3?

If you continue to face problems, you may want to try [Running the Docker Container](https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-docker.md) instead.
