### ISSUE TITLE
Creating new dataset and training detectNet with that dataset

### ISSUE THREAD

**Issue by mozcelikors** [dusty-nv/jetson-inference#779]
Hi,
I integrated jetson-inference output to my Qt application using RTP URI recently. By doing this, I am running `detectnet-console.py input_URI output_URI` and see the result in my Qt application. Now, I would like to customize the image processing part.

I want to create a new dataset and label set and train detectNet with that dataset and then use it in `detectnet-console.py`. This way, I want to be able to detect objects with my own dataset and labels by using detectNet (keeping model intact). Basically, say, I want to detect traffic signs with detectNet and run it using jetson-inference ecosystem. What do I gotta do? Is there a guide somewhere which explains this procedure?

I'd be glad to hear about this. Thank you in advance.

**Comment by Fkjmp** [comment]
I am not sure if that is what you meant, but isn't this a guide on how to create your own dataset and use it for training: 
[https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect-detection.md](url)
