### ISSUE TITLE
detectnet: suppress all but maximum detection for each class

### ISSUE THREAD

**Issue by silent-code** [dusty-nv/jetson-inference#783]
Using detectnet, is it possible to suppress drawing on the image all but the maximum detection box for each class? I'm using the following command with 3 classes not including the Background class and I'd like for the image to only show the max bounding box per class if that class probability exceeds the threshold: 

detectnet --model=models/ppe/ssd-mobilenet.onnx --labels=models/ppe/labels.txt           --input-blob=input_0 --output-cvg=scores --output-bbox=boxes   --threshold=.15     "./images/ppe/ppe-test_1.jpg" ./images/test/ppe/ppe-test_1.jpg

Is this possible? Thanks in advance!

**Comment by dusty-nv** [comment]
Hi @silent-code, that isn't a built-in option, but you could modify the detectNet sample by removing the detections from the detections list that you don't want, and then using detectNet::Overlay() function (which accepts list of detections)
