### ISSUE TITLE
Structure for Creating Subclasses for Image Classification 

### ISSUE THREAD

**Issue by GOBish** [dusty-nv/jetson-inference#784]
Hi @dusty-nv ,
Thanks again for the great tutorials.
I am trying to create a custom image classification model that has subclasses. Could you demonstrate what the file structure and labels.txt format should look like?

For example:
Dinasour
--Velociraptor
--Trex

Fish
--Salmon
--Tuna

So far, I have made the file system as below:

Training
-Main Class 1(i.e. Dinasour)
--subclass 1 (i.e. Trex)
----img1.jpg

-Main Class 2(i.e. fish)
--subclass 1 (i.e. salmon)
----img2.jpg

Is that correct?
I'm not sure how to make the labels.txt file though!

Thanks!

**Comment by dusty-nv** [comment]
Hi GOBish, this document shows the structure of classification dataset:   https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect.md
________________________________

**Comment by GOBish** [comment]
Thanks @dusty-nv — I have used that successfully for creating object classification and it works well.
Do you have any examples, though, related to my question above of having sub-classes?
Thanks!

**Comment by dusty-nv** [comment]
I haven't seen that supported with ResNet, GoogleNet, ect.   They just support N number of classes.  Additional structure you would have to store yourself in another file (i.e. Golden Retriever is Dog)
________________________________

**Comment by GOBish** [comment]
Ok, got it.
Do you think there is a way to approach it with multi-label classifying, as described here:
https://www.learnopencv.com/multi-label-image-classification-with-pytorch/

**Comment by dusty-nv** [comment]
That article is using a model that they modified to do multi-label classification- you would need to export it from PyTorch to ONNX and see if you could load it with trtexec (from /usr/src/tensorrt/bin).

Then you would have to modify imageNet C++ class to interpret the multiple outputs.

Of course, you could just run it in PyTorch on the Jetson if the PyTorch performance is good enough for you.
________________________________

**Comment by GOBish** [comment]
Got it! Thanks as always @dusty-nv
