### ISSUE TITLE
How to run this with Jetbot & Jupyter?

### ISSUE THREAD

**Issue by villesau** [dusty-nv/jetson-inference#790]
Hi,

What is the recommended way to run this with Jetbot & Jupyter notebook? Is there a way to install this as a library?

**Comment by dusty-nv** [comment]
You can run it in a Jupyter notebook, but if you want to view the video stream remotely, I recommend using RTP streaming as shown here:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#transmitting-rtp
