### ISSUE TITLE
failed to initialize segnet

### ISSUE THREAD

**Issue by wuzhishiwo** [dusty-nv/jetson-inference#795]

**Comment by wuzhishiwo** [comment]
![Screenshot from 2020-11-13 13-09-15](https://user-images.githubusercontent.com/71299816/99077853-5c902600-25f8-11eb-9032-06a473a1fb72.png)

**Comment by dusty-nv** [comment]
It appears that you have a space in `--network= fcn-alexnet-aerial-fpv-720p`

Can you try removing the space and trying `--network=fcn-alexnet-aerial-fpv-720p`

**Comment by wuzhishiwo** [comment]
Thank you very much ,but I have remove the space, and the same problem appears, Are there other problems?my version is jetpack3.3, and I choose the L4T-R28.1 branch.

**Comment by wuzhishiwo** [comment]
> It appears that you have a space in `--network= fcn-alexnet-aerial-fpv-720p`
> 
> Can you try removing the space and trying `--network=fcn-alexnet-aerial-fpv-720p`
Thank you very much ,but I have remove the space, and the same problem appears, Are there other problems?my version is jetpack3.3, and I choose the L4T-R28.1 branch.
