### ISSUE TITLE
Using custom Digits trained model in TX1 inference.

### ISSUE THREAD

**Issue by loukbabi** [dusty-nv/jetson-inference#8]
Hello Dusty.

I managed to successfully run your example with no issues (Jetpack 2.3). I would like to use my own DetectNet, which I trained using Digits 4 as shown in this example (https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection), for inference on TX1. I believe that I have changed all the corresponding fields of your repository in order to load my own .prototxt, .caffemodel and .binaryproto files. After running the detectnet-console example I get the following error:

./detectnet-console /home/ubuntu/Downloads/car2.jpg
detectnet-console
  args (2):  0 [./detectnet-console]  1 [/home/ubuntu/Downloads/car2.jpg]  

[GIE]  platform has FP16 support.
[GIE]  loading /home/ubuntu/code/digits/gie_dusty1/jetson-inference/detectnet_car_model/deploy.prototxt /home/ubuntu/code/digits/gie_dusty1/jetson-inference/detectnet_car_model/snapshot_iter_191190.caffemodel
could not parse layer type Python
[GIE]  failed to parse caffe network
failed to load /home/ubuntu/code/digits/gie_dusty1/jetson-inference/detectnet_car_model/snapshot_iter_191190.caffemodel
detectNet -- failed to initialize.
detectnet-console:   failed to initialize detectNet

Tracing back this leads me to the detectNet.cpp file where I found that the error occurs during the net->LoadNetwork(...) command. Is there any idea about the origin of this problem?

Thank you!

**Comment by dusty-nv** [comment]
Hi loukbabi, 

GIE does not support the Python clustering layer.  It should be removed from the prototxt and re-run.  The detectNet class from the repo contains the clustering code instead.

Best regards,
Dustin

**Comment by S4WRXTTCS** [comment]
I also ran into this issue, but even when you remove it from the prototxt it will come back with the same error message.  Apparently it got far enough to cache it, and now it pulls up the cache'd one. 

I haven't gotten it to work quite yet because I haven't figured out how to delete the cache'd version,
