### ISSUE TITLE
my-detection.py

### ISSUE THREAD

**Issue by Hasandaoud** [dusty-nv/jetson-inference#803]
hi

i trained ssd-mobilenet on my own dataset and tested it using: 
NET=models/<YOUR-MODEL>

detectnet --model=$NET/ssd-mobilenet.onnx --labels=$NET/labels.txt \
          --input-blob=input_0 --output-cvg=scores --output-bbox=boxes \
            csi://0
on terminal

i tried my-detection.py and it worked on the default model.
how can i run it on my trained model?

thank you.

**Comment by dusty-nv** [comment]
Hi @abu3ali, try changing [this](https://github.com/dusty-nv/jetson-inference/blob/c8a0392b1b49d9892aa4ec0556eb058f5d2e7145/python/examples/my-detection.py#L27) line of my-detection.py to the following:

``` python
net = jetson.inference.detectNet(argv=['--model=models/ssd-mobilenet.onnx', '--labels=models/labels.txt', '--input-blob=input_0', '--output-cvg=scores', '--output-bbox=boxes'], threshold=0.5)
```
