### ISSUE TITLE
my-detection.py didnt open

### ISSUE THREAD

**Issue by DylanTan997** [dusty-nv/jetson-inference#807]
Hi,

I was following the video online and typed this code:

[my-detection (copy).txt](https://github.com/dusty-nv/jetson-inference/files/5565665/my-detection.copy.txt)

The terminal  logs came with this

[Terminal Log.txt](https://github.com/dusty-nv/jetson-inference/files/5565676/Terminal.Log.txt)

Any ideas?

Thanks

**Comment by dusty-nv** [comment]
Hi @DylanTan997 , there is a typo on the last line of code - `display.SetTtile`

Instead, it should be `display.SetTitle`
