### ISSUE TITLE
How to see the training picture with XML (object detection)?

### ISSUE THREAD

**Issue by AK51** [dusty-nv/jetson-inference#811]
Hi,
I have training my own object detection by following "Collecting your own Detection Datasets"
After the training, two labels never showed up and I suspect my train/var data have some problem.
How can I see my collected data? Is there a software to show the XML data on the picture?

One time, during the data collection, I saved one wrong label. What is the proper way to delete it? Delete the picture, and delete the XML file in train, var, test, right? (I set the merge data during data collect)

Thanks,
Andy

**Comment by dusty-nv** [comment]
Hi @AK51, I haven't tried this, but I found this tool which appears to visualize datasets in Pascal VOC format:

https://github.com/rmalav15/visualize-voc-format-data



> One time, during the data collection, I saved one wrong label. What is the proper way to delete it? Delete the picture, and delete the XML file in train, var, test, right? (I set the merge data during data collect)

Technically all you need to do is remove that ImageID from the .txt files under `ImageSets/Main` (test/train/trainval/val)

But if you wanted to completely remove it from the dataset, then also delete the image from `JPEGImages/` and the XML from `Annotations/`
