### ISSUE TITLE
ImportError:No module named 'jetson'

### ISSUE THREAD

**Issue by wuzhishiwo** [dusty-nv/jetson-inference#813]
I have not started the container,I don't know if this step is necessary, I just run the .py and the image, and then the question occured, if you know how to solve,please tell me.

**Comment by wuzhishiwo** [comment]
-

**Comment by wuzhishiwo** [comment]
![Uploading 111.png…]()

**Comment by wuzhishiwo** [comment]
![1111](https://user-images.githubusercontent.com/71299816/99924358-f3857c80-2d74-11eb-8177-084fa8ac6442.png)

**Comment by dusty-nv** [comment]
Hi @wuzhishiwo , if you did not [Build from Source](https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-repo-2.md), then yes you would need to [Run the Container](https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-docker.md) first.

When starting the container, you can mount your `my-recognition-python` directory into the container like so:

``` bash
docker/run.sh --volume ~/my-recognition-python:/my-recognition-python
```
It will then show up inside the container under `/my-recognition-python`
