### ISSUE TITLE
video-viewer rtsp input and rtp output

### ISSUE THREAD

**Issue by gyillikci** [dusty-nv/jetson-inference#815]
Hello,

I would like to connect an IP camera which serves the video through rtsp. I can get the video via:
`video-viewer rtsp://username:password@<remote-ip>:1234`
My aim is to get the video of IP camera and send it to another remote jetson via rtp. 
something like below:
`video-viewer rtsp://username:password@<remote-ip>:1234 rtp://<remote-ip>:1235 `
Is this possible? I would be happy to have alternative ideas.

Thank you

**Comment by dusty-nv** [comment]
Hi @gyillikci , yes it should be possible to transmit RTP.   You appear to already have the correct syntax to do it.   For more info, please see here:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#transmitting-rtp
