### ISSUE TITLE
DetectNet + MSCOCO problem

### ISSUE THREAD

**Issue by antoniodourado** [dusty-nv/jetson-inference#82]
Hey there.

I'm trying to train a DetectNet based on dusty example with MSCOCO. I developed a python script to convert COCO annotations to KITTI format and the built the dataset normally.
I adapted the network as follows:

_name: "DetectNet"
layer {
  name: "train_data"
  type: "Data"
  top: "data"
  data_param {
    backend: LMDB
    source: "/media/antonio/LinuxOutro/DIGITS/digits/jobs/20170522-184156-7112/train_db/features/data.mdb"
    batch_size: 10
  }
  include: { phase: TRAIN }
}
layer {
  name: "train_label"
  type: "Data"
  top: "label"
  data_param {
    backend: LMDB
    source: "/media/antonio/LinuxOutro/DIGITS/digits/jobs/20170522-184156-7112/train_db/labels/data.mdb"
    batch_size: 10
  }
  include: { phase: TRAIN }
}
layer {
  name: "val_data"
  type: "Data"
  top: "data"
  data_param {
    backend: LMDB
    source: "/media/antonio/LinuxOutro/DIGITS/digits/jobs/20170522-184156-7112/val_db/features/data.mdb"
    batch_size: 6
  }
  include: { phase: TEST stage: "val" }
}
layer {
  name: "val_label"
  type: "Data"
  top: "label"
  data_param {
    backend: LMDB
    source: "/media/antonio/LinuxOutro/DIGITS/digits/jobs/20170522-184156-7112/val_db/labels/data.mdb"
    batch_size: 6
  }
  include: { phase: TEST stage: "val" }
}
layer {
  name: "deploy_data"
  type: "Input"
  top: "data"
  input_param {
    shape {
      dim: 1
      dim: 3
      dim: 640
      dim: 640
    }
  }
  include: { phase: TEST not_stage: "val" }
}_

The LMDB source I pointed to the "data.mdb" files generated by Digits. I couldn't find the lmdb files and considered that these were correct. Is it?

It took 24 hours to train and it's not working at all with mAP zero. It doest give me any bbox even when I test with the train images:
![results](https://cloud.githubusercontent.com/assets/110608/26383046/e7f1ec78-4006-11e7-9547-09dcaa99dc72.png)

Here are the parameters for model training:
![configs](https://cloud.githubusercontent.com/assets/110608/26383081/288a31c8-4007-11e7-97e3-9375a0d5ad06.png)

Here an example of image with the following label:
`sink 0 0 0 0.0 346.43 180.78 79.66 0 0 0 0 0 0 0`
`bowl 0 0 0 359.22 385.68 24.07 19.57 0 0 0 0 0 0 0`

When I submit it to test for detecting with bboxes:
![zeros](https://cloud.githubusercontent.com/assets/110608/26383366/b48c8f9e-4008-11e7-82d7-9d3537f03eb9.png)

Obviously I messed something up, can you guys help me out here?

**Comment by YTed** [comment]
Hi, I have a similar situation. But you should not ask here, try seeking for help [there](https://github.com/NVIDIA/DIGITS/issues), good luck.
