### ISSUE TITLE
[Question] TensorRT video inference example.

### ISSUE THREAD

**Issue by berkantay** [dusty-nv/jetson-inference#826]
Hello @dusty-nv,
I am trying to make inference from live video using TensorRT engine. I am having memory issues during inference from a live stream after the first frame. Have you got any example code for running the engine on a video?

**Comment by dusty-nv** [comment]
Hi @berkantay, please see here for info about playing video files: 

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#video-files
