### ISSUE TITLE
Error with "train_ssd.py"

### ISSUE THREAD

**Issue by DylanTan997** [dusty-nv/jetson-inference#829]
![Terminal Error](https://user-images.githubusercontent.com/74696909/100982552-230d6380-3583-11eb-8319-6d03cb4041d0.png)
Hi, needed some help after creating our own dataset and attempting to retrain

![ImageSetMain text Files](https://user-images.githubusercontent.com/74696909/100982534-1e48af80-3583-11eb-9f28-0be9705a9550.png)
![Permission Denied](https://user-images.githubusercontent.com/74696909/100982957-a333c900-3583-11eb-9702-bd202805d552.png)

We tried to copy over our ImageIDs to create test.txt and val.txt but was denied access due to permission. Is there a way to be granted access to add the text files or are we missing something?

Thanks.

**Comment by dusty-nv** [comment]
You can change the permissions so that your user can read/write your datasets files with this command:

``` bash
sudo chmod -R 666 /home/tailu/jetson-inference/python/training/detection/ssd/data/items
```
