### ISSUE TITLE
the error of 'jetson-inference/build/aarch64/bin/'

### ISSUE THREAD

**Issue by hejun888** [dusty-nv/jetson-inference#830]
hi dusty-nv:
why my fold('jetson-inference/build/aarch64/bin/') is below 
![Lark20201203-172136](https://user-images.githubusercontent.com/28728850/100989657-09bce500-358c-11eb-937b-47f1d479ef37.png)
and not networks and images

**Comment by dusty-nv** [comment]
Hi @hejun888 , are you missing the `networks/` and `images/` symbolic link?

These should be setup during the `cmake ../` step when you built the project.    Are you sure your disk is formatted as EXT3 or EXT4?    If you are storing this on a FAT or NTFS drive, it won't be able to make symbolic links.

If it is indeed an EXT3/EXT4 drive, you can make the symlinks yourself like so:

``` bash
cd /path/to/your/jetson-inference/build/aarch64/bin
ln -s /path/to/your/jetson-inference/data/networks networks
ln -s /path/to/your/jetson-inference/data/images images
```

**Comment by hejun888** [comment]
dusty-nv，This question is difficult for me，the disk is formatted as EXT4 as shown in the image below
![Lark20201204-102810](https://user-images.githubusercontent.com/28728850/101114039-9793e100-361b-11eb-8b0a-cc989cf74323.png)
after executing the cmake ../ many times, there are no images/ and networks/ but as below
![Lark20201204-103437](https://user-images.githubusercontent.com/28728850/101114394-594af180-361c-11eb-9dd2-5133460638cc.png)
