### ISSUE TITLE
error: MESA-LOADER: failed to open swrast 

### ISSUE THREAD

**Issue by hejun888** [dusty-nv/jetson-inference#832]
Hi,
Thank you for making this great tutorial!
I have installed the project but when I try to run the imagenet-camera.py demo, I got this error
 
![Lark20201204-144057](https://user-images.githubusercontent.com/28728850/101130616-c1aaca80-363e-11eb-81d9-813d83ea51f7.png)

And show no picture as below when the program is finished. It seems that my OpenGL lin is broken? Have you ever encountered this issue? 
![Lark20201204-173617](https://user-images.githubusercontent.com/28728850/101147389-43a6ed80-3657-11eb-82bb-080b92d0b855.png)

Thank you!

**Comment by dusty-nv** [comment]
Hmm...is your display connected to your Jetson, or are you running headlessly over SSH?

Are you able to run glxgears or glxinfo?   (you may have to install the mesa-utils package first)

This may repair your OpenGL installation if you install it:  https://github.com/NVIDIA/libglvnd

Alternatively, you could try the jetson-inference container, or if all else fails re-flash your SD card to get OpenGL back.

**Comment by hejun888** [comment]
thanks,now, it's OK

**Comment by Kshitij09-ag** [comment]
I'm also facing the same issue and I'm running headlessly but have opened the screen via VNC server

**Comment by Kshitij09-ag** [comment]
Thanks for the quick reply @dusty-nv. I tried using rtp but for some reason I was not able to stream that rtp on VLC

**Comment by dusty-nv** [comment]
> Thanks for the quick reply @dusty-nv. I tried using rtp but for some reason I was not able to stream that rtp on VLC

VLC can be finiky with RTP.  Try installing GStreamer on your PC instead:   https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-streaming.md#viewing-rtp-remotely
