### ISSUE TITLE
Is it possible to delete or overwrite the mounted directory?

### ISSUE THREAD

**Issue by 2g1bz0** [dusty-nv/jetson-inference#833]
I'm sorry if my translation is wrong.
I downloaded the fuit data from the open image dataset. I thought there were too many images downloaded. So I used the same code again to specify 2500 sheets. I specified the fruit folder, so I thought I'd overwrite it, but the number of images didn't decrease. Is there a way to overwrite it? It was also mounted on the container and could not be removed. Please tell me how to delete or overwrite the mounted directory.
Thank you

**Comment by dusty-nv** [comment]
Hi @2g1bz0 , first shutdown the container, and then delete the fruit dataset folder with sudo.   Then you should be able to download it again.
