### ISSUE TITLE
How to watch the detected video on my pc without wi-fi

### ISSUE THREAD

**Issue by 2g1bz0** [dusty-nv/jetson-inference#836]
Hi.
I'm sorry if the translation is wrong.
I want to output the detected video of jetson nano to my PC. I'm not going to use wifi. Can this be achieved using a usb cable? Can it be achieved using gstreamer and vlc?
thank you.

**Comment by dusty-nv** [comment]
Hi @2g1bz0, if you connect the microUSB port on your Jetson to your PC, it should automatically create a virtual USB connection.  Your Jetson will have a static IP of 192.168.55.1 on that interface.   You should be able to use that networking connection to stream the video just like you would wifi.  Alternatively, you could connect an ethernet cable or via an ethernet switch.
