### ISSUE TITLE
git submodule update --init no result

### ISSUE THREAD

**Issue by yuyuanc-chen** [dusty-nv/jetson-inference#840]
Hi. I was building the project from source.I totally do the every step.But when I input the command git submodule update --init,there is no response.Then I input cmake ../  and it occures :required git submodules have not been detected.First,please run the git submodule update --init  from the project's roo directory to clone them.But I run the comman for servral times without any response.I don't know how to solve it.

**Comment by dusty-nv** [comment]
Hmm ok.   Can you try re-cloning the repo with the `--recursive` flag, like below?

``` bash
$ git clone --recursive https://github.com/dusty-nv/jetson-inference
```

This will automatically grab the submodules for you, so you won't need the `git submodule` step then.

**Comment by yuyuanc-chen** [comment]
Thank you.I can't download it by git clone xx because vpn doesn't work. I download it on the github directely.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dustin Franklin"<notifications@github.com&gt;; 
发送时间: 2020年12月12日(星期六) 凌晨4:21
收件人: "dusty-nv/jetson-inference"<jetson-inference@noreply.github.com&gt;; 
抄送: "1002067845"<1002067845@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dusty-nv/jetson-inference] git submodule update --init no result (#840)





 
Hmm ok.   Can you try re-cloning the repo with the --recursive flag, like below?
 $ git clone --recursive https://github.com/dusty-nv/jetson-inference
 
This will automatically grab the submodules for you, so you won't need the git submodule step then.
