### ISSUE TITLE
Read the content of PyCapsule using jetson.utils.cudaToNumpy

### ISSUE THREAD

**Issue by bilel-bj** [dusty-nv/jetson-inference#841]
I had a buffer is of type PyCapsule. I tried to read it using the instruction:

jetson.utils.cudaToNumpy(buffer)

but got this error:

Exception: jetson.utils – cudaToNumpy() failed to get input CUDA pointer from first arg (should be cudaImage or cudaMemory)

How to read this buffer?

**Comment by dusty-nv** [comment]
Hi @bilel-bj , please refer to this post from the forums:

https://forums.developer.nvidia.com/t/what-is-pycapsule-objects-in-jetson-inference-python-scripts/78793/27?u=dusty_nv

Also this part of the documentation shows how to access the pixel data from Python:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-image.md#image-capsules-in-python
