### ISSUE TITLE
docker/run.sh error about permission

### ISSUE THREAD

**Issue by ingbeeedd** [dusty-nv/jetson-inference#849]
There was an error executing docker/run.sh

I think there was an error in the running part after installing the model. The strange thing is that the owner of the training/classification is `root`, is it correct?

![1](https://user-images.githubusercontent.com/57895472/102452610-f88cd180-407d-11eb-9555-f0e79e84e61f.png)
![2](https://user-images.githubusercontent.com/57895472/102452621-fb87c200-407d-11eb-92b0-a6f128dba0c5.png)

**Comment by ingbeeedd** [comment]
In addition, ssd wget failed in model folder due to permission issue

**Comment by dusty-nv** [comment]
What version of JetPack are you running?   It should be JetPack 4.4.1 (L4T R32.4.4) to run the jetson-inference:r32.4.4.   There is also a container tag for JetPack 4.4 (L4T R32.4.3), jetson-inference:r32.4.3.

The folder permissions seem unrelated - you can run wget with sudo or change the folder permissions with `chmod -R 666 <directory>`

**Comment by ingbeeedd** [comment]
I've only run a Docker script, and that directory has root privileges. When checking nv_tegra_release, it is 4.4.

**Comment by ingbeeedd** [comment]
I just installed the github contents after installing the jetpack, so I don't think there will be any conflicts.

**Comment by ingbeeedd** [comment]
It's good to do it on the server, not the docker client.
