### ISSUE TITLE
error when detectnet run

### ISSUE THREAD

**Issue by 2g1bz0** [dusty-nv/jetson-inference#852]
When I run detectnet, I get the following error: Can you help me (I used sudo, but it failed.)

[TRT]    note -- when processing a single image, run 'sudo jetson_clocks' before
                to disable DVFS for more accurate profiling/timing measurements

[image] imageLoader -- End of Stream (EOS) has been reached, stream has been closed

**Comment by dusty-nv** [comment]
I think it loaded and ran an image, because of that `[TRT]` message you see.  That wouldn't be printed if it didn't run the model on at least one image.

Neither of these messages are errors.
