### ISSUE TITLE
Some Problems about onnx to trt in jetson nano

### ISSUE THREAD

**Issue by yuyuanc-chen** [dusty-nv/jetson-inference#859]
I transformed a model trained by pytorch to onnx.And when I detected  a image  in jetson nano.It showed  model format 'custom' not suppooted by jetson-inference. What's  the problem? Can U help me

**Comment by dusty-nv** [comment]
Hi @yuyuanc-chen , can you post the detectnet command line that you ran and the console log?   Thanks.
