### ISSUE TITLE
I have a question about the ssd transfer learning

### ISSUE THREAD

**Issue by ingbeeedd** [dusty-nv/jetson-inference#860]
I downloaded the model I learned through VOC during ssd transfer learning in docs, but why didn't you do it with COCO based SSD mobilenet? Is it possible with COCO? Where can I download the model?

**Comment by dusty-nv** [comment]
The COCO-based SSD-Mobilenet came from the TensorFlow Model Zoo and was trained with TensorFlow, not PyTorch.

In theory you could train a similar COCO model in PyTorch, but you would need to adapt the training script to be able to use the [`torchvision.datasets.coco`](https://pytorch.org/docs/0.4.0/_modules/torchvision/datasets/coco.html) dataloader.

The VOC model works fine for transfer learning, so I haven't felt the need to make the above changes for COCO.
