### ISSUE TITLE
How to correctly transpose dimensions in input frame?

### ISSUE THREAD

**Issue by SergeyMalashenko** [dusty-nv/jetson-inference#868]
Good day! I have two caffe models and they expect input data in DHW format. Can you give me some tips how to transpose dims HWD -> DHW?

**Comment by dusty-nv** [comment]
Hi @SergeyMalashenko , by DHW I think that means the same thing as CHW (Channel, Height, Width).   If so, the pre-processing kernels from the project already do that:

https://github.com/dusty-nv/jetson-inference/blob/master/c/tensorConvert.h

**Comment by SergeyMalashenko** [comment]
Thank you
