### ISSUE TITLE
Image Crop isn't working

### ISSUE THREAD

**Issue by tkislan** [dusty-nv/jetson-inference#875]
Even when using example implementation in `build/aarch64/bin/cuda-examples.py`, it produces invalid images when cropping
Not sure what is this related to, because when tracked back to cuda implementation, it seems, that is just copies the underlying memory, which is just a 1 dimensional array .. so no idea why the images gets messed up like this
```
output[out_y * outWidth + out_x] = input[in_y * inWidth + in_x];
```

![out_kitten](https://user-images.githubusercontent.com/5370798/103408121-829a6700-4b61-11eb-9f34-ee2771a1253e.jpg)

**Comment by marcelosantoro** [comment]
Same problem here :(

**Comment by dusty-nv** [comment]
Hi all, please see this post for similar image and make sure that your ROI is specified correctly:

https://forums.developer.nvidia.com/t/cudacrop-mangling-my-image/166467/7?u=dusty_nv

Can you also check that this sample code works correctly for you:  https://github.com/dusty-nv/jetson-inference/blob/master/docs/aux-image.md#cropping
