### ISSUE TITLE
How should Do inference  using own resnet model?

### ISSUE THREAD

**Issue by bundelesneha05** [dusty-nv/jetson-inference#876]
I have trained the resnet18 model on the custom dataset. I would like to include that in the available networks. what are the steps to be followed?

**Comment by dusty-nv** [comment]
Hi @bundelesneha05 - was it trained with PyTorch and has it been converted to ONNX?

If so, you can run it like this by specifying your custom model arguments on the command line:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-cat-dog.md#processing-images-with-tensorrt

**Comment by bundelesneha05** [comment]
Thanks for the reply. It has been converted to the ONNX. The above link worked.

**Comment by bundelesneha05** [comment]
I have also trained the ssd_fpn_resnet_18 model using TensorFlow(1.15.1) on a custom dataset. The model has converted to the ONNX format. Not getting how to do the inference for this model using detectnet.py.

**Comment by dusty-nv** [comment]
Supporting different model architectures requires that the pre/post-processing code be added to jetson-inference/c/detectNet.cpp

The code supporting the ONNX models for detectNet.cpp/.py are currently setup for the SSD-Mobilenet models trained with PyTorch like here:   https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-ssd.md
