### ISSUE TITLE
Training with existing PascalVOC Format Data

### ISSUE THREAD

**Issue by naimulhq** [dusty-nv/jetson-inference#877]
I have been working on a project which involves coming up with an object detection model. At first, I was using ImageAI to train and run an object detection model but it ended up running out of memory and running to slow on the Jetson Nano. Now, I have switched to this package and I am trying to figure out how to train with already existing data? I already have all the images and annotations for each of the images but am unsure of how to set up the directory and its structures.

**Comment by neilyoung** [comment]
@naimulhq Did you figure it out?

**Comment by naimulhq** [comment]
@neilyoung Yes. Another existing issue helped out alot when trying to figure it out. #789

**Comment by neilyoung** [comment]
@naimulhq Thanks for sharing!
