### ISSUE TITLE
How long does it take to build the project from scratch on a Nano 4G dev board?

### ISSUE THREAD

**Issue by neilyoung** [dusty-nv/jetson-inference#878]
I'm just asking because I'm a bit flashed from the build speed in your video. I suppose it is not the first build, right?

Otherwise if you tell me, that you reach the same performance on a freshly flashed device, then I would need to know the difference :)

**Comment by naimulhq** [comment]
I am working on the same dev kit as well. For me, it took about 15-20 minutes to build the project from scratch.

**Comment by neilyoung** [comment]
@naimulhq Thanks for confirmation :)
