### ISSUE TITLE
Re-training SSD MobileNet on host platform rather than on Jetson platforms

### ISSUE THREAD

**Issue by mozcelikors** [dusty-nv/jetson-inference#879]
Hi,
There are instructions given in https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-ssd.md for retraining MobileNet with custom dataset on Jetson platforms. What I like to train is quite big and I want to make use of the GTX 2070 / Ubuntu 16.04 host platform to speed up the process. Is there any instruction to train for Jetson on a computer?
Thank you very much in advance.

**Comment by dusty-nv** [comment]
Hi @mozcelikors , it is the same process, I train it on my Ubuntu laptop with GeForce 1070 card.

You can clone the submodule directly to your PC:   https://github.com/dusty-nv/pytorch-ssd

Then make sure you have CUDA and PyTorch installed to your PC, according to the instructions from PyTorch.org.  You also need to install the prerequisite Python packages for pytorch-ssd.

**Comment by mozcelikors** [comment]
Thank you
