### ISSUE TITLE
“WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.”

### ISSUE THREAD

**Issue by neilyoung** [dusty-nv/jetson-inference#883]
I see this warning while attempting to serve three USB cameras from one network. Not always, but at least twice already.

Even though the message is pretty verbose, I don't understand the meaning and the cause, since it happens after the model is loaded and before any of the three cams is touched.

**Comment by dusty-nv** [comment]
After the first time you run a model, the TensorRT .engine file is saved to disk so it's cached and loads much faster on subsequent runs.   When the .engine file gets loaded on subsequent runs, TensorRT cross-checks that the engine was made on the GPU that you are attempting to run it on.

It seems that sometimes, TensorRT spuriously detects the .engine was created on a different GPU, when in fact it wasn't.  You can ignore this warning.

**Comment by neilyoung** [comment]
Ah, thanks for the explanation. This leads me to the question: Is it legit to transfer the cache to another machine or should one better not do that?

**Comment by dusty-nv** [comment]
It needs to have the same GPU in order to transfer it to another machine and work well.   For example, you can transfer it between Jetson Nano's.    But you shouldn't transfer it between a Jetson Nano and a Jetson Xavier NX (because they have different GPUs)

**Comment by dusty-nv** [comment]
Also the engine should be generated by the same version of TensorRT (i.e. the same JetPack version if on Jetson) in order to transfer it between devices.

**Comment by neilyoung** [comment]
Thanks a lot
