### ISSUE TITLE
Code documentation on click in VSCode?

### ISSUE THREAD

**Issue by neilyoung** [dusty-nv/jetson-inference#884]
Is there any way to have the Python code documentation available on click in VSCode?

Right now neither "Goto definition" nor clicking on a library function leads to the documentation of the functions.

**Comment by dusty-nv** [comment]
@neilyoung that is probably because the Python functions are C++ extension modules - they are not actually implemented in Python.

**Comment by neilyoung** [comment]
Yepp... too bad :)

Anyway, documentation is great, samples are great. Should be able to find it out. Thanks for your efforts.
