### ISSUE TITLE
How can I hide the gl title

### ISSUE THREAD

**Issue by lzcchl** [dusty-nv/jetson-inference#900]
![1611302567(1)](https://user-images.githubusercontent.com/34515022/105463784-88e8b280-5ccb-11eb-8518-28ad7c2438d9.png)
I want show frame with fullscreen, but I can't find a function to hide the gl window title, can you help me?

**Comment by lzcchl** [comment]
Emm. I find an answer at "https://github.com/dusty-nv/jetson-inference/issues/801", but when I try it, it's also a title on the window,  is there a function to hide title?

**Comment by dusty-nv** [comment]
Hi @lzcchl , there isn't a built-in function, but you could try the recommendation from this post:

https://forums.developer.nvidia.com/t/display-in-jetson-inference-without-title-bar-and-image-blending/165214/2?u=dusty_nv

**Comment by flow-dev** [comment]
I was having trouble with full screen output, 
so it was very helpful!

I changed the code like this and it worked.

https://github.com/dusty-nv/jetson-utils/blob/833fc7998e34d852672277730a11aeed90024959/display/glDisplay.cpp#L322

```
	// Add FullScreen output
	Atom wm_state   = XInternAtom (mDisplayX, "_NET_WM_STATE", true );
	Atom wm_fullscreen = XInternAtom (mDisplayX, "_NET_WM_STATE_FULLSCREEN", true );
	XChangeProperty(mDisplayX, win, wm_state, XA_ATOM, 32, PropModeReplace, (unsigned char *)&wm_fullscreen, 1);
```

**Comment by lzcchl** [comment]
@flow-dev this is good!
