### ISSUE TITLE
Camera-capture object detection labeling with image set

### ISSUE THREAD

**Issue by BENJI16** [dusty-nv/jetson-inference#907]
I think I might just be missing something here. I have a set of images that I would like to manually label for object detection and I've been able to open the camera-capture tool while passing in the image directory. The issue I'm having is stepping through the images. With the input-loop = 0 I'm not sure how to advance to the next image. But with the input-loop = -1 I won't be able to realistically label all of the images. I've collected them with the intention of labeling each individually, so playing them back as a video is not ideal.

Is there a simple way to just step through the images in a directory?

**Comment by dusty-nv** [comment]
Hi @BENJI16, for labeling existing images/video, I recommend using the [CVAT](https://cvat.org/) tool.   You can export your annotated dataset from CVAT in Pascal VOC format.  Then when you extract your downloaded annotated dataset, add a labels.txt to it.
