### ISSUE TITLE
High Resolution Object Detection Model

### ISSUE THREAD

**Issue by rsamvelyan** [dusty-nv/jetson-inference#912]
Hello
I'm looking for an SSD object detection model that has a higher resolution than MobileNet. Ideally something like 1200x1200.
Is there a way to increase the MobileNet's resolution or is there another model which I could run inference on Jetson Xavier and which would be supported by DetectNet? 
Thanks!

**Comment by dusty-nv** [comment]
Hi @rsamvelyan, you might want to see this forum thread where we got SSD-512 working:

https://forums.developer.nvidia.com/t/how-train-jetson-inference-ssd512-model/168510/6?u=dusty_nv

**Comment by rsamvelyan** [comment]
Thanks a lot Dusty! I will try to do it as well. 
I wonder if SSD-512 could work with MobileNet V1?  Or is it going to have an incompatible size? 
I just need it to run real-time.
