### ISSUE TITLE
Install where?

### ISSUE THREAD

**Issue by grusboyd** [dusty-nv/jetson-inference#918]
Please pardon the newbie but where does all this get installed - host or Jetson? I ask only because docker/run.sh doesn't find a Jetson TX2 configuration description on the host (because it doesn't exist, even though Jetpack 4.5 is freshly installed on both). It exists on the Jetson but the instructions _seem_ to indicate that the software should be installed on the host.
Thanks,
Rusty

**Comment by dusty-nv** [comment]
Hi there, it should be run from the Jetson, not PC.
________________________________
