### ISSUE TITLE
How to mark the bounding box location of my own images without using camera-capture?

### ISSUE THREAD

**Issue by jugfk** [dusty-nv/jetson-inference#919]
Dear Dusty

This is Stephen Lee.
Thank you for the YouTube(Jetson AI Fundamentals - S3E5).
**I want to mark the bounding box location of my own images without using the camera-capture.** 
So, the information would be XML data within bounding box location information from my own images.(like the YOLO Marker)

References:
[1] Jetson AI Fundamentals - S3E5: https://youtu.be/2XMkPW_sIGg
[2] https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect-detection.md

**Comment by dusty-nv** [comment]
Hi @jugfk, please see my reply to similar question here:

https://forums.developer.nvidia.com/t/camera-capture-for-single-images-inside-a-local-folder/168317/2?u=dusty_nv

**Comment by jugfk** [comment]
That is not the question.

**Comment by dusty-nv** [comment]
The question was 'how can I annotate images that already exist', which is the same as yours.  You can use the CVAT tool to do that.

**Comment by jugfk** [comment]
@dusty-nv I have 100 images without using the camera-capture. I have succeeded in the experiment of Training Image Classification Models. but I'm struggling with Training Object Detection Models.

**Comment by dusty-nv** [comment]
Import your images into CVAT, annotate them with bounding boxes, and export from CVAT in Pascal VOC format.  Then add a labels.txt to your extracted dataset, where there is one classname per line of your labels.txt.  Then train it with train_ssd.py like you would have. 

You may need more than 100 images to get a good result, it depends on the subject matter / environment conditions and the accuracy you desire.

**Comment by jugfk** [comment]
> The question was 'how can I annotate images that already exist', which is the same as yours. You can use the CVAT tool to do that.

@dusty-nv  Thank you for precious time. I'm also looking for offline software. Could you recommend it?

**Comment by dusty-nv** [comment]
I believe you can install CVAT locally, although I haven't done that.  I had tried a couple other tools but CVAT exported the data in the closest way.

**Comment by jugfk** [comment]
> I believe you can install CVAT locally, although I haven't done that. I had tried a couple other tools but CVAT exported the data in the closest way.

Thank you for helping. I have done to locally install it.
