### ISSUE TITLE
Depth estimation

### ISSUE THREAD

**Issue by Noam-M** [dusty-nv/jetson-inference#926]
Hello 

I want to run my own depth estimation application.
Since the output is an image, it could make sense to use the segNet class. 
Is there a way to use it with infinite amount of classes? or at least a very high number of classes?
Also, is there a way to output a grayscale image at the output? or does that require post-processing?

Thanks!

**Comment by dusty-nv** [comment]
Hi @Noam-M, I believe FCN-Resnet18 used in this repo is limited to 21 classes.   There may be other semantic segmentation architectures that allow for more classes, although I haven't tested them with TensorRT.   I also think that with many segmentation classes, you would find the output to be increasingly noisy/inaccurate.

segNet can output two types of mask images - a classID mask, where each pixel is the classID.  And the 'colorized' mask where each pixel is the color of the class.  So you could set the class colors to grayscale colors.   Or you could just use the classID mask and create your own treatment.
