### ISSUE TITLE
Can someone tell me which Jetson Device is being referred to in this repo when they say "Xavier"

### ISSUE THREAD

**Issue by sisaha9** [dusty-nv/jetson-inference#928]
https://github.com/dusty-nv/jetson-inference#semantic-segmentation

I know Jetson Nano but which Xavier is being referred to here? Xavier NX or AGX Xavier?

**Comment by dusty-nv** [comment]
That was with Jetson AGX Xavier

**Comment by sisaha9** [comment]
Which semantic segmentation model would you recommend for real time inference in Xavier NX?

**Comment by sisaha9** [comment]
I have 720x1280 images but I will scale down if need be since fast real time inference is important for my application (self driving car)

**Comment by dusty-nv** [comment]
They should all still be realtime on NX.  If your input is 1280x720, try `fcn-resnet18-cityscapes-1024x512` or `fcn-resnet18-cityscapes-512x256`

**Comment by sisaha9** [comment]
Got it. Thanks!
