### ISSUE TITLE
Raspberry camera v2 video appears to be purplish in the jetson nano 

### ISSUE THREAD

**Issue by MuhammedRishdhi** [dusty-nv/jetson-inference#938]

**Comment by dusty-nv** [comment]
Hi @MuhammedRishdhi, you may want to try this post:   https://jonathantse.medium.com/fix-pink-tint-on-jetson-nano-wide-angle-camera-a8ce5fbd797f

If that doesn't help, please post about it to the Jetson Nano forum here:  https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76
