### ISSUE TITLE
Face Recognition using facenet.

### ISSUE THREAD

**Issue by apoorvmishra28** [dusty-nv/jetson-inference#942]
Hi @dusty-nv , I'm trying to build face recognition system. So, facenet is working fine in detecting faces but I need some suggestion regarding the integration of face recognition alongside facenet. Can you please help me out with your suggestion.

**Comment by dusty-nv** [comment]
Hi @apoorvmishra28, you might want to check out DLIB, I believe it does face recognition.   Essentially the features from the detected faces are stored in a database and compared against later to find matches.

**Comment by fasa79** [comment]
Hi @apoorvmishra28 and @dusty-nv . I m still new here. Do you mind to share where can I find the DLIB and so I can learn to do the face recognition.
