### ISSUE TITLE
camera capture (input: images) problem

### ISSUE THREAD

**Issue by ingbeeedd** [dusty-nv/jetson-inference#945]
I have an image directory as below, and I put a file option using the camera-capture program, but the files move quickly and then work like below, is there any way to annotate one by one in the file directory?

```bash
camera-capture file://images/
```

[image] imageLoader -- End of Stream (EOS) has been reached, stream has been closed

![image](https://user-images.githubusercontent.com/57895472/109805421-c0e9fa80-7c66-11eb-8e69-d545f00d7e82.png)

![image](https://user-images.githubusercontent.com/57895472/109805192-7cf6f580-7c66-11eb-924c-a4143fcbd39b.png)

**Comment by dusty-nv** [comment]
Hi @ingbeeedd, please use [CVAT](https://cvat.org/) tool or similar for annotating images that you have already captured.

**Comment by ingbeeedd** [comment]
Thank you for inform `CVAT`. I will close it
