### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#946]
ifollowing Jetson AI Fundamentals - S3E4 - Object Detection Inference in youtube

first and i try to use 

./detectnet.py --network=ssd-mobilenet-v2 "images/humans_*.jpg" images/test/humans_%i.jpg

it's ok  but  when try to use 

./detectnet.py --network=facenet "images/humans_*.jpg" images/test/humans_%i.jpg

[TRT]    invalid engine cache file size (0 bytes)  networks/facenet-120/snapshot_iter_24000.caffemodel.1.1.7103.GPU.FP16.engine
[TRT]    detectNet -- failed to initialize.
jetson.inference -- detectNet failed to load network

Traceback (most recent call last):
  File "./detectnet.py", line 51, in <module>
    net = jetson.inference.detectNet(opt.network, sys.argv, opt.threshold)
Exception: jetson.inference -- detectNet failed to load network

thanks

**Comment by dusty-nv** [comment]
Hi @tianzanaruk, try running `rm networks/facenet-120/snapshot_iter_24000.caffemodel.1.1.7103.GPU.FP16.engine` and then re-running detectnet

**Comment by tianzanaruk** [comment]
thanks for help
