### ISSUE TITLE
Using it real time with Intel Realsense D435i

### ISSUE THREAD

**Issue by dlee640** [dusty-nv/jetson-inference#947]
Hello. I have successfully built and tested all three modules (image, object, semantic seg) on sample images on my Xavier NX with ubuntu 18.04. However, I would like to run some of these algorithms real time on D435i that is connected to my NX.

I searched issue page with keywords 'intel' and 'realsense' but nothing really came up that could help. Any guidance or direction on setting up the stream? I have also downloaded and built ros version for jetson-inference. Should I use ROS to do this?

**Comment by surefyyq** [comment]
I am trying to develop both jetson-inference and RealsenseD435 on jetson equipment, and I have successfully make them work separately. Maybe you should firstly configure the realsense device for your Xavier according to https://github.com/IntelRealSense/librealsense.
