### ISSUE TITLE
Is it possible to integrate a foreign model with an already generated .engine file to the repository - with hopes of being able to utilize the provided ROS nodes with the new model?

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [dusty-nv/jetson-inference#949]
Hey dusty-nv, 

Thanks for the great framework. I was wondering if it's possible to integrate a new model with an already generated .engine file to the repository - with hopes of being able to use the ROS nodes provided by the repository?

The model currently works using TensorRT on it's own with it's pre/post-processing functions already implemented.

**Comment by dusty-nv** [comment]
Hi @rocketsfallonrocketfalls, there is a function [`tensorNet::LoadEngine()`](https://github.com/dusty-nv/jetson-inference/blob/35f896c7a3cce5cb552f3737aa295e43db7b5798/c/tensorNet.h#L303) that loads a serialized TensorRT engine.  That function is used internally but it is there.
