### ISSUE TITLE
best graphical user interface framework for Jetson tx2

### ISSUE THREAD

**Issue by ShervinAr** [dusty-nv/jetson-inference#95]
Hello,
Could you please advise me of the best graphical user interface framework for Jetson tx2?
I am in the final stage of creating and application using jetson tx2 and need a suitable framework to create a GUI.

many thanks

**Comment by Myzhar** [comment]
Qt5 ... but you are a bit off-topic here
This is the right place for generic question about TX2:
https://devtalk.nvidia.com/default/board/188/jetson-tx2/
