### ISSUE TITLE
Return Code in case pipeline stops

### ISSUE THREAD

**Issue by rlrahulkanojia** [dusty-nv/jetson-inference#960]
I am calling the jetson infernece as a module but in case of any error, the pipeline just stops and does not return anything. is there a way to return something from the function which is calling the pipeline in case of EOS.

eg

def module(INPUT_URLS):
    input = jetson.utils.videoSource(INPUT_URLs[0], argv=sys.argv)]
    while True:
        frame = input.capture()
        ***
     (how to make sure this return something)
    return 200

**Comment by rlrahulkanojia** [comment]
@dusty-nv  Please help me with this

**Comment by dusty-nv** [comment]
@rlrahulkanojia, try the optional `timeout` argument to `videoSource.Capture()`, where timeout is in milliseconds.  By default, the timeout is -1, which means never timeout and wait indefinitely.  A timeout of 0 means return immediately if no image is ready.   A timeout of 1000 would mean wait 1 second for new image.

If a timeout occurs, it will throw a python exception, so you would want to catch that if you want your program to keep executing.

**Comment by rlrahulkanojia** [comment]
Got it, Thanks!
