### ISSUE TITLE
mobilenet v3 object detection model?

### ISSUE THREAD

**Issue by ghylander** [dusty-nv/jetson-inference#965]
any plans to implement mobilenet v3 for object detection?

**Comment by dusty-nv** [comment]
@ghylander I don't currently have plans to, as the pytorch-ssd code I use for training doesn't support it.  Perhaps in the future I can look into it, or if it gets added on the pytorch side in the training code.

**Comment by ghylander** [comment]
do you want me to leave the issue open or  close it?
