### ISSUE TITLE
cmake 

### ISSUE THREAD

**Issue by ZeeshanSar** [dusty-nv/jetson-inference#967]
hi i just bought a jetson nano and trying get started with hello world. i am face a problem with the cmake the error is below.

### cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

how to fix this error?

**Comment by ZeeshanSar** [comment]
i made i mistake while cmake ../ i just typed cmake


do i can add more images to the images folder to identify more objects?

**Comment by dusty-nv** [comment]
Yes or you can save your images to a different directory and specify the full path to your image(s) that you want to process.

**Comment by ZeeshanSar** [comment]
and how can i can run this remotely using IP address?

**Comment by dusty-nv** [comment]
You would SSH into the device.  If you are on Windows, use an SSH client like Putty or MobaXTerm.

**Comment by ZeeshanSar** [comment]
my jetson is giving an error for   ./detectne.console.py: no such file or directory. while testing

**Comment by dusty-nv** [comment]
Is the working directory of your terminal `<path-to-your-jetson-inference>/build/aarch64/bin`

If not, go to that directory, or just run it as `detectnet.py` (no forward slash at beginning)

**Comment by ZeeshanSar** [comment]
ok fixed this but now i am facing another error 

[TRT] Could not register plugin creator - : :FlattenCorcat_TRT version 1

nvbuf_utils: dmabuf_fd -1 mapped entry not found
nvbuf_utils: Can not get buffer from FD... Exiting...
[gstreamer] gstCamera -- end of stream (E0S)

(python:11425): GStreamer-CRITICAL **:23:24:35.764: gst_mini_object_set_qdatat: assertion 'object !=NULL' failed


I am using raspberry pi camera RV 1.3

**Comment by dusty-nv** [comment]
> I am using raspberry pi camera RV 1.3

I don't think rPI camera v1.3 is supported, it is the IMX219-based rPI camera v2 that is supported in JetPack.   You can check if you can view it with `nvgstcapture-1.0`, but I think the v1.3 isn't supported out of the box because the older Omnivision sensor it uses is EOL.

**Comment by ZeeshanSar** [comment]
ok now i am using imx219 8-0010 (platform:54080000.vi:4): connected to video

error is 
[gstreamer] gstreamer changed state from READY to PAUSED ==> mysink

**Comment by dusty-nv** [comment]
Can you view it with `nvgstcapture-1.0`?

**Comment by ZeeshanSar** [comment]
yes

**Comment by dusty-nv** [comment]
OK, that is good.  Does it work with video-viewer utility from jetson-inference?

**Comment by ZeeshanSar** [comment]
Yes it is working as well.

**Comment by ZeeshanSar** [comment]
hi dusty how i can use the mix 219 camera? i have an error estremer changed state from ready to paused ==> mysink

**Comment by dusty-nv** [comment]
Can you provide the whole terminal output from when you run 'video-viewer csi://0' command?
________________________________

**Comment by ZeeshanSar** [comment]
after command 
nvidia@nvidia-desktop:~ video-viewer csi://0

it opens a window with the video signal
video-viewer: captured 955 frames (1280 x 720)

**Comment by ZeeshanSar** [comment]
nvidia@nvidia-desktop:~$ video-viewer csi://0
[gstreamer] initialized gstreamer, version 1.14.5.0
[gstreamer] gstCamera -- attempting to create device csi://0
[gstreamer] gstCamera pipeline string:
[gstreamer] nvarguscamerasrc sensor-id=0 ! video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, framerate=30/1, format=(string)NV12 ! nvvidconv flip-method=2 ! video/x-raw ! appsink name=mysink
[gstreamer] gstCamera successfully created device csi://0
[video]  created gstCamera from csi://0
------------------------------------------------
gstCamera video options:
------------------------------------------------
  -- URI: csi://0
     - protocol:  csi
     - location:  0
  -- deviceType: csi
  -- ioType:     input
  -- codec:      raw
  -- width:      1280
  -- height:     720
  -- frameRate:  30.000000
  -- bitRate:    0
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: rotate-180
  -- loop:       0
------------------------------------------------
[OpenGL] glDisplay -- X screen 0 resolution:  1366x768
[OpenGL] glDisplay -- X window resolution:    1366x768
[OpenGL] glDisplay -- display device initialized (1366x768)
[video]  created glDisplay from display://0
------------------------------------------------
glDisplay video options:
------------------------------------------------
  -- URI: display://0
     - protocol:  display
     - location:  0
  -- deviceType: display
  -- ioType:     output
  -- codec:      raw
  -- width:      1366
  -- height:     768
  -- frameRate:  0.000000
  -- bitRate:    0
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
  -- loop:       0
------------------------------------------------
[gstreamer] opening gstCamera for streaming, transitioning pipeline to GST_STATE_PLAYING
[gstreamer] gstreamer changed state from NULL to READY ==> mysink
[gstreamer] gstreamer changed state from NULL to READY ==> capsfilter1
[gstreamer] gstreamer changed state from NULL to READY ==> nvvconv0
[gstreamer] gstreamer changed state from NULL to READY ==> capsfilter0
[gstreamer] gstreamer changed state from NULL to READY ==> nvarguscamerasrc0
[gstreamer] gstreamer changed state from NULL to READY ==> pipeline0
[gstreamer] gstreamer changed state from READY to PAUSED ==> capsfilter1
[gstreamer] gstreamer changed state from READY to PAUSED ==> nvvconv0
[gstreamer] gstreamer changed state from READY to PAUSED ==> capsfilter0
[gstreamer] gstreamer stream status CREATE ==> src
[gstreamer] gstreamer changed state from READY to PAUSED ==> nvarguscamerasrc0
[gstreamer] gstreamer changed state from READY to PAUSED ==> pipeline0
[gstreamer] gstreamer stream status ENTER ==> src
[gstreamer] gstreamer message new-clock ==> pipeline0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> capsfilter1
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> nvvconv0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> capsfilter0
[gstreamer] gstreamer message stream-start ==> pipeline0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> nvarguscamerasrc0
GST_ARGUS: Creating output stream
CONSUMER: Waiting until producer is connected...
GST_ARGUS: Available Sensor modes :
GST_ARGUS: 3264 x 2464 FR = 21.000000 fps Duration = 47619048 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 3264 x 1848 FR = 28.000001 fps Duration = 35714284 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1920 x 1080 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1640 x 1232 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 59.999999 fps Duration = 16666667 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 120.000005 fps Duration = 8333333 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: Running with following settings:
   Camera index = 0 
   Camera mode  = 5 
   Output Stream W = 1280 H = 720 
   seconds to Run    = 0 
   Frame Rate = 120.000005 
GST_ARGUS: Setup Complete, Starting captures for 0 seconds
GST_ARGUS: Starting repeat capture requests.
CONSUMER: Producer has connected; continuing.
[gstreamer] gstCamera -- onPreroll
[gstreamer] gstCamera -- map buffer size was less than max size (1382400 vs 1382407)
[gstreamer] gstCamera recieve caps:  video/x-raw, width=(int)1280, height=(int)720, framerate=(fraction)30/1, format=(string)NV12
[gstreamer] gstCamera -- recieved first frame, codec=raw format=nv12 width=1280 height=720 size=1382407
RingBuffer -- allocated 4 buffers (1382407 bytes each, 5529628 bytes total)
[gstreamer] gstreamer changed state from READY to PAUSED ==> mysink
[gstreamer] gstreamer message async-done ==> pipeline0
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> mysink
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> pipeline0
RingBuffer -- allocated 4 buffers (2764800 bytes each, 11059200 bytes total)
video-viewer:  captured 1 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
[OpenGL] creating 1280x720 texture (GL_RGB8 format, 2764800 bytes)
[cuda]   registered openGL texture for interop access (1280x720, GL_RGB8, 2764800 bytes)
video-viewer:  captured 2 frames (1280 x 720)
video-viewer:  captured 3 frames (1280 x 720)
video-viewer:  captured 4 frames (1280 x 720)
video-viewer:  captured 5 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 6 frames (1280 x 720)
video-viewer:  captured 7 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 8 frames (1280 x 720)
video-viewer:  captured 9 frames (1280 x 720)
video-viewer:  captured 10 frames (1280 x 720)
video-viewer:  captured 11 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 12 frames (1280 x 720)
video-viewer:  captured 13 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 14 frames (1280 x 720)
video-viewer:  captured 15 frames (1280 x 720)
video-viewer:  captured 16 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 17 frames (1280 x 720)
video-viewer:  captured 18 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 19 frames (1280 x 720)
video-viewer:  captured 20 frames (1280 x 720)
video-viewer:  captured 21 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 22 frames (1280 x 720)
video-viewer:  captured 23 frames (1280 x 720)
video-viewer:  captured 24 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 25 frames (1280 x 720)
video-viewer:  captured 26 frames (1280 x 720)
video-viewer:  captured 27 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 28 frames (1280 x 720)
video-viewer:  captured 29 frames (1280 x 720)
video-viewer:  captured 30 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 31 frames (1280 x 720)
video-viewer:  captured 32 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 33 frames (1280 x 720)
video-viewer:  captured 34 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 35 frames (1280 x 720)
video-viewer:  captured 36 frames (1280 x 720)
video-viewer:  captured 37 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 38 frames (1280 x 720)
video-viewer:  captured 39 frames (1280 x 720)
video-viewer:  captured 40 frames (1280 x 720)
video-viewer:  captured 41 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 42 frames (1280 x 720)
video-viewer:  captured 43 frames (1280 x 720)
video-viewer:  captured 44 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 45 frames (1280 x 720)
video-viewer:  captured 46 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 47 frames (1280 x 720)
video-viewer:  captured 48 frames (1280 x 720)
video-viewer:  captured 49 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 50 frames (1280 x 720)
video-viewer:  captured 51 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 52 frames (1280 x 720)
video-viewer:  captured 53 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 54 frames (1280 x 720)
video-viewer:  captured 55 frames (1280 x 720)
video-viewer:  captured 56 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 57 frames (1280 x 720)
video-viewer:  captured 58 frames (1280 x 720)
video-viewer:  captured 59 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 60 frames (1280 x 720)
video-viewer:  captured 61 frames (1280 x 720)
video-viewer:  captured 62 frames (1280 x 720)
video-viewer:  captured 63 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 64 frames (1280 x 720)
video-viewer:  captured 65 frames (1280 x 720)
video-viewer:  captured 66 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 67 frames (1280 x 720)
video-viewer:  captured 68 frames (1280 x 720)
video-viewer:  captured 69 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 70 frames (1280 x 720)
video-viewer:  captured 71 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 72 frames (1280 x 720)
[OpenGL] glDisplay -- set the window size to 1280x720
video-viewer:  captured 73 frames (1280 x 720)
video-viewer:  captured 74 frames (1280 x 720)
video-viewer:  captured 75 frames (1280 x 720)
video-viewer:  captured 76 frames (1280 x 720)
video-viewer:  captured 77 frames (1280 x 720)
video-viewer:  captured 78 frames (1280 x 720)
video-viewer:  captured 79 frames (1280 x 720)
video-viewer:  captured 80 frames (1280 x 720)
video-viewer:  captured 81 frames (1280 x 720)
video-viewer:  captured 82 frames (1280 x 720)
video-viewer:  captured 83 frames (1280 x 720)
video-viewer:  captured 84 frames (1280 x 720)
