### ISSUE TITLE
Can i ask you something?

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#970]
Jetson Nano can be create into application?
Such as detection using Application via mobile phone or computer

**Comment by dusty-nv** [comment]
Hi, yes this project supports Jetson Nano
________________________________
From: tianzanaruk ***@***.***>
Sent: Sunday, March 28, 2021 10:52:02 AM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] Can i ask you something? (#970)


Jetson Nano can be built into application?

**Comment by tianzanaruk** [comment]
it's can create .exe files? 
how to do?
