### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#972]
how to create application files or .exe files

**Comment by dusty-nv** [comment]
Are you using Python or C++?

**Comment by tianzanaruk** [comment]
Python

**Comment by tianzanaruk** [comment]
I​ meaning need to​ create​ files type​ application.exe for​ Windows​ or​ Playstore​ in​ mobliephone

**Comment by dusty-nv** [comment]
This project supports Linux running on Jetson, not Windows or mobile app stores.
________________________________

**Comment by tianzanaruk** [comment]
So how can I run the program not in terminals jetson  but on another linux For example, PC with linux operating system.

**Comment by dusty-nv** [comment]
There are some folks who have built it for x86 but there are Jetson-specific things in the project, like the camera/codec interfaces.  Officially it supports the Jetson devices.
