### ISSUE TITLE
How​ to​ remove

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#980]
![IMG_20210401_223430](https://user-images.githubusercontent.com/80049634/113322460-ec800380-933e-11eb-9c06-7ac4d644aa46.jpg)
![IMG_20210401_223421](https://user-images.githubusercontent.com/80049634/113322471-eee25d80-933e-11eb-96de-036a589bfbb2.jpg)

Can't​ delete

**Comment by dusty-nv** [comment]
Restore it to it's original location, and then delete it with sudo - `sudo rm -r -f 121`

**Comment by tianzanaruk** [comment]
Thank for​ help
