### ISSUE TITLE
Can i ask and How to ?

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#981]
i'm follow Jetson AI Fundamentals - S3E3 - Training Image Classification Models.
Everything went well. until 29:24 min in youtube last process i got this 

![113291365-22ac8b80-931d-11eb-8bb1-9831ee6d2922](https://user-images.githubusercontent.com/80049634/113347400-527c8300-935f-11eb-84e7-f4a27a7db8e4.jpg)

can i ask how to fixed

**Comment by dusty-nv** [comment]
Can you delete the `.engine` file from your model's directory?

**Comment by tianzanaruk** [comment]
No.​ I'm​ mot
