### ISSUE TITLE
ask something about Coding Your Own Object Detection Program

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#983]
import jetson.inference
import jetson.utils

```
net = jetson.inference.detectNet("ssd-mobilenet-v2", threshold=0.5)
camera = jetson.utils.videoSource("csi://0")      # '/dev/video0' for V4L2
display = jetson.utils.videoOutput("display://0") # 'my_video.mp4' for file

while display.IsStreaming():
	img = camera.Capture()
	detections = net.Detect(img)
	display.Render(img)
	display.SetStatus("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))
```
	

how i can use data while camera finded or detected person 
example detected 1 person GPIO or led ON

**Comment by dusty-nv** [comment]
Hi @tianzanaruk, you would loop through each detection and check if it is a person:

``` python
for n in range(net.GetNumClasses()):
   if net.GetClassDesc(n) == 'person':
      person_class_id = n

while display.IsStreaming():
   img = camera.Capture()
   detections = net.Detect(img)

   for detection in detections:
      if detection.ClassID == person_class_id:
         print('detected a person!')
         # do your GPIO here

   display.Render(img)
   display.SetStatus("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))

**Comment by tianzanaruk** [comment]
Thank​ for​ help.​ ill.learn more

**Comment by tianzanaruk** [comment]
hi @dusty-nv  i need to merge code for while detected person should start code left in picture

![Screenshot from 2021-04-03 22-07-58](https://user-images.githubusercontent.com/80049634/113482467-16fdc800-94c9-11eb-9676-6e312960a301.png)

**Comment by tianzanaruk** [comment]
this code 

```
import jetson.inference
import jetson.utils

net = jetson.inference.detectNet("ssd-mobilenet-v2", threshold=0.5)
camera = jetson.utils.videoSource("/dev/video0") 
display = jetson.utils.videoOutput("display://0")

for n in range(net.GetNumClasses()):
   	if net.GetClassDesc(n) == 'person':
      		person_class_id = n

while display.IsStreaming():
	img = camera.Capture()
	detections = net.Detect(img)
	for detection in detections:
      		if detection.ClassID == person_class_id:
         		print('detected a person!')
	display.Render(img)
	display.SetStatus("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))
```
 and need to merge with this

```
import speech_recognition as sr  
from gtts import gTTS
from playsound import playsound 
from datetime import datetime


r = sr.Recognizer()

with sr.Microphone() as source: 
	playsound("./signal.mp3") 
	audio = r.record(source, duration=5) 
	playsound("./signal.mp3") 

	try:
		text = r.recognize_google(audio, language="th") 
		if "ผม" in text:
			text = text.replace("ผม", "ฉันเองก็")
		if "ครับ" in text:
			text = text.replace("ครับ", "ค่ะ")
		if text == "กี่โมงแล้ว":
			now = datetime.now() 
			text = now.strftime("ขณะนี้เวลา%Hนาฬิกา%Mนาที%Sวินาที")
	except:
		text = "ขอโทษค่ะ"
	tts = gTTS(text, lang="th") 
	tts.save("./answer.mp3") 
	playsound("./answer.mp3")
```

i try to this 

```
import jetson.inference
import jetson.utils
import speech_recognition as sr  
from gtts import gTTS
from playsound import playsound 
from datetime import datetime

net = jetson.inference.detectNet("ssd-mobilenet-v2", threshold=0.5)
camera = jetson.utils.videoSource("/dev/video0") 
display = jetson.utils.videoOutput("display://0")
r = sr.Recognizer()

for n in range(net.GetNumClasses()):
   	if net.GetClassDesc(n) == 'person':
      		person_class_id = n

while display.IsStreaming():
	img = camera.Capture()
	detections = net.Detect(img)
	for detection in detections:
      		if detection.ClassID == person_class_id:
         		print('detected a person!')
                       
```
                        with sr.Microphone() as source: 
	                         playsound("./signal.mp3") 
	                        audio = r.record(source, duration=5) 
	                        playsound("./signal.mp3") 

	                        try:
		                         text = r.recognize_google(audio, language="th") 
		                        if "ผม" in text:
		                        	text = text.replace("ผม", "ฉันเองก็")
	                         	if "ครับ" in text:
		                         	text = text.replace("ครับ", "ค่ะ")
		                        if text == "กี่โมงแล้ว":
		                        	now = datetime.now() 
		                          	text = now.strftime("ขณะนี้เวลา%Hนาฬิกา%Mนาที%Sวินาที")
                        	except:
                         		text = "ขอโทษค่ะ"
                        	tts = gTTS(text, lang="th") 
                        	tts.save("./answer.mp3") 
                        	playsound("./answer.mp3")
```
	display.Render(img)
	display.SetStatus("Object Detection | Network {:.0f} FPS".format(net.GetNetworkFPS()))
```

**Comment by h3retek** [comment]
> but not work

Please ellaborate...

**Comment by tianzanaruk** [comment]
> > but not work
> 
> Please ellaborate...

when i use python3 test.py  
TabError : inconstent yse of tabs and spaces in indentation

**Comment by h3retek** [comment]
I welcome you, to the world where `ctr+c` and `ctrl+v` falls apart.

You are facing what is called: formatting.

> The Python “TabError: inconsistent use of tabs and spaces in indentation” error is raised when you try to indent code using both spaces and tabs.

Which text editor are you using?

**Comment by tianzanaruk** [comment]
Nothing.txt

**Comment by dusty-nv** [comment]
You need to convert the tabs to spaces (or vice versa)

Also, the way your code is structured, it will freeze the video for several seconds while your audio plays/records, but maybe that is ok.  The alternative would be to use Python multiprocessing, and have the microphone running in another thread or process.

**Comment by tianzanaruk** [comment]
@dusty-nv freeze​ the​video.it's ok.
But.need to​ know how​ to.structured​ my​ Code.for running

**Comment by h3retek** [comment]
Text editor? khrab

Gedit
Nano
Notepad++
...

**Comment by tianzanaruk** [comment]
but my code is work? if use text editor?

**Comment by h3retek** [comment]
Nope, but you can use text editor to convert all /tabs to /space :)

If you tell me which text editor you use, I can point you to the tutorial on how to do it.

**Comment by tianzanaruk** [comment]
ok

**Comment by tianzanaruk** [comment]
> Nope, but you can use text editor to convert all /tabs to /space :)
> 
> If you tell me which text editor you use, I can point you to the tutorial on how to do it.

now i'm ready can u help ?

**Comment by tianzanaruk** [comment]
Hi @dusty-nv  can't run coz something lost about `with`

![hhhhhhhh](https://user-images.githubusercontent.com/80049634/113744692-20886980-972f-11eb-93b8-39f0cdf481a9.png)

**Comment by dusty-nv** [comment]
There still must be leading spaces lurking in your file.  Or if you changed to spaces, there still must be tabs somewhere.  Typically it is around the line of the error...

**Comment by tianzanaruk** [comment]
thanks all

**Comment by h3retek** [comment]
@tianzanaruk because life is all about automation... you can check [this post](https://stackoverflow.com/questions/2490686/enforce-spaces-or-tabs-only-in-python-files) as well

have a look at the nifty script: [reindent.py](http://svn.python.org/projects/python/trunk/Tools/scripts/reindent.py)
