### ISSUE TITLE
Can't.export.onnx 

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#984]
![IMG_20210402_235547](https://user-images.githubusercontent.com/80049634/113436598-3506f200-940f-11eb-8a6b-bcae34ecbc0f.jpg)

**Comment by dusty-nv** [comment]
Hi @tianzanaruk, this can happen if the number of classes in your labels.txt doesn't match the number of classes that your model was trained with.   Does the file `models/test/labels.txt` contain the `BACKGROUND` class?   The `BACKGROUND` should have automatically been added during training.

Can you try using this command line:   `python3 onnx_export.py --model-dir=models/test --labels=models/test/labels.txt`

**Comment by tianzanaruk** [comment]
@dusty-nv same error

**Comment by tianzanaruk** [comment]
@dusty-nv and​ now​ done.​ insert background​ and​ run​ again​ thank​ for​ help.

**Comment by dusty-nv** [comment]
FYI `BACKGROUND` should be the first class in the labels.txt.  train_ssd.py inserts this and then saves a new copy of labels.txt in your model's folder.

**Comment by tianzanaruk** [comment]
Hi @dusty-nv But​ my​ detectnet.​ Not​ found​everything

**Comment by dusty-nv** [comment]
From your screenshot, it looks like you trained it for 1 epoch.  You'll need to train it for more epochs to get decent result (30 is typical)

Also, try running `detectnet` with `--threshold=0.25` argument to lower the detection threshold (the default threshold is `0.5`)

**Comment by tianzanaruk** [comment]
ok thanks
