### ISSUE TITLE
Re-training on custom image data set rather than openImages data

### ISSUE THREAD

**Issue by Dylan-oss** [dusty-nv/jetson-inference#986]
Hello,

How may I go about re-training the object detection model using a folder of my own custom images instead of downloading a dataset from openimages? What is the easiest way to label these images and do the bounding boxes? I want to do something similar to what is done in Jetson AI youtube video with tractors, but without placing in front of the camera every time? Any tips?

**Comment by h3retek** [comment]
[[Jetson] re-training the object detection model using a folder of my own custom images](Jetson retraining the object detection model using a folder of my own custom images)
