### ISSUE TITLE
How​ to

### ISSUE THREAD

**Issue by tianzanaruk** [dusty-nv/jetson-inference#987]
![IMG_20210403_205739](https://user-images.githubusercontent.com/80049634/113480610-57f0df00-94bf-11eb-96e2-67dfe64aa190.jpg)

I​ need​ to​ remote

**Comment by h3retek** [comment]
`ssh` or `vnc`?

**Comment by tianzanaruk** [comment]
thank for help

**Comment by tianzanaruk** [comment]
Hi @h3retek i follow vnc step 2 : gsettings set org.gnome.Vino prompt-enabled false
but No such schema “org.gnome.Vino”
