### ISSUE TITLE
OpenBLAS warning

### ISSUE THREAD

**Issue by skakavyponik** [dusty-nv/jetson-inference#993]
hi,
during train_ssd I get :
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
It looks like it shows at each step
I dont have information about steps but only at epoch done 
Thanks for help

**Comment by dusty-nv** [comment]
Hmm interesting, I have not seen this warning before.  Are you using the jetson-inference container, or built from source?

**Comment by skakavyponik** [comment]
From source, but next time I tried it on docker and it worked without warning 
HW: agx xavier

**Comment by skakavyponik** [comment]
ok I am sry 
this one: [https://elinux.org/Jetson_Zoo#PyTorch_.28Caffe2.29](url)  helps a lot 
Thank you and also very good tutorials and trial programs btw
