### ISSUE TITLE
Re-training SSD-Mobilenet

### ISSUE THREAD

**Issue by higho51420** [dusty-nv/jetson-inference#994]
i want to build my own data, probably open images don't have the objection which i want.how could i build the data? then i could train my ssd model. 
thank you !!!

**Comment by dusty-nv** [comment]
Hi @higho51420, see this page for tutorial on collecting/training your own detection dataset:

https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect-detection.md

Or if you already have unannotated images, you can use the CVAT tool (cvat.org)
